### ISSUE TITLE
[Low] Auto-responder cut message issue on visitor and operator chat - since LHC version 2.55

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1006]
Auto responder message can be set long in admin side but is cut on visitor side.
![1](https://cloud.githubusercontent.com/assets/5006150/24448739/5c0e164e-1475-11e7-9331-7df0cbea10cb.png)
![2](https://cloud.githubusercontent.com/assets/5006150/24448746/5f41abb4-1475-11e7-96f4-057c8a57f737.png)

If message is long than is showed fully on the admin side but not in visitor side.

Tested message text:

"**La tua richiesta è in corso. L'attesa massima totale è di 15 minuti prima di poter lasciare un messaggio. Se si fornisce un indirizzo email potremmo provare a dare seguito alle richieste e alle chat non risposte. | Please hold on, your request still** be in progress. The max total waiting time is 15 minutes before you can leave a message. If an email is provided we can try to contact you back."

**Comment by remdex** [comment]
This should be fixed. Atleast in database field length is text. Reopen if still cannot use long text.

**Comment by PeopleInside** [comment]
Tested now in the demo, this issue still be present
