### ISSUE TITLE
[Medium] LHC 2.56 operator imput field issue: cannot be resized for see text of canned message!

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1007]
![issue lhc](https://cloud.githubusercontent.com/assets/5006150/24560042/3cc12f1a-1641-11e7-9fc2-832f8d0ef9e9.png)

this is for me a big issue.

**Comment by remdex** [comment]
It's auto resize now. That's why it's now shorter. Does auto resize works for you?

**Comment by PeopleInside** [comment]
Oh yes seems work. Sorry. I never know this ^_^

**Comment by PeopleInside** [comment]
Yes, is not working on canned message. If you click the button to see and edit canned message you cannot resize input box and have issue on see all text if the canned message is long!
