### ISSUE TITLE
Compression gzip 

### ISSUE THREAD

**Issue by andmattia** [LiveHelperChat/livehelperchat#1008]
Hi check the google tools for performance and I see a strange situation.
If you enable gzip compression on your web server you can have livechat compressed on main page, but if you try to add your widget via JS on other site you can see that live chat are not compressd

you can check the same issue on public site

https://livehelperchat.com/

https://developers.google.com/speed/pagespeed/insights/?hl=it&url=https%3A%2F%2Flivehelperchat.com%2F&tab=desktop

**Comment by remdex** [comment]
Yes i know. I just need to finish configure my nginx for compression :)

**Comment by MKI-Miro** [comment]
anything new?

**Comment by remdex** [comment]
It's server configuration issues, it has nothing to do with LHC. Contact your server admins.

**Comment by MKI-Miro** [comment]
no its not, it is mix of php and js thats why it is hard to minify this js

**Comment by remdex** [comment]
Just enable zlib compression :)

**Comment by MKI-Miro** [comment]
please understand that many people use shared hosting so there is now way to enable it, but it shoudnt be problem to minify it... :)

**Comment by PeopleInside** [comment]
MKI usually in a shared hosting terms will deny the install of a script / software like a live chat.
Is very wrong install a live chat in a shared host and will give always issue or very often,
