### ISSUE TITLE
The best way to update LHC

### ISSUE THREAD

**Issue by UralZima** [LiveHelperChat/livehelperchat#1010]
Hello. I am using a 1mo old master branch. I am following RSS feed about new commits.
Usually, I did git pull and it worked fine. 

Now, when I did git pull, LHC was broken. When I login as admin, I receive HTTP 503 error, and no any errors related in logs. I reverted all back... I use nginx + php7-fpm

What is the best and safe way to update LHC? If some db structure changes, are they handled 
somehow? How to update now?

Thanks

**Comment by PeopleInside** [comment]
Hi,
suggested update procedure are here:
https://livehelperchat.com/article/view/63

**Comment by UralZima** [comment]
Oh thanks.
