### ISSUE TITLE
[High] BUG: Error are no more printed to the user if field on widget or pop are invalid

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1012]
https://github.com/LiveHelperChat/livehelperchat/issues/1003

First issue is that in the name field the grey descritpion text are missed

BUT

**the most important issue is that if one field on start chat is mandatory and user do not compile it there are no error showed.**

How reproduce:

1. Set name field mandatory in the live helper chat demo on start chat pop up and widget set also to be visible and required

2. start a chat without compiling the name

Result: User are unable to start a chat and no error is printed.

You can also add email field as mandatory, compile the name and miss email and no error are printed.

I hope this will be fixed very soon.... is a strong error who made difficult for the user understand what is wrong, why chat is not starting.
Thanks.

**Comment by PeopleInside** [comment]
2.53 seems to be not affected. Downgraded to this version... please hope in this week this bug will be fixed so I can upgrade to the last version. Thank you!

**Comment by remdex** [comment]
This report is invalid. New version in FF just focuses cursor on missing field :)

**Comment by PeopleInside** [comment]
Thanks is a Firefox BUG. Reported also if will be fixed in Firefox 54. Was a BUG but not of live helper chat.
