### ISSUE TITLE
LHC not working properly on new version. Please help

### ISSUE THREAD

**Issue by UralZima** [LiveHelperChat/livehelperchat#1018]
Hello! 
I had version 2.53, I tried to update it to latest 2.61 using documentation, but it failed. After logging in, white blank screen, no errors in php log.
I decided to install all from scratch. Dropped database, git pulled, configured.

Now I have a problem, when user reopens a chat, he get an error.
/chat/index.php/rus/chat/reopen/2/eb348c02a7411216aafa90b380dea0ae7ce1f6e/(mode)/widget
If I access it in browser, I see 'page is not redirecting properly'

Before I didn't had such problems on version 2.53. 
I use nginx with your config (maybe something changed? page was last updated in 2014)
PHP7.1.2

Please help

**Comment by remdex** [comment]
Try this,
https://livehelperchat.com/how-to-use-debug-output-291a.html

**Comment by PeopleInside** [comment]
You can try also to repeat the update, maybe you missed some files. Be carefull all necessary is transfered.
https://livehelperchat.com/article/view/63
