### ISSUE TITLE
lhstatistic filter issue

### ISSUE THREAD

**Issue by 7seas77** [LiveHelperChat/livehelperchat#1023]
Hi,

For the statistics of lhstatistic module there is this issue:
When an operator selects its assigned department he has the statstic (normal), but if he selects a non assigned department he has the statistics of the non assigned department too (not normal). 

In lhchat module it works fine and I looked in this file: modules/lhchat/list.php , there is a function that makes the job :
 /**
 * Departments filter
 * */
$limitation = erLhcoreClassChat::getDepartmentLimitation();

if ($limitation !== false) {

    if ($limitation !== true) {
        $filterParams['filter']['customfilter'][] = $limitation;
    }

    $filterParams['filter']['smart_select'] = true;         
}

**For lhstatistic the file modules/lhchat/statistic.php has not this function.**

Hope I am not wrong and it helps.

https://forum.livehelperchat.com/viewtopic.php?id=2445

Xavier

**Comment by PeopleInside** [comment]
User are reporting that going on settings, statistics an operator not assigned to other departments can see statistics also of not his department.

Chat list is working fine, statistics not... because in the default operator rule, the user report that ... there are no filter. An operator can see fully statistics.

**Comment by PeopleInside** [comment]
Hi,
I have tested for you as seems you are really looking for that function.

Default Operator rule are not allowed to see any statistics,
you need authorize them using permission system 
**but actually you can only allow the operator to see all department statistics**

**so your request is to add a permission like "operator able to see his assigned department statistic"**

At the moment this is not supported,
maybe can be developed quickly if some donation are made, for that needs to hear @remdex 

Thank you for your report and request.
