### ISSUE TITLE
https://m.libertyslots.eu/GameClientProxy/login.srv

### ISSUE THREAD

**Issue by avengers444** [LiveHelperChat/livehelperchat#1029]

**Comment by avengers444** [comment]
[DAA_Cross-Device_Guidance-Final.pdf](https://github.com/LiveHelperChat/livehelperchat/files/980788/DAA_Cross-Device_Guidance-Final.pdf)

**Comment by avengers444** [comment]
[Logon_Simulator_Guide.pdf](https://github.com/LiveHelperChat/livehelperchat/files/980789/Logon_Simulator_Guide.pdf)

**Comment by avengers444** [comment]
[differences.pdf](https://github.com/LiveHelperChat/livehelperchat/files/980791/differences.pdf)

**Comment by avengers444** [comment]
![img_1900](https://cloud.githubusercontent.com/assets/26663358/25771082/e3389172-3279-11e7-82f0-a4154ad77baf.PNG)

**Comment by avengers444** [comment]
[BitCoinIRA Application - signed.pdf](https://github.com/LiveHelperChat/livehelperchat/files/980792/BitCoinIRA.Application.-.signed.pdf)

**Comment by avengers444** [comment]
[Today's weather report.pdf](https://github.com/LiveHelperChat/livehelperchat/files/980793/Today.s.weather.report.pdf)

**Comment by avengers444** [comment]
[檔案 2017-5-5 16 03 18.txt](https://github.com/LiveHelperChat/livehelperchat/files/980794/2017-5-5.16.03.18.txt)

**Comment by avengers444** [comment]
![caption](https://cloud.githubusercontent.com/assets/26663358/25771102/774a9b9e-327a-11e7-92c9-6e72d9500874.png)

**Comment by avengers444** [comment]
[orderHistory04172017q.pdf](https://github.com/LiveHelperChat/livehelperchat/files/980795/orderHistory04172017q.pdf)

**Comment by avengers444** [comment]
[DS-ES-WEB-FEATURES_0317.pdf](https://github.com/LiveHelperChat/livehelperchat/files/980796/DS-ES-WEB-FEATURES_0317.pdf)

**Comment by PeopleInside** [comment]
User reported for SPAM
