### ISSUE TITLE
Nginx Help

### ISSUE THREAD

**Issue by onlyindia** [LiveHelperChat/livehelperchat#1033]
You did not mention where this code goes.

**Comment by blomman9** [comment]
This would be example nginx configuration. It depends on you nginx installation, it is usually put into /etc/nginx/ folder and the sites configuration is either in /etc/nginx/conf.d or /etc/nginx/sites-enabled, depending on version/preference.

If you need further assistance please check the forums https://forum.livehelperchat.com/search.php <https://forum.livehelperchat.com/search.php> Search for nginx.
