### ISSUE TITLE
Error Line 312 File chatwidget.php

### ISSUE THREAD

**Issue by FrankSanabria** [LiveHelperChat/livehelperchat#1034]
**I have this error in Widget**  
`Fatal error: Can't use function return value in write context in /var/www/html/lhc_web/modules/lhchat/chatwidget.php on line 312`

**I need comment this lines in version 2.63v after upgrade from 2.62v for the widget will work** 

```
if ( empty(trim($chat->nick)) ) {
                 $chat->nick = erTranslationClassLhTranslation::getInstance()->getTranslation('chat/startchat','Visitor');
             }
```
**My VPS:**
Server: Centos 7.3 64 bits
Web: Apache Server version: Apache/2.4.6 (CentOS)
PHP: PHP 5.4.16 (cli) (built: Nov  6 2016 00:29:02) 
BD:  MariaDB Server 5.5.52-MariaDB 

**File Permissions:**
drwxr-xr-x. 14 apache apache 4,0K jun  3 01:49 .
drwxr-xr-x. 15 apache apache  16K jun  3 13:37 ..
-rwxr-xr-x.  1 apache apache  251 feb 23 16:55 bower.json
drwxrwxr-x.  6 apache apache 4,0K feb 23 16:55 cache
drwxr-xr-x.  3 apache apache 4,0K feb 23 16:55 cli
-rwxr-xr-x.  1 apache apache 2,6K feb 23 16:55 cron.php
drwxr-xr-x.  5 apache apache 4,0K mar 23 09:28 design
drwxr-xr-x.  9 apache apache 4,0K may 17 07:16 doc
drwxr-xr-x.  2 apache apache 4,0K feb 23 16:55 extension
drwxr-xr-x. 29 apache apache 4,0K mar 23 09:28 ezcomponents
-rwxr-xr-x.  1 apache apache 6,8K feb 23 16:55 gulpfile.js
-rwxr-xr-x.  1 apache apache 1,7K jun  3 13:43 index.php
drwxr-xr-x.  5 apache apache 4,0K mar 23 09:28 lib
drwxrwxr-x. 33 apache apache 4,0K jun  3 01:49 modules
-rwxr-xr-x.  1 apache apache  447 feb 23 16:55 package.json
drwxr-xr-x. 13 apache apache 4,0K mar 23 09:28 pos
drwxr-xr-x.  2 apache apache 4,0K feb 23 16:55 settings
drwxr-xr-x. 30 apache apache 4,0K mar 23 09:28 translations
drwxr-xr-x. 11 apache apache 4,0K feb 23 16:55 var
-rwxr-xr-x.  1 apache apache 1,4K feb 23 16:55 webpack.config.js

**Comment by PeopleInside** [comment]
You are using and old and no more supported PHP.

**Comment by FrankSanabria** [comment]
Yes, I update my PHP and fixed

**Comment by PeopleInside** [comment]
Thank you for the feedback
