### ISSUE TITLE
Error 503 in syncadmininterface/(limita)/10/(limitu)/10/(limitp)/10/(limito)

### ISSUE THREAD

**Issue by alex4321** [LiveHelperChat/livehelperchat#1035]
In main admin page - in console I had lot of errors like 

    DevTools failed to parse SourceMap: http://45.55.192.217/index.php/site_adm … min.js.map
    ...
    Failed to load resource http://45.55.192.217/index.php/site_adm … limitd)/10: the server responded with a status of 503 (Service Temporarily Unavailable)
    e84a585….js:212 error"

With turned on "debug_output" flag - I saw next exception - https://gist.github.com/alex4321/63c7707ffd5aa8113be0e175aaa4a715

So I found that error related to next mysql query

    # SELECT `lh_userdep`.`id`, `lh_userdep`.`user_id`, `lh_userdep`.`dep_id`, `lh_userdep`.`last_activity`, `lh_userdep`.`hide_online`, `lh_userdep`.`last_accepted`, `lh_userdep`.`active_chats` FROM `lh_userdep` WHERE `lh_userdep`.`last_activity` > 1496541103 GROUP BY `lh_userdep`.`user_id` ORDER BY active_chats DESC, hide_online ASC LIMIT 10 OFFSET 0;
    ERROR 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'test_livehelperchat.lh_userdep.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

About mine installation:
- LiveHelperChat - 2.62

    # mysql --version
    mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using  EditLine wrapper
    # cat /etc/lsb*
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=16.04
    DISTRIB_CODENAME=xenial
    DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

Seems like by default it uses incorrect sql_mode (for this query). I fixed it by setting sql_mode in "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" in mysql config, but - error related to this flag: "only_full_group_by".

And as I can see in https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html - "ONLY_FULL_GROUP_BY" must be turned on by default in MySQL 5.7 - so it must be a good idea to fix this queries or add sql_mode parameter setting in queries, no?

**Comment by PeopleInside** [comment]
Hi,
**I asked to test in the live helper chat demo before open a GitHub topic** but seems you create a forum post than also a GitHub post and reply in the forum is not related to what I asked.

This can be an issue present on your side until you cannot reproduce in the demo.

**Comment by alex4321** [comment]
Of course - it depends on MySQL server configuration. And yep - I unable to reproduce it on your server.

But as I written there - seems like this behaviour must be default in newest MySQL versions.

**Comment by PeopleInside** [comment]
Well, this topic is not useful if you do not give information of what mysql version are you using :)
however I will leave this to the attention of the chat owner.

**Comment by alex4321** [comment]
> if you do not give information of what mysql version are you using

As you can see in topic start message :-)
> mysql --version
> mysql Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using EditLine wrapper"

So - it's 5.7.18 version.

**Comment by PeopleInside** [comment]
Thanks. Last LHC version is 2.63 just for let you know.
2.62 is the previous version, we have to check if the issue still be present in LHC 2.63

**Comment by alex4321** [comment]
Thanks - maybe I'll test it later and let you know about results.

**Comment by defive** [comment]
The solution in this issue should help: https://github.com/LiveHelperChat/livehelperchat/issues/1026

**Comment by alex4321** [comment]
Yep, at least - it related to common problem :-)

**Comment by raykai** [comment]
same here [https://github.com/LiveHelperChat/livehelperchat/issues/1026#issuecomment-331038836](https://github.com/LiveHelperChat/livehelperchat/issues/1026#issuecomment-331038836) plz fix! as MySQL 5.7 and up has ONLY_FULL_GROUP_BY trend on by default : [https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by) its there for a reason.
