### ISSUE TITLE
Automatic chats assignment workflow not set next user

### ISSUE THREAD

**Issue by edgardmessias** [LiveHelperChat/livehelperchat#1036]
To work, I Changed the line: https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/lib/core/lhchat/lhchatworkflow.php#L313

```php
// from
if ($chat->user_id == 0 && $chat->tslasign < time()-$department->max_timeout_seconds) {

//to
if ($chat->user_id == 0 || $chat->tslasign < time()-$department->max_timeout_seconds) {
```

**Comment by remdex** [comment]
You should not have changed. Because there now in your logic chat will change owner every time check is done, which is not correct logic. Automatic assigned is done then visitor browser window checks for chat status.

**Comment by Mike-Benoit** [comment]
Looks like a very similar fix was just commited here: https://github.com/LiveHelperChat/livehelperchat/commit/8345827bc9d0dd46c1173980e7f94f9c0dc0c80f
