### ISSUE TITLE
Redis Error

### ISSUE THREAD

**Issue by onlyindia** [LiveHelperChat/livehelperchat#1037]
Hi Remdex!

I'm trying to implement node js extension on Centos 7 with NGINX but without PROXY.
It works fine with If I set "settings.use_publish_notifications = false;"
If I set "settings.use_publish_notifications = true;" then I get below error in SSH consol

![redis](https://user-images.githubusercontent.com/5064665/26945858-dd165e64-4caa-11e7-857b-bf51326bcbea.jpg)

And this error in browser console

![error2](https://user-images.githubusercontent.com/5064665/26945982-4bf010d2-4cab-11e7-9579-6a03548fad6e.jpg)

Pls tell what's wrong I'm doing

**Comment by remdex** [comment]
https://github.com/LiveHelperChat/NodeJS-Helper/commit/a3b82f6508c9c0df35f7df6a1143f27806e7638c
