### ISSUE TITLE
I/O Error when switching language

### ISSUE THREAD

**Issue by muellerlukas** [LiveHelperChat/livehelperchat#1042]
When switchting the language simplexml throws an error-message:
`Warning: simplexml_load_file(): I/O warning : failed to load external entity "/....//translations/de_DE/translation.ts" in /.../lhc_web/ezcomponents/Translation/src/backends/ts_backend.php on line 233`

Temporary fix: Replace
`return simplexml_load_file( $filename, $returnClass );`
with
`return simplexml_load_string( file_get_contents( $filename ), $returnClass );`

Problem also posted on the forum: https://forum.livehelperchat.com/viewtopic.php?pid=10327

**Comment by PeopleInside** [comment]
Hi, welcome and thank you for your report.
I replied to you on the forum and I AM currently waiting the steps for reproduce the issue as from first test I AM unable to replicate the issue reported by you.

Are you sure to use a PHP version same or superior to 5.6?
However please continue the discussion on the forum. Thanks.

**Comment by PeopleInside** [comment]
Thank you for the fix, merged.
