### ISSUE TITLE
Embed code is not showing all available departments

### ISSUE THREAD

**Issue by simsketch** [LiveHelperChat/livehelperchat#1044]
![screencapture-extremereachsupport-livehelperchat-site_admin-system-htmlcode-1497551547643](https://user-images.githubusercontent.com/3129129/27197548-9e438bee-51dc-11e7-8190-5a86f1937377.png)
![screencapture-extremereachsupport-livehelperchat-site_admin-departament-departaments-1497553818947](https://user-images.githubusercontent.com/3129129/27197596-cd653dbe-51dc-11e7-863b-3d07f6029992.png)

**Comment by PeopleInside** [comment]
Your operator are not assigned to the department that you cannot see in the dropdown, this is why you are not able to select this department: you are not assigned. An admin should open your profile and assign from the department assignment tab.

⁣Mobile - Marco Borla 
Www.PeopleInside.IT - www.MarcoBorla.it ​

Il giorno 15 Giu 2017, 21:10, alle ore 21:10, Elon Zito <notifications@github.com> ha scritto:

**Comment by simsketch** [comment]
Thank you very much!!!

**Comment by PeopleInside** [comment]
You are welcome 👍
