### ISSUE TITLE
How can I create a login that is for admin access only?

### ISSUE THREAD

**Issue by flyingcoder** [LiveHelperChat/livehelperchat#1048]

**Comment by PeopleInside** [comment]
Hi,
I think this is a question for the commercial support also you cannot create an issue without any details here :) is just something who made time to be lost :)

"We" are very busy at live helper chat :)

**Comment by flyingcoder** [comment]
I understand I very sorry

**Comment by PeopleInside** [comment]
What you want do? :) I cannot understand you from your request :)
The admin area is for the admin only. If you want operator you can create operators :)
So maybe your post here is missing details. GitHub here is most used for report issue or suggestions, for support or discussion you can use the forum https://forum.livehelperchat.com/

How we can help you?

**Comment by flyingcoder** [comment]
Oh, I am very sorry, I am trying to display a list of user that is created by the $currentUser.
I understand that $currentUser is an object that have hasAccessTo function. I wanted to create a function something like this $currentUser->users where it displays the users which he created.

**Comment by flyingcoder** [comment]
I wanted to code it in the extension directory but don't know how.

**Comment by PeopleInside** [comment]
Sorry I cannot help about this, you can try to wait here for a reply from the chat owner. 
Have a nice time :)

**Comment by flyingcoder** [comment]
okay thank you

**Comment by PeopleInside** [comment]
You are very welcome :) sorry to be unable to help you more, you need to wait :)
All official documentation is here: 
https://livehelperchat.com/documentation-6c.html

**Comment by remdex** [comment]
I suggest just see what permissions has operators role. Everything what can be reached from back office is configured through roles and functions.
