### ISSUE TITLE
Issue when status widget is set on right center position 50 %

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1052]
I want move the status widget from bottom of the page to the center of the page but seems there are some issue.,

I want the widget button on center of the page but when user click on it widget should not be opened from where the status widget start (middle of the page)
maybe widget should always opened from the bottom of the page if not, you can see in the video the issue that I AM able to fix only manually by moving the widget with hand cursor.

https://www.screencast.com/t/pH16blMMGp

Please can you fix this by allowing the widget to be opened from the bottom of the page also if the status widget button is on center of the page?

When this will be fixed I will be able to start to convert my widget status button, for now not because widget are not showed well on all screen if this is not fixed.
Thanks.

Here is the link where the video was recorded: http://peopleinside.altervista.org/
This is a test page. Once the issue here will be fixed I will update my status widget in all my official websites and pages.

**Comment by remdex** [comment]
Sorry, but this issue won't be fixed. Just to complex... Use status widget at the bottom of page.
