### ISSUE TITLE
Extension classes directory not loading

### ISSUE THREAD

**Issue by flyingcoder** [LiveHelperChat/livehelperchat#1054]
I check other extensions sample with classes directory and it seems classes directory on extensions are auto added to the autoload system of live helper chat.

I am trying to create an extension that will override an erLhcoreClassChat class by extending it. It was written in the classes directory but when I added the class to the module folder under the said extension directory. It creates an error that my class in classes directory is not found.

Is there a way to manually autoload my class in classes folder? Thanks

**Comment by remdex** [comment]
You have to do something like that.

https://github.com/LiveHelperChat/fbmessenger/blob/master/bootstrap/bootstrap.php#L9
https://github.com/LiveHelperChat/fbmessenger/blob/master/bootstrap/bootstrap.php#L302
https://github.com/LiveHelperChat/fbmessenger/blob/master/bootstrap/bootstrap.php#L309
