### ISSUE TITLE
XMMP auth failed, but account works

### ISSUE THREAD

**Issue by ioscanner** [LiveHelperChat/livehelperchat#1055]
I just loaded version 2.65.  I setup XMMP using standard XMPP service.  I have my own servers.  I have other software using XMMP as well using the same account.  I enter the account details and save.  I then try to test and I just see auth failed.  I even verified in the server logs it says auth failed.  I have other XMMP clients using that account.  I tested to confirm, it works.  It seems it is not taking the passwords from the password field.  Even after saving, no hash for the password field is shown.

Is this a known bug?

**Comment by PeopleInside** [comment]
Hi,
this issue started after an upgrade of LHC or it's on a new install of LHC this issue?

I ask this because maybe the upgrade process you done was not done well.
It's a possibility.

The issue is only in XMMP or also when you try to login to admin interface?

Thank you

**Comment by ioscanner** [comment]
It was a new install on a fresh install of Debian 8.  Install is fine.  I can login to the admin interface just fine.

**Comment by ioscanner** [comment]
I did look in the database and the password is in the table, if that helps.

**Comment by ioscanner** [comment]
I did a new install and new install of Linux.  Still the same issue.

**Comment by ioscanner** [comment]
Any update on this?  I have tried everything I can think of.  Is this a bug?  I can't seem to get jabber client to work.  Does anyone else have their Jabber server working?

**Comment by remdex** [comment]
Sorry, but all works here. That's means you just entered invalid credentials somewhere in system. There is a commercial support if you need one. But from plain issue description, just impossible to help especially that it works here...
