### ISSUE TITLE
Proactive  Issue

### ISSUE THREAD

**Issue by onlyindia** [LiveHelperChat/livehelperchat#1056]
When we have two proactive invitations, 1) time based 2) page views based then only 1 invitations trigger and then message_seen_timeout event occurs which does not allow 2 invitation to process.

I think message_seen_timeout should be different for both for time-based and page view based proactive invitation.

This necessary because of the following scenario.

A visitor has seen time-based invitation after 15 seconds and he closed invitation window but he is still on the website, now we want to show him a second proactive invitation when he reaches 5 page views.

And this doesn't work.

**Comment by remdex** [comment]
It won't work. Proactive invitation is shown only once and the very first which meet's condition.
