### ISSUE TITLE
user showing for other departments

### ISSUE THREAD

**Issue by ioscanner** [LiveHelperChat/livehelperchat#1057]
I have setup different users with different departments for different sites.  When I log in with the different users they are showing up in different departments.

So I login as support on support site as user support.

Then login as sales: on sales site as user sales.

If go to support site and the support user is not logged in.  Then I see users online when sales is online and support is offline. This is not what I want. It should show offline. The site support should only send requests to users in Department support with user support or other users in Department support if online.

I setup departments for each Sales and Support with the users only in each department.  I setup group for each department and only have each in each group. I did have in Role operators, but I also tried to create a new role for each department but that didn't seem to work either.  I thought it was the role that was causing this issue.

I tried to create new role and group or request permission from scratch but when I try to add individual permissions it errors.  So it seems so it seems to be all or none.

Can anyone help me with this?  It seems like a bug.  My guess is it is in the roles that some rule is allowing all users in the Operator role to show up in other departments.

UPDATE:  I did test and sales can't see support and it doesn't show up in sales either.

**Comment by jm4rc05** [comment]
I had a somewhat similar problem and unchecked the option "User can see all pending chats, not only assigned to him" at Settings / Users / "Your user operator" / Pending chats (tab). Hope this help!

**Comment by ioscanner** [comment]
That got it thanks.

**Comment by ioscanner** [comment]
Ok I tried now it just shows the  departments the user is in.  But now I can't access the chats. It says auth failed when I click one.

**Comment by remdex** [comment]
Just to complicated to understand from your request. Please use forum...
