### ISSUE TITLE
Can't see [operators_online] widget at dashboard panel

### ISSUE THREAD

**Issue by jm4rc05** [LiveHelperChat/livehelperchat#1059]
I actually never saw this widget since I'm using Livehelperchat for three days now, but checked to see this widget in the panel configuration and nothings change!

I'm using the latest version downloaded right now!

**Comment by remdex** [comment]
Hi,

You have to enable it in chat configuration first. 
https://demo.livehelperchat.com/site_admin/chat/listchatconfig#/misc

"List online operators"
