### ISSUE TITLE
2.65 bug: If in the operator profile all department is not working

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1062]
Hi,
from the forum: https://forum.livehelperchat.com/viewtopic.php?id=2574
verified by me

if there are more than one department and operator are assigned only to all department you are not online for all department.
You are online only for the department selected.

**Comment by remdex** [comment]
Sorry, but can't reproduce locally. In new version was a change, that if department id is provided it has to be checked explicitly. So if what provide exact steps to reproduce.

**Comment by hussainwali74** [comment]
getthing this issue, any update on this?

**Comment by remdex** [comment]
If you are passing multiple departments, your agents has to choose departments explicitly for them to be seen as online.

**Comment by hussainwali74** [comment]
can you give me a direction? what should I do now? I want to show the users offline form if no operator is online. When I set this option in back office settings all chats are shown the offline form regardless of operator status online or offline

**Comment by remdex** [comment]
I can't give any advice as you did not gave steps to reproduce your issue in https://livehelperchat.com/demo-12c.html as for me all works as expected.

**Comment by hussainwali74** [comment]
i am sharing screenshots

**Comment by remdex** [comment]
Sorry, but no screenshots. Configure demo to reproduce the issue. Also, you can order paid support, and if you prove it's a bug will be free :)

**Comment by hussainwali74** [comment]
http://chatdev.propsure.rocks/index.php/site_admin

this is a demo

**Comment by hussainwali74** [comment]
with the issue reproduced

**Comment by remdex** [comment]
Sorry, but your report does not make any sense what I'm suppose to do with that back office address? :D

**Comment by hussainwali74** [comment]
you can check for yourself that there are agents  online and on the frontend it shows that there are no agents online

**Comment by remdex** [comment]
End of story, either you reproduce as I asked on demo either order paid support to investigate...

**Comment by hussainwali74** [comment]
should I share credentials?

**Comment by hussainwali74** [comment]
I am sharing the whole site how else can i share demo? should I make a video?

**Comment by hussainwali74** [comment]
> http://chatdev.propsure.rocks/index.php/site_admin
> 
> this is a demo

this is the demo deployment where the issue is reproduced

**Comment by remdex** [comment]
I repeat last time, reproduce issue using demo credentials here https://livehelperchat.com/demo-12c.html

**Comment by hussainwali74** [comment]
I have created the demo setup:

i have created new department graan, embeded popup widget  code into my own server FE

https://chatdev.propsure.rocks/ramis/

can you see this?

**Comment by remdex** [comment]
![image](https://user-images.githubusercontent.com/1146085/207804851-ce200158-c43a-47ee-809e-9ccad0ff02aa.png)

**Comment by remdex** [comment]
Share embed code you used, if you can't make it public your demo.

**Comment by hussainwali74** [comment]
![image](https://user-images.githubusercontent.com/24194686/207805076-edb123a2-c114-4406-a6eb-b065b47ca4a5.png)

**Comment by hussainwali74** [comment]
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <script>var LHC_API = LHC_API||{};
        LHC_API.args = {mode:'popup',lhc_base_url:'//demo.livehelperchat.com/',wheight:450,wwidth:350,pheight:520,pwidth:500,leaveamessage:true,department:["3"],check_messages:false};
        (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.setAttribute('crossorigin','anonymous'); po.async = true;
        var date = new Date();po.src = '//demo.livehelperchat.com/design/defaulttheme/js/widgetv2/index.js?'+(""+date.getFullYear() + date.getMonth() + date.getDate());
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
        </script>
    
</body>
</html>
```

**Comment by remdex** [comment]
Don't check `Auto start chat if there is no required fields. Usefull in case bot handles chat.` while using popup. and I don't see offline chat.
