### ISSUE TITLE
2.67: Autoresponder issue

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1066]
Thanks for the first fix ( https://github.com/LiveHelperChat/livehelperchat/issues/1064 ), it works but other auto responder bugs are present.

![00](https://user-images.githubusercontent.com/5006150/28251301-d1ad08be-6a7a-11e7-9f2b-b455af8f54b6.png)

After your fix first auto responder is showed correctly, second autoresponder are showed correctly after 300 seconds but the third is showed immediately after the second without wait 300 seconds.

**Comment by PeopleInside** [comment]
Well,
seems auto responder are not all respecting waiting time and are not showed in the correct order.
Please see the video below at full screen!

https://www.screencast.com/t/SVMqbMt8m

**Comment by remdex** [comment]
You have to set Wait timeout messages in increment order.
300
600
900
1200
Etc. Wait timeout is not time from last item
