### ISSUE TITLE
Encrypt or make URL friendly for parameter security

### ISSUE THREAD

**Issue by Sandenberg** [LiveHelperChat/livehelperchat#1072]
Hello, I have a question, would you like to get the URL that is provided by LIVE Helper" ex: http://demo.livehelperchat.com/chat/sta … ame%20here
&value_items_admin[0]=back_office_field" and make it be encrypted or friendly to not show the parameters for the user?

Thanks for listening

**Comment by remdex** [comment]
you can encrypt all passing fields. 
https://livehelperchat.com/pre-filling-form-fields-and-adding-custom-fields-140a.html
"How securely pass attributes?"
