### ISSUE TITLE
Round Robin distribution and auto-assign chat if operator don't accept

### ISSUE THREAD

**Issue by setcolmbia** [LiveHelperChat/livehelperchat#1073]
Hi, 

I'm testing the automatic distribution according to the documentation (https://livehelperchat.com/how-to-setup-round-robin-automatic-chats-assignment-workflow-322a.html) and so far it works perfect with the round robin distribution method, but i have an issue with the auto assignment, i configured the system to automatically assign chats to another operator if operator did not accepted chat in X seconds (20 Secs for my tests), but once the chat is assigned to an operator, never goes to another...

I tested with 2 and 3 online operators, and one single chat never jumps from operator to operator...

Looking for any similar case i found this request: https://github.com/LiveHelperChat/livehelperchat/issues/1036 I have the same problem, and with the posted change i actually works!, But i can't understand the reply from remdex, he said: "You should not have changed. Because there now in your logic chat will change owner every time check is done, which is not correct logic. Automatic assigned is done then visitor browser window checks for chat status."... So i'm confused, that change is wrong? How can i fix the system to make RoundRobin work?

Thanks and regards.

**Comment by remdex** [comment]
Sorry, but for me it works. There is commercial support if you need one. Make sure your operators are assigned to each of department.

**Comment by Mike-Benoit** [comment]
We just upgraded from v2.51 to v2.96, prior to the upgrade auto-assign was working fine, and if one operator didn't answer in 45 seconds it would try another, then after 95 seconds transfer to another department where it would repeat the process with a new set of operators. 

However after the upgrade that doesn't work anymore. It seems to assign the chat to a random operator initially, but never try another one if that operator does not answer, even after it transfers the chat to another department. The operators are assigned to the proper departments. 

What we are ultimately trying to achieve is a two tier system where the end-user should always get to an operator. Starting with the initial department, it should keep trying operators until 95 seconds passes, then it escalates the chat to 2nd tier department which has all employees in the company assigned, and keep trying operators until someone answers there.
