### ISSUE TITLE
Closing chat does not close

### ISSUE THREAD

**Issue by altomarketing** [LiveHelperChat/livehelperchat#1076]
1. I see Active chats
2. I start chatting
3. I close the chat from little x in tab it close the chat, and it still remains in active chat... but with X in (3), it should dissapear from Active chats, right ?
4. It does not dissapear.

I notice that from Windows app it does not happen, only on web.

![livechat](https://user-images.githubusercontent.com/474889/28936786-278a9dae-785f-11e7-82be-f30937f4e0d4.png)

**Comment by remdex** [comment]
Sorry, but for me it works. There is some problems with your instance. You should try to debug. Not mutch i can do with access to server etc..
