### ISSUE TITLE
Users register and login

### ISSUE THREAD

**Issue by c2sam** [LiveHelperChat/livehelperchat#1079]
Hello
Thank you for this amazig live chat
I would like to  ask i there are away to force users register and login before chat (only logged is user can chat not guest)
Thank you!

**Comment by remdex** [comment]
Hi,

You can try to use https://livehelperchat.com/how-to-use-paid-chats-feature-439a.html paid chats feature. So users won't be able to start chat, unless appropriate variable in JS is generated.

**Comment by c2sam** [comment]
Hi,
thank you for your help
just i would ask how to retieve emails or name before starting chat

thank you
