### ISSUE TITLE
Very slow from hosted

### ISSUE THREAD

**Issue by markdl58** [LiveHelperChat/livehelperchat#1083]
Hi, you host our LHC and it has become very slow to respond, and I just had aa page fail with internal server error message.... 
HELP!

**Comment by remdex** [comment]
Hi,
I see. It's just overloaded because of one excessive client use... I'll see what i can do, but do not promise anything. :(

**Comment by remdex** [comment]
It should be fine now :)

**Comment by patrykbujak** [comment]
I have 404 server error

**Comment by remdex** [comment]
@patrykbujak what's instance addrss?

**Comment by markdl58** [comment]
Mobexx.livehelperchat<http://Mobexx.livehelperchat>

Regards
Mark Dale-Lace

Sent from my Sony Xperia™


---- Remigijus Kiminas wrote ----


@patrykbujak<https://github.com/patrykbujak> what's instance addrss?

**Comment by remdex** [comment]
It should be fine, now. Can you check?

**Comment by remdex** [comment]
Ok, i'm stopping hosting for 30 min. It will have 2x power it has now.

**Comment by remdex** [comment]
Ok,
So I have decided to migrated to dedicated server during the weekend. Thank you all for the patience :)
