### ISSUE TITLE
Current page and url history (footprint) not popuplating in back office

### ISSUE THREAD

**Issue by stratacorps** [LiveHelperChat/livehelperchat#1087]
We are getting the page referrer url just fine, but we are not getting the page visit url.  The page title is being displayed and correct for each page visit, but the url is just the protocol and the domain (e.g. https://mydomainl.com/" but missing the full page url information (file/query string, etc.).

![screen_2017-08-17_01-12-34_pm](https://user-images.githubusercontent.com/31138795/29469111-82629728-840c-11e7-84d4-eab65fa5a78a.png)
![screen_2017-08-17_01-13-26_pm](https://user-images.githubusercontent.com/31138795/29469192-cefceb42-840c-11e7-8b0a-ac5cf1eaeca4.png)

**Comment by remdex** [comment]
About that I don't know never happened on my environment. Perhaps your apache config forbids passing these or something else. Really impossible to tell...

**Comment by stratacorps** [comment]
:(  we got the same results  on a similar system, Centos 7, Apache 2.4 via standard yum install, etc. before I moved it to my primary server.  Disabled all cache, etc.  Of course our other scripts like Google Analytics seems to work so I didn't know where to even begin trying to track things down with this script.  It was a nice experiment while it lasted.  Thanks.

**Comment by ggermes** [comment]
@stratacorps How did you solve the problem?

**Comment by yugdeep17** [comment]
Did anyone find the solution? why footprint shows only homepage URL?
![image](https://user-images.githubusercontent.com/61185415/74731193-8c7aea80-526d-11ea-9505-2ee3ae3671f9.png)

**Comment by remdex** [comment]
Hi,

Sorry but this one I can't reproduce... Most likely you have you have entered incorrect domain in embed code generation window.

**Comment by yugdeep17** [comment]
Thanks for your reply @remdex 

this is the script generated in embed code. 
![image](https://user-images.githubusercontent.com/61185415/74803554-5ab46300-5303-11ea-8e33-21e688f7ddcf.png)

Any other possibility that we can trigger to let it work correctly?

**Comment by remdex** [comment]
As I don't see what values you have in domain attributes just make sure it's domain like 'example.com' without any http in front...

**Comment by yugdeep17** [comment]
Yes, It's plain domain like 'abc.com' or 'example.com' withour any http or https
Even i have cleared the cache but not working as expected.
I am still wondering what might need to be corrected.

**Comment by yugdeep17** [comment]
@remdex 
It's resolved now.  It took some time after cleaning the cache.
Not it's giving all traverse URLs.
Thank you.
