### ISSUE TITLE
Alert message when the operator leaves an open chat after a "Idle Time

### ISSUE THREAD

**Issue by Sandenberg** [LiveHelperChat/livehelperchat#1089]
Hello,
I would like to know if there is any configuration to send a message to the operator when he leaves the chat open for a long time, thus leaving the client unanswered or simply leaving the chat open without closing.

I want a warning for the operator that is still online and just left the chat open. Something like a popup like what pops up when there is a new chat, just letting the operator know That he is "a few minutes" without responding to this chat, so he would talk to the client again.

Is there such a setting?
Thank you

**Comment by remdex** [comment]
Notice before closing.
Just use auto responder or continous webhooks. Everything in the docs.
