### ISSUE TITLE
How a can disable: clamav_enabled on upload ?

### ISSUE THREAD

**Issue by ricardojlrufino** [LiveHelperChat/livehelperchat#1090]
I am having problems without uploading files,
How can I disable this setting  ?

https://github.com/LiveHelperChat/livehelperchat/blob/51542bfa6e555dbaaee58a63327626f37a8c61b7/lhc_web/modules/lhfile/uploadfileonline.php#L18

**Comment by remdex** [comment]
In file configuration section.

**Comment by ricardojlrufino** [comment]
On here ?

![image](https://user-images.githubusercontent.com/515675/29650929-54a39eb0-8874-11e7-9104-b1f2f1913676.png)

**Comment by remdex** [comment]
Yes, it has to be unchecked.

**Comment by ricardojlrufino** [comment]
Already, and was giving error in upload as OPERATOR using ctrl + v

**Comment by ricardojlrufino** [comment]
PHP Fatal error:  Call to a member function scan() on a non-object in /srv/www/criativasoft.com.br/public_html/livehelperchat/lib/core/lhcore/lhfileupload.php on line 45

**Comment by remdex** [comment]
Wait i check

**Comment by ricardojlrufino** [comment]
Database value
```
a:10:{i:0;b:0;s:5:"ft_op";s:43:"gif|jpe?g|png|zip|rar|xls|doc|docx|xlsx|pdf";s:5:"ft_us";s:26:"gif|jpe?g|png|doc|docx|pdf";s:6:"fs_max";i:2048;s:18:"active_user_upload";b:1;s:16:"active_op_upload";b:1;s:19:"active_admin_upload";b:1;s:14:"clamav_enabled";b:0;s:10:"clamd_sock";s:26:"/var/run/clamav/clamd.sock";s:14:"clamd_sock_len";i:20000;}
```

**Comment by ricardojlrufino** [comment]
My temp solution:
![image](https://user-images.githubusercontent.com/515675/29651075-1c4933f8-8875-11e7-9379-0983f53ee1e6.png)

I'm not a php developer  =/

**Comment by remdex** [comment]
Can you clear cache from back office after unchecking this checkbox

**Comment by ricardojlrufino** [comment]
By default it was already unchecked, and I had just updated the system version

**Comment by remdex** [comment]
Also you can update https://github.com/LiveHelperChat/livehelperchat/commit/8b77088e452f2a0962319501e3b23e2ccb7e09cc this file. and just resave config if what. Because i can't reproduce it on my own server... If it's unchecked it's not executed.

**Comment by ricardojlrufino** [comment]
not work...

**Comment by ricardojlrufino** [comment]
on save i see this erros on log:
```
PHP Warning:  include(cache/compiledtemplates/dfe35f5de282f01c213d4edc9c76a6ab.php): failed to open stream: No such file or directory in /srv/www/criativasoft.com.br/public_html/livehelperchat/lib/core/lhtpl/tpl.php on line 535, referer: http://chat.criativasoft.com.br/index.php/site_admin/file/configuration
[Thu Aug 24 02:56:08.739176 2017] [:error] [pid 4773] [client 187.41.90.125:44032] PHP Warning:  include(): Failed opening 'cache/compiledtemplates/dfe35f5de282f01c213d4edc9c76a6ab.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /srv/www/criativasoft.com.br/public_html/livehelperchat/lib/core/lhtpl/tpl.php on line 535, referer: http://chat.criativasoft.com.br/index.php/site_admin/file/configuration

```

**Comment by remdex** [comment]
It's not related please update lib/core/lhcore/lhfileupload.php this file

**Comment by ricardojlrufino** [comment]
WoW... Its working ... thanks .... !!
I'm in Brazil, so here it is 3:00 am ... rsr

A question ..
If it is possible to show the preview of the images after the upload ?!

**Comment by remdex** [comment]
Well theoretically possible. But if it's not supported it's not supported :)

**Comment by remdex** [comment]
At the moment it was intentionally doe do not show preview :)

**Comment by ricardojlrufino** [comment]
I understood, thank you very much for your help ...
