### ISSUE TITLE
Visual pop up notification for new chat is sometimes delayed for some users

### ISSUE THREAD

**Issue by simsketch** [LiveHelperChat/livehelperchat#1094]
Any idea what might be causing this or if there is a setting I can change? I recommended to the operators to use the chrome extension because that has been consistent in my experience, as far as notifications of new chats.

**Comment by PeopleInside** [comment]
Hi, is this issue still present in the latest version of live helper chat?
Try to do not use the Chrome extension. Live helper chat support browser notification.
The Chrome extension can be not updated.

**Comment by PeopleInside** [comment]
Hi, I'm closing this as no response.
Feel free to comment if you still need help.
