### ISSUE TITLE
extension_module_multiinclude.tpl.php is empty

### ISSUE THREAD

**Issue by yadimen** [LiveHelperChat/livehelperchat#1097]
I wonder how the extra modules are being enabled without having any code in this file "extension_module_multiinclude.tpl.php", however this is being called in <?php include(erLhcoreClassDesign::designtpl('pagelayouts/parts/modules_menu/extension_module_multiinclude.tpl.php'));?>

I guess due to this, i'm not getting extra modules displayed in the page..

**Comment by remdex** [comment]
It's correct file content. This template is for overrides. So you create template in your own extension with same path and enter any html you want. It combines all templates which ends with multiinclude.tpl.php keyword
