### ISSUE TITLE
[Forum report/request] Speech page strange?

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1104]
https://forum.livehelperchat.com/viewtopic.php?pid=10785#p10785

> In your account settings, the default language is selected in the "Speech" tab.
> But when you click on the microphone in the operator's dialogue - writes only in English.
> 
> Other languages in the account settings are not selected. There instead of the list of languages - 0 zeros. In dialects - the same way.
> 
> Prompt the decision.
> 
> Thank you.

![screen lhc](https://user-images.githubusercontent.com/5006150/30518651-670efcd4-9b84-11e7-8678-5c973a0f4d59.png)

**Comment by raykai** [comment]
so why are all the  Dialect options being 0 (0)? what do they do?
