### ISSUE TITLE
Pro active chat invitation on mobile

### ISSUE THREAD

**Issue by visionieu** [LiveHelperChat/livehelperchat#1105]
Hi, we are using Live Helper Chat, and we find it great.
According to our experience, could be interesting, to show the mobile user, the pro active chat, or at  least, the message sent from active user list.
Thank you,
Francesco

**Comment by webriz** [comment]
Hi,
Also for me not working on mobile browser the 'pro active chat' and message sent from active user list.

**Comment by PeopleInside** [comment]
Pro active chat on mobile is not supported at the moment.

**Comment by PeopleInside** [comment]
Pro active support was added on version 2.77
seems manual pro active invitation from visitor list still not work on mobile, maybe should be implemented also so operator will be able to send manual pro active / message also if the visitor is on mobile.

**Comment by PeopleInside** [comment]
Hi, this issue seems to be solved as was implemented. If there are any reason this stay open let us know.
