### ISSUE TITLE
cant Import themes

### ISSUE THREAD

**Issue by raykai** [LiveHelperChat/livehelperchat#1108]
ok so i tried importing 3 themes from [https://livehelperchat.com/free-themes-22c.html](https://livehelperchat.com/free-themes-22c.html)

but its not working im on the master version and im not getting  any php errors...  all i see is this 
![bug](https://user-images.githubusercontent.com/8138894/30677791-db1bc344-9e5b-11e7-9147-0da276fd2c54.JPG)

**Comment by PeopleInside** [comment]
Hi, thank you for the report.
Are you trying to import an old theme in a new version?

**Comment by PeopleInside** [comment]
Another user has reported this issue:
https://forum.livehelperchat.com/viewtopic.php?pid=10815#p10815

**Comment by Hamburgo58** [comment]
yes, i have the same problem with the theme dark-red-theme.json.

I do not know, if it is a old one or not.

**Comment by remdex** [comment]
This issue was fixed in the related commit. Just update.

**Comment by Hamburgo58** [comment]
yes, this bug is fixed after this update. I was be able to import the theme. Thanks

**Comment by raykai** [comment]
How should we update? the admin panel says Your version - 2.73 Current version - 2.73 : Your database does not require any updates. so how should we proceed?

**Comment by PeopleInside** [comment]
Hi, for update now with the fix you can download the package here:
https://livehelperchat.com/article/static/5
and simply replace the edited file or follow the update procedure here:
https://livehelperchat.com/article/view/63

thank you!

Made a backup of folder and database before do any actions.
