### ISSUE TITLE
Emails sent continuously when there is new chat

### ISSUE THREAD

**Issue by samapraku** [LiveHelperChat/livehelperchat#1109]
Hello,

After upgrading to version 2.73, when there is a new chat request, LHC sends many emails for New chat Request until the chat is accepted.

**Comment by PeopleInside** [comment]
Hi, thank you for your report!
Do you mean you have set email notification for new chat but you receve more than one email for the same pending chat?

**Comment by samapco** [comment]
Yes. More emails are sent repeatedly

**Comment by PeopleInside** [comment]
Hope if this is an issue in Live helper chat will be fixed.
Thank you for your report, will be rewieved as soon as possibile :)

**Comment by samapraku** [comment]
This issue has been resolved
