### ISSUE TITLE
Speech page strange, missing info?

### ISSUE THREAD

**Issue by raykai** [LiveHelperChat/livehelperchat#1115]
ok so in Home > System  configuration > Default speech recognition language:

there is a list under Dialect there all 0 (0) .... so what do they do? what are they? maybe best to add something more than 0 (0) as a name for each one? don't seem to have a documentation page about this.

should be fixed as seen here: https://github.com/LiveHelperChat/livehelperchat/issues/1104 but only part has been fixed. seems like im not the only one wondering what the difference is with the Dialect options.

**Comment by remdex** [comment]
This one should be fixed already in recent version.
