### ISSUE TITLE
Cookie law, need list of cookie used

### ISSUE THREAD

**Issue by raykai** [LiveHelperChat/livehelperchat#1117]
Hi, i would need the list of cookies this software uses. need its name, description of what its used for and the duration it stays on the user's device.

This is common info we need to display on a cookie privacy page required by law. Would be good to have this in the documentation too for others to use.

**Comment by raykai** [comment]
bump i really need this.

**Comment by raykai** [comment]
bump.

**Comment by black23** [comment]
Related to #1161

**Comment by remdex** [comment]
lhc_per - stores unique online visitor hash. Information was need help tooltip shown or not.
lhc_ses - stores session data as widget positions, current chat hash.

**Comment by PeopleInside** [comment]
This topic seems to be related to an answered / resolved question, i will close it. 
If there are any reason this should stay open let us know :)
