### ISSUE TITLE
Errors after updating ver 2.71

### ISSUE THREAD

**Issue by KatTek73** [LiveHelperChat/livehelperchat#1118]
Hi,
After updating Live Helper Chat to version 2.71, I get error messages:
<img width="682" alt="nayttokuva 2017-09-28 kello 13 25 57" src="https://user-images.githubusercontent.com/32359176/30962258-b8e6eabe-a451-11e7-8c67-df9aee11f15f.png">
Auto responser do not work properly. What went wrong? Does it help, if I update to version 2.73?

**Comment by PeopleInside** [comment]
Hi,
have you updated the database also?
What procedure you follow for update?

**Comment by KatTek73** [comment]
Hi,
Yes I have.
I followed this procedure  https://livehelperchat.com/article/view/63

Thank you for your help!

**Comment by PeopleInside** [comment]
Strange you have issue, seems like your database is corrupted. How is the update screen ? If you go on the update page on your install? It's all updated?

**Comment by KatTek73** [comment]
Everything was okay during the update process and all was updated. But now there is the error message in the update screen and we are having problems with auto responser.

**Comment by KatTek73** [comment]
Now updated to version 2.73 and errors are gone. Still having issues with auto responser.

**Comment by PeopleInside** [comment]
Sorry I cannopt help with that. Corruption of Database are something that I do not know. You need wait or ask Commercial Support https://forum.livehelperchat.com/viewtopic.php?id=2255

Another solution is resume the backup at the last version who worked and try to update more carefully. Something went wrong maybe in your update.

**Comment by KatTek73** [comment]
Ok, thank you :)
