### ISSUE TITLE
iOS Safari: chatwindow scroll away and disappeares (tested on 9.3.5)

### ISSUE THREAD

**Issue by Marnix-gefeliciTAART** [LiveHelperChat/livehelperchat#1119]
When starting a chat as a customer and selecting the box to write down your name, the popup disappeares.

**Comment by PeopleInside** [comment]
Thank you for the topic @Marnix-gefeliciTAART ,
please can you check if the issue is also present here:
https://livehelperchat.com/
on the demo?
Are you able to reproduce?

**Comment by Marnix-gefeliciTAART** [comment]
Hi Marco, 

Thank you for your fast reply. Yes it does occur on your site aswell. 

 	* i tap the "help is available"
 	* the panel with your welcome message shows
 	* i tap in the textarea "write your message here"
 	* the screen scrolls a little. After some searching, i find the panel
at the end of the page (scrolled to the bottom of the document). A cusor
is blinking in the textarea. 

 While reproducing several times, the first time is different to the
following times: 

First reproduction: my on screen keyboard opens and the chat panel
disappears. 

following reproductions: my text appears, but I can't have any other
interaction with the chat panel: 

 	* it doesn't respond to tapping the x to close
 	* after blur (by tapping on the page), I can't reselect the textarea

would you like screenprints with this? 

Kind regards, 

Marnix Keer 

gefeliciTAART.nl 

On 2017-09-29 11:34, Marco wrote:

> Thank you for the topic @Marnix-gefeliciTAART [1] ,
> please can you check if the issue is also present here:
> https://livehelperchat.com/
> on the demo?
> Are you able to reproduce? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/marnix-gefelicitaart
[2]
https://github.com/LiveHelperChat/livehelperchat/issues/1119#issuecomment-333079993
[3]

**Comment by PeopleInside** [comment]
Thank you for the report, will be review from the chat owner.
Maybe some screen can help the chat owner. :)
Have a great day!

**Comment by Marnix-gefeliciTAART** [comment]
Ok, here are screens from the process. 

thank you for looking into this.

On 2017-09-29 12:01, Marco wrote:

> Thank you for the report, will be review from the chat owner.
> Maybe some screen can help the chat owner. :)
> Have a great day! 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/LiveHelperChat/livehelperchat/issues/1119#issuecomment-333086068
[2]
