### ISSUE TITLE
Transfer chat permission per department

### ISSUE THREAD

**Issue by zoelca** [LiveHelperChat/livehelperchat#1121]
Hi,

We need to allow to transfer a chat from department1 to deapartment2, but no from department2 to deapartment2

I have 2 active departments in my chat, and operators can only be included in one department, i mean: if operator1 is in department1 will never be assigned to department2

Users can only start chat to department2 if they are logged as users in our web (subdomain.ourdomain.com)
Users can start chat to department1 always (when they are logged in our web in "subdomain.ourdomain.com" and if they are not logged, in domain "ourdomain.com"
It's configured in empbed code and codes included in our web (Joomla)

I need to configure that operators from department1 can transfer chats to department2 but operators in deparment2 cant transfer chats from department2 to deapartment1

Is there a way to configure this from administration? How?

Thanks in advance!

It comes from https://forum.livehelperchat.com/viewtopic.php?id=2677

**Comment by remdex** [comment]
All this is in documentation now...
