### ISSUE TITLE
Possibility to disable - offline requests storage

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1126]
Forum request:
https://forum.livehelperchat.com/viewtopic.php?id=2685

> Hi,
> 
> with Version 2.72 - offline requests storage was introduced. It's a nice feature, but would also nice if I could disable it.

**Comment by PeopleInside** [comment]
When an offline message is opened from admin operator console:
- sound notification for offline message should be reproduced just once and not more as for pending chats
- in the offline message (operator window) should be disable the filed to send a message. The look seems the look of an opened chat when is an offline message. The look of the window should be as a closed chat not opened.

**Comment by remdex** [comment]
Option to disable storage for offline messages are done. The other things won't be changed.
