### ISSUE TITLE
How can I store a custom field value when user starts chat?

### ISSUE THREAD

**Issue by serveiwebs** [LiveHelperChat/livehelperchat#1129]
Hello,
I want to store a custom id field value (it's calculated by code in the page) when a new visitor starts a chat. I've created a new field name 'IDfield' in table lh_chat, but I don't see the way to store a string value in this field when the user start the chat.
How can I do this?

Thanks a lot and kind regards.

**Comment by remdex** [comment]
https://livehelperchat.com/pre-filling-form-fields-and-adding-custom-fields-140a.html
You do not need new table field. Just prefill field in JS
