### ISSUE TITLE
Custom fields within the contact form

### ISSUE THREAD

**Issue by angeljs6** [LiveHelperChat/livehelperchat#1131]
Is it possible to have a custom field for when the visitor asks a question? At the moment, I can only see 'Email' and 'Question'. I'd like to be able to add different fields, such as 'Order Number', 'Country' etc.

**Comment by remdex** [comment]
Yes, in start chat form settings page.

**Comment by angeljs6** [comment]
I can't see to find those settings.

**Comment by PeopleInside** [comment]
Settings >> Live help configuration (tab) >> Start chat form settings >>

**Comment by angeljs6** [comment]
I don't have that tab, for some reason :(
![bizweb](https://user-images.githubusercontent.com/26563865/33447951-a0e77636-d5fc-11e7-8a49-fdeedb9d35ea.jpg)

**Comment by PeopleInside** [comment]
This doesn't seem live helper chat
