### ISSUE TITLE
2 step authentication 

### ISSUE THREAD

**Issue by ArjonBu** [LiveHelperChat/livehelperchat#1132]
It would be great to have 2 step authentication to LHC.

**Comment by remdex** [comment]
It's under way. Together with - #1173

**Comment by black23** [comment]
It's not same like SSO. Its second layer of sing-in procedure. SSO It's one login information fo many systems. 2 way (factor) autehntification is one code thath system ask on login.
https://developers.yubico.com/php-yubico/
https://www.codementor.io/slavko/google-two-step-authentication-otp-generation-du1082vho

**Comment by remdex** [comment]
I know. But it will support both cases.
