### ISSUE TITLE
New updates made new important BUG: work schedule/office hours

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1138]
The work time are not working anymore, chat is always online.
I AM able to see this issue to also reported on the forum:
https://forum.livehelperchat.com/viewtopic.php?id=2718

Seems with each new update important BUG are created :-) so maybe do less update :D

**Comment by PeopleInside** [comment]
Not Valid. Checking Status operator and settings. Close this as invalid.

**Comment by luanjsc** [comment]
is it possible set ('disabled' at option) page initial, when outside the configured time?

**Comment by PeopleInside** [comment]
@luanjsc I cannot understand what you mean

**Comment by luanjsc** [comment]
department out of the configured time -> (add (option disabled value="depart_id"))

![fill in the form to start a chat - live helper chat](https://user-images.githubusercontent.com/32711794/32669348-5b5975f4-c627-11e7-8195-3e5c85f0d097.jpg)

**Comment by PeopleInside** [comment]
The department is disabled or hidden in the department settings?
