### ISSUE TITLE
cannot finish the installation ( redirect back to first page )

### ISSUE THREAD

**Issue by rezk2ll** [LiveHelperChat/livehelperchat#1140]
Hello,
whenever I try to install the latest version of Livehelperchat in my server I fail,
* after creating a database I head to the installation page to face this screen:

![image](https://user-images.githubusercontent.com/6764881/32886256-6d121d9e-cac0-11e7-8cbb-06c931110e5b.png)

* then, I filled the database connection parameters and continued to the next step

* in this third I step, whenever I try to submit and continue I get redirected back to the first step.

![image](https://user-images.githubusercontent.com/6764881/32886418-eac7303a-cac0-11e7-8144-2695a97520b8.png)

how can i fix this?

**Comment by PeopleInside** [comment]
Hi,
what version of PHP are you using?
PHP should be minimum 5.6 (is old) last PHP is 7.1

Are you installing last version 2.76?
Is mod_rewrite active?

**Comment by rezk2ll** [comment]
Hi,
I have `PHP 5.6.31`, I'm using the latest version in GitHub `2.75v` i guess ( just pulled the code now half an hour ago), also `rewrite_module` is enabled.

**Comment by PeopleInside** [comment]
Do you have any error logs on the server?
Please check.

**Comment by rezk2ll** [comment]
I already did that, `/var/log/httpd/error_log` has nothing.

**Comment by PeopleInside** [comment]
Maybe there are some issue on your server.
Maybe can be where you are trying to install the livechat. 
If you are trying in root try to do the install in a folder, check .htaccess and server settings.
I have no other suggestion at the moment.

**Comment by rezk2ll** [comment]
I tried installing it on a local server, then I uploaded the files to the server, and imported the database there, and modified the `settings.ini.php` ( updated the MySQL server credentials ).

now i'm getting this error `Cannot connect to database. If you are installing application please use /index.php/install/install url. If you keep getting this error please check that application can write to cache folder and cgi.fix_pathinfo = 1`.

even though the credentials are correct, it cannot connect to the database, could it be something related to PHP modules? I have Drupal installed on the server and it's working perfectly fine, so I doubt that.

**Comment by remdex** [comment]
Just,
https://livehelperchat.com/article/view/58

**Comment by rezk2ll** [comment]
I did set the `debug_output` to true in the settings.ini.php but nothing showed up, no debug messages.

**Comment by dphelpsBrownco** [comment]
Has this issue ever been resolved?  I'm having the same difficulty.  The LiveChat with LiveChat told me to look on GitHub.  Looks like this is just more of the same lack of answers.

**Comment by rezk2ll** [comment]
I found the issue ( in my case ), my MySQL server does not support `utf8mb4`.
after some debugging, I got
```
SQLSTATE[42000]: Syntax error or access violation: 1115 Unknown character set: 'utf8mb4'
```

the solution is to upgrade your MySQL server.
