### ISSUE TITLE
After updates to 2.76 / 2.77 Existing Survey not accesible (blank page)

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1142]
Hi,
I have the same issue on two different installation upgraded.

I think should be an issue somewhere. I AM with Apache and PHP 7.1
When I load survey list than click on a survey a blank page is showed.

Error logs report:

 [proxy_fcgi:error] 
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'ezcPersistentFindQuery' not found

**Comment by remdex** [comment]
Sorry, but I think it's your installation error or something. It's kernel class which is loaded by autoloader. Try to re-upload ezcomponents directory.

**Comment by PeopleInside** [comment]
Thank you remdex, I tried a clean install from Softacolous and issue is the same.

**Comment by PeopleInside** [comment]
OK I enabled debug same issue in two installations and debug find two different random string php file located on cache/compiledtemplates/ with error:

> Parse error: syntax error, unexpected '<', expecting end of file in

So I opened the file and I see:
![wrong](https://user-images.githubusercontent.com/5006150/32966567-6e881dac-cbda-11e7-9cd7-f9c48deb46ef.png)

So I fixed

![fixed](https://user-images.githubusercontent.com/5006150/32966573-7a099c0a-cbda-11e7-8360-118d085cb681.png)

and now is working. Why this error? This random file seems to be with different name in different installation, are generated from another file that miss the` ?>` ?
