### ISSUE TITLE
Issue from the forum: Some translation is not working

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1150]
https://forum.livehelperchat.com/viewtopic.php?id=2737
Seems the issue is also present on the Italian translation so maybe all translation.
See the forum topic for more info.

**Comment by PeopleInside** [comment]
User has added another forum topic with a little bit notes:
https://forum.livehelperchat.com/viewtopic.php?id=2740

**Comment by remdex** [comment]
Implemented. Updated in this commit #6e369b8ca25b70bdf94db1bfe53c2eb324330f16
