### ISSUE TITLE
Idea from the forum: add massive close pending chat (chatlist)

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1156]
Hi,
from the forum post 
https://forum.livehelperchat.com/viewtopic.php?pid=11260#p11260

can be a nice idea allow listed pending chat to be selected and close with a button. Actually maybe you can only delete. For pending chat admin should have possibility to mass close pending chats.

**Comment by PeopleInside** [comment]
+ 1 
https://forum.livehelperchat.com/viewtopic.php?id=2775

**Comment by remdex** [comment]
This one implemented already i think.
