### ISSUE TITLE
API documentation: Active chats

### ISSUE THREAD

**Issue by koosvanderkolk** [LiveHelperChat/livehelperchat#1168]
On 

it says
```PHP
/* 
 * Possible values for status
 * 
    const STATUS_PENDING_CHAT = 0;
    const STATUS_ACTIVE_CHAT = 1;
    const STATUS_CLOSED_CHAT = 2;
    const STATUS_CHATBOX_CHAT = 3;
    const STATUS_OPERATORS_CHAT = 4;
*/
// Fetch chats
$response = $LHCRestAPI->execute('chats', array(
    'status' => 1,
    'departament_id' => 5,
    'user_id' => 1,
    'update_activity' => 1 // Forces to update last acitivity, can be used with any call <optional>
));
print_r($response);
```

Are the provided arguments (status, departament_id, user_id, update_activity) optional or mandatory?

I would expect them to be filters, so if no arguments provided: all chats are being returned, if status provided: only chats having that status, etc.

**Comment by remdex** [comment]
They all are optional. I have also just run Swagger page for documentation. https://api.livehelperchat.com/#/
