### ISSUE TITLE
Connection restored -> user can't chat

### ISSUE THREAD

**Issue by ujja** [LiveHelperChat/livehelperchat#1170]
Tested on demo environment

1 User writes something, operator gets it (the text is displayed in black for the user)
2 connection lost
3 user writes something, operator does not get it (text is gray)
4 connection back 
5 user writes something, operator does not get it (text is gray) !!!

**Comment by remdex** [comment]
How you tested this? turning off internet? :D

**Comment by ujja** [comment]
yes. :)
switched off my wifi connection.
