### ISSUE TITLE
load html in module faq

### ISSUE THREAD

**Issue by marcipriano** [LiveHelperChat/livehelperchat#1171]
is it possible to put the faq module with an html editor and not just plain text? If it were possible we could have a much more advanced knowledge base module for the users.

**Comment by marcipriano** [comment]
extension for load html in module faq
https://github.com/marcipriano/faqloadhtml

**Comment by marcipriano** [comment]
I'm trying to upload the image in summernote. at the moment it just saves the binary in html and this generates error depending on the size of the image. I found an upload class but I have to create a route to upload the image. know in which file I should create the faq module route and in which class do I add an upload function?

**Comment by Marnix-gefeliciTAART** [comment]
Excuse me if I say foolish things, but could it work to embed images as base64 data?

**Comment by marcipriano** [comment]
Hello, sorry for the delay in responding ... the summernote sends as base64 images even. But depending on the size, say the size of the field type where it is stored. was working for the release of the media manager. ms is missing time
