### ISSUE TITLE
Suggestion: chat tagging

### ISSUE THREAD

**Issue by Marnix-gefeliciTAART** [LiveHelperChat/livehelperchat#1176]
I'd like to get a feel for which questions are asked the most to our customer service. I think tagging chats would help with that: with an overview of most used tags and the option to filter archived chats by tag(s), we could investigate our most common problems. With this info we can improve our site and service.

**Comment by remdex** [comment]
Should it support multiple tags per chat or single?

**Comment by Marnix-gefeliciTAART** [comment]
I guess any tagging would be nice (the tag would be the main subject of a chat); but when building this, why not support multiple to allow additional subjects from the chat to be added as tag.

**Comment by remdex** [comment]
Implemented. New version released.

**Comment by Marnix-gefeliciTAART** [comment]
I have been looking how this is implemented; is it the 'subject' field?
How do I get an overview of which tags have been used and how often they have been used?
Can I see which chats are labelled by a specific tag?

**Comment by remdex** [comment]
At the moment only setting chat subject or multiple subjects are set. In statistic this at the moment is not represented will be enhanced in next few versions :)

**Comment by Marnix-gefeliciTAART** [comment]
Ah, nice!
Thanks for your fast response! :)
