### ISSUE TITLE
Chat users are viewing exchanged messages of other users

### ISSUE THREAD

**Issue by Cadorin** [LiveHelperChat/livehelperchat#1177]
Code: Live help embed code

Context: I tested this on my computer, operating with two browser windows, each one for a different username. The idea is to simulate two different visitors using the same computer or in a network with shared valid external IP. There is only one operator that is chatting with both visitors.

Problem:
When visitors start chatting, there is no problem. Each opens a chat in the browser and the operator can view and chat with them. However, when one of the visitors reloads the page, it loses access to your chat and takes the chat from the other visitor, accessing the messages already sent and even sending messages as if it were the other visitor. This is true even if the other visitor had already closed your window.

Reference: https://forum.livehelperchat.com/viewtopic.php?pid=11525#p11525

**Comment by remdex** [comment]
Sorry, but i cannot reproduce your problem. Are you sure you are not embeding chatbox instead of live help widget? IP or browser really does not have any influence.

**Comment by Cadorin** [comment]
I am pretty sure!

To reproduce is just need to open 2 tabs on your browser (I am using
Chrome) and start a chat. Keep the messages on queue, no problem. The
operator with see the 2 chats and he can chat separately with them. Until
this point, no problems at all.

However, if you reload one of the pages this one will replicate the chat of
the other user and both tabs will be like one.

Please, try one more time following what I said now. If you still can't see
the problem maybe I can record a movie to show you the problem.

Thanks for your quick reply

Best regards
Eduardo Cadorin



Em 29 de jan de 2018 15:43, "Remigijus Kiminas" <notifications@github.com>
escreveu:

**Comment by remdex** [comment]
Cookie is stored per browser it's unique per browser. Not per browser tab :) Open incognito window and try again or just firefox and chrome. In that case it's normal behaviour :)

**Comment by Cadorin** [comment]
Hello. 
With the incognito window the problem doesn't occur, so it is a cookie issue. You said it is normal behaviour, but it matters to me. Could you tell me the name of the cookie the system create and in what file I can find the code that deals with the cookies? Thanks for supporting!

**Comment by remdex** [comment]
It's not an issue all sites and web in general works that way. You won't be able just technically set cookie per browser tab. It just does not work like that.

**Comment by Cadorin** [comment]
I did few modifications in your code and I could overcome this problem. Now I have the chat working per tab!

**Comment by Cadorin** [comment]
Hey,

I did few modifications in your code and I could overcome this problem. Now
I have the chat working per tab!



2018-01-30 7:34 GMT+01:00 Remigijus Kiminas <notifications@github.com>:

**Comment by remdex** [comment]
Just for purpose of interest could you share these changes? :)

**Comment by Cadorin** [comment]
Actually, I can. As I said you before, it was very few modifications. Maybe
it is not the best way to do this, but considering that you - the developer
- said I wouldn't be able to do, I think I found my way.

First I created a variable in the URL called by (code)/<?=$code?>. This
$code identifies the operator of my system using the tab browser. So, each
tab has a different $code, then I have a way to know which tab I'm working
with.

Then, I looked in your code to find where you set the cookies (I have
requested that for you, but you didn't tell me!).

By doing a search at linux terminal I found 3 main files:

/design/defaulttheme/tpl/lhchat/getstatus.tpl.php,
/design/defaulttheme/tpl/lhchat/getstatusembed.tpl.php
/design/defaulttheme/tpl/lhchat/getstatus/functions/init_session_storage.tpl.php

In these 3 files I found the functions :

- storeSesCookie : function(){

- initSessionStorage : function(){

which I added  the lines below:
<?php
  $identificador=$_SERVER['REQUEST_URI'];
  $arr = explode('/(code)/', $identificador);
  $arr = explode('/', $arr[1]);
  $identificador = $arr[0];
?>

These lines aim to get this special $code from the main URL.

And also I changed the cookie names from lhc_ses to
lhc_ses_<?=$identificador?>.

These modifications were the trick. It is working perfectly now.

Hope it can help you to improve the chat. Thank you for your support, even
if you believed it could not be done.

Eduardo Cadorin




2018-01-30 15:45 GMT+01:00 Remigijus Kiminas <notifications@github.com>:
