### ISSUE TITLE
Error on create table on install 2.86 version

### ISSUE THREAD

**Issue by taillis** [LiveHelperChat/livehelperchat#1180]
I'm trying to install the latest version of the chat and I'm getting the fallowed error in lh_faq table:

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

**Comment by remdex** [comment]
Hi,
You have to update your mysql server to 5.7 minimum to support utf8mb4 in utf8mb4_unicode_ci collation.

**Comment by taillis** [comment]
Hi, I already have the 5.7.19 version of MySQL. Thank you for response me.

**Comment by remdex** [comment]
I'll try to put one change perhaps it will help. Give me half hour.

**Comment by taillis** [comment]
OK, I'll waiting for your response, thank you until now!

**Comment by remdex** [comment]
Can you try for me execute. this query, just to test does it works on your server?
```
CREATE TABLE IF NOT EXISTS `lh_faq` (
				  `id` int(11) NOT NULL AUTO_INCREMENT,
				  `question` varchar(250) NOT NULL,
				  `answer` text NOT NULL,
				  `url` varchar(250) NOT NULL,
				  `email` varchar(50) NOT NULL,
				  `identifier` varchar(10) NOT NULL,
				  `active` int(11) NOT NULL,
				  `has_url` tinyint(1) NOT NULL,
				  `is_wildcard` tinyint(1) NOT NULL,
				  PRIMARY KEY (`id`),
				  KEY `active` (`active`),
				  KEY `active_url` (`active`,`url`),
				  KEY `has_url` (`has_url`),
				  KEY `identifier` (`identifier`),
				  KEY `is_wildcard` (`is_wildcard`)
				) ENGINE=InnoDB ROW_FORMAT=DYNAMIC CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

**Comment by taillis** [comment]
I tested here and it worked, my db collation is utf8mb4_unicode_ci, case you needed it.

**Comment by remdex** [comment]
Ok,
I'll update tomorrow. Late here already :)

**Comment by taillis** [comment]
All right, I'm very thankful about your help.

**Comment by remdex** [comment]
Please update and try again :)

**Comment by feltoar** [comment]
Will MySQL 5.7 be the new minimum requirement for LHC? If so perhaps update the Documentation: https://livehelperchat.com/requirements-84a.html

For me running MariaDB 10.0.34 the latest fix unfortunately does not work. There is a new error. Likely due to the shared hosting server being used.

```
ERROR:
SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SUPER privilege(s) for this operation
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
```

**Comment by remdex** [comment]
Ok,
I'll try to reduce index size to 191 I ques.

**Comment by remdex** [comment]
Can you try update again. You may need to click few times just update. Thanks for you help :)

**Comment by feltoar** [comment]
Thank you :) Seems to have worked. Had to click the update button a few times like you said but it now appears to be up to date.

**Comment by taillis** [comment]
I updated here and everything worked properly, thank you for help me.
