### ISSUE TITLE
Trouble with page embed code after install 2.86 version

### ISSUE THREAD

**Issue by taillis** [LiveHelperChat/livehelperchat#1182]
I installed the latest version and now I'm not getting a error, but the page embed code that create a iframe at my page is increasing it height by 15px every time. I searched for some solutions and I'm can't get anything

**Comment by remdex** [comment]
Can you update all files. Regarding this issue. I was solving it this morning.

**Comment by taillis** [comment]
I did it, I download again from github.

**Comment by remdex** [comment]
Ok, managed to reproduce i ques. Will take a look.

**Comment by taillis** [comment]
Thank you, I'll be waiting for your response.

**Comment by remdex** [comment]
Update this one file and clear cache from back office and should be alright :)
https://github.com/LiveHelperChat/livehelperchat/commit/e26b64cc4c8c9bcecb53e848cc8ffbdd28e53ab9

**Comment by taillis** [comment]
It worked now, I cleared cache and everything worked properly, thank you and have a good day :)
