### ISSUE TITLE
Screenshot, Screen Sharing and Microphone chat do not working with me

### ISSUE THREAD

**Issue by taillis** [LiveHelperChat/livehelperchat#1183]
Hi, I need some help to make some functions work properly, I remember that a older version, I guess that was 2.83 I got Screen Sharing working but after this version I can't get anymore. I set it up the nodejs server and put it online and not worked yet. Screenshot does not take any pic and Microphone always ask me to allow it. Can you help me with it? I'm thinking about your translations to Portuguese Brazil, some phrases is in English yet. Can I help you to translate that phrases to PT-BR? I want to make you some donations because we like so much your project and we want to keep it alive. Thank you until now!

**Comment by remdex** [comment]
Hi,

1. Microphone is asked each time if you are not using https
2. Taking screenshot works for me
3. As for co-browsing i'll test next week. last time i tested it worked as it should :)

**Comment by taillis** [comment]
How screenshot works? I try and try but it does not work for me, it does not take any pic, and about the microphone I'm not using https so it will ask me every time, but nothing happens after I allow it. Thank you for response me.

**Comment by taillis** [comment]
Hi, I made the last update and it do not works for me yet. I've tested screenshot, microphone and screen sharing.

**Comment by remdex** [comment]
Sorry, but for me it works. Protocol on site and on lhc installation has to match if site is using https, so chat also has to support https. No other idea at the moment why does not work for you

**Comment by taillis** [comment]
Ok, I'll do update to latest version again and I'll test it.
