### ISSUE TITLE
[BUG] Emoji in Hyperlink

### ISSUE THREAD

**Issue by guilhermecfviana** [LiveHelperChat/livehelperchat#1192]
Version livehelperchat: 2.88

After updating the livehelperchat the links that are used in the conversation have emojis, see the example:

![livehelperchat](https://user-images.githubusercontent.com/17053653/36482118-ef81cfd2-16f0-11e8-983b-4036442a3099.jpg)

Because it was a hyperlink I expected that emoji would not display. How disable emojis, is there an option?

**Comment by remdex** [comment]
This issue was fixed in one of the recent commints. Please update/replace this file https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/lib/core/lhbbcode/lhbbcode.php

**Comment by PeopleInside** [comment]
@guilhermecfviana  you can also subscribe on the Announcement section on the forum: https://forum.livehelperchat.com/viewforum.php?id=2 for important update notification :) I will try to do my best for alert in any important update.

Have a great day :)

**Comment by guilhermecfviana** [comment]
@remdex Thanks, work fine!

@PeopleInside I sub this forum, thanks!
