### ISSUE TITLE
How to integrate a web service in the start form of livehelperchat?

### ISSUE THREAD

**Issue by coutinho17** [LiveHelperChat/livehelperchat#1197]
Hello, a query, it is required to integrate a web service in the start form to consult and save data
Personalized, you could help me.

Thanks.  :)

**Comment by remdex** [comment]
Take a look at, this extension how it handles chat started event and sends data to osticket.
https://github.com/LiveHelperChat/osTicket/blob/master/osticket/bootstrap/bootstrap.php#L30

**Comment by PeopleInside** [comment]
This topic seems to be related to an answered question so i will close it, if there are some reason this should stay open let us know.
