### ISSUE TITLE
Feature request; Categories for the tickets

### ISSUE THREAD

**Issue by Jarvil** [LiveHelperChat/livehelperchat#1199]
Hello,

I would like to use livehelperchat so I could categorize my tickets so operator or Admin should be able to correct the department (transfer to a department) also if is offline or there could be an another way to categorize and create categories for them @remdex

**Comment by remdex** [comment]
At the moment you can use Subjects i ques for that purposes. Department change for chat will be published in few hours.

**Comment by Jarvil** [comment]
Can you provide us screenshot where do you specify the subject and how can you find tickets in specified categories when they are closed? @remdex

**Comment by Jarvil** [comment]
Can you provide us screenshot where do you specify the subject and how can you find tickets in these specified categories when they are closed? @remdex

**Comment by remdex** [comment]
Hi,
At the moment data is collected within chats. But there is no capability to search by it. It will be done in the feature.

**Comment by Jarvil** [comment]
Hello,

Do you mean categories are not available at this moment but will be in 
the future? Do you have timetable?

Urpo Karhula


Remigijus Kiminas kirjoitti 26.4.2018 klo 8.13:

**Comment by remdex** [comment]
Your talked categories are just Subjects. They are available within chat window on the right. Subjects rows. Subjects can be precreated in https://demo.livehelperchat.com/site_admin/abstract/list/Subject So data itself is collected. Just they are not represented in statistic yet. As for timeline. Within 2/3 weeks should appear.

**Comment by Jarvil** [comment]
Hello,

Thank your for your reply, now I understand subjects and can see/create 
subjects. By statistics you mean that after you have made the code they 
can be searched for from closed chats in:

https://demo.livehelperchat.com/site_admin/chat/list

Did I understand correctly?

Urpo Karhula


Remigijus Kiminas kirjoitti 26.4.2018 klo 8.36:

**Comment by remdex** [comment]
Yes that and in Statistic feature at some point.

**Comment by Jarvil** [comment]
Hello,

Thanks you very much, this will be great feature in your great product :)

Urpo Karhula


Remigijus Kiminas kirjoitti 26.4.2018 klo 9.01:

**Comment by Jarvil** [comment]
So in summary for everyone else;

For example in demo site

Back office
https://demo.livehelperchat.com/site_admin/
User: admin
Password: demo

if you open a chat in the right side of the chat window you can see Subjects-row and can select a subject for it. Subjects can be created here:

https://demo.livehelperchat.com/site_admin/abstract/list/Subject

at the moment you can't search closed ticket by subjects in:

https://demo.livehelperchat.com/site_admin/chat/list

but the developer said that feature is coming 2-3 weeks.

![subj1](https://user-images.githubusercontent.com/15193418/39288562-32600fcc-4931-11e8-8b6c-f05cdf626517.PNG)
![subj2](https://user-images.githubusercontent.com/15193418/39288570-368f98a6-4931-11e8-8acf-fd800dfd4041.PNG)
![creatingsubjects](https://user-images.githubusercontent.com/15193418/39288575-394e2f08-4931-11e8-9701-4cfc9dd1fc10.PNG)

**Comment by jensskov** [comment]
Thank you a lot for your work!

In what build were subjects introduced? I do not see them in mine (2.86)

Jens W. Skov

Fra: Erkki Virtanen <notifications@github.com>
Sendt: 26. april 2018 08:07
Til: LiveHelperChat/livehelperchat <livehelperchat@noreply.github.com>
Cc: Jens W. Skov - JS Consult <jens@jsconsult.dk>; Comment <comment@noreply.github.com>
Emne: Re: [LiveHelperChat/livehelperchat] Feature request; Categories for the tickets (#1199)


So in summary for everyone else;

For example in demo site

Back office
https://demo.livehelperchat.com/site_admin/
User: admin
Password: demo

if you open a chat in the right side of the chat window you can see Subjects-row and can select a subject for it. Subjects can be created here:

https://demo.livehelperchat.com/site_admin/abstract/list/Subject

at the moment you can't search closed ticket by subjects in:

https://demo.livehelperchat.com/site_admin/chat/list

but the developer said that feature is coming 2-3 weeks.

[subj1]<https://user-images.githubusercontent.com/15193418/39288562-32600fcc-4931-11e8-8b6c-f05cdf626517.PNG>
[subj2]<https://user-images.githubusercontent.com/15193418/39288570-368f98a6-4931-11e8-8acf-fd800dfd4041.PNG>
[creatingsubjects]<https://user-images.githubusercontent.com/15193418/39288575-394e2f08-4931-11e8-9701-4cfc9dd1fc10.PNG>

**Comment by Jarvil** [comment]
Hello,

The demo site seems to be in version - 2.92

**Comment by remdex** [comment]
Subjects were introduced to 2.87v

**Comment by Jarvil** [comment]
Hello,

Is it already to possible search by subject from closed tickets? @remdex

**Comment by remdex** [comment]
Implemented 2.97v. 
1. Possible to search by subject
2. In statistic will be chart by grouped subjects.
