### ISSUE TITLE
Whatsapp integration

### ISSUE THREAD

**Issue by ArjonBu** [LiveHelperChat/livehelperchat#1205]
Is it possible to have Whatsapp integration? I have seen a couple of live chat services that include it. 
Having an extension for Whatsapp would be great now that it has a version for businesses.

**Comment by remdex** [comment]
What's app does not have official API. That's the biggest issue...

**Comment by Arjoni** [comment]
There is no workaround until they provide the API (if they do)?

**Comment by ArjonBu** [comment]
@remdex There is an API for Whatsapp for business.

**Comment by dkwiebe** [comment]
We'd be interested in sponsoring this once their business API is generally available. So far you have to send them your details for their consideration.

**Comment by dkwiebe** [comment]
The Twilio Whatsapp interface might be a simple way to do this as you already have an existing Twilio integration.  https://www.twilio.com/docs/sms/whatsapp/api

**Comment by jersonjunior** [comment]
Twillio SMS is similar to WhatsApp Twillio API, it would be interesting to suporte this resource in livechathelper

**Comment by ArjonBu** [comment]
@remdex any feedback about this?

**Comment by jersonjunior** [comment]
https://www.twilio.com/docs/sms/whatsapp/api#configuring-inbound-message-webhooks

**Receiving a WhatsApp message**
The web hook for inbound messages uses the same format as incoming SMS messages, with the exception that To and From addresses will be set to WhatsApp addresses (whatsapp:<your E.164 number> and whatsapp:<User's E.164 phone number>) respectively.

**Comment by remdex** [comment]
Hi,
Callback is processed here
https://github.com/LiveHelperChat/twilio/blob/master/modules/lhtwilio/callbacks.php

At the end this function is called
https://github.com/LiveHelperChat/twilio/blob/1cdbbfe02711c31e8fb140385ac4a8e612e67966/bootstrap/bootstrap.php#L441

**Comment by jersonjunior** [comment]
When Twilio sends message to LHC I get back error 503, I believe it's because of To: and From: I'm going to try to implement whatsapp: phonenumber in callbacks but I'm not a developer, but with your tip, it's already a good way.

**Comment by jersonjunior** [comment]
Looks rhe Format of WhatsApp Twillio:

Array
(
    [SmsMessageSid] => SM3b22472402ca531aaf5ccd6555b452cf
    [NumMedia] => 0
    [SmsSid] => SM3b22472402ca531aaf5ccd6555b452cf
    [SmsStatus] => received
    [Body] => Ol?
    [To] => whatsapp:+14155238886
    [NumSegments] => 1
    [MessageSid] => SM3b22472402ca531aaf5ccd6555b452cf
    [AccountSid] => AC663f71df6c2e243ea4836527808067df
    [From] => whatsapp:+556198002190
    [ApiVersion] => 2010-04-01
)

**Comment by jersonjunior** [comment]
Hi @dkwiebe 

Always when the twilio consumes the callbacks I get the following error:

**HTTP Error 500: Internal Server Error**


If I remove the code block below the callbacks.php I get consume the callbacks, something happens in the block:
```
try {
    $dynmarkSMS = erLhcoreClassModule::getExtensionInstance('erLhcoreClassExtensionTwilio');
    $dynmarkSMS->processCallback($dumpArray);
} catch (Exception $e) {
   throw $e;
    erLhcoreClassLog::write(print_r($_POST,true));
    erLhcoreClassLog::write(print_r($e,true));
}
```

I saw that you commented on a part of the code that I believe you used for tests in the Twilio standard, could it help with how I can consume the callbacks without using twilio for testing?

**Comment by remdex** [comment]
Hi,

Just enter in your browser url like http://example.com/twilio/callbacks

**Comment by jersonjunior** [comment]
Is not working!
I always get the HTTP 500 ERROR return. 

It works when I remove the try block
try {
    $dynmarkSMS = erLhcoreClassModule::getExtensionInstance('erLhcoreClassExtensionTwilio');
    $dynmarkSMS->processCallback($dumpArray);
} catch (Exception $e) {
    throw $e;
    erLhcoreClassLog::write(print_r($_POST,true));
    erLhcoreClassLog::write(print_r($e,true));
}

**Comment by jersonjunior** [comment]
@remdex 

Thanks for the help!
I was able to implement **Twilio Whatsapp** by modifying the file

/var/www/volts.eng.br/public_html/chat/extension/twilio/design/twiliotheme/tpl/lhtwilio/parts

**Original:**
`<input type="text" maxlength="**15**" class="form-control" name="phone" value="<?php echo htmlspecialchars($item->phone)?>" />`

**Modified:**
**`<input type="text" maxlength="**25**" class="form-control" name="phone" value="<?php echo htmlspecialchars($item->phone)?>" />`**

And change install.sql

**Original:**
```
CREATE TABLE `lhc_twilio_chat` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `chat_id` bigint(20) unsigned NOT NULL, `phone` varchar(**15**) NOT NULL, `ctime` int(11) NOT NULL, `utime` int(11) NOT NULL, `tphone_id` int(11) NOT NULL, PRIMARY KEY (`id`),  KEY `phone_utime` (`phone`,`utime`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `lhc_twilio_phone` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `phone` varchar(**15**) NOT NULL,`originator` varchar(15) NOT NULL, `account_sid` varchar(35), `auth_token` varchar(35), `dep_id` int(11) unsigned NOT NULL, `chat_timeout` int(11) unsigned NOT NULL, PRIMARY KEY (`id`), KEY `phone` (`phone`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Modified:**
```
CREATE TABLE `lhc_twilio_chat` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `chat_id` bigint(20) unsigned NOT NULL, `phone` varchar(**25**) NOT NULL, `ctime` int(11) NOT NULL, `utime` int(11) NOT NULL, `tphone_id` int(11) NOT NULL, PRIMARY KEY (`id`),  KEY `phone_utime` (`phone`,`utime`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `lhc_twilio_phone` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `phone` varchar(**25**) NOT NULL,`originator` varchar(15) NOT NULL, `account_sid` varchar(35), `auth_token` varchar(35), `dep_id` int(11) unsigned NOT NULL, `chat_timeout` int(11) unsigned NOT NULL, PRIMARY KEY (`id`), KEY `phone` (`phone`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
The changes allowed to register the Phone with whatsapp: +14155238886 standard of **Twilio**.

The changes allowed to register the Phone with whatsapp: +14155238886 standard of Twilio and the callback to receive FROM and TO in format whatsapp: + phonenumber

![image](https://user-images.githubusercontent.com/7052700/50771776-c4de8580-1272-11e9-879f-da3c1452d3dc.png)

**Comment by remdex** [comment]
@jersonjunior Your changes were applied to to master branch of twilio extension.
