### ISSUE TITLE
407 Proxy Authentication Required - Widget not displaying in the website

### ISSUE THREAD

**Issue by deeneshchowdhary** [LiveHelperChat/livehelperchat#1214]
Can someone please help me with this issue?

Request URL : https://chat.example.comindex.php/chat/getstatus/(click)/internal/(position)/bottom_right/(ma)/br/(check_operator_messages)/true/(top)/350/(units)/pixels/(leaveamessage)/true/(department)/2/(theme)/1?r=//www.example.com/&l=//www.example.com/contact
Status Code: 407 proxy Authentication Required

Issue is the widget is not displaying in the website. I have replaced my domain with example.com.
---
The widget code I have used it.

<script type="text/javascript">
var LHCChatOptions = {};
LHCChatOptions.opt = {widget_height:400,widget_width:300,popup_height:520,popup_width:500,domain:'example.com'};
(function() {
var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
var referrer = (document.referrer) ? encodeURIComponent(document.referrer.substr(document.referrer.indexOf('://')+1)) : '';
var location  = (document.location) ? encodeURIComponent(window.location.href.substring(window.location.protocol.length)) : '';
po.src = '//chat.example.com/index.php/chat/getstatus/(click)/internal/(position)/bottom_right/(ma)/br/(check_operator_messages)/true/(top)/350/(units)/pixels/(leaveamessage)/true/(department)/2/(theme)/1?r='+referrer+'&l='+location;
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
})();
</script>

Thank you,

**Comment by blomman9** [comment]
What if you open the getstatus url in a new window? Same header? If
prompted for username password can you get to see Javascript code and if so
go back to the main page and refresh. It might be that your chat requires
login for access.

**Comment by deeneshchowdhary** [comment]
hi @blomman9, thank you! I tried that and did not help.

The problem was in the https conf file. I had to add "/" at the end of the domain name.
Example : https://example.com/ instead of https://example.com
