### ISSUE TITLE
Auto Assign Not assigning

### ISSUE THREAD

**Issue by deeneshchowdhary** [LiveHelperChat/livehelperchat#1218]
![image](https://user-images.githubusercontent.com/7607347/39945363-d42fe5a2-552f-11e8-92c4-304e95ebf6a8.png)

I have turned on the auto assign for a department and add operators but auto assign feature does not seem to be working.  Chat goes pending to one operator and never moves around. Can someone please help?

**Comment by remdex** [comment]
Hi,
1. In order auto assignment to work you have to assign department explicitly to operators. Assign all departments won't work. It's mentioned on documentation. It's one of possible reasons. Other reasons requires logging to your instance etc. But this feature works for sure.
