### ISSUE TITLE
Saving new Theme: ERROR 503

### ISSUE THREAD

**Issue by rafanake** [LiveHelperChat/livehelperchat#1232]
Looks like theres a really problem when trying to add a new theme

The same thing is happening at the demo version
https://demo.livehelperchat.com/site_admin/abstract/new/WidgetTheme

**Comment by PeopleInside** [comment]
Thank you for your report. Seems in the demo if a new widget theme is saved a blank page is showed and the new theme is not saved. I can confirm that on the demo, chat owner will review this issue as soon as possible :)
