### ISSUE TITLE
User login events not working?

### ISSUE THREAD

**Issue by rehv** [LiveHelperChat/livehelperchat#1236]
Hi, I have an issue with the user login events dispatched in [livehelperchat/lhc_web/modules/lhuser/login.php](https://github.com/LiveHelperChat/livehelperchat/blob/99382622c020a306dc0ec92f146cdc604ee027d7/lhc_web/modules/lhuser/login.php). 

I have successfully used other lhc events, but "user.login_after_success_authenticate" and "user.login_site_access" don't work for me. I tried searching for examples using these, but couldn't find any.

Here is the relevant code:
```
    public function run() {

        $dispatcher = erLhcoreClassChatEventDispatcher::getInstance();

        // Attatch event listeners
        $dispatcher->listen('user.login_after_success_authenticate', array($this, 'userLoginAfterAuth'));
        $dispatcher->listen('user.login_site_access', array($this, 'userLoginSiteAccess'));
        $dispatcher->listen('chat.operator_status_changed', array($this, 'userStatusChanged'));
    }

    public function userLoginAfterAuth($params) {
        self::consoleLog('userLoginAfterAuth'); //something to set XDebug breakpoint
    }

    public function userLoginSiteAccess($params) {
        self::consoleLog('userLoginSiteAccess'); //something to set XDebug breakpoint
    }

    public function userStatusChanged($params) {
        self::consoleLog('userStatusChanged'); //something to set XDebug breakpoint
        $hide_online = $params['user']->hide_online;
    }
```

The function userStatusChanged works, but the login ones don't. I use XDebug and a log so I'm sure they're not being called. Is it not working properly?

**Comment by remdex** [comment]
Hi,

Your syntax looks correct and for me these events works. Perhaps you have overridden login module where these events are missing?

**Comment by rehv** [comment]
Hi @remdex and thanks for your reply! You are absolutely correct, I only copied your customstatus extension example to test some events and only modified bootstrap.php so of course I forgot to check that this extension overrides login module. I'm sorry for wasting your time, and thanks again for replying!
