### ISSUE TITLE
Error in statistics filter

### ISSUE THREAD

**Issue by rodrigopalacio** [LiveHelperChat/livehelperchat#1244]
In statistics, when selecting "Exclude offline request from charts", it shows the same values as without selecting the option. The "Show only offline requests" shows values correctly.

Is it a global issue?

**Comment by remdex** [comment]
Fixed just replace https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/lib/core/lhchat/lhchat.php this file :)
