### ISSUE TITLE
formatting message sent to OSTicket

### ISSUE THREAD

**Issue by babgond** [LiveHelperChat/livehelperchat#1245]
Hello,

when converting / sending the chat to osticket, the line breaks do not pass.
All information is found one after the other: it is not readable. 
Is it possible to add line breaks?
Thanks

sample

"Chat ID - 2 User nick - bab, User e-mail - , User time zone - Europe/Helsinki Chat was created at - 11-08-2018 17:42:17 //---------------// URL to view a chat (url provided if chat exists) https://babgond.dtc/lhchat/index.php/sit … UvMg%3D%3D //---------------// Referer //---------------// Chat log 11-08-2018 17:42:17 Beryl: C’est un test 11-08-2018 17:42:43 Assistance système: Support Niveau 2 et 3 a accepté le chat! 11-08-2018 17:42:50 Support Niveau 2 et 3: Bonjour 11-08-2018 17:43:01 Beryl: Gaz ? 11-08-2018 17:45:07 Support Niveau 2 et 3: Test 11-08-2018 18:38:14 Support Niveau 2 et 3: Sf //---------------// Operator remarks //----------------// User geo data: Country code - fr France //----------------// Additional chat data "

![capture d ecran 2018-08-12 a 16 21 19](https://user-images.githubusercontent.com/26592385/44005227-66304f30-9e70-11e8-9a7a-c3c859563cba.png)

**Comment by remdex** [comment]
This one is fixed in recent osTicket releases.
