### ISSUE TITLE
User can't accept/assign chat via web-interface

### ISSUE THREAD

**Issue by nemethit** [LiveHelperChat/livehelperchat#1255]
Hello,

I've a strange issue with two users who **are able to assign/accept chats** via the Windows-Client-Application (**✓**) but aren't able to accept or operate/moderate chats via the Web-Interface (**x**).

1. My first thought was that this could be a permission/role issue and gave them administrator privilegs, but this doesn't changed anything. On the Web-Interface they don't "own" the chat.
2. My second thought was to cheat by accepting the chat via Windows-Client-Application and then look into the chat. And indeed, the message in the input-field (that: "They don't own this chat.") was gone, but the input-field is still disabled and they don't have access to any moderative-functionality. (Hint: In this scenario they own this chat! Chat-Owner and current Web-User are the same!)
3. My third thought was that the names could be confusing, but they wasn't.

4. ***Fun-Fact*:** If I "Login As" with my account (=the first user), then I have access to the input-field (not disabled/)(could this be something like a super-admin?)  

For Demonstration, see video: https://streamable.com/m0hkm

The user is assigned to the correct `Department`, has `Administrator-Role`  in this demonstration.
So what could I do wrong?

*The debug-output just shows the usual informations about the loaded templates, but no error-message.*

**LiveHelper Chat Version**: 3.05

**Comment by inovek** [comment]
Fixed the issue and found some design aspect which should be changed.

The issue itself was produced by the user (me) by clicking on the **Read Only**-checkbox on the Department-Tab of the User-Configuration screen.

I would suggest to...
1. Replace the checkbox-type to radio-type.
2. Replace the "eye-icon" with the Text "Read only"
3. Replace the right department-text with "Operate" or "Assign"
4. Put the department-text (department-name) to the front of the two radio buttons.

As like:
```
Technical Support | (o) Read only ( ) Assign
Salseman 		  | ( ) Read only (o) Assign

```

**Comment by remdex** [comment]
I see. I'll think about it :)
