### ISSUE TITLE
[Forum bug report] unsafe.javascript error

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1258]
Please see the topic: https://forum.livehelperchat.com/viewtopic.php?pid=12531#p12531

How to reproduce:
- once logged into admin console [open the chat tab on the right](https://forum.livehelperchat.com/viewtopic.php?pid=12531#p12531)

- press on chat tabs

**Comment by PeopleInside** [comment]
Forum user is also asking if Is the[ list of directories to overwrite](https://livehelperchat.com/article/view/63) complete? As now exist also cli folder (and var folder).

**Comment by remdex** [comment]
Yes, directories are complete, cli is optional.
