### ISSUE TITLE
Command to disable cache

### ISSUE THREAD

**Issue by ArjonBu** [LiveHelperChat/livehelperchat#1259]
It would be great to have a command that can be run to disable and enable cache (all 3 caches). This would make upgrading easier and more automated.

**Comment by remdex** [comment]
It's more usefull after git pull just do.
php cron.php -s site_admin -c cron/util/clear_cache
php cron.php -s site_admin -c cron/util/update_database

So first one clears cache and second updates database. And then there is no need to disable/enable cache :)
