### ISSUE TITLE
Possibile issue: Try to guess the language works also for subdomains?

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1271]
Seems when i generate embed code with default Italian language but i select to detect language this work on main domain but not in sub domain where is used English.

**Comment by PeopleInside** [comment]
I have tested the Embed code with language recognition on main domain and subdomain , each website was in Italian. On main domain the Italian widget is showed correctly but in subdomain (tested in more than one subdomain) the language showed to the Italian visitors are English and not Italian.

I think this can be an issue somewhere... anyway at the moment i cannot use language recognition on subdomains.

**Comment by remdex** [comment]
Language detection works by parsing html so html on subdomain also has to be valid and indicate correct language. Try to run in console this code and then just console.log(_l); you should see what language is detected from html itself :)
```
var _l = '';var _m = document.getElementsByTagName('meta');var _cl = '';for (i=0; i < _m.length; i++) {if ( _m[i].getAttribute('http-equiv') == 'content-language' ) {_cl = _m[i].getAttribute('content');}}if (document.documentElement.lang != '') _l = document.documentElement.lang;if (_cl != '' && _cl != _l) _l = _cl;if (_l == undefined || _l == '') {_l = '';} else {_l = _l[0].toLowerCase() + _l[1].toLowerCase(); if ('eng' == _l) {_l = ''} else {_l = _l + '/';}}

**Comment by PeopleInside** [comment]
![00](https://user-images.githubusercontent.com/5006150/47950612-e9f20780-df54-11e8-9bd5-f47d02b00ada.png)

**Comment by charliehu** [comment]
Hello,

I facing with the same issues. I think the root cause is, the content-language require to using ISO 659-1 codes, but livehelperchat using ISO 659-2/b, the three character format.
