### ISSUE TITLE
Remove the close

### ISSUE THREAD

**Issue by AlexShapka** [LiveHelperChat/livehelperchat#1278]
Hello! Thanks for the great soft. Giving it a try today I noticed there is a close button in the right corner, which in fact does not close anything - the form is still there even if you click on close button.  So please consider removing it as it is useless, at least in the : 

<img width="922" alt="screen shot 2018-11-17 at 10 50 09 pm" src="https://user-images.githubusercontent.com/9372724/48665314-2711da00-eabd-11e8-8d45-cdee4ebb7a98.png">

**Comment by PeopleInside** [comment]
Hi @AlexShapka , thank you for your message.
Your Live Helper Chat install is self-hosted? Seems you are using an old version, the new widget has a different look.

**Comment by AlexShapka** [comment]
Well, I downloaded using `wget https://github.com/remdex/livehelperchat/archive/master.zip` per instructions on https://livehelperchat.com/article/static/5 Should I get it differently?

**Comment by PeopleInside** [comment]
Strange... You can check the version in the settings.
The screen on a webpage should be https://demo.livehelperchat.com/ maybe you has only not activated multi language. If you try the X button on that links the browser tab should close.

I was supposing this is a widget screen maybe is not. A demo of the widget is showed here: https://forum.livehelperchat.com/#

**Comment by AlexShapka** [comment]
I've just re-installed everything using `git clone https://github.com/LiveHelperChat/livehelperchat.git` with the same result.

> You can check the version in the settings.

I am not sure how to do that, but I see `3.09v` on very top of `doc/CHANGELOG.txt`. Is it the latest version?

> maybe you has only not activated multi language

I have not logged in to activate anything yet. I've just installed it. From your surprised reaction I believe the multi-language feature should be activated by default, right? Have you tried to fresh-install it to see there is no multi-language by default? 

Anyway when I go to https://demo.livehelperchat.com/# and click on X button, it does not close.

**Comment by AlexShapka** [comment]
I see now how it works. On https://demo.livehelperchat.com/# first I started a test chat, then clicked on X button and then chat form only closed. But that button give an impression the whole window should close. Anyway, if it works as designed then its apparent flow in this kind of design. The button should appear only when chat started and disappear when it has not started not to confuse users.

**Comment by PeopleInside** [comment]
The version 3.09 is the last one :)
Yes now is not closing the tab any way this suggestion will be maybe reviewed, i do not think it's an issue the close button. Maybe can be hidden until a chat is not active.

**Comment by AlexShapka** [comment]
I see that. Now since you got surprised to see only X button without language drop-down, can you please confirm the languages should be activated after the setup and logging in? OR should they be activated from the very beginning by default?

**Comment by PeopleInside** [comment]
Languages can be select in settings, live help configuration, chat configuration, Misc, Don't remember now if is active by default or not, maybe.

You can have mail issue if SMTP settings are not configured correctly on live helper chat. Check your spam. I have no issue with live helper chat mail.

Please remember GitHub is a place for report bug. For discussion you can visit the [forum](https://forum.livehelperchat.com/).

If you are new on live helper chat take your time to explore settings and to read the [documentation](https://livehelperchat.com/documentation-6c.html).

**Comment by AlexShapka** [comment]
Fair enough.
