### ISSUE TITLE
Change wait time in forums

### ISSUE THREAD

**Issue by AlexShapka** [LiveHelperChat/livehelperchat#1281]
I was told that we should report only bugs on github and use forums to discuss various issues and ask questions. But it's real torture to use forums, because of wait time. I just wanted to update the forum thread that I created earlier with the newly found information, but it gives:
 
> The following errors need to be corrected before the message can be posted:
> 
> At least 3600 seconds have to pass between posts. Please wait 2959 seconds and try posting again.

Now, tell me who will wait so long just to add new piece of information? Don't you think you, guys, are missing lot's of useful contributions from users by applying so strict rules?

**Comment by PeopleInside** [comment]
Hi @AlexShapka , when you register on the forum all is explained in the registration terms. Few sentence.
You should be able to edit a post without need to create another post.
When you are new on the forum you should have a little bit more patience, very soon the account will be automatically upgraded. Seems you have create a lot of post, thread also here on GitHub... the forum limit this volume of posts. Anyway no issue on the forum, all is working fine.

Please do not "spam" GitHub.
