### ISSUE TITLE
How to hide index.php from url paths?

### ISSUE THREAD

**Issue by AlexShapka** [LiveHelperChat/livehelperchat#1282]
Nobody answers in the forums and it has ridiculous time intervals enforced between posts, so copying https://forum.livehelperchat.com/viewtopic.php?id=3241 here.

On https://demo.livehelperchat.com/site_admin there is not index.php in the path, however on my new install the path looks like mysite.com/index.php/site_admin. How can I hide index.php in URL paths in a browser's address bar?

The solution on https://stackoverflow.com/questions/4365129/htaccess-remove-index-php-from-url works most of the time, however some menu links still have `index.php` hardcoded, so when clicked shown in the url paths. Can you, guys, share the correct .htaccess file, please?

**Comment by AlexShapka** [comment]
Ok, I had to use the following code in .htaccess file to get it working:

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php?/$1 [L]
RewriteCond %{THE_REQUEST} ^GET.*index\.php [NC]
RewriteRule (.*?)index\.php/*(.*) /$1$2 [R=301,NE,L]
```

however, it's not ideal. Because when I hover links on https://demo.livehelperchat.com/site_admin it never shows `index.php` at all, but with my solution found, while it effectively redirects to URLs without `index.php`, the hovering still occasionally shows the `index.php` in the paths. So please share better solution if you have.

**Comment by PeopleInside** [comment]
You are spamming GitHub https://github.com/LiveHelperChat/livehelperchat/issues/1281 already created a topic for the forum and i told there are no issue.

**Please do not spam.**

**Comment by AlexShapka** [comment]
Please concentrate on the subject matter, on actual issue here. And the forums rules suck. You are not going to attract lot's of new users with this kind of attitude. Users have real issues and they want efficient support. And instead of giving them support you are just playing the ruler here. Sad.

**Comment by PeopleInside** [comment]
If you want fast and dedicated support you can visit the page related to the commercial support https://livehelperchat.com/support-13c.html

As free help i think you cannot pretend nothing :)

**Comment by AlexShapka** [comment]
I'll be ready to pay to deal with real issues. If you gonna charge for such simple requests as sharing your .htaccess file, then you'll just push new users away. Give them a chance to get used to your software first. В любом случае, спасибо, уже насытился отношением.

**Comment by PeopleInside** [comment]
We are not asking to pay.
You are using a free software in just one day you created different GitHub topic and also made two post in the forum. You seems to pretend an immediate reply as in the forum you do not give the time to reply.

If you want different support because the free is not enough i just suggested to consult the commercial support page. Also consider the help i can give to you is really limited: i am just an passionate user of live helper chat. Consider also the chat owner are very busy so reply can't be granted always and can take time on the free support.

**Comment by AlexShapka** [comment]
Well, when you decide to give a try to new software it is quite normal to create multiple issues here or on forums. And it is quite disturbing to hear how you have complained already two times about me: 

> in just one day you created different GitHub topics and also made two post in the forum

Couple or more threads is really nothing and you should stop crying over number of issues I created. And new users like me do not have any idea who is who around here. We just come and start trying things. But when any party who is associated with the software (like yourself lecturing about "spamming in github") they just feel to go away and never go into further experience with the software. Your nagging about spamming on GitHub just because I create two different issues is really epic.

**Comment by PeopleInside** [comment]
Hi @AlexShapka , the limitation in the forum has a sense that maybe you cannot understand.
It's all explained when you register a new account.

From user side i see that this limitation can be not easy but is a temporary limitation. Seems you have registered a forum account without read what you accepted.

![screen lhc](https://user-images.githubusercontent.com/5006150/48678903-02cfff00-eb8a-11e8-9896-d223c1563dbc.png)

I am sorry for your negative experience, fortunately you are the first.
So if you read what you accepted you do not have to create a second post in the same thread.

Also if you opened a thread do not pretend a free reply in the day less than 24 hours, please.
In general you can have meet not perfect system but maybe you also are not perfect.

Again sorry for the bad experience but on my point of view nothing should be change. Maybe in the future the forum can be updated in some other way to block spam.

You should continue to wait a reply and do not pretend to have it immediately or in the same day. There is no granted support also again: my help can be basic and is done in my free time.

**Comment by gituser** [comment]
@AlexShapka check my issue here (created 6 years ago and only partially resolved) - https://github.com/LiveHelperChat/livehelperchat/issues/204

**Comment by slevimk** [comment]
> force_virtual_host

how did you solve it? add me on slevimk discord # 7309, i need the same help.

**Comment by remdex** [comment]
> > force_virtual_host
> 
> how did you solve it? add me on slevimk discord # 7309, i need the same help.

https://doc.livehelperchat.com/docs/development/remove-index-php/
https://doc.livehelperchat.com/docs/nginx-configuration-tips
