### ISSUE TITLE
Upgraded to php 7.2 - XMPPHP issue

### ISSUE THREAD

**Issue by khrizo** [LiveHelperChat/livehelperchat#1287]
I had to disable XMPP to avoid the error in new chats, here is the log while trying to send a test message.

Fatal error: Uncaught Error: [] operator not supported for strings in `/home/josh/contoso.com/lhc_web/lib/core/lhxmp/XMPPHP/XMLStream.php:468 Stack trace: #0 /home/josh/contoso.com/lhc_web/lib/core/lhxmp/lhxmp.php(13): XMPPHP_XMLStream->processUntil(Array) #1 /home/josh/contoso.com/lhc_web/cache/compiledtemplates/0cb88c4ac01337b785132406833a11dc.php(2): erLhcoreClassXMP::sendTestXMP(Object(erLhcoreClassModelUser)) #2 /home/josh/contoso.com/lhc_web/lib/core/lhcore/lhmodule.php(95): include('/home/josh/...') #3 /home/josh/contoso.com/lhc_web/lib/core/lhcore/lhmodule.php(485): erLhcoreClassModule::runModule() #4 /home/josh/contoso.com/lhc_web/index.php(38): erLhcoreClassModule::moduleInit() #5 {main} thrown in /home/josh/contoso.com/lhc_web/lib/core/lhxmp/XMPPHP/XMLStream.php on line 468`

**Comment by remdex** [comment]
This one is older one and was fixed as i remember
