### ISSUE TITLE
The screen sharing is not working. 

### ISSUE THREAD

**Issue by Fiona-Wei** [LiveHelperChat/livehelperchat#1288]
Hello,
       When I chat with my customer, I click the icon"screen share" .It told me to "Click blue eye at the top to request screen share",I did but nothing happen.
       I‘ve also tested on my own computer, it turned out the same matter! 
      Sorry for my poor English.

**Comment by Fiona-Wei** [comment]
version：Live Helper Chat 3.12
The operating system：CentOS 7
The browser：IE 11

**Comment by PeopleInside** [comment]
Hi, are you using a firewall like Wordfence?
What is the php version?
