### ISSUE TITLE
What's the Chat_id and Hash to pass for the AddmsgUser endpoint

### ISSUE THREAD

**Issue by sylendra7** [LiveHelperChat/livehelperchat#1290]
From where we get the Chat_id and Hash for the AddmsgUser Endpoint

**Comment by PeopleInside** [comment]
Hi, sorry for the delay in a reply.
You can include the chat ID number in email templates with the string `[{chat_id}]`

Can be this answering your question?

**Comment by PeopleInside** [comment]
I will close this as solved for now; for any dubt you can comment here and we will be back soon.
