### ISSUE TITLE
I need configuration tutorials about  bots

### ISSUE THREAD

**Issue by Fiona-Wei** [LiveHelperChat/livehelperchat#1292]
I‘ve spent several hours on the bots setting...
However, the problem has not been solved.
I’m looking forward to configuration tutorial about it.
Thank you in advance!

**Comment by remdex** [comment]
I'm not sure what exactly you are asking but bot setup is in these short steps
1. You craeate a bot.
2. In bot list click it's name
3. Setup bot triggers. You can choose in trigger options what trigger should be default one. It willbe executed as soon chat starts.
4. In department edit window you choose your newly created bot.
That's all :)
