### ISSUE TITLE
Play a new pending chat sound on a new chat request -> not working

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1294]
As from the forum report https://forum.livehelperchat.com/viewtopic.php?id=3262
and my test on the demo seems disable the check box "Play a new pending chat sound on a new chat request" under https://demo.livehelperchat.com/site_admin/chat/syncandsoundesetting doesn't stop new chat to play sound.

**Comment by remdex** [comment]
1. This setting applies only to new user accounts then they first time opens chat application.
2. Existing accounts should manually disable/enable sound in their back office interface in top menu.
