### ISSUE TITLE
Detect language automatically

### ISSUE THREAD

**Issue by broboredo** [LiveHelperChat/livehelperchat#1296]
Hi!

So, I have some doubts.

In admin side, on Settings > Embed Code > Live help embed code > Widget embed code..

I checked the "Try to detect language automatically" option.

My website have the metatag: <meta http-equiv="content-language" content="{{ lang }}">, this content change when the user change the website language (pt, fr and en).

In debugging, I discoverd that live-helpers script get the content pt or fr, for example, from metatag. But the language on widget keep the same (en).

What I have to do?

**Comment by remdex** [comment]
Hi,
Please change in https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/settings/settings.ini.default.php#L31 /settings/settings.ini.php on prod siteaccess names. E.g if it's pt most likely at the moment it's 'por' so just replace 'por' to 'pt' also in this place https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/settings/settings.ini.default.php#L207 :)

**Comment by broboredo** [comment]
Solved! Thx
