### ISSUE TITLE
"Access-Control-Allow-Origin" header not being set on index.php

### ISSUE THREAD

**Issue by Mike-Benoit** [LiveHelperChat/livehelperchat#1324]
When accessing "index.php/chat/getstatus", the "Access-Control-Allow-Origin" is not being added to the request, so it causes CORS failures. It appears to be manually added to many other requests, but not index.php. 

Is there another way to get it added to "index.php/chat/getstatus" requests?

**Comment by Mike-Benoit** [comment]
FYI: This is somewhat related to #1346

**Comment by altomarketing** [comment]
any update on this ?

**Comment by remdex** [comment]
Hi,

I have added these headers in .htaccess directly you can find in lhc_web folder. I won’t be adding them directly in index.php file. I have nothing to do more with this issue. Also I suggest just use new widget.

**Comment by remdex** [comment]
Hi,

Update. 

Seems I missed that the Rest API call that starts a php session which should not be happening this is fixed now. So there won't be warning about same site cookie.

Update how .htaccess file should look like.
https://doc.livehelperchat.com/docs/integrating/#my-widget-does-not-work-i-have-live-helper-chat-installed-on-one-domain-but-code-is-embeded-on-another-domain

Just update from master branch.
