### ISSUE TITLE
New chats not working via usual form -- REPLICABLE IN DEMO

### ISSUE THREAD

**Issue by rehv** [LiveHelperChat/livehelperchat#1326]
Hello,

there is a major problem in newer versions of livehelperchat with starting new chats. If you start a new chat by going to the default form (not widget), like 34.73.172.173/chat/index.php or even your own demo.livehelperchat.com/index.php , it displays a "We'll be back soon" message (the chat is created in back office normally, but user gets error message).

![image](https://user-images.githubusercontent.com/1697639/52788793-2996b800-3049-11e9-93d5-60b5f182f7a8.png)

![image](https://user-images.githubusercontent.com/1697639/52788774-1daaf600-3049-11e9-96bd-82f3bf975e95.png)

the error DOES NOT occur when you are logged in back office and try to start a chat. I've checked the logs, and it's due to the new chat checking for a user id while starting a chat, which of course doesn't exist unless you're also an operator.

see the log below for details:

[default.log](https://github.com/LiveHelperChat/livehelperchat/files/2865235/default.log)

**Comment by remdex** [comment]
Just a moment i'll check it now.

**Comment by remdex** [comment]
Issue was fixed in these two commits
https://github.com/LiveHelperChat/livehelperchat/commit/b0582b9767749e43033175abd564f08ef0db54a4
https://github.com/LiveHelperChat/livehelperchat/commit/ed1843fad2ef6d9acdaf0dae91e9eb4ac32d1594

Thanks for report :)

**Comment by rehv** [comment]
Thanks for fixing this so fast!

reinstalled with new commits and everything works fine :)
