### ISSUE TITLE
paid chat. Lacking documentation

### ISSUE THREAD

**Issue by salsero72** [LiveHelperChat/livehelperchat#1327]
Hi,
I am sorry to bother but to me the documentation here is lacking some info.
https://livehelperchat.com/how-to-use-paid-chats-feature-439a.html

Or maybe my mind is limited in understanding.

I am trying to interpolating info there and tried to implement this on my site but have a few doubts.

1. Must user be registered somewhere? Otherwise, how can I track the user payment is valid and link payment_id_hash to that user? 
2. I have seen that if payment_id_hash is different from secred payment_id_hash, than the chat does not run ("Hash is invalid"), But if the chat is started during payment validity period,  and the payment expires, being it hardcoded in the widget code, the user can continue chatting.

I think the user should be prompted a system message like "Hey, payment is expired, to continue chatting please make a new payment [here]"

Thanks for your work guys.

**Comment by remdex** [comment]
Hi,

1. payment_id_hash - it can be any your payment hash value. Like md5(transaction id + user_id)
2. As fore second I'm not sure what exactly you are asking for. But lhc does not have option to expire generated hash. But if chat is closed there is option to paid chat configuration to choose that closed chat cannot be reopened,

**Comment by salsero72** [comment]
Thank you.
That helped a bit.

**Comment by remdex** [comment]
https://doc.livehelperchat.com/docs/paid-chats/
