### ISSUE TITLE
Config to enable/disable automatic image loading

### ISSUE THREAD

**Issue by rehv** [LiveHelperChat/livehelperchat#1328]
Hi, is it possible to have a config to enable or disable images loading automatically in chat? Before the new design changes, we had the download link plus a preview button:

![image](https://user-images.githubusercontent.com/1697639/53173558-afc17a00-35c6-11e9-8a6d-bc9cb1811fba.png)

Now the image just loads automatically and to download it we have to press right click then save/open the image. Sometimes the text is small so there's really no use previewing the image in this case. Can we have a setting to re-enable the previous behavior (link + preview button)? 

Thanks again in advance.

**Comment by remdex** [comment]
There was done enhancement that moving mouse over it would show download icon.
