### ISSUE TITLE
Error when saving Chat Configuration and other settings.

### ISSUE THREAD

**Issue by MNU-497** [LiveHelperChat/livehelperchat#1330]
https://chat.lemonsquad.com/index.php/site_admin/chat/listchatconfig#!#copyright

I am running php 7 non thread safe,  in a windows server 2012 environment on iis.

Putting in a simple file existence test solves the problem.
\lib\core\lhtpl\tpl.php on line 556
```
if(file_exists($file)){
     $result = include($file);
} else {
     $result=false;
}
```

PHP Warning:  include(cache/compiledtemplates/28837ec504ebf9d47a868bd18294c8bb.php): failed to open stream: No such file or directory in C:\inetpub\wwwroot\expertautocheck.com.chat\lib\core\lhtpl\tpl.php on line 556
PHP Warning:  include(): Failed opening 'cache/compiledtemplates/28837ec504ebf9d47a868bd18294c8bb.php' for inclusion (include_path='.;C:\php\pear') in C:\inetpub\wwwroot\expertautocheck.com.chat\lib\core\lhtpl\tpl.php on line 556

**Comment by MNU-497** [comment]
https://chat.lemonsquad.com/index.php/site_admin/chat/onlineusers

perhaps related to the earlier mentioned error, I have been getting another error

Putting a simple array test solves the problem.
\lib\core\lhcore\lhmodule.php on line 405
`
if(!is_array($cacheModules)){
     $cacheModules = array();
}
`

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to erLhcoreClassCacheStorage::store() must be of the type array, integer given, called in C:\inetpub\wwwroot\lemonsquad.com.chat\lib\core\lhcore\lhmodule.php on line 405 and defined in C:\inetpub\wwwroot\lemonsquad.com.chat\lib\core\lhtpl\tpl.php:19
Stack trace:
#0 C:\inetpub\wwwroot\lemonsquad.com.chat\lib\core\lhcore\lhmodule.php(405): erLhcoreClassCacheStorage->store('moduleCache_cha...', 1)
#1 C:\inetpub\wwwroot\lemonsquad.com.chat\lib\core\lhcore\lhmodule.php(95): erLhcoreClassModule::getModuleFile()
#2 C:\inetpub\wwwroot\lemonsquad.com.chat\lib\core\lhcore\lhmodule.php(533): erLhcoreClassModule::runModule()
#3 C:\inetpub\wwwroot\lemonsquad.com.chat\index.php(39): erLhcoreClassModule::moduleInit()
#4 {main}
  thrown in C:\inetpub\wwwroot\lemonsquad.com.chat\lib\core\lhtpl\tpl.php on line 19

**Comment by MNU-497** [comment]
this could be a related error

```
PHP Fatal error:  Uncaught Error: Call to a member function getUserID() on null in C:\inetpub\wwwroot\lemonsquad.com.chat\modules\lhchat\onlineusers.php:66
Stack trace:
#0 C:\inetpub\wwwroot\lemonsquad.com.chat\lib\core\lhtpl\tpl.php(36): include()
#1 C:\inetpub\wwwroot\lemonsquad.com.chat\lib\core\lhcore\lhmodule.php(283): erLhcoreClassCacheStorage->restore('moduleCache_cha...')
#2 C:\inetpub\wwwroot\lemonsquad.com.chat\lib\core\lhcore\lhmodule.php(95): erLhcoreClassModule::getModuleFile()
#3 C:\inetpub\wwwroot\lemonsquad.com.chat\lib\core\lhcore\lhmodule.php(533): erLhcoreClassModule::runModule()
#4 C:\inetpub\wwwroot\lemonsquad.com.chat\index.php(39): erLhcoreClassModule::moduleInit()
#5 {main}
  thrown in C:\inetpub\wwwroot\lemonsquad.com.chat\modules\lhchat\onlineusers.php on line 66
```
I noticed that you use this method elsewhere in the document

**Comment by MNU-497** [comment]
It got so bad I completely disabled cache in the settings.ini.php file.

I slowly turned features back  on until I got errors again, then backed off. Current working settings are: 
```
      'templatecache' => true,
      'templatecompile' => true,
      'modulecompile' => false,
```
Things are working, but, if I set modulecompile to true, I get errors as noted above.

**Comment by remdex** [comment]
For me it looks that something is not right with your installation or just environment. Error you showed it should never be happening. For me it looks something not right with PHP Sessions on your end just. Changes regarding warning I did. Either they were harmless :)

**Comment by MNU-497** [comment]
I'll do some digging and see if I can pinpoint a true cause. I think I am just seeing symptoms at this point. Also, Thank you for making the update "[Check if file exists before inclusion](/LiveHelperChat/livehelperchat/commit/374fdf7e54e2315f1fe9604668de57071b9c62aa)" it won't cause problems and it may just help reduce issues in some cases.

**Comment by MNU-497** [comment]
It is still locking up at times. and it appears to me to have something to do with the "non thread safe" nature of my installation. I got another error about file rename failure in template
lib/core/lhcore/ihdesign.php: 165 
rename($fileName, $file);

after reading the comment:
//Atomic template compilation to avoid concurent request compiling and writing to the same file

This appears to be a method used to rename a file using multi-thread-friendly methods. However it a single threaded system it is appears to be creating issues.

Here is my settings file if that helps. I just don't know what to look for. If someone can offer some suggestions, I would greatly appreciate it. at this point it could be something as simple as an empty time_zone value. 
```
<?php
 return array (
  'settings' => 
  array (
    'site' => 
    array (
      'title' => 'Lemon Squad Chat',
      'site_admin_email' => 'support@lemonsquad.com',
      'locale' => 'en_EN',
      'theme' => 'defaulttheme',
      'installed' => true,
      'secrethash' => '9fb06b7e85',
      'debug_output' => false,
      'templatecache' => true,
      'templatecompile' => false,
      'modulecompile' => false,
      'force_virtual_host' => false,
      'one_login_per_account' => false,
      'time_zone' => '',
      'date_format' => 'Y-m-d',
      'date_hour_format' => 'H:i:s',
      'date_date_hour_format' => 'Y-m-d H:i:s',
      'default_site_access' => 'eng',
      'maps_api_key' => false,
      'extensions' => 
      array (
      ),
      'available_site_access' => 
      array ( 

           ...

      ),
    ),
    'default_url' => 
    array (
      'module' => 'chat',
      'view' => 'startchat',
    ),
    'chat' => 
    array (
      'online_timeout' => 300,
      'back_office_sinterval' => 10,
      'chat_message_sinterval' => 3.5,
      'check_for_operator_msg' => 10,
      'new_chat_sound_enabled' => true,
      'new_message_sound_admin_enabled' => true,
      'new_message_sound_user_enabled' => true,
    ),
    'memecache' => 
    array (
      'servers' => 
      array (
        0 => 
        array (
          'host' => '127.0.0.1',
          'port' => '11211',
          'weight' => 1,
        ),
      ),
    ),
    'redis' => 
    array (
      'server' => 
      array (
        'host' => 'localhost',
        'port' => 6379,
        'database' => 0,
      ),
    ),
    'db' => 
    array (
      'host' => 'localhost',
      'user' => 'lemonsqu_lemon',
      'password' => '*************',
      'database' => 'lemonsqu_chat',
      'port' => 3306,
      'use_slaves' => false,
      'db_slaves' => 
      array (
        0 => 
        array (
          'host' => '',
          'user' => '',
          'port' => 3306,
          'password' => '',
          'database' => '',
        ),
      ),
    ),
    'site_access_options' => 
    array (

           ...
     
        'default_url' => 
        array (
          'module' => 'chat',
          'view' => 'startchat',
        ),
      ),
      'site_admin' => 
      array (
        'locale' => 'en_EN',
        'content_language' => 'en',
        'dir_language' => 'ltr',
        'theme' => 
        array (
          0 => 'customtheme',
          1 => 'defaulttheme',
        ),
        'login_pagelayout' => 'login',
        'default_url' => 
        array (
          'module' => 'front',
          'view' => 'default',
        ),
      ),
    ),
    'cacheEngine' => 
    array (
      'cache_global_key' => 'global_cache_key',
      'className' => false,
    ),
  ),
  'comments' => NULL,
);
?>
```

**Comment by remdex** [comment]
1. Template cache
2. Template compile
3. Module complie
Should be true

Debug output should be false

If after saving configuration you see warning. Means your php configuration shows errors/warnings by default. It should be false on prod environments.

And what you mean locking at times?

**Comment by MNU-497** [comment]
I'll make those changes and keep testing.

> And what you mean locking at times?

Good question.. If I open a "Private Browsing" window and start a chat as a website visitor, it takes about 27 seconds for each chat message to reach the logged in chat operator/agent. The agent chat messages likewise take about 27 seconds to reach the website visitor. These "Locking" events release all at once. Meaning that in developer view in the browser I can see about 8 requests stack up, and, when they return, two or three of them will be 500 errors and the others will return normally but I see the chat message stacked up in developer tools [network] tab.
![image](https://user-images.githubusercontent.com/4730399/54078729-1b783800-4293-11e9-8ed9-725766627f49.png)

Messages take a very long time to show up but after about a minute of waiting, they do appear.

**Comment by MNU-497** [comment]
I applied the settings you instructed and also found that "Long polling (experimental)" was turned on ... appliying those changes and turning "Long polling (experimental)" off, appears to have helped. I will test it for the next few days and report back.

Thank you for your help. I appreciate your time.
