### ISSUE TITLE
Statistic data differ for filtered date.

### ISSUE THREAD

**Issue by breaker84** [LiveHelperChat/livehelperchat#1331]
When generate stat monthly (eg. 2019-01-01 ~ 2019-01-31) the stat is 521
But when we put longer period (2018-01-01 ~ 2019-01-31) across the one we select up there, we got 550 for the exact month (Jan).
I already untick Active, Operators and Pending, only select Closed

**Comment by remdex** [comment]
Hi,
Can you ping me on skype. Nick "remdex" I would like to investigate directly on your instance.

**Comment by breaker84** [comment]
I think problem solve...
I include the hour and minutes in stat generate...
I suggest of no minute or hour select, it will select the last minute and 1st minute og the period..
Regards
