### ISSUE TITLE
Auto assign - operators can bypass it entirely

### ISSUE THREAD

**Issue by equipeppjejlf** [LiveHelperChat/livehelperchat#1337]
Hello, 

I'm using the Auto Assign feature, but I've discovered that operators can bypass the "queue" completely if they go to Chat List and click on any of the pending chats there. I currently have a limit of 1 chat per operator, so it is common to have a few chats with operator unassigned, waiting in queue.

I've been searching how to remove operators access to chat list, but you said it is impossible (#990). 

So, can you please tell me if there's any other way to block them from accepting pending chats unless auto assigned? There's really no point in having auto assign if they can just bypass it... There are some operators who will accept more chats than allowed to boost their statistics.

Thanks in advance.

**Comment by remdex** [comment]
Hi,
That's interesting problem actually.... I tried to look, but I do not think it's possible now. All this auto assign was done to control auto assign workflow. But at the moment I do not have workflow to block accepting chats manually...

**Comment by remdex** [comment]
I have scheduled this implementation so should be done at some point.

**Comment by remdex** [comment]
Implemented. After update there is new permission in lhchat module
"lhchat","open_all" without it operators will be able to open only chats assigned to them.

**Comment by equipeppjejlf** [comment]
Hey, sorry for taking this long to reply. Thanks for the modification! But this blocks all chats not assigned to operator from being read. We've added this condition to the related code so it only blocks pending chats, as I think it's what you intended:

`$chat->status == erLhcoreClassModelChat::STATUS_PENDING_CHAT`

so:

`
if ($chat->status == erLhcoreClassModelChat::STATUS_PENDING_CHAT && $chat->user_id != $userData->id && !$currentUser->hasAccessTo('lhchat','open_all')) {
throw new Exception('You do not have permission to open all pending chats.');
}`

Again, thanks in advance for taking your time to consider this suggestion.

**Comment by remdex** [comment]
Made this change on official version
