### ISSUE TITLE
Way to create two embed chats in the same page

### ISSUE THREAD

**Issue by futbolsalas15** [LiveHelperChat/livehelperchat#1340]
Currently, LHC doesn't support add two embed chat widgets in the same page, when in _Widget embed code_ option we create a new code with _Native Placement_ enabled. 

The reason for this is that the id of the div generated always shows _lhc_status_container_, regarding of the changes that we made to the file _design/defaulttheme/tpl/lhchat/getstatus/options_variable.tpl.php_. According to the code, changing `$chatCSSPrefix` in this file allow to create new JS code with a new id generated. e.g.:

```php
<?php
    $chatOptionsVariable = 'LHCChatOptions';
    $chatCSSPrefix = 'crucero';
    $chatCSSLayoutOptions = array(
        'container_id' => 'crucero_container'
    )
?>
```

The previous change allows to create the following JS file:

![Captura de pantalla 2019-03-30 a la(s) 9 28 28 a  m](https://user-images.githubusercontent.com/1960482/55277435-36582e00-52ce-11e9-8169-0e30e8b4c642.png)

Although it works initially, there is some parts of the code that have references to a non-parametrized id. e.g.: _design/defaulttheme/tpl/lhabstract/custom/widget_theme.tpl.php_:

```php
<div id="lhc_status_container"><a id="online-icon" class="status-icon" href="#">{{ngModelAbstractInput_online_text || <?php echo json_encode(htmlspecialchars_decode(erTranslationClassLhTranslation::getInstance()->getTranslation('chat/getstatus','Live help is online...'),ENT_QUOTES))?>}}</a></div>
```
(I ran this search in github to find the coincidences: https://github.com/LiveHelperChat/livehelperchat/search?q=lhc_status_container&unscoped_q=lhc_status_container)

The idea is maintain the consistency of the prefix through all the code. 

Thanks.

**Comment by remdex** [comment]
It does support now. https://livehelperchat.com/demo-12c.html
