### ISSUE TITLE
Improper Session Management

### ISSUE THREAD

**Issue by ravi24june1** [LiveHelperChat/livehelperchat#1341]
The chat window URL has ID and Hashed token attached which can be accessed on any System from URL directly. Chat window must be mapped with Unique ID and Session per request and should be validated at the server side. 

**Sample URL after opening the chat** 
https:///livehelperchat.com/index.php/chat/chat/9519/42e2fc4ceaae2da8796d3ad9fe28920e5024b4af

**Comment by remdex** [comment]
I'm not sure what's your problem exactly. If you share this url and hash, yes you can open it in any other browser just like with google doc if you share url.

**Comment by ravi24june1** [comment]
There may be chance of MITM (Man in the Middle Attack). If someone have url (by any wrong means), can see the chat and reply. 

How can i protect and bind the url for a single user?

**Comment by remdex** [comment]
If chat is closed this url becomes invalid. So chat after chat session just should be closed. There is no other way to block it.
