### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setAttribute' of null

### ISSUE THREAD

**Issue by Mike-Benoit** [LiveHelperChat/livehelperchat#1346]
We're seeing the following JS exception from some users:

`Uncaught TypeError: Cannot read property 'setAttribute' of null in https://<domain>/index.php/chat/getstatus/(click)/internal/(position)/api/(ma)/br/(dot)/true/(top)/350/(units)/pixels/(leaveamessage)/true/(department)/2/(disable_pro_active)/true?r=&l=<snip>&ttr=1555414444554 line 10`

Unfortunately because the javascript is minified, we're not sure what Line 10 is. Is there a way to not minify the javascript code so we can get better error messages?

Taking a quick look, the following is the only code that doesn't call setAttribute() on a newly created element, so my best guess is that domContainer isn't being found for some reason therefore calls to domContainer.setAttribute() are failing.

`        var domContainer = document.getElementById('lhc_container');
        var domIframe = 'lhc_iframe';
        var domContainerId = 'lhc_container';
        domContainer.onmousedown = function(e) {
            domContainer.setAttribute('draggable', 'true');
        }
        ;
        domContainer.onmouseup = function(e) {
            domContainer.setAttribute('draggable', 'false');
        }`

`  this.addEvent(window, 'dragover', function(event) {
                if (lhc_obj.is_dragging == true) {
                    domContainer = document.getElementById(domContainerId);
                    domContainer.setAttribute('draggable', 'false');
<...>
`

**Comment by remdex** [comment]
Hi,
Just set those to false and you will see exact row
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/settings/settings.ini.default.php#L14-L15

**Comment by Mike-Benoit** [comment]
Thanks, I will give that a try and see if it helps at all. 

Something else we noticed along the same lines is that when we enabled LHC we started seeing a huge increase (ie: hundreds per week) in "Script Error" javascript exceptions. We can't tell what is triggering these errors or what they even are due to the fact that our LHC server is on a different domain from our website, even though when loading LHC code we set "cross-origin=anonymous" and also have "Access-Control-Allow-Origin: *" headers sent from the chat server. We suspect this is because LHC loads other .js files without the "cross-origin=anonymous" attribute, so if that code triggers the errors they are obscured by the browser.

To better help troubleshoot and make LHC more stable and less likely to trigger these errors, it would be nice if there was a setting to enable the "cross-origin=anonymous" attribute everywhere so the errors aren't obscured.

**Comment by remdex** [comment]
Update. 

Just use new widget.

Seems I missed that the Rest API call that starts a php session which should not be happening this is fixed now. So there won't be warning about same site cookie.

Update how .htaccess file should look like.
https://doc.livehelperchat.com/docs/integrating/#my-widget-does-not-work-i-have-live-helper-chat-installed-on-one-domain-but-code-is-embeded-on-another-domain

Just update from master branch.
