### ISSUE TITLE
Any working Android Client?

### ISSUE THREAD

**Issue by gusarg81** [LiveHelperChat/livehelperchat#1348]
Hi,

Currently Wurrd (seems not maintained anymore, gone from Play Store, but found the apk directly) not working (its extension gives me error 500 when enable in Live Helper Chat site) and Live Helper Chat client (when I open it, and try to configure server, keyboard does not show to write server, password, etc) either.

My phone is running Android 9.

Thanks in advance.

**Comment by PeopleInside** [comment]
Hi @gusarg81 , sorry at the moment there are no official client.
You can use the web interface or try this unofficial solution: https://forum.livehelperchat.com/viewtopic.php?id=1149

**Comment by gusarg81** [comment]
Hi @PeopleInside !

Livehelperchat messenger is the app that has the keyboard problem at least in Android 9. Thanks.

**Comment by PeopleInside** [comment]
So seems there are no solution at the moment, just the web interface.
You can also set to be informed by email after chat is pending for some time. You can set this in the department settings.

**Comment by PeopleInside** [comment]
https://forum.livehelperchat.com/viewtopic.php?pid=13175#p13175

**Comment by gusarg81** [comment]
Yes! I was installing that version after you gave me the forum link (sorry, missed that in the last page). keyboar is working and I've connected to Live Helper Chat. Thanks @PeopleInside .

**Comment by PeopleInside** [comment]
You are welcome.
