### ISSUE TITLE
Leave message when operator is offline

### ISSUE THREAD

**Issue by marcelloinfoweb** [LiveHelperChat/livehelperchat#1352]
Function to leave message when operator is offline is not working, even if all operators are offline and logged out of the system. It stopped working when I upgraded from version 3.14 to 3.21.

**Comment by PeopleInside** [comment]
Hi @marcelloinfoweb , this seems to be your installation issue as **i tested now and i don't see any issue with offline message on version 3.21**

Check your PHP version is a supported version: https://www.php.net/supported-versions.php
Check your server error log. Maybe something went wrong on your update... in this case you should restore your backup and try again better following the guide for the upgrade: https://livehelperchat.com/article/view/63

**Comment by marcelloinfoweb** [comment]
we discovered what happened: the administrators were in the departments, so even the attendants were logged off, I did not see the message to leave a message.
It could be an improvement, if any administrator is in the departments, do not count as an attendant. Because here, departmental administrators only help if everyone is busy, but they do not go online.

**Comment by PeopleInside** [comment]
If the admin is online and assigned to the department the department will be online. This is normal. The admin or the operator can set his status to offline in the profile or on the top of the operator console.

**Comment by marcelloinfoweb** [comment]
Thank you, and I'm sorry for the misunderstanding.
