### ISSUE TITLE
User chat error.

### ISSUE THREAD

**Issue by Vintic** [LiveHelperChat/livehelperchat#1356]
Hi, 
what can cause this error?

`PHP Notice:  Undefined index: default_from in E:\PUB33\autotest\livehelperchat\lhc_web\lib\core\lhchat\lhchatmail.php on line 25`

When user submit form in dialog chat appear this message and infinite loading icon. But on LHC page new dialog appears, as it should.

In default.log is only one row, and it may be is not referred to this error:
`May 24 12:56:06 [Warning] [default] [default] Unexpected error, the message was : Object of class erLhcoreClassModelGroup could not be converted to string in E:\PUB33\autotest\livehelperchat\lhc_web\cache\compiledtemplates\8ad46707b73924ad5fb9ec1efbfc36a0.php on line 1
`

**Comment by PeopleInside** [comment]
Hi @Vintic , sorry i have no idea about this error. 

- Is a new installation?
- Have you customized live helper chat?

Consider the free support is imitated

**Comment by Vintic** [comment]
- new installation with update from Master branch
- not. just configs.

Fixed, made clean install. All is OK now.
Thanks.

**Comment by Vintic** [comment]
Clean install.

Same error appear when redirect user to contact form.
- User submit form and appear this error with infinite loading icon.

`PHP Notice:  Undefined index: default_from in E:\PUB33\autotest\livehelperchat\lhc_web\lib\core\lhchat\lhchatmail.php on line 25`

**Comment by remdex** [comment]
Thanks for report. But in production environment you really should have disabled error outputs to frontend.

**Comment by Vintic** [comment]
Yes, I know thank you. Just research possibilities and possible problems.
One more thing about ERROR... Form appear with email input, that was not set as active in configs.

**Comment by Vintic** [comment]
I disabled un-comment "ini-sets" in index.php and now is working well. I apologize.
