### ISSUE TITLE
How to know a new chat via nodejshelper

### ISSUE THREAD

**Issue by NguyenXuanNam** [LiveHelperChat/livehelperchat#1359]
Hi admin,
When I press the start button in widget chat, when in nodejs server how to know a new chat. 
Thanks advanced,

**Comment by PeopleInside** [comment]
Hi @NguyenXuanNam ,
new chat should be notified if you have the operator console by browser opened, if you are logged with an admin or operator account associated to the right department where the visitor are pending a reply and if you activate also browser notification on your operator profile page, notification tab.

You can also edit department settings to have an email notification after some time visitor are in the queue.

**Comment by PeopleInside** [comment]
Hi @NguyenXuanNam I hope my previous reply can answer to your question / issue, if not let us know by replying to this... and if this is an issue i will re-open it. For questions you can use the support forum: https://forum.livehelperchat.com/
