### ISSUE TITLE
fields validation problem

### ISSUE THREAD

**Issue by multiplesplit** [LiveHelperChat/livehelperchat#1361]
Hi

Got the problem on validation of some fields.

The problem is - it didn't add "is-invalid" class to "phone" field, anywhere. Because "name" field and "question" textarea gets their "is-invalid" classes to their wrappers.
BTW i checked template files and find, that "phone" fields got that needed code:
```

[== PHP ==]
<?php if (isset($errors['phone'])) : ?> is-invalid<?php endif;?>
```

, but still doesn't work.

[https://forum.livehelperchat.com/img/2613/1560752376_1.png](url)
[https://forum.livehelperchat.com/img/2613/1560752392_2.png](url)

**Comment by remdex** [comment]
This issue was fixed as i remember.
