### ISSUE TITLE
chat widget

### ISSUE THREAD

**Issue by NguyenXuanNam** [LiveHelperChat/livehelperchat#1362]
Hi Admin,
I have attached widget embed code in website and i had a problem: when refesh page website i lost message chat in widget and start a new chat.
Help me,
Thanks.

**Comment by PeopleInside** [comment]
Hi, please see: [My users looses chat session then they navigate through the site, duplicate online users records](https://livehelperchat.com/my-users-looses-chat-session-then-they-navigate-through-the-site-duplicate-online-users-records-377a.html)

**Comment by NguyenXuanNam** [comment]
Thanks PeopleInside!!

**Comment by PeopleInside** [comment]
You are welcome ;)
