### ISSUE TITLE
Product Name variable in offline e-mail templates

### ISSUE THREAD

**Issue by webriz** [LiveHelperChat/livehelperchat#1363]
Hi,
It's possible to insert product name variable in "offline Chat e-mail template"?

**Comment by PeopleInside** [comment]
Hi, have you looked in the offline page configuration?

- Settings
- live help configuration (tab)
- Start chat form settings

I suppose you should be able to have product selection on the offline form.

**Comment by PeopleInside** [comment]
@webriz let us know if my previous reply can help you to solve your question/issue. 
I will close this issue for now, if you feel this should stay open please let us know by replying here.
