### ISSUE TITLE
transfer chat from the bot to another department

### ISSUE THREAD

**Issue by webriz** [LiveHelperChat/livehelperchat#1364]
Not is present action to transfer chat from the bot to another department

**Comment by PeopleInside** [comment]
Hi, thank you for your report, i will keep this opened to be rewiew by the chat owner.

**Comment by remdex** [comment]
This one now can be done with help of
![image](https://user-images.githubusercontent.com/1146085/62371686-22ebf680-b53e-11e9-9c66-35b9b4fa5461.png)

In your case it should be like
dep_id and department id should be department you want to transfer to.
