### ISSUE TITLE
How to send email notifications of chats to department members?

### ISSUE THREAD

**Issue by samtuke** [LiveHelperChat/livehelperchat#1366]
By default the email notifications about new chats (or messages left when operators are offline) go only to the admin account. How to make these notifications go to all members of a particular department, or the default department email address, instead of the default admin address?

Using a hosted paid account at https://phplist.livehelperchat.com.

**Comment by PeopleInside** [comment]
Hi @samtuke , thank you for your question and for using the [hosted version of live helper chat](https://livehelperchat.com/order/now)!

Have you looked into deaprtment settings?
Here you can set a department email. You may use an address that forward emails to all operators.

Actually if i'm not understand bad you have set in department options the directiver to receive an email alert when a chat is started and in queue. Just one email is sent at the department address so maybe you can use the department address email to forward emails to all operators.

Usually operators should be notified by the web interface if they are online and has activated the browser notification in the operator profile Notification tab.

I hope this reply can help you, let us know.

**Comment by samtuke** [comment]
@PeopleInside Great, thanks. Setting the department email worked, but as you say, we'd need to setup an alias address to make all department members, or one in particular, receive notifications.
The use case is that we don't necessarily expect people to remember to keep the browser window open all the time, or check for new messages after a weekend etc., so email notifications to the staff are useful, but not necessarily to the company manager which registered the account (and is the admin).
I have set one operator's address as the department address, but if they change roles then their address remains 'hard-coded'.
Therefore consider this a feature request to allow sending chat notifications relating to a particular department to all members of that department. Thanks!

**Comment by PeopleInside** [comment]
Umh at the moment i cannot access to te hosted version for made test.
In department you can set an email address like department @ domain . ext

Than on your side you can activate forwarder (in your email hosting panel ) that foward all email to this email to the single operatos email addresses.

This will maybe solve your issue as for now i think what you want is not supported, i don't know if this function will be implemented. I will keep this maybe open for a review by @remdex
