### ISSUE TITLE
Domain filtration

### ISSUE THREAD

**Issue by CryptorClub** [LiveHelperChat/livehelperchat#1367]
Important thing for security is possibility of allowance on a single domain/ip working of the chat. If someone outside puts script code from main site to another domain(s), there is no solution to filter it. 

Please let me know if I can block somehow, that set the script on their sites.
Thanks for your product!

**Comment by PeopleInside** [comment]
@CryptorClub thanks for your suggestion, i will keep this opened for be rewiew by the chat owner.
Enjoy :)

**Comment by remdex** [comment]
Implemented. In 3.33v
https://doc.livehelperchat.com/docs/chat/configuration#domains-where-script-can-be-embedded-eg-examplecom-googlecom
