### ISSUE TITLE
Widget and Theme Documentation

### ISSUE THREAD

**Issue by ComputerCarl** [LiveHelperChat/livehelperchat#1370]
It would be difficult, in words, to explain all of the various issues I am having with theming the widgets. Is there documentation I am missing with explains what the fields do, the types of images which can be used (jpg, png, gif, ...) and the allowed/recommended sizes.

My biggest issues currently are;
* changing the "Need help? Our staff are always ready to help"
* changing the phrase: "Pending a support staff member to join, you can write your questions, and as soon as a support staff member confirms this chat, he will get your message"
* Can the image in "Show copyright widget logo in left corner" be changed rather than disabled?

The other questions are pretty much summed up into this image where I attempted to figure out how to change the widgets.

![image](https://user-images.githubusercontent.com/29293242/61558930-69b5f880-aa36-11e9-9a72-4181eb73043e.png)

**Comment by PeopleInside** [comment]
Hi @ComputerCarl , thank you for your interest on Live Helper Chat.

Mantain an open source project is not easy also you have not full time but you need to use your free time after work.

Remdex, the chat owner, is an amazing person :) update the documentation also required time and i imagine this time is used for fix bug or do improvments on the software.

I will try to help with your basic issue.

The avaiable documentation can be reached here: https://livehelperchat.com/documentation-6c.html

> changing the "Need help? Our staff are always ready to help"

You can change this into settings, live helper configuration (tab), widget theme, edit or create a new theme. Need Help widget (tab) than you can edit the two field as showed in the following screenshot:

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/61560164-d4355b80-aa6b-11e9-9e98-0ca697dc16ad.jpg)

> changing the phrase: "Pending a support staff member to join, you can write your questions, and as soon as a support staff member confirms this chat, he will get your message"

You can change this into Chat Widget tab as showed in this other screenshot:

![SharedScreenshot 1](https://user-images.githubusercontent.com/5006150/61560301-368e5c00-aa6c-11e9-9c39-6a8d348487b6.jpg)

> Can the image in "Show copyright widget logo in left corner" be changed rather than disabled?

Sure, let me search where is this for you.

![SharedScreenshot 2](https://user-images.githubusercontent.com/5006150/61560382-72c1bc80-aa6c-11e9-9404-e6a9c3e09560.jpg)

Hope this reply will solve your question / issue.

**Comment by ComputerCarl** [comment]
I'm sure it very difficult to maintain, from what I've explored of it - it is a very powerful application.  Thank you for time in supporting this project and for pointing out the places to change the text!

I will hack the other images and CSS to customize to my needs.

**Comment by PeopleInside** [comment]
Happy to help.
Enjoy :)
