### ISSUE TITLE
chat auto start, without filling visitor name

### ISSUE THREAD

**Issue by skumarchahar** [LiveHelperChat/livehelperchat#1375]
I am looking solution for visitor no need to fill form before start chat in visitor chat wizard.

**Comment by remdex** [comment]
Hi,
In start chat form settings you can disable all fields requirements. Also there is checkbox to auto start chat on widget open.

**Comment by PeopleInside** [comment]
Hi, i will close this as seems not an issue to keep open. 
If you need this to be reopened please alert us.
