### ISSUE TITLE
demo broken

### ISSUE THREAD

**Issue by adrelanos** [LiveHelperChat/livehelperchat#1381]
On https://forum.livehelperchat.com when you click the livehelperchat it just says "Chat was deleted".

**Comment by PeopleInside** [comment]
Hi @adrelanos ,
i hope your day is going well. Thank you for your interest in live helper chat!

The demo is opened to everyone so maybe someone has simply deleted your chat. This can be "fixed" by closing the widget and reopen again.

The demo works, no issue found.

Hope this helps you.
Have a nice day :)

Marco
