### ISSUE TITLE
SMTP settings working in some versions and not working in some versions

### ISSUE THREAD

**Issue by margach** [LiveHelperChat/livehelperchat#1384]
I have tested v2.46 v2.47 and SMTP settings work well and i tested the same settings against v3.14 and latest version and i get a `failed to authenticate` issue.

I think this bug is not due to Gmail as in earlier issues but with the Application it's self.

**Comment by remdex** [comment]
It's your configuration issues. My settings works fine. settings has to look like
![image](https://user-images.githubusercontent.com/1146085/66377928-2dea5980-e9bb-11e9-8570-9301970e043c.png)
