### ISSUE TITLE
Front end JS snippet not working after running update as per instructions

### ISSUE THREAD

**Issue by margach** [LiveHelperChat/livehelperchat#1386]
I Have updated from 2.47 to 3.24 using the upgrade.php method, these are the steps i followed:
1. Migrated DB and then executed upgrade.php file as per instructions.
2. over write the necessary files and enable cache again.
3. I enabled debug after the front end snippet failed to work and this is the stack trace.
`Fatal error: Uncaught Error: Call to undefined function MaxMind\Db\Reader\bcadd() in /var/www/html/lib/core/lhexternal/MaxMind/Db/Reader/Decoder.php:252 Stack trace: #0 /var/www/html/lib/core/lhexternal/MaxMind/Db/Reader/Decoder.php(236): MaxMind\Db\Reader\Decoder->decodeBigUint('\x00\x00\x00\x00T\xAC\xAF\xD7', 8) #1 /var/www/html/lib/core/lhexternal/MaxMind/Db/Reader/Decoder.php(125): MaxMind\Db\Reader\Decoder->decodeUint64('T\xAC\xAF\xD7') #2 /var/www/html/lib/core/lhexternal/MaxMind/Db/Reader/Decoder.php(91): MaxMind\Db\Reader\Decoder->decodeByType('uint64', 2786861, 4) #3 /var/www/html/lib/core/lhexternal/MaxMind/Db/Reader/Decoder.php(189): MaxMind\Db\Reader\Decoder->decode(2786861) #4 /var/www/html/lib/core/lhexternal/MaxMind/Db/Reader/Decoder.php(98): MaxMind\Db\Reader\Decoder->decodeMap(9, 2786859) #5 /var/www/html/lib/core/lhexternal/MaxMind/Db/Reader/Decoder.php(91): MaxMind\Db\Reader\Decoder->decodeByType('map', 2786788, 9) #6 /var/www/html/lib/core/lhexternal/MaxMind/Db/Reader.php(63): MaxMind\Db\Reader\Decoder in /var/www/html/lib/core/lhexternal/MaxMind/Db/Reader/Decoder.php on line 252` 

What i am missing here.

**Comment by remdex** [comment]
Your php installation is missing php bcmath extension.

**Comment by margach** [comment]
Thank you very much
