### ISSUE TITLE
Chats lists not being exported in version 3.24

### ISSUE THREAD

**Issue by margach** [LiveHelperChat/livehelperchat#1388]
After running an update from v2.39 to v3.25, the exporting to XLS files of the chat data does not seem to function.

I enabled debug and this is the file content i got in the XLS file.

![Screenshot from 2019-10-18 08-02-53](https://user-images.githubusercontent.com/19574578/67113508-5c014200-f1e2-11e9-815e-0bf2768960ab.png)

**Comment by PeopleInside** [comment]
Hi, the file has been generated from chat list?
I don't see any problem on my installation, maybe something went wrong on your update process.

When you update from an older version and not from the previous one you can expect more easly errors.

Are you sure all file has been uploaded correctly? Only indicated folders?
https://livehelperchat.com/article/view/63

What is your php version?
Are you using an old no supported php version?
https://www.php.net/supported-versions.php

**Comment by margach** [comment]
The file was only generated after i enabled debug, it says `zipArchive missing` in the log

**Comment by PeopleInside** [comment]
Maybe is something needed in your PHP installation. Extra configuration.
I'm not sure but maybe you can try a Google Search about missing zipArchive on php

**Comment by PeopleInside** [comment]
Hi @margach , have you resolved?

**Comment by margach** [comment]
Yes, a php extension was missing, the `zip extension`.
