### ISSUE TITLE
Short Time Zone Display in Online Visitors List

### ISSUE THREAD

**Issue by bkonia** [LiveHelperChat/livehelperchat#1390]
The time zone in the Online Visitors list is displayed in a long format like "America/Los Angeles", which is confusing, because it looks like a location. Could you please provide an option to display the time zone in a short format, like "10:41:27 UTC-8" and/or hide the display of the visitor's local time entirely?

**Comment by PeopleInside** [comment]
I don't agree with that but will leave opened for a review from the chat owner. I don't think this is confusing.
