### ISSUE TITLE
Chat icon not linking to correct page

### ISSUE THREAD

**Issue by jalamaack** [LiveHelperChat/livehelperchat#1396]
when i create the widget i get code .but its linking to the completely incorrect page if i hover over it it shows its linking back to the same page i am on with
https://www.ts3hosting.net/test.php

<script type="text/javascript">
var LHCChatOptions = {};
LHCChatOptions.opt = {widget_height:340,widget_width:300,popup_height:520,popup_width:500,domain:'ts3hosting.net'};
(function() {
var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
var referrer = (document.referrer) ? encodeURIComponent(document.referrer.substr(document.referrer.indexOf('://')+1)) : '';
var location  = (document.location) ? encodeURIComponent(window.location.href.substring(window.location.protocol.length)) : '';
po.src = 'https://helpdesk.ts3hosting.net/index.php/chat/getstatus/(click)/internal/(position)/bottom_right/(ma)/br/(top)/350/(units)/pixels/(leaveamessage)/true?r='+referrer+'&l='+location;
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
})();
</script>

**Comment by remdex** [comment]
You should adjust your server configuration because seems you have some security addon on your server or something similar.
![image](https://user-images.githubusercontent.com/1146085/67860011-972a3c00-fb25-11e9-896e-0ab79f2b786e.png)

**Comment by jalamaack** [comment]
Here is where its installed under this subdomain witch it works here same server
https://helpdesk.ts3hosting.net/test.php
linking it to page https://www.ts3hosting.net/test.php it fails.
only diffrence is the www. uses php 7.2 and helpdesk is set to php 5.6

**Comment by PeopleInside** [comment]
Hi, thanks to remdex.
Please see this FAQ article on the support forum https://forum.livehelperchat.com/viewtopic.php?id=2195#

**Comment by jalamaack** [comment]
Have tried that also tried on 2 other server https://reverseproject.trade/status/test.php still same issue so do not think its a server side problem

**Comment by PeopleInside** [comment]
Yes looks like is a configuration server side issue. I'm not at the PC right now but from the remdex screen seems something related to the article I linked.

**Comment by jalamaack** [comment]
Instead of using ifraims is there a way to have this open in a new window when they click the chat icon.
