### ISSUE TITLE
Support for Unix

### ISSUE THREAD

**Issue by MESWEB** [LiveHelperChat/livehelperchat#1401]
Is any way to get app for Unix for chat with customers?
When I try open Windows app on Linux:

> Cannot open assembly 'lhc.exe': File does not contain a valid CIL image.

**Comment by PeopleInside** [comment]
Hi @MESWEB,
there is not an app updated but you can use the web interface.

The Windows (and maybe also the Linux) app is not updated and has much lesser functions of the web interface that still be updated with the latest version.

You can install a dedicated browser than use this as chat software.
