### ISSUE TITLE
Chats not shown in the left panel under active chats section after update

### ISSUE THREAD

**Issue by margach** [LiveHelperChat/livehelperchat#1402]
1. I have updated from 2.45 to 3.00.
2. The active chats are not being displayed.
3. I have cleared cache in the app and also disabled cache in settings.ini.php but still geting the same issues.

what i am missing?

**Comment by remdex** [comment]
1. Make sure you updated database from back office.
2. Check for error in cache/default.log file.

**Comment by margach** [comment]
The file default.log is not in the cache folder

**Comment by remdex** [comment]
Well, not much I can help. You can try to use google chrome developer to see what you get in ajax request also enable debug output.  Then debug enable go to regular chat list to see do you see any chats.
https://livehelperchat.com/article/view/58

**Comment by PeopleInside** [comment]
Hi @margach the last live helper chat version is 3.25
Have you tried from different browsers or in incognito mode of the browser?
Also as remdex told you can try to enable debug and also check server error logs.

Be sure to use an updated PHP version: https://www.php.net/supported-versions.php

**Comment by margach** [comment]
It's not the browser or the version of PHP, i have tested on 5.5 and 7.3 and i still ran into the same issue.
The logs don't have any information.
The XHS  get returns a 503 http error.

I believe this is a cache issue, because i am using upgrade.php

**Comment by margach** [comment]
ezcPersistentQueryException Object
(
    [originalMessage] => A query failed internally in Persistent Object: SQLSTATE[HY000]: General error: 1364 Field 'conversion_id' doesn't have a default value Query: 'INSERT INTO `lh_chat_online_user` ( `ip`, `vid`, `current_page`, `invitation_seen_count`, `page_title`, `chat_id`, `last_visit`, `first_visit`, `user_agent`, `user_country_name`, `user_country_code`, `operator_message`, `operator_user_id`, `operator_user_proactive`, `message_seen`, `message_seen_ts`, `pages_count`, `tt_pages_count`, `lat`, `lon`, `city`, `identifier`, `time_on_site`, `tt_time_on_site`, `referrer`, `invitation_id`, `total_visits`, `invitation_count`, `requires_email`, `requires_username`, `requires_phone`, `dep_id`, `reopen_chat`, `operation`, `operation_chat`, `screenshot_id`, `online_attr`, `online_attr_system`, `visitor_tz`, `last_check_time`, `user_active`, `notes` ) VALUES ( :ezcValue1, :ezcValue2, :ezcValue3, :ezcValue4, :ezcValue5, :ezcValue6, :ezcValue7, :ezcValue8, :ezcValue9, :ezcValue10, :ezcValue11, :ezcValue12, :ezcValue13, :ezcValue14, :ezcValue15, :ezcValue16, :ezcValue17, :ezcValue18, :ezcValue19, :ezcValue20, :ezcValue21, :ezcValue22, :ezcValue23, :ezcValue24, :ezcValue25, :ezcValue26, :ezcValue27, :ezcValue28, :ezcValue29, :ezcValue30, :ezcValue31, :ezcValue32, :ezcValue33, :ezcValue34, :ezcValue35, :ezcValue36, :ezcValue37, :ezcValue38, :ezcValue39, :ezcValue40, :ezcValue41, :ezcValue42 )'
    [message:protected] => A query failed internally in Persistent Object: SQLSTATE[HY000]: General error: 1364 Field 'conversion_id' doesn't have a default value Query: 'INSERT INTO `lh_chat_online_user` ( `ip`, `vid`, `current_page`, `invitation_seen_count`, `page_title`, `chat_id`, `last_visit`, `first_visit`, `user_agent`, `user_country_name`, `user_country_code`, `operator_message`, `operator_user_id`, `operator_user_proactive`, `message_seen`, `message_seen_ts`, `pages_count`, `tt_pages_count`, `lat`, `lon`, `city`, `identifier`, `time_on_site`, `tt_time_on_site`, `referrer`, `invitation_id`, `total_visits`, `invitation_count`, `requires_email`, `requires_username`, `requires_phone`, `dep_id`, `reopen_chat`, `operation`, `operation_chat`, `screenshot_id`, `online_attr`, `online_attr_system`, `visitor_tz`, `last_check_time`, `user_active`, `notes` ) VALUES ( :ezcValue1, :ezcValue2, :ezcValue3, :ezcValue4, :ezcValue5, :ezcValue6, :ezcValue7, :ezcValue8, :ezcValue9, :ezcValue10, :ezcValue11, :ezcValue12, :ezcValue13, :ezcValue14, :ezcValue15, :ezcValue16, :ezcValue17, :ezcValue18, :ezcValue19, :ezcValue20, :ezcValue21, :ezcValue22, :ezcValue23, :ezcValue24, :ezcValue25, :ezcValue26, :ezcValue27, :ezcValue28, :ezcValue29, :ezcValue30, :ezcValue31, :ezcValue32, :ezcValue33, :ezcValue34, :ezcValue35, :ezcValue36, :ezcValue37, :ezcValue38, :ezcValue39, :ezcValue40, :ezcValue41, :ezcValue42 )'
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /var/www/html/ezcomponents/PersistentObject/src/persistent_session.php
    [line:protected] => 822
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /var/www/html/ezcomponents/PersistentObject/src/handlers/save_handler.php
                    [line] => 315
                    [function] => performQuery
                    [class] => ezcPersistentSession
                    [type] => ->
                    [args] => Array
                        (
                            [0] => ezcQueryInsert Object
                                (
                                    [values:protected] => Array
                                        (
                                            [`ip`] => :ezcValue1
                                            [`vid`] => :ezcValue2
                                            [`current_page`] => :ezcValue3
                                            [`invitation_seen_count`] => :ezcValue4
                                            [`page_title`] => :ezcValue5
                                            [`chat_id`] => :ezcValue6
                                            [`last_visit`] => :ezcValue7
                                            [`first_visit`] => :ezcValue8
                                            [`user_agent`] => :ezcValue9
                                            [`user_country_name`] => :ezcValue10
                                            [`user_country_code`] => :ezcValue11
                                            [`operator_message`] => :ezcValue12
                                            [`operator_user_id`] => :ezcValue13
                                            [`operator_user_proactive`] => :ezcValue14
                                            [`message_seen`] => :ezcValue15
                                            [`message_seen_ts`] => :ezcValue16
                                            [`pages_count`] => :ezcValue17
                                            [`tt_pages_count`] => :ezcValue18
                                            [`lat`] => :ezcValue19
                                            [`lon`] => :ezcValue20
                                            [`city`] => :ezcValue21
                                            [`identifier`] => :ezcValue22
                                            [`time_on_site`] => :ezcValue23
                                            [`tt_time_on_site`] => :ezcValue24
                                            [`referrer`] => :ezcValue25
                                            [`invitation_id`] => :ezcValue26
                                            [`total_visits`] => :ezcValue27
                                            [`invitation_count`] => :ezcValue28
                                            [`requires_email`] => :ezcValue29
                                            [`requires_username`] => :ezcValue30
                                            [`requires_phone`] => :ezcValue31
                                            [`dep_id`] => :ezcValue32
                                            [`reopen_chat`] => :ezcValue33
                                            [`operation`] => :ezcValue34
                                            [`operation_chat`] => :ezcValue35
                                            [`screenshot_id`] => :ezcValue36
                                            [`online_attr`] => :ezcValue37
                                            [`online_attr_system`] => :ezcValue38
                                            [`visitor_tz`] => :ezcValue39
                                            [`last_check_time`] => :ezcValue40
                                            [`user_active`] => :ezcValue41
                                            [`notes`] => :ezcValue42
                                        )

                                    [table:ezcQueryInsert:private] => `lh_chat_online_user`
                                    [db:protected] => ezcDbHandlerMysql Object
                                        (
                                            [identifierQuoteChars:protected] => Array
                                                (
                                                    [start] => `
                                                    [end] => `
                                                )

                                            [dbParams:ezcDbHandlerMysql:private] => Array
                                                (
                                                    [phptype] => mysql
                                                    [dbsyntax] => mysql
                                                    [username] => root
                                                    [password] => 123456
                                                    [protocol] => tcp
                                                    [hostspec] => 172.18.0.2
                                                    [port] => 3306
                                                    [socket] => 
                                                    [database] => mlc_nssf
                                                )

                                            [dsn:ezcDbHandlerMysql:private] => mysql:dbname=mlc_nssf;host=172.18.0.2;port=3306
                                            [reconnectedCounter:ezcDbHandlerMysql:private] => 0
                                            [transactionNestingLevel:protected] => 0
                                            [transactionErrorFlag:protected] => 
                                        )

                                    [aliases:ezcQuery:private] => 
                                    [boundCounter:ezcQuery:private] => 42
                                    [boundParameters:ezcQuery:private] => Array
                                        (
                                        )

                                    [boundParametersType:ezcQuery:private] => Array
                                        (
                                        )

                                    [boundValues:ezcQuery:private] => Array
                                        (
                                            [:ezcValue1] => 172.18.0.1
                                            [:ezcValue2] => 00ff5e9c3a59eec3fb72
                                            [:ezcValue3] => 
                                            [:ezcValue4] => 0
                                            [:ezcValue5] => 
                                            [:ezcValue6] => 0
                                            [:ezcValue7] => 1573471360
                                            [:ezcValue8] => 1573471360
                                            [:ezcValue9] => 
                                            [:ezcValue10] => 
                                            [:ezcValue11] => 
                                            [:ezcValue12] => 
                                            [:ezcValue13] => 0
                                            [:ezcValue14] => 
                                            [:ezcValue15] => 0
                                            [:ezcValue16] => 0
                                            [:ezcValue17] => 0
                                            [:ezcValue18] => 0
                                            [:ezcValue19] => 0
                                            [:ezcValue20] => 0
                                            [:ezcValue21] => 
                                            [:ezcValue22] => 
                                            [:ezcValue23] => 0
                                            [:ezcValue24] => 0
                                            [:ezcValue25] => 
                                            [:ezcValue26] => 0
                                            [:ezcValue27] => 1
                                            [:ezcValue28] => 0
                                            [:ezcValue29] => 0
                                            [:ezcValue30] => 0
                                            [:ezcValue31] => 0
                                            [:ezcValue32] => 0
                                            [:ezcValue33] => 0
                                            [:ezcValue34] => 
                                            [:ezcValue35] => 
                                            [:ezcValue36] => 0
                                            [:ezcValue37] => 
                                            [:ezcValue38] => 
                                            [:ezcValue39] => 
                                            [:ezcValue40] => 1573471360
                                            [:ezcValue41] => 0
                                            [:ezcValue42] => 
                                        )

                                    [boundValuesType:ezcQuery:private] => Array
                                        (
                                            [:ezcValue1] => 2
                                            [:ezcValue2] => 2
                                            [:ezcValue3] => 2
                                            [:ezcValue4] => 2
                                            [:ezcValue5] => 2
                                            [:ezcValue6] => 2
                                            [:ezcValue7] => 2
                                            [:ezcValue8] => 2
                                            [:ezcValue9] => 2
                                            [:ezcValue10] => 2
                                            [:ezcValue11] => 2
                                            [:ezcValue12] => 2
                                            [:ezcValue13] => 2
                                            [:ezcValue14] => 2
                                            [:ezcValue15] => 2
                                            [:ezcValue16] => 2
                                            [:ezcValue17] => 2
                                            [:ezcValue18] => 2
                                            [:ezcValue19] => 2
                                            [:ezcValue20] => 2
                                            [:ezcValue21] => 2
                                            [:ezcValue22] => 2
                                            [:ezcValue23] => 2
                                            [:ezcValue24] => 2
                                            [:ezcValue25] => 2
                                            [:ezcValue26] => 2
                                            [:ezcValue27] => 2
                                            [:ezcValue28] => 2
                                            [:ezcValue29] => 2
                                            [:ezcValue30] => 2
                                            [:ezcValue31] => 2
                                            [:ezcValue32] => 2
                                            [:ezcValue33] => 2
                                            [:ezcValue34] => 2
                                            [:ezcValue35] => 2
                                            [:ezcValue36] => 2
                                            [:ezcValue37] => 2
                                            [:ezcValue38] => 2
                                            [:ezcValue39] => 2
                                            [:ezcValue40] => 2
                                            [:ezcValue41] => 2
                                            [:ezcValue42] => 2
                                        )

                                    [expr] => ezcQueryExpression Object
                                        (
                                            [db:protected] => ezcDbHandlerMysql Object
                                                (
                                                    [identifierQuoteChars:protected] => Array
                                                        (
                                                            [start] => `
                                                            [end] => `
                                                        )

                                                    [dbParams:ezcDbHandlerMysql:private] => Array
                                                        (
                                                            [phptype] => mysql
                                                            [dbsyntax] => mysql
                                                            [username] => root
                                                            [password] => 123456
                                                            [protocol] => tcp
                                                            [hostspec] => 172.18.0.2
                                                            [port] => 3306
                                                            [socket] => 
                                                            [database] => mlc_nssf
                                                        )

                                                    [dsn:ezcDbHandlerMysql:private] => mysql:dbname=mlc_nssf;host=172.18.0.2;port=3306
                                                    [reconnectedCounter:ezcDbHandlerMysql:private] => 0
                                                    [transactionNestingLevel:protected] => 0
                                                    [transactionErrorFlag:protected] => 
                                                )

                                            [aliases:ezcQueryExpression:private] => 
                                            [quoteValues:protected] => 1
                                            [intervalMap:protected] => Array
                                                (
                                                    [SECOND] => SECOND
                                                    [MINUTE] => MINUTE
                                                    [HOUR] => HOUR
                                                    [DAY] => DAY
                                                    [MONTH] => MONTH
                                                    [YEAR] => YEAR
                                                )

                                        )

                                )

                        )

                )

            [1] => Array
                (
                    [file] => /var/www/html/ezcomponents/PersistentObject/src/handlers/save_handler.php
                    [line] => 103
                    [function] => saveInternal
                    [class] => ezcPersistentSaveHandler
                    [type] => ->
                    [args] => Array
                        (
                            [0] => erLhcoreClassModelChatOnlineUser Object
                                (
                                    [id] => 
                                    [ip] => 172.18.0.1
                                    [vid] => 00ff5e9c3a59eec3fb72
                                    [current_page] => 
                                    [user_agent] => 
                                    [chat_id] => 0
                                    [last_visit] => 1573471360
                                    [first_visit] => 1573471360
                                    [user_country_name] => 
                                    [user_country_code] => 
                                    [operator_message] => 
                                    [identifier] => 
                                    [operator_user_id] => 0
                                    [operator_user_proactive] => 
                                    [message_seen] => 0
                                    [message_seen_ts] => 0
                                    [pages_count] => 0
                                    [tt_pages_count] => 0
                                    [lat] => 0
                                    [lon] => 0
                                    [invitation_id] => 0
                                    [city] => 
                                    [time_on_site] => 0
                                    [tt_time_on_site] => 0
                                    [referrer] => 
                                    [page_title] => 
                                    [total_visits] => 1
                                    [invitation_count] => 0
                                    [requires_email] => 0
                                    [requires_username] => 0
                                    [dep_id] => 0
                                    [invitation_seen_count] => 0
                                    [screenshot_id] => 0
                                    [operation] => 
                                    [operation_chat] => 
                                    [online_attr] => 
                                    [online_attr_system] => 
                                    [visitor_tz] => 
                                    [notes] => 
                                    [requires_phone] => 0
                                    [last_check_time] => 1573471360
                                    [user_active] => 0
                                    [reopen_chat] => 0
                                    [store_chat] => 1
                                    [invitation_assigned] => 
                                )

                            [1] => 
                            [2] => ezcPersistentNativeGenerator Object
                                (
                                )

                        )

                )

            [2] => Array
                (
                    [file] => /var/www/html/ezcomponents/PersistentObject/src/persistent_session.php
                    [line] => 454
                    [function] => saveOrUpdate
                    [class] => ezcPersistentSaveHandler
                    [type] => ->
                    [args] => Array
                        (
                            [0] => erLhcoreClassModelChatOnlineUser Object
                                (
                                    [id] => 
                                    [ip] => 172.18.0.1
                                    [vid] => 00ff5e9c3a59eec3fb72
                                    [current_page] => 
                                    [user_agent] => 
                                    [chat_id] => 0
                                    [last_visit] => 1573471360
                                    [first_visit] => 1573471360
                                    [user_country_name] => 
                                    [user_country_code] => 
                                    [operator_message] => 
                                    [identifier] => 
                                    [operator_user_id] => 0
                                    [operator_user_proactive] => 
                                    [message_seen] => 0
                                    [message_seen_ts] => 0
                                    [pages_count] => 0
                                    [tt_pages_count] => 0
                                    [lat] => 0
                                    [lon] => 0
                                    [invitation_id] => 0
                                    [city] => 
                                    [time_on_site] => 0
                                    [tt_time_on_site] => 0
                                    [referrer] => 
                                    [page_title] => 
                                    [total_visits] => 1
                                    [invitation_count] => 0
                                    [requires_email] => 0
                                    [requires_username] => 0
                                    [dep_id] => 0
                                    [invitation_seen_count] => 0
                                    [screenshot_id] => 0
                                    [operation] => 
                                    [operation_chat] => 
                                    [online_attr] => 
                                    [online_attr_system] => 
                                    [visitor_tz] => 
                                    [notes] => 
                                    [requires_phone] => 0
                                    [last_check_time] => 1573471360
                                    [user_active] => 0
                                    [reopen_chat] => 0
                                    [store_chat] => 1
                                    [invitation_assigned] => 
                                )

                        )

                )

            [3] => Array
                (
                    [file] => /var/www/html/lib/models/lhchat/erlhcoreclassmodelchatonlineuser.php
                    [line] => 855
                    [function] => saveOrUpdate
                    [class] => ezcPersistentSession
                    [type] => ->
                    [args] => Array
                        (
                            [0] => erLhcoreClassModelChatOnlineUser Object
                                (
                                    [id] => 
                                    [ip] => 172.18.0.1
                                    [vid] => 00ff5e9c3a59eec3fb72
                                    [current_page] => 
                                    [user_agent] => 
                                    [chat_id] => 0
                                    [last_visit] => 1573471360
                                    [first_visit] => 1573471360
                                    [user_country_name] => 
                                    [user_country_code] => 
                                    [operator_message] => 
                                    [identifier] => 
                                    [operator_user_id] => 0
                                    [operator_user_proactive] => 
                                    [message_seen] => 0
                                    [message_seen_ts] => 0
                                    [pages_count] => 0
                                    [tt_pages_count] => 0
                                    [lat] => 0
                                    [lon] => 0
                                    [invitation_id] => 0
                                    [city] => 
                                    [time_on_site] => 0
                                    [tt_time_on_site] => 0
                                    [referrer] => 
                                    [page_title] => 
                                    [total_visits] => 1
                                    [invitation_count] => 0
                                    [requires_email] => 0
                                    [requires_username] => 0
                                    [dep_id] => 0
                                    [invitation_seen_count] => 0
                                    [screenshot_id] => 0
                                    [operation] => 
                                    [operation_chat] => 
                                    [online_attr] => 
                                    [online_attr_system] => 
                                    [visitor_tz] => 
                                    [notes] => 
                                    [requires_phone] => 0
                                    [last_check_time] => 1573471360
                                    [user_active] => 0
                                    [reopen_chat] => 0
                                    [store_chat] => 1
                                    [invitation_assigned] => 
                                )

                        )

                )

            [4] => Array
                (
                    [file] => /var/www/html/lib/models/lhchat/erlhcoreclassmodelchatonlineuser.php
                    [line] => 820
                    [function] => saveThis
                    [class] => erLhcoreClassModelChatOnlineUser
                    [type] => ->
                    [args] => Array
                        (
                        )

                )

            [5] => Array
                (
                    [file] => /var/www/html/modules/lhchat/startchat.php
                    [line] => 302
                    [function] => handleRequest
                    [class] => erLhcoreClassModelChatOnlineUser
                    [type] => ::
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [message_seen_timeout] => 24
                                    [check_message_operator] => 1
                                    [vid] => 00ff5e9c3a59eec3fb72
                                )

                        )

                )

            [6] => Array
                (
                    [file] => /var/www/html/lib/core/lhcore/lhmodule.php
                    [line] => 97
                    [args] => Array
                        (
                            [0] => /var/www/html/modules/lhchat/startchat.php
                        )

                    [function] => include
                )

            [7] => Array
                (
                    [file] => /var/www/html/lib/core/lhcore/lhmodule.php
                    [line] => 485
                    [function] => runModule
                    [class] => erLhcoreClassModule
                    [type] => ::
                    [args] => Array
                        (
                        )

                )

            [8] => Array
                (
                    [file] => /var/www/html/index.php
                    [line] => 38
                    [function] => moduleInit
                    [class] => erLhcoreClassModule
                    [type] => ::
                    [args] => Array
                        (
                        )

                )

        )

    [previous:Exception:private] => 
)

**Comment by remdex** [comment]
It seems you are using someway older version and it seems not all files were updated...

**Comment by margach** [comment]
This log does not show in the dashboard but show only in the front end user widget when you try to start a chat.

Let try another version

**Comment by margach** [comment]
By the way, am trying to update from 2.44 and i noticed it's missing in the releases, any particular reason.

**Comment by margach** [comment]
`"GET /index.php/site_admin/chat/syncadmininterface/(limita)/10/(limitu)/10/(limitp)/10/(limito)/10/(limitc)/10/(limitd)/10/(limitmc)/10/(limitb)/10` 

`HTTP/1.1" 503 401 "http://172.18.0.3/index.php/site_admin/system/configuration" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0" `

This is the exact http call that is failing, any directions on fixing it, comes back with a 503 error

**Comment by PeopleInside** [comment]
Hi @margach sorry but this seems not a live helper chat issue (503) error.

Are you trying to instal the last 3.25 version with PHP 7.3?
What steps did you follow for do the installation?

If you need there is premium support or you can consider the hosted version.
Premium support: https://forum.livehelperchat.com/viewtopic.php?id=2255
Hosted version: https://livehelperchat.com/order/now

**Comment by margach** [comment]
@PeopleInside We are doing an update and a migration and yes, i have tested PHP 7.3 as well, these are the steps:
1. export and import the DB
2. Over write design, lib, modules, pos, translations,doc,ezcomponents
3. copy upgrade.php in root and run it in browser
4. It indicates the "UPDATE DONE" and i can login in

All seems to work well part from the section of the app that displaces chats in active queue and the front end widget does not update to the current theme as well and it stops working.

**Comment by PeopleInside** [comment]
Maybe try to do a new completely install of 2.35 with PHP 7.3
It works?

Also you can try maybe to do the upgrade without use update.php try just the standard update.

**Comment by PeopleInside** [comment]
Hi, I'm closing this issue as seems to be not related to a feature request or a bug.
You can try the suggestions on my previous message also I suggest to keep software updated to avoid this kind of issue.

**Comment by margach** [comment]
Okay, but is they a way to clear cache manually when in the app folder, i do believe this is a cache issue

**Comment by PeopleInside** [comment]
You can clear cache in settings, clean cache.
You can also disable temporary cache: https://livehelperchat.com/article/view/40
