### ISSUE TITLE
BOT API

### ISSUE THREAD

**Issue by cincenfrank** [LiveHelperChat/livehelperchat#1403]
Hi,
I would like to know if is it possible to set an api call to an external service inside a lhc bot.
For example I would like to set a trigger for any chat event (start, new message, new file, close ecc), and then suddenly send a request via POST (with all chat info and parameter), wait for a response and then make the bot to execute an action based on the obtained value.

Thank's in advance

**Comment by PeopleInside** [comment]
Hi, have you looked here: https://api.livehelperchat.com/ ?

**Comment by cincenfrank** [comment]
Hi, thank you very much for your reply. Yes i looked at that material but my problem is that i don't understand how can i make the bot to automatically send a request via post every time a chat event is triggered and then wait for a response.

**Comment by PeopleInside** [comment]
Umh I cannot help with that.

**Comment by remdex** [comment]
Take a look here.
https://github.com/LiveHelperChat/lhcgooglesuggest
