### ISSUE TITLE
Have purchase after/before some chat to resume conversation

### ISSUE THREAD

**Issue by mmdm95** [LiveHelperChat/livehelperchat#1405]
Hi, I want have purchase during the chat or even before chat starts. What can I do? Anyone can help?

**Comment by PeopleInside** [comment]
Hi, have you looked at the relative documentation: [How to use paid chats feature?](https://livehelperchat.com/how-to-use-paid-chats-feature-439a.html)

**Comment by mmdm95** [comment]
Yes I have and i need to show a purchase link to user and save chat_id and my id for user in another database and the paid configuration you mentioned, is for (and i quote from documentation) 

> User won't be able to start new chat if chat is already started.

**Comment by PeopleInside** [comment]
In this case i cannot help as i don't have other informations. You need help from @remdex 
Remember a commercial support exist and help this project to stay alive for free: https://livehelperchat.com/support-13c.html
