### ISSUE TITLE
final stages of install... mySQL

### ISSUE THREAD

**Issue by venkytt** [LiveHelperChat/livehelperchat#1409]
Hello

Install takes too much time. 

I got a time out message after 31 seconds the 1st time. Turned out to be the timeout in httpd.conf : IPCCommTimeout which had been at 31

I tried increasing PHP ini max_execution_time = 300 and also set IPCCommTimeout  to 300

I see tables being created in mySQL. After creating 91 pages, i get "empty response"

Is there a way I can run an SQL script to create all the tables and avoid the timeout issue?

Maybe worst case, i will set it to 1 hour, install it and then set the timeouts back? uggghh... :-(

Any help/ advise will be welcome

Thanks

**Comment by PeopleInside** [comment]
Hi, live helper chat should not take long to install on a server.
Are you installing in a VPS or dedicated server?
Have you checked error server log?

What version of PHP and MySQL are you using?

**Comment by venkytt** [comment]
It took a while.. about 12 minutes and finally installed

Thanks!

**Comment by PeopleInside** [comment]
I'm happy to read the issue was resolved.
