### ISSUE TITLE
ClamAV - socket connection failure - No such file or directory

### ISSUE THREAD

**Issue by b060149ee** [LiveHelperChat/livehelperchat#1412]
Hi,

I want to enable clamav virus scan on the files that a user uploads. I've enabled the scanner in the Files Configuration.

The livehelperchat is installed at /var/www/chat/. I've installed clamav and clamav-daemon using apt-get. Both the clamav-daemon and clamav-freshclam services are now active on my server. The socket file path is /var/run/clamav/clamd.ctl.

Now, when I upload a file, the socket method tries to make a socket connection (using socket_connect) and I get a "No such file or directory" error. I think socket_connect's 2nd param accepting a unix path is getting the /var/run/clamav/clamd.ctl value, but the socket_conecction is expecting the path under /var/www/chat/ resulting in /var/www/chat/var/run/clamav/clamd.ctl.

How can I make it to use the root->/var/run/clamav/clamd.ctl?

Should I install clamav via source for this to work?

**Comment by remdex** [comment]
In my case it worked like this. If it does not work for you. Means you are using some chroot or some custom php configuration which forces php see wrong path.
![image](https://user-images.githubusercontent.com/1146085/71887092-1485b480-3146-11ea-9e2d-6cb8a297d93d.png)

**Comment by b060149ee** [comment]
Thanks for the quick reply. Really appreciate it. Yes, we have chroot on our server. Does that mean that I have to build it via source code and install clamav inside the chat directory?

Also the clamav by default gives a ctl and not a sock, I hope that is ok.

**Comment by b060149ee** [comment]
I continued the investigation and decided to use 'mount --bind'. After this we were able to successfully open a socket connection. But now I get 'Can't open file or directory' error at the time of scanning the file'.

**Comment by remdex** [comment]
It's not related to LHC so closing this issue.

**Comment by RejithkumarR** [comment]
if (isset($this->options['antivirus']) && $this->options['antivirus'] !== false && is_object($this->options['antivirus']) && !$this->options['antivirus']->scan(realpath($this->options['upload_dir'] . $file->name))) {
            unlink($this->options['upload_dir'] . $file->name);
            erLhcoreClassFileUpload::removeRecursiveIfEmpty('var/', str_replace('var/', '', $this->options['upload_dir']));
            $file->error = 'Virus found in file!';
        }
        
        is this above code correct I have installed clamdav in my server but if i enabled antivirus check flag in live chat helper "Virus found error only throwing";
how can i complete this
