### ISSUE TITLE
Chat "referrer" property is empty after update

### ISSUE THREAD

**Issue by andrerinaldi** [LiveHelperChat/livehelperchat#1435]
Hi,

I've updated LiveHelper to the latest version.

I was listening for the chat.new_chat event and checking the calling hostname from the `$chat->referrer` property.

When developing on my machine I was used to see that property filled in with the value "http://localhost". After updating LiveHelper I always get it empty.

Is there something I'm missing?

Thank you in advance.

`{
   "id":19,
   "nick":"ffa",
   "status":0,
   "status_sub":0,
   "status_sub_sub":0,
   "time":1582563164,
   "user_id":0,
   "sender_user_id":0,
   "hash":"26d9c2012281c76410393266606334f3f8e4fc07",
   "ip":"::1",
   "referrer":"",
   "dep_id":1,
   "email":"",
   "user_status":0,
   "support_informed":0,
   "country_code":"",
   "country_name":"",
   "phone":"",
   "user_typing":0,
   "user_typing_txt":"",
   "operator_typing":0,
   "has_unread_messages":0,
   "last_user_msg_time":0,
   "last_msg_id":28,
   "mail_send":0,
   "lat":"0",
   "lon":"0",
   "city":"",
   "additional_data":"",
   "session_referrer":"",
   "wait_time":0,
   "chat_duration":0,
   "priority":0,
   "online_user_id":0,
   "lsync":1582563164,
   "transfer_if_na":0,
   "transfer_timeout_ts":0,
   "transfer_timeout_ac":0,
   "transfer_uid":0,
   "pnd_time":1582563164,
   "cls_time":0,
   "auto_responder_id":0,
   "user_tz_identifier":"Europe\/Paris",
   "na_cb_executed":0,
   "nc_cb_executed":1,
   "fbst":0,
   "operator_typing_id":0,
   "chat_initiator":0,
   "chat_variables":"",
   "remarks":"",
   "operation":"",
   "operation_admin":"",
   "screenshot_id":"0",
   "unread_messages_informed":0,
   "reinform_timeout":0,
   "last_op_msg_time":0,
   "has_unread_op_messages":0,
   "unread_op_messages_informed":0,
   "user_closed_ts":0,
   "unanswered_chat":1,
   "product_id":0,
   "usaccept":0,
   "status_sub_arg":"",
   "tslasign":0,
   "chat_locale":"en-IT",
   "chat_locale_to":"",
   "uagent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/80.0.3987.106 Safari\/537.36 Edg\/80.0.361.54",
   "anonymized":0,
   "invitation_id":0,
   "device_type":0,
   "updateIgnoreColumns":[

   ],
   "department":{
      "id":1,
      "name":"IT",
      "email":"",
      "priority":0,
      "sort_priority":0,
      "department_transfer_id":0,
      "transfer_timeout":0,
      "identifier":"",
      "xmpp_recipients":"",
      "xmpp_group_recipients":"",
      "mod_start_hour":-1,
      "mod_end_hour":-1,
      "tud_start_hour":-1,
      "tud_end_hour":-1,
      "wed_start_hour":-1,
      "wed_end_hour":-1,
      "thd_start_hour":-1,
      "thd_end_hour":-1,
      "frd_start_hour":-1,
      "frd_end_hour":-1,
      "sad_start_hour":-1,
      "sad_end_hour":-1,
      "sud_start_hour":-1,
      "sud_end_hour":-1,
      "inform_delay":0,
      "inform_options":"",
      "inform_close":0,
      "online_hours_active":0,
      "disabled":0,
      "hidden":0,
      "inform_unread":0,
      "inform_unread_delay":0,
      "na_cb_execute":0,
      "nc_cb_execute":0,
      "active_balancing":0,
      "max_active_chats":0,
      "max_timeout_seconds":0,
      "attr_int_1":0,
      "attr_int_2":0,
      "attr_int_3":0,
      "visible_if_online":0,
      "inform_close_all":0,
      "inform_close_all_email":"",
      "pending_max":0,
      "pending_group_max":0,
      "exclude_inactive_chats":0,
      "max_ac_dep_chats":0,
      "active_chats_counter":4,
      "delay_before_assign":0,
      "pending_chats_counter":8,
      "closed_chats_counter":0,
      "assign_same_language":0,
      "product_configuration":"",
      "bot_configuration":"",
      "delay_lm":0,
      "inform_options_array":[

      ]
   }
}`

**Comment by remdex** [comment]
Actually all is working as expected. Now I just check referee for javascript variable (https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/design/defaulttheme/widget/wrapper/src/index.js#L53) if it's set - it's stored. Otherwise empty string is stored. It means if you open page first time without any referrer you will have empty referee.
Old widget behaved a little bit different that's why i ques there is this different.
