### ISSUE TITLE
PHP Fatal error:  Can't use function return value in write context

### ISSUE THREAD

**Issue by JosueUh** [LiveHelperChat/livehelperchat#1439]
I see the following error in the console:

PHP Fatal error: Can't use function return value in write context in /var/www/html/lhc_web/lib/core/lhchat/lhchatvalidator.php on line 788

PHP version 7.2.28

Code snippet:

if (isset($data[str_replace('lhc_var.','',$jsVar->js_variable)]) && !empty(str_replace('lhc_var.','',$jsVar->js_variable))) {
    789                 $val = $data[str_replace('lhc_var.','',$jsVar->js_variable)];
    790             } elseif (isset($data[$jsVar->id]) && !empty($data[$jsVar->id])) {
    791                 $val = $data[$jsVar->id];
    792             }

I replaced line 788 with:

if (isset ($ var_js) &&! empty ($ var_js_replace)) {

the error is resolved on that line, but the error appears on another line of similar code.

**Comment by remdex** [comment]
Well i think you misconfigured something as i can't reproduce just...

**Comment by remdex** [comment]
Then you define custom variable in variables seciton you have to define also all fields. See https://livehelperchat.com/pre-filling-form-fields-and-adding-custom-fields-140a.html
Seems you did not filled all fields.
