### ISSUE TITLE
Suggested changes to RTL view css

### ISSUE THREAD

**Issue by appa1303** [LiveHelperChat/livehelperchat#1440]
Hi after installing the LHC, there are some minor RTL issues
I can correct those using the 
\design\customtheme\css\override_rtl.css

Can you make it can be part of the default CSS ?

Move the button to the left in the Enter question 
        .user-chatwidget-buttons {
            /*border: 1px solid red; */
            right:unset;
            left:3px;
        }

Fix the "send message" button image (flip vertical)
        #ChatSendButtonContainer a i {
            -webkit-transform: scaleX(-1);
            transform: scaleX(-1);
        }

**Comment by shahmirf** [comment]
I have the same issue as well
