### ISSUE TITLE
Copyright widget logo in left corner

### ISSUE THREAD

**Issue by shahmirf** [LiveHelperChat/livehelperchat#1442]
Hello 
In version 3.29 when enable Show copyright widget logo in left corner, It will not show logo in chat start form. 
Detailed is mentioned in LHC forum too.
https://forum.livehelperchat.com/viewtopic.php?pid=13877#p13877
Thank you in advance

**Comment by PeopleInside** [comment]
Hi, can you show the issue with a screenshot where you suppose to find the image?
The new chat widget as changed.

In the forum you mentioned chatbox who is something of different from the widget chat.

**Comment by PeopleInside** [comment]
I understood you mean in the theme editing options.
Maybe the function is not yet available on the new widget and don't know if will be implemented.
I will keep this issue open for the chat owner.

**Comment by shahmirf** [comment]
Hello
Sorry for misunderstanding, I mean widgetcontainer, ( I tried with the modern mode and old one as well)
I will attached the sample / in preview is working but it will not visible when loading in web.
![12](https://user-images.githubusercontent.com/62466468/77230632-2e665d80-6bb3-11ea-9d44-53405dfec502.png)

**Comment by remdex** [comment]
I have removed this attribute in new updated. Please update. It won't be visible anymore. It was removed because a lot of clients don't want it in any case...
