### ISSUE TITLE
How to impliment in laravel or other mvc project

### ISSUE THREAD

**Issue by chirumist** [LiveHelperChat/livehelperchat#1446]
Hi 
I have issue with implementation on existing project 
I have try iframe or inclue lhc_web/index.php file but get error class not found 
Is any way to impliment on existing project

**Comment by remdex** [comment]
Hi,

I really don't think it's possible to do it that way. Most integrations are done using just 
https://api.livehelperchat.com/#/

Or generating auto login links.
https://doc.livehelperchat.com/docs/users/auto-login/

**Comment by remdex** [comment]
As for iframe embeding it should work. So this error you get is really not related to lhc itself..

**Comment by chirumist** [comment]
Thanks For Fast Response
i cant try using iframe but login dose not work or also try auto login url
