### ISSUE TITLE
Chat from to bot to other bot

### ISSUE THREAD

**Issue by altomarketing** [LiveHelperChat/livehelperchat#1449]
How can i define to transfer from a bot to other bot ?

I can not see where can i set destination bot.

**Comment by remdex** [comment]
You can't change if chat is going with one bot. But you can reuse another bot logic by editing bot and chooses what other bot logic should be applied

**Comment by altomarketing** [comment]
> You can't change if chat is going with one bot. But you can reuse another bot logic by editing bot and chooses what other bot logic should be applied

Sorry but i dont understand. I have one robot for billing, other for tech support, and so on. I can not paste json from one to another, because i dont want a super-long bot logic.

Can i transfer with a bot to a department > and that this dept only a bot is answering, could it be a solution?

**Comment by remdex** [comment]
Hi,

Solution is
1. You edit a bot, "Edit" button.
2. You choose "These bot logic applies also" there you choose what bot's include in editing bot. Once you again got to standard bot building interface you will see trigger groups from chosen bots.

**Comment by altomarketing** [comment]
ok some questions and i will write how to use it in doc.livehelper

i have BotA - BotB - BotC

BotB include BotA

1. What happen if building inside BotB i erase a group ? it erase on BotA also?
2. If BotC include botA and botB , every change i make in BotC , is changed on other bots ?

**Comment by remdex** [comment]
1. yes it is erased also from BotA
2. Correct
