### ISSUE TITLE
setup cronjob for Notifications autoload.php missing

### ISSUE THREAD

**Issue by ayman-mahmoud** [LiveHelperChat/livehelperchat#1450]
I'm trying to run this command to enable cronjob notifications for visitor unread messages

    php cron.php -s site_admin -c cron/notifications
    But error occur due to missing files "lib/vendor/autoload.php"
    PHP Warning: include(lib/vendor/autoload.php): failed to open stream: No such file or directory in
    E:...\lhc_web\modules\lhcron\notifications.php on line 10

How can I solve this problem

**Comment by remdex** [comment]
Hi,

I'll update tutorial regarding these type of notifications. As there is two types in genreal
1. Browser notifications about unread messages. This is the one you are trying to setup. You have to run `composer.phar` update being in `lhc_web` folder.

2. For simple mail notifications to visitors about unread messages it's enough to run
https://doc.livehelperchat.com/docs/development/cronjob/#default-cronjob-setup

**Comment by ayman-mahmoud** [comment]
Hi,
Actually I mean the second type of notifications, I want to send email to visitors if they have unread messages from operator. So, you mean that this command is enough
php cron.php -s site_admin -c cron/workflow

plus enable this option with minutes more than 0 in Chat configuration page
Inform visitor about unread messages from operator, value in minutes. 0 - disabled

But, I may need also enabling browser notifications but no files with name composer.phar in the lhc_web folder.

Thanks

**Comment by remdex** [comment]
Hi,
1. Yes enough to be running workflow cronjob as you wrote.
2. You have to enter 1 in Settings -> Chat configuration -> Workflow -> "Inform visitor if he has unread messages"

And it should be enough. As i told next week I'll prepare tutorial for both scenarios.

**Comment by ayman-mahmoud** [comment]
Hi,
Thanks for your feedback, but I made all the steps but it didn't work. No mails are sent to visitors. I tried this from the version installed on my servers and even from our hosted domain on livehelperchat.com/
For the version on my servers I made the following steps
1- Settings -> Chat configuration -> Workflow -> "Inform visitor if he has unread messages" set to "1"
2- php cron.php -s site_admin -c cron/workflow
3- php cron.php -s site_admin -c cron/notifications "I made this as written in https://doc.livehelperchat.com/docs/development/cronjob/#notifications

Thanks for your effort, hope we can solve this issue asap

**Comment by remdex** [comment]
Follow this..

I just tested myself and all works. Means problems on your end so nothing more I can help.
https://doc.livehelperchat.com/docs/chat/unread-chat-notifications

**Comment by ayman-mahmoud** [comment]
Well,
I will make the steps again as you mentioned in the help, but I have two questions if you please.
1- How do I know that cronjob setup was correct, when I run the command I got the following messages
Starting chat/workflow
Closed chats - 0
Purged chats - 0
Ended chat/workflow

Is that correct and now cronjob is configured and running 

2- My second questions, why from my subdomain hosted on Livehelperchat domain, notifications aren't sent to visitors although sure your mail server is sending mails as operators always receive the new request chat and accepted chats mails.

Thanks

**Comment by remdex** [comment]
1. Yes it's correct.
2. I don't think I presently have this workflow on hosted version. Will be adding next week.

**Comment by ayman-mahmoud** [comment]
Well,
Thank you very much for your support, but my last question is how to make cronjob run automatically with out the need to re-run the command manually or should i make a task scheduler to run it every defined period.

**Comment by remdex** [comment]
Yes, it has to be cronjob every minute or five minutes up to you :)
