### ISSUE TITLE
Access to XMLHttpRequest at 'https://xx.x/index.php/nld/widgetrestapi/submitonline' has been blocked

### ISSUE THREAD

**Issue by mrdanleey** [LiveHelperChat/livehelperchat#1453]
Live Helper Chat version : 3.32

Hello,

I installed Live Helper Chat on my website and inserted the HTML (Beta) widget on my support website. The chatbutton is vissible and when I'm offline the visitor can fill in the form in the chatwidget. But when I'm online the chatwidget is blank and the console in the browser gives the following error:

Access to XMLHttpRequest at 'https://xx.x/index.php/nld/widgetrestapi/submitonline' from origin 'https://support.dfeenstra.nl' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I went to my hostingprovider and they said that everything for the CORS Policy is working as it should. So the problem should be in the code from Live Helper Chat.

**Comment by remdex** [comment]
Sorry, but your hosting provider is lying. Because PHP script send these headers. So means your apache configuration removes them.

**Comment by remdex** [comment]
Also in your chat configuration I see you have Auto start checked. But you require message field. Please disable Auto start in start chat configuraiton or disable message field requirement form visitor.

**Comment by remdex** [comment]
As stated here you should not have any required field if you have Auto Start enabled.
https://doc.livehelperchat.com/docs/chat/start-chat-form-settings/#auto-start-chat-if-there-is-no-required-fields-usefull-in-case-bot-handles-chat
