### ISSUE TITLE
LHC_API.args offline_redirect  does not work

### ISSUE THREAD

**Issue by altomarketing** [LiveHelperChat/livehelperchat#1454]
As you can test here: https://chatconclientes.info/index.html  if no operators, gives a blank html

And it does not redirect as code says:

```javascript
LHC_API.args = {
        mode: 'embed',
        lhc_base_url: '//www.chatconclientes.info/index.php/',
		offline_redirect: 'https://www.google.com', 
        wheight: 450,
        wwidth: 350,
        pheight: 520,
```

**Comment by remdex** [comment]
1. You should fix your cors headers. https://doc.livehelperchat.com/docs/integrating/#my-widget-does-not-work-i-have-live-helper-chat-installed-on-one-domain-but-code-is-embeded-on-another-domain

2. Offline_redirect is not used in embed mode in general.

**Comment by altomarketing** [comment]
1. fixed

2. how can i use this variable then ? , i want a simple html with the chat, and in case no operator, to redirect to another website.

**Comment by remdex** [comment]
I'll add support for redirect in embed mode in next relese. Thursday/Friday or earlier :)

**Comment by remdex** [comment]
Released new version which should take care of your workflow. See documentation notice to be sure you met.
https://doc.livehelperchat.com/docs/javascript-arguments/

**Comment by altomarketing** [comment]
it works like charm now ! 👯‍♂️
