### ISSUE TITLE
Changing language (to nl_NL) as user blocks to site maintenance

### ISSUE THREAD

**Issue by CoMPaTech** [LiveHelperChat/livehelperchat#1456]
Hi

Fantastic tool from what I've gathered sofar in your demo site and while deploying it locally. As soon (as admin or as operator) as I change my language to nl_NL from the dropdown I get the 'We'll be back soon!' site maintenance (which you can't get out of because of session cookie). Manually changing it back in MySQL and deleting the cookie works, but either I missed a step or something is missing.

Using latest cloned version (3.33) (as codeload is down for releases packages) - while at it, your download button on the site still points to your old repository. Checking out 3.32v tag doesn't seem different.

**Comment by remdex** [comment]
Right. I’ll check tomorrow if I can reproduce :)

**Comment by CoMPaTech** [comment]
Be happy to help you out, was just setting up, didn't start debugging yet - btw, quick & swift response @remdex :)

**Comment by remdex** [comment]
One more thing chech cache/default.log for error message :)

**Comment by CoMPaTech** [comment]
Right, fixed ... php-xml must be included as install dependency (I had all green so that might be useful to include. Apologies for not looking in cache for logging, duly noted.

**Comment by CoMPaTech** [comment]
(ow right, what I found was simplexml no such function or likewise, so it was pretty obvious php-xml needed to be apt installed)
