### ISSUE TITLE
Issue with chat print

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1460]
Chat print is not possible if the chat has been closed; visitor can only see the transcript online of the closed chat.

If the chat with the visitor has been closed by the operator or visitor there is no option to print the chat. The chat can be printed only if opened, this should be possible also if the chat has been closed.

**Comment by remdex** [comment]
Sorry, but I can print a chat if chat is closed by operator.

**Comment by PeopleInside** [comment]
You can check this in theme so visitor won' be redirected to survey isntantlyIt's in theme
![picturemessage_sxc5os3q jvt](https://user-images.githubusercontent.com/5006150/80871151-54e7e000-8cab-11ea-8c36-7b634db0357f.png)

This is avoid this issue
