### ISSUE TITLE
Get chat attachments

### ISSUE THREAD

**Issue by ayman-mahmoud** [LiveHelperChat/livehelperchat#1466]
Hi,
I have cronjob running to close chats using setup I defined in the back office, but I need to have the chat attachments, voice records, screen records and screen shots if exist to be sent with the closing mail whichs sent to the operator. I opened the classes that send the mails but I didn't know how to get those items.

**Comment by remdex** [comment]
In that part you can do something like to get all file list.

erLhcoreClassModelChatFile::getList(['filter' => ['chat_id' => $chat->id]]);

**Comment by ayman-mahmoud** [comment]
Thanks
