### ISSUE TITLE
Preserve online option after logout. For plugins to work independently.

### ISSUE THREAD

**Issue by Vintic** [LiveHelperChat/livehelperchat#1468]
related to https://github.com/LiveHelperChat/telegram/issues/26

Can we have option in User, Department, Global or Telegram settings - "Preserve online option after logout"? Or to be able to set online/offline status from Telegram?

This option is necessary for telegram plugin to work properly with "Auto assignment workflow".

Story:
I created department with user and his manager. Set both online. Both connected to telegram. And both logged out.
Set working hours for dep.. Set reassign after 30sec. Added widget with user assign.
Now message is sent to assigned user, after 30 sec. manager don't receive it. When I login to Manager account, chat will reassign to him and message will be sent to his telegram.

**Comment by remdex** [comment]
Please try it out this branch or just wait for a new release on friday.
https://github.com/LiveHelperChat/livehelperchat/tree/master-alwaysonline

**Comment by remdex** [comment]
I have released new version so just update to official version. There will be an option to set your online condition in top menu.
