### ISSUE TITLE
Canned messages unable to add more using delay.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1471]
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/82765977-76a43500-9e1b-11ea-888f-5892eba6d803.jpg)

I have one canned message that is sent when chat is accepted (1) in the screenshot.
This canned message inform the visitor about protected SSL chat.

I need after 10 second send another canned message automatically after the first one and from my test I still be unable to do so. I tried to set delay, to use different position, same, etc. Nothing work.

The second massage (2) should be sent automatically after chat has been accepted and after the delay time. It contain a different message that i cannot include in the first one because will be too long to read. Doesn't work on my install and on the demo.

I'm wrong, is not supported or should maybe be implemented?
I use the latest version of live helper chat 3.35

**Comment by remdex** [comment]
Use auto responder
