### ISSUE TITLE
about the cache config

### ISSUE THREAD

**Issue by TianNex** [LiveHelperChat/livehelperchat#1477]
'templatecache' => true,
'templatecompile' => true,
'modulecompile' => true,

hello,please rename these key name,
i still don't know whether the cache is enable or not 

it's the right setting when the system running?
'templatecache' => true,
'templatecompile' => false,
'modulecompile' => false,
maybe the 'templatecache' => true,  means regenerate cache  ?
maybe
'enable_template_cache' => true,
better,
thank you

**Comment by remdex** [comment]
For sure won't be done  it would break thousands of installations...
