### ISSUE TITLE
404 bot_chats file

### ISSUE THREAD

**Issue by Vintic** [LiveHelperChat/livehelperchat#1479]
After update, and then clean install on same db, I receive 404 error every 10 seconds, on: https://example.com/livehelperchat/lhc_web/index.php/site_admin/chat/syncadmininterface/(limita)/10/(limitu)/10/(limitp)/10/(limito)/10/(limitc)/10/(limitd)/10/(limitmc)/10/(limitb)/10/(limitgc)/10/(w)/online_operators/departments_stats/online_visitors/group_chats/my_chats/pending_chats/transfered_chats/active_chats/bot_chats

**Comment by remdex** [comment]
Sorry,

But I really have nothing to do with your installation... You should contact your hosting... Make sure you followed update procedure and updated DB first.

**Comment by Vintic** [comment]
Version 3.34 work well, but on 3.37 I receive this error. And es I updated DB first -> then I pull changes from git.

**Comment by remdex** [comment]
It has nothing to do with LHC it's 404 error. Means your server does not find some files. PErhaps some mod security disables long URL. You should contact your hosting.

**Comment by remdex** [comment]
404 Error is always generated by web server itself not lhc...

**Comment by Vintic** [comment]
firstly problem appears in 3.35 on revision from 5.22.2020 8:56

I tried to move project to one folder ahead. Not helped.
Now url is: https://domain.com/lhc_web/index.php/site_admin/chat/syncadmininterface/(limita)/10/(limitu)/10/(limitp)/10/(limito)/10/(limitc)/10/(limitd)/10/(limitmc)/10/(limitb)/10/(limitgc)/10/(w)/online_operators/departments_stats/online_visitors/group_chats/my_chats/pending_chats/transfered_chats/active_chats/bot_chats

When I remove bot_chats from url -> it works.
When I remove it and replace active_chats to bot_chats in url -> it works.
When I replace bot_chats with active_chats in url -> 404 error.

I use IIS 8.5 on Windows server 2012.

**Comment by remdex** [comment]
Problem is with your IIS server. Please check does he have any limitation how long url can be. Try just remove "active_chats to bot_chats" and just add any random string you will get same error 100%

**Comment by Vintic** [comment]
Thank you. IIS by default has limit to 32 url segments, but there was 38.

**Comment by TheDoudou** [comment]
Hi same here, thx for the fix.

[https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/sites/site/limits](https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/sites/site/limits)
