### ISSUE TITLE
Translation duplicated on visitors side

### ISSUE THREAD

**Issue by fenandosr** [LiveHelperChat/livehelperchat#1487]
![image](https://user-images.githubusercontent.com/13926115/84716402-99b49700-af38-11ea-900d-0644d220a20b.png)

The visitor should only see i) her/his message *not translated*, and ii) the operator message *translated*

I'm using 3.38v

**Comment by fenandosr** [comment]
I tried to change this, by changing the function `erLhcoreClassTranslate::translateChatMsgVisitor`, but this way we also change the behavior on the operators' side, and we want this behavior ONLY on the operator chat... 

Also> I'm using gTranslate :wink:

**Comment by fenandosr** [comment]
The applied changes hides the translated message for the visitor, but the visitor should see the translated message instead of the "original message"

![image](https://user-images.githubusercontent.com/13926115/85364969-f9d3ac00-b4e9-11ea-897a-f97db25917e2.png)

I switch `translation` and `msg` in the function `translateChatMsgVisitor`, but I think that's not the way to fix it...

Thank you for your response

**Comment by remdex** [comment]
So made one more change. Originally I missed that in old widget we also show original and translated message in different background color. So I have added background color and restored translated message visibility.
