### ISSUE TITLE
Is postgres branch alive?

### ISSUE THREAD

**Issue by freerider7777** [LiveHelperChat/livehelperchat#1490]
Hello! Is posgresql branch alive? Last commit was 5 years ago...

**Comment by remdex** [comment]
Hi,

Yes a little bit dead...

**Comment by freerider7777** [comment]
It's a pity...

**Comment by freerider7777** [comment]
Is there a way to run master version on postgres?

**Comment by remdex** [comment]
Instructions once it was up to date was these 
https://livehelperchat.com/postgresql-support-267a.html

Ofcourse before all that you should merge with official branch. But there will be missing tables/columns for sure...

**Comment by freerider7777** [comment]
Ok, thanks!
