### ISSUE TITLE
cors problem

### ISSUE THREAD

**Issue by werrweroiewjroiuewj** [LiveHelperChat/livehelperchat#1491]
We were testing your solution and found a problem with the chat widget and access-control-allow-origin.

Basically there is both a security concern, performance issue and a logic error in telling the webserver to put
Access-Control-Allow-Origin: *

in every single response.
The * should be replaced with one of our approved domains. This requires script code which is not something the webserver can do.
Unfortunately, the chat widget is using URLs that refer to static content that have no possibility for script coding.

We therefore changed lhc_base_url to a php-file /widget.php/ we created and let the requests go through this. This is a hack and not a good solution, but perhaps this will inspire to redesign the widget solution to allow for secure and proper cors.

```
<?php
header("Access-Control-Allow-Origin: https://<your site here / check origin header>");

if ($_SERVER["PATH_INFO"] == "/")
{
        header("content-type: application/javascript");
        echo file_get_contents("design/defaulttheme/js/widgetv2/index.js");
}
else
{
        if (strpos($_SERVER["PATH_INFO"], "widgetrestapi") !== FALSE)
        {
                foreach ($_SERVER as $k => $v)
                        $_SERVER[$k] = str_replace("/widget.php", "/index.php", $v);
                $_SERVER['HTTP_HOST'] .= "/widget.php";
                require("index.php");
        }
        else
        {
                $p = strrpos($_SERVER["PATH_INFO"], '.');
                if ($p && substr($_SERVER["PATH_INFO"], $p+1) == "css")
                        header("content-type: text/css");
                echo file_get_contents("." . $_SERVER["PATH_INFO"]);
        }
}
?>
```

**Comment by remdex** [comment]
Hi,

For performance reasons I really won't be adding php file just to load these through php and put headers in PHP. If you want tweak you can just play around with .htaccess and specify strictly files you want to add this headers. But problem is the way widget is build CORS headers has to be presented on more than JS files it also requires font files, css files etc. So it's not as simple as putting php file in front of it.

**Comment by remdex** [comment]
And as you see here cors are set only for static content.

https://doc.livehelperchat.com/docs/integrating#my-widget-does-not-work-i-have-live-helper-chat-installed-on-one-domain-but-code-is-embeded-on-another-domain

**Comment by werrweroiewjroiuewj** [comment]
.htaccess-files was used during the 90s and are today obsolete:) They also have performance issues which was one of the reasons why they were abandoned.
There files also can't write the correct cors-header with the domain you are using it from.
Using a wildcard * in cors is a security concern and is not something we want in the header.

**Comment by remdex** [comment]
You can always change CORS header value to domain you want. But for general users it's just way to confusing :) 
As for performance reasons. You can always disable .htaccess and put rules in virtual host directly.
Personally I always use nginx just and there is no .htaccess thing at all :)

So three options.
1. .htaccess
2. virtual host definition
3. or just edit Access-Control-Allow-Origin value :)
4. Use nginx and tweak there rules :)

**Comment by werrweroiewjroiuewj** [comment]
I think you perhaps are misunderstanding my original post.

We have multiple sites using the widget.
It is not possible to put a proper cors-header without script code.
Access-control-allow-origin can only appear once in the http response.
Hacking the webserver to use a proper dynamic header value is neither a good solution as it is outside the scope of the site installation.

**Comment by remdex** [comment]
Well you can have this value dynamically using https://forum.livehelperchat.com/viewtopic.php?id=3459 same .htacess.

But in your situation as you can't tweak these headers based on request not sure how can I help :)

And all these answers are based just on .htaccess. There for sure should be some solution for your problem also.

https://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains

And from my knowledge other chat service providers they just but * and that's it :)
