### ISSUE TITLE
Improve tooltip on new widget for when widget switch from offline to online and vice versa

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1495]
When the widget switch to offline the tooltip is not hidden if the page is not refreshed
When the widget switch to online, the tooltip is not showed if the page is not refreshed

**Comment by remdex** [comment]
You are talking about need help tooltip or proactive invitation?

**Comment by PeopleInside** [comment]
need help tooltip, not tested with the pro active.

**Comment by remdex** [comment]
That just means you have old version because here all works.

**Comment by PeopleInside** [comment]
Have you fixed this recently? Because I have the latest 3.38 but i not downloaded and installed today and the issue are present also on the demo.
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/85831439-9ddd8180-b78e-11ea-9cbc-340fde308167.jpg)

**Comment by remdex** [comment]
You were talking about proactive not need help tooltip!
Create another issue with proper description indicating you are talking about proactive invitation not need help tooltip.

**Comment by PeopleInside** [comment]
Umh no... I'm talking about tooltip but maybe in the demo there is pro active active and is difficoult to test tooltip.
I have version 3.38 and have the tooltip issue. I will try to download latest live helper chat also if is the same version I have, maybe you do some fixes that is not included in mine install.

**Comment by PeopleInside** [comment]
Works, thanks. Just updated in GitHub.
