### ISSUE TITLE
Passing pre-filling-form-fields data through GET Method

### ISSUE THREAD

**Issue by haizad** [LiveHelperChat/livehelperchat#1496]
Hi,
I have gone through the documentations , https://doc.livehelperchat.com/docs/custom-fields-and-prefill/ and I believed that I can define the fields using Javascript. Instead, is there any ways where I can pass the fields variable using the PHP , so that user won't see any form input before they allowed to chat.

I was thinking to pass the data into index.php using PHP GET method , like so
lhc_web/index.php?**username=yadayada&email=yada@test.com** or
lhc_web/index.php/chat/start?**username=yadayada&email=yada@test.com** , so that when the user access the link, they can  just chat with us, at the same time ,we already know who are they.

I believed that this kind of _custom-fields & prefill_ issue already been discussed, but I don't find something similar like passing the data through the GET method request. 

Big thanks.

**Comment by remdex** [comment]
It was documented just not very clear. I have written dedicated section for that.

https://doc.livehelperchat.com/docs/custom-fields-and-prefill/#prefilling-variables-by-url

**Comment by haizad** [comment]
Thank you for this :)
