### ISSUE TITLE
Feature request: REST API to create user

### ISSUE THREAD

**Issue by ofrzeta** [LiveHelperChat/livehelperchat#1498]
Hi, thanks for the nice software! It's very powerful and flexible. However for a project we lack the ability to create users through the REST API.  Is this a planned feature or should we just go ahead and implement it ourselves?

**Comment by remdex** [comment]
Hi,

At the moment it's not planned. As for implementation yes you can create one https://github.com/LiveHelperChat/livehelperchat/tree/master/lhc_web/modules/lhrestapi

Or just contact me and sponsor this feature :)

**Comment by remdex** [comment]
Implemented as discussed.
