### ISSUE TITLE
REST API, Token access error

### ISSUE THREAD

**Issue by Vintic** [LiveHelperChat/livehelperchat#1501]
Hi,
Can't pass authorization using API Token mode, with Basic Auth is OK.
Received error:
PHP Notice:  Undefined offset: 1 in D:\live_chat\lhc_web\lib\core\lhrestapi\lhrestapivalidator.php on line 114

Steps to reproduce:
1. Add API key using UI and activate. Key: "my_test_key"
2. Create request (I use Postman) to: .../lhc_web/index.php/site_admin/restapi/setonlinestatus/5/1
3. Add Header: key="authorization" value="admin:my_test_key" | value="my_test_key"
4. Send request

Where to find some docs, how to create key, and send request?

**Comment by remdex** [comment]
https://doc.livehelperchat.com/docs/development/rest-api/

**Comment by Vintic** [comment]
> https://doc.livehelperchat.com/docs/development/rest-api/

Sorry, I meant about Token.

**Comment by remdex** [comment]
I don’t know about what token you are talking

**Comment by Vintic** [comment]
API key

**Comment by remdex** [comment]
Read documentation... and see swagger you have to use username and api token as password...

**Comment by Vintic** [comment]
I found problems.
1) I should encode to base64 my login:password
2) I don't know why you make explode " " in lhrestapivalidator.php: 
`$dataAuthorisation = explode(' ', $headers['Authorization']);`

When I use only `$apiData = explode(':', base64_decode($headers['Authorization']));`
All is OK

**Comment by remdex** [comment]
Because authorization header is always send in two parts authorization and base64 encoded part. It’s standard method and if you change code, you just breaking things.

**Comment by remdex** [comment]
Also if you look swagger it does exactly what I wrote.
It's basic Authentification method header is send.

**Comment by Vintic** [comment]
OK, thank you.
Problem was that my header looks like: 
key: "authorization" Value: "encriptedBase64(username:api_key)"
But it should be: key: "authorization" Value: "Basic: encriptedBase64(username:api_key)"

May be, response message, should be more clear (not error line).
