### ISSUE TITLE
Canned messages disappear when you click

### ISSUE THREAD

**Issue by marcelloinfoweb** [LiveHelperChat/livehelperchat#1507]
Gif with the error
in any browser

--
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2093128/89687458-a620f480-d8d6-11ea-9c66-52a9ad0d43db.gif)

**Comment by remdex** [comment]
See your network log and response what you get when yo type.

**Comment by marcelloinfoweb** [comment]
I can't type, just click on the input and it disappears and shows me that
error on the browser console.

Em dom, 9 de ago de 2020 15:47, Remigijus Kiminas <notifications@github.com>
escreveu:

**Comment by remdex** [comment]
Just do what i told... On click you will see a request in chrome network console tab..

**Comment by marcelloinfoweb** [comment]
> Just do what i told... On click you will see a request in chrome network console tab..


![Captura de Tela 2020-08-10 às 09 11 51](https://user-images.githubusercontent.com/2093128/89781413-a47b4a80-dae9-11ea-884e-ed871c012ea5.png)

Thank you for guiding me to discover my problem.
This happened after I upgraded to version 3.39, but now I'll try to release it.

I'm sorry to take your time, thank you so much for your attention.

**Comment by remdex** [comment]
It's wrong content you are pasting. Please come to discord and just share in private chat and your installation details. So i could look directly. Impossible to help if users don't know how to report properly...

**Comment by marcelloinfoweb** [comment]
I'm sorry I wasn't clear, but I went to the network tab and clicked on the request that appeared when I clicked on the canned response input, and that was the message.

I just solved it, thank you very much.
