### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function translate() on boolean

### ISSUE THREAD

**Issue by khrizo** [LiveHelperChat/livehelperchat#1509]
After updating to the latest version - I have disabled cache and the same thing.

`Fatal error: Uncaught Error: Call to a member function translate() on boolean in /lhc_web/modules/lhchat/chatwidget.php:45 Stack trace: #0 /lhc_web/lib/core/lhcore/lhmodule.php(96): include() #1 /lhc_web/lib/core/lhcore/lhmodule.php(547): erLhcoreClassModule::runModule() #2 /lhc_web/index.php(39): erLhcoreClassModule::moduleInit() #3 {main} thrown in /lhc_web/modules/lhchat/chatwidget.php on line 45`

**Comment by remdex** [comment]
You are passing theme which does not exists...

**Comment by khrizo** [comment]
Thank you, for the quick response! issue solved.
...and thank you for this great piece of software.
