### ISSUE TITLE
active_chats not updating

### ISSUE THREAD

**Issue by euojeff** [LiveHelperChat/livehelperchat#1512]
All chats for user id 77 are closed.
However **active_chats** = **2**.

Probably some update is missing.
Is that a bug? Are there any batch that adjust these values?

![image](https://user-images.githubusercontent.com/13109005/90291315-06bfac80-de56-11ea-9625-d65c20165dd1.png)

**Comment by remdex** [comment]
https://demo.livehelperchat.com/index.php/site_admin/system/usersactions

**Comment by remdex** [comment]
Also make sure you are working with recent version as older versions could have some cases unhandled just..
