### ISSUE TITLE
"New widget (beta)" stopped working. widgetrestapi/onlinesettings: 503 error

### ISSUE THREAD

**Issue by ClayRabbit** [LiveHelperChat/livehelperchat#1516]
Hello

Probably after recent update our chat widget stopped working for some reason - after click on the chat icon blank widget displayed.
Only popup mode still works, but in embed or widget mode widgetrestapi/onlinesettings call responding with error:
"**A query failed internally in Persistent Object: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'chat_id' cannot be null Query: 'INSERT INTO `lh_msg` ( `msg`, `meta_msg`, `time`, `chat_id`, `user_id`, `name_support` ) VALUES ( :ezcValue1, :ezcValue2, :ezcValue3, :ezcValue4, :ezcValue5, :ezcValue6 )'**"

<details>
<summary>HTTP Response</summary>

```HTTP/1.1 503 Service Temporarily Unavailable
Server: nginx
Date: Wed, 19 Aug 2020 06:49:36 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Keep-Alive: timeout=10
X-Powered-By: PHP/7.4.7
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, API-Key, Authorization
Retry-After: 300

{"error":true,"message":"A query failed internally in Persistent Object: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'chat_id' cannot be null Query: 'INSERT INTO `lh_msg` ( `msg`, `meta_msg`, `time`, `chat_id`, `user_id`, `name_support` ) VALUES ( :ezcValue1, :ezcValue2, :ezcValue3, :ezcValue4, :ezcValue5, :ezcValue6 )'"}
```
</details>
<details>
<summary>HTTP Request</summary>

```POST /rus/widgetrestapi/onlinesettings HTTP/1.1
Host: li.do.ruweb.ws
Connection: keep-alive
Content-Length: 107
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
DNT: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
Content-Type: application/json;charset=UTF-8
Origin: https://ruweb.ws
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://ruweb.ws/test-li2.htm
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7

{"department":[1],"product":[],"theme":2,"mode":"widget","pvhash":null,"phash":null,"bot_id":"","online":1}
```
</details>

I'm not sure what caused this. I am running LHC from digitalocean droplet. I was on 3.38 version and clicked "update database structure" on system/update page. But I'm not finished the update - I didn't updated files to 3.39 at that time. Then after a week or so I have noticed that widget can't start new chat because of this error (while already active chats was still working). A am updated files to 3.39, cleared cache, even rebooted server, but it did not help. Maybe it's not related to update at all.

https://ruweb.ws/test-li2.htm - widget mode is not working
https://ruweb.ws/test-li3.htm - embed mode is not working
https://ruweb.ws/test-li4.htm - popup mode works
https://ruweb.ws/test-li.htm - legacy widget works

**Comment by remdex** [comment]
You have to update files also...

**Comment by remdex** [comment]
Also looking at error looks like you have setup bot in a such way it requires working chat to be working... Please check that..

**Comment by ClayRabbit** [comment]
> You have to update files also...
> https://doc.livehelperchat.com/docs/development/hosting-on-digitalocean/#how-to-update-live-helper-chat
> Full error log you can also find in cache/default.log
> 
> You can find me also on discord server perhaps there I could help you...

**Of course I am updated files to 3.39, cleared cache, even rebooted server, but it did not help**

**Comment by ClayRabbit** [comment]
> Also looking at error looks like you have setup bot (in theme) in a such way it requires working chat to be working... Please check that..

Many thanks for pointing me in right direction. I have disabled "manually bot ant trigger" inside "Theme - Custom Content" settings and all gone back to normal.
