### ISSUE TITLE
chmod 777???

### ISSUE THREAD

**Issue by reinethernal** [LiveHelperChat/livehelperchat#1517]
Guys are you serious? chmod 777? recuresively? That's a really dangerous security vulnerability.
tried to use 755 but doesn't work. WHY do we need to use 777?

**Comment by remdex** [comment]
You can use other command if you want and create a pull request once you be happy...  App in short just to have permission to write to folders mentioned in install how you do that it's up to you.

**Comment by remdex** [comment]
Changed instructions to reflect 755. You can see it here https://doc.livehelperchat.com/docs/install
