### ISSUE TITLE
Inconsistent attribute naming when storing by button click

### ISSUE THREAD

**Issue by nielosz** [LiveHelperChat/livehelperchat#1520]
The "identifier" of the chat variable given by "store_name" of quick reply button is lowered but key isn't.
Example result is:
`    Array(
        [identifier] => choiceid
        [key] => choiceId
        [value] => 5
    )
`
Backend additional chat data says for example: 
"choiceId - 5"
But the var is accessible in replacement only by {{lhc.add.choiceid}}.

**Comment by remdex** [comment]
Variable is always replaced by identifier... once it's stored.
```
if (isset($addItem['identifier'])) {
                        if (is_string($addItem['value']) || is_numeric($addItem['value'])) {
                            $replaceArray['{lhc.add.' . $addItem['identifier'] . '}'] = $addItem['value'];
                        }
                    } else if (isset($addItem['key'])) {
                        if (is_string($addItem['value']) || is_numeric($addItem['value'])) {
                            $replaceArray['{lhc.add.' . $addItem['key'] . '}'] = $addItem['value'];
                        }
                    }
```

**Comment by nielosz** [comment]
Maybe I wrote too unclear. If I set "store_name" in quick reply to "choiceId", lhc code create a var 
`  Array( [identifier] => choiceid, [key] => choiceId, [value] => 5 )`
which is inconsistent because I can't change this exact variable for example by js with `window.parent.lhc_var.choiceId` and also not with `window.parent.lhc_var.choiceid` and leads to
![loweredvar](https://user-images.githubusercontent.com/1521157/91290662-2cbd4900-e794-11ea-917a-c0e137a55815.png)
What am I missing?

**Comment by remdex** [comment]
![image](https://user-images.githubusercontent.com/1146085/91291541-e0770680-e79d-11ea-86e1-e318808bc708.png)
![image](https://user-images.githubusercontent.com/1146085/91291588-f08ee600-e79d-11ea-93d8-cc4c0ec08d25.png)

And i have constant name where var can be updated via bot trigger click or javascript.

**Comment by nielosz** [comment]
Thanks, then I would say, "Button ID" is really misnamed. I left it empty.

**Comment by nielosz** [comment]
You're too nice, thanks a load

**Comment by remdex** [comment]
Button ID has nothing to do what you reported. It just set's element Id does not influence how value are stored.

**Comment by nielosz** [comment]
This means, variables autogenerated by store_name get a lowered and trimmed version of name as identifier

**Comment by remdex** [comment]
Please see related commit I did. It changes that.

**Comment by nielosz** [comment]
Yes, I saw! This is by far the friendliest and fastest reaction of a developer I ever met. I can't say enough thanks!
