### ISSUE TITLE
Tooltip issue on Chrome: scrollbar showed

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1528]
The following css seems create issue on Chrome:

```
.pb-4, .py-4 {
    padding-bottom: 1.5rem!important;
}
```

This CSS is a default LHC code and I'm unable to remove or fix.
The result of this in Chrome is:

![InkedSharedScreenshot_LI](https://user-images.githubusercontent.com/5006150/92121916-2154c800-edfb-11ea-9b02-b95b5e7b9c0e.jpg)

A scroll bar not very nice and not useful is showed.
Disabling this CSS seems fix the issue:

![InkedSharedScreenshot 1_LI](https://user-images.githubusercontent.com/5006150/92122003-3c273c80-edfb-11ea-9dc6-fe2a878d1d88.jpg)

LHC 3.41

**Comment by remdex** [comment]
You uploaded to big image. You can adjust tooltip size in theme.
