### ISSUE TITLE
Personal canned message delay issue

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1529]
I have department A, when chat is accepted a **canned message A** is sent automatically.

1. If a particular operator set a personal canned message in his profile and check the box to Automatically send this message to user, then chat is accepted, the **canned message A** is not sent and is replaced by the operator canned message. What is expect from me is that the operator message is appended and not replaced to the canned message A.

Currently if an operator set a personal canned message and check the box to send when chat is accepted, the department canned message A is not sent.

2. The delay of Personal canned message seems to be not respected in both cases: If the box to Automatically send this message to user is checked or unchecked, delay is not respected.

This issue is similar but not the same of https://github.com/LiveHelperChat/livehelperchat/issues/1471

Tested on LHC 3.41

**Comment by remdex** [comment]
Personall canned messages overrides global ones.
