### ISSUE TITLE
Feature Request - Disable Direct Chat Access Spam

### ISSUE THREAD

**Issue by Si-Richards** [LiveHelperChat/livehelperchat#1548]
We use the chat widget api but sometimes get spam directly calling the chat pages on the server as my widget is behind a private portal.

_https://demo.livehelperchat.com/chat/start/(theme)/1/(vid)/abca8c1096e8aa299a26/(mobile)/true/(department)/2/(priority)//(sound)/1?ses_ref=//www.google.com/_

I wonder if there is an easy way to disable direct calling of the start chat widget.

**Comment by remdex** [comment]
It means you have auto start chat enabled?

**Comment by Si-Richards** [comment]
Ah ok... thanks so much for a fast reply
