### ISSUE TITLE
Can You Send A Copy To People, When They Leave An Offline Message?

### ISSUE THREAD

**Issue by fxbo2020** [LiveHelperChat/livehelperchat#1550]
Hi Memebrs,

I think with "Live Help Chat", when a person leaves an offline message, they should receive a copy of that for themselves, does anybody agree with that, or can that be done now?

Stephen Smith.

**Comment by remdex** [comment]
Thats good idea in general as confirmation. If you sponsor it could be done faster :D

**Comment by fxbo2020** [comment]
How do I go about doing that please?

Stephen Smith.

**Comment by remdex** [comment]
You can find me on discord or skype me nick remdex.

**Comment by remdex** [comment]
Flow should be similar to this
https://doc.livehelperchat.com/docs/bot/send-mail just event `chat.chat_offline_request` or `chat.chat_offline_request_saved`
