### ISSUE TITLE
Offline messaging button

### ISSUE THREAD

**Issue by marcelloinfoweb** [LiveHelperChat/livehelperchat#1554]
How to remove the offline message button when there is no form and the email input is hidden?

**Comment by PeopleInside** [comment]
Hi, do you checked the documentation?
https://doc.livehelperchat.com/docs/chat/offline/

**Comment by marcelloinfoweb** [comment]
![Captura de tela 2020-10-05 175755](https://user-images.githubusercontent.com/2093128/95131392-59219900-0734-11eb-83ed-161018493b82.png)

**Comment by PeopleInside** [comment]
From the documentation URL I sent:

- [Disable the offline message for a widget](https://doc.livehelperchat.com/docs/chat/offline/#disable-the-offline-message-for-a-widget)
- [Disable the offline message for a static url](https://doc.livehelperchat.com/docs/chat/offline/#disable-the-offline-message-for-a-static-url)

You need have an updated version of LHC. Latest one was released today: https://livehelperchat.com/news-5c.html

**Comment by marcelloinfoweb** [comment]
I've already unchecked the "leave message" options for the theme and embed settings

**Comment by marcelloinfoweb** [comment]
I noticed that the documentation doesn’t have the paths to the settings, so it’s difficult to find the settings.

**Comment by PeopleInside** [comment]
>     If you pass more than one department or do not pass any
> 
>     Offline message form always will be shown even if you do not pass department.
>     caution
> 
>     This behaviour should change in future releases and respect offline request settings per department.

Maybe you have more than one department so, from documentation I understood in the direct URL page the offline form will be always showed. In that case you can only hide widget not the page at the moment.

**Comment by marcelloinfoweb** [comment]
No, it's just a department.

Here the code.

`

<div id="lhc_status_container_page" ></div>


<script>var LHC_API = LHC_API||{};
LHC_API.args = {mode:'embed',lhc_base_url:'//assistemas.com.br/ch@t/lhc_web/',wheight:450,wwidth:350,pheight:520,pwidth:500,domain:'dietpro.com.br',department:[2],theme:6,check_messages:false,proactive:false,lang:'site_admin/'};
(function() {
var po = document.createElement('script'); po.type = 'text/javascript'; po.setAttribute('crossorigin','anonymous'); po.async = true;
var date = new Date();po.src = '//assistemas.com.br/ch@t/lhc_web/design/defaulttheme/js/widgetv2/index.js?'+(""+date.getFullYear() + date.getMonth() + date.getDate());
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
})();
</script>
`

**Comment by PeopleInside** [comment]
The issue happen on a widget or a page that I can see, a private page or a direct page URL?

**Comment by marcelloinfoweb** [comment]
Chat page on this page https://dietpro.com.br/site/suporte-dietpro/

**Comment by PeopleInside** [comment]
OK thanks for the info.
Please hold on for a reply, let's waiting @remdex 

Thank you for the patience and all informations.

**Comment by marcelloinfoweb** [comment]
I will do what you recommended and update.

Thanks!

**Comment by remdex** [comment]
I can verify we are missing this scenario page embed and offline is disabled. I'll making changes now and will publish update in a few hours.

**Comment by remdex** [comment]
Implemented. Just update. Theme -> Chat Widget -> Chat is unavailable and offline form is disabled. change this text to have a custom text.

**Comment by marcelloinfoweb** [comment]
works perfectly, thank you very much !!!
