### ISSUE TITLE
Error installing co-browsing

### ISSUE THREAD

**Issue by marcelloinfoweb** [LiveHelperChat/livehelperchat#1556]
Error:

`npm WARN cobrowsing@1.0.0 No repository field.`

OS: CentOS 6.9
node: v10.22.0
npm: 6.14.8

**Comment by remdex** [comment]
This error has mothing to do with lhc. See docker repository how i setup co-browsing node server there.

**Comment by marcelloinfoweb** [comment]
So should I take the folder co browsing and put it in the extensions folder? I took it from the docker directory and apparently it worked, I'm going to do the tests.

**Comment by marcelloinfoweb** [comment]
Another question: Is it possible to use nodejshelper and cobrower together?

**Comment by remdex** [comment]
Just see docker. As docker composer combines all the services... If you want you can take nodejs also from docker repository. These two are independent solutions.
