### ISSUE TITLE
Cannot insert a file uploaded by the operator in the chat

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1558]
Hi, maybe the latest SECURITY (good) update to the new bootstrap broke the possibility to insert an attachment in the chat.
Press to attach as bbcode did not work.

1. Upload an attachment from the operator side while chatting
2. try to include in the chat but the button to insert as BB code will no do nothing

**Comment by remdex** [comment]
This was fixed few days ago. Issue closed
