### ISSUE TITLE
Service died when change language

### ISSUE THREAD

**Issue by DevDorrejo** [LiveHelperChat/livehelperchat#1567]
Hello when i change the language the service enter to a 404 state and can't do nothing, every page 404 and the main page on blank.

apache logs nothing.

![image](https://user-images.githubusercontent.com/7697566/97039894-2dc3ea00-153b-11eb-94ad-643b6eb7c6b1.png)
![image](https://user-images.githubusercontent.com/7697566/97039944-416f5080-153b-11eb-9980-7da081adbb86.png)

debug output not show nothing.

**Comment by DevDorrejo** [comment]
Executing this command load the website with the selected language and fix the issue of blank page and 404

sudo -u wwwrun php cron.php -s site_admin -c cron/util/clear_cache
sudo -u wwwrun php cron.php -s site_admin -c cron/util/update_database
sudo -u wwwrun php cron.php -s site_admin -c cron/util/generate_translation_file

**Comment by DevDorrejo** [comment]
'force_virtual_host' => true, not work, will make all the website go to 404 error

**Comment by remdex** [comment]
https://doc.livehelperchat.com/docs/development/remove-index-php/
