### ISSUE TITLE
can't trace the right url

### ISSUE THREAD

**Issue by TianNex** [LiveHelperChat/livehelperchat#1570]
can't trace the right url , all url in  Footprint is site url
the same issue with https://demo.livehelperchat.com/

**Comment by remdex** [comment]
Sorry it's just way to little info about your environment and everything else.

**Comment by PeopleInside** [comment]
Hi @TianNex, we need more info for help you, also there is a community for help https://forum.livehelperchat.com/ but you need include more info or will be difficult help you.

I think you done something of wrong or wrong configuration as here seems all works.
