### ISSUE TITLE
can't trace the right footprint of user

### ISSUE THREAD

**Issue by TianNex** [LiveHelperChat/livehelperchat#1571]
![1](https://user-images.githubusercontent.com/8756686/97259212-37a85e80-1855-11eb-987d-61eea0dedda7.png)

hello, as the picture shows,
i browser some pages of the demo sites, 
but it can't trace the right footprint of user

**Comment by remdex** [comment]
Now I see. I'll test in a hour and push fix if it's required.

**Comment by remdex** [comment]
Fixed. Strange no one noticed it over for 9 months. It was effecting only old widget.

**Comment by TianNex** [comment]
thank you
