### ISSUE TITLE
logic of "Please complete previous process"

### ISSUE THREAD

**Issue by lfedorko** [LiveHelperChat/livehelperchat#1579]
Hello! 
We use bots with collection custom attributes. Their effectiveness is on 25% higher than contact form in our project. It`s a cool tool. But there is a some kill problem with it. It is a lack of possibility of reset previous process.

There are 3 user cases which needed in a reset previous process:

1. Visitor does`t answer on a collection attribute question, then close the chat. Next dialog with this visitor will be failed if visitor will face  any collect custom attribute question because of "Please complete previous process" message. The visitor will be lost in the most of cases.

2. In some steps we use collection custom attribute with quick reply button in one trigger. Please look at trigger "Goods verifying" in the bot. We do it for visitor possibility to come back on previous step if collection attribute question isn`t relevant for the visitor. Both of "step back button" (quick reply) and visitor typing field are staying active. If a visitor use this button he can face with collection attribute question and "Please complete previous process"

Scenario:
quick reply: goods verifying -> quick reply: back to main menu -> button: help -> choose: status 

3. Sometimes we use button list. It is useful if a text of buttons too big for quick reply button. This button list is always active, so a visitor can scroll up his feed and use any button of list. You can look at the trigger "Help" In case of using collect custom attribute and if visitor doesn`t complete it he can come back to this buttons and use any. In next collection attribute question will be fail again.  

Scenario: 
quick reply:Help -> button: Status -> click again button: Status

maybe will solve by this two changes:
1) possibility of autoreset previous process after visitor closing chat (case 1)
2) reset previous process trigger (cases 2-3)

We just refused using button list totally and go back buttons after collect custom attribute question. But we think we lost the visitors.
Also we use "On each refresh start a new chat", but to see all history chat it is very convenient for both agent and visitor

Code:  [lhc-bot-6.txt](https://github.com/LiveHelperChat/livehelperchat/files/5523531/lhc-bot-6.txt)
change to txt because github does not attach .json 
lisavet

**Comment by remdex** [comment]
https://doc.livehelperchat.com/docs/bot/bot-update-current-chat/#remove-any-previous-process
https://doc.livehelperchat.com/docs/bot/collect-custom-attribute/#soft-event
