### ISSUE TITLE
After update all users shows wrong ip address

### ISSUE THREAD

**Issue by CryptorClub** [LiveHelperChat/livehelperchat#1587]
After update all users shows wrong ip address - servers ip.
I could be not lhc direct problem but apache2/ngnix config or vps provider config.

I know that `$_SERVER["REMOTE_ADDR"];`
shows wrong ip (servers)
And I use instead `$_SERVER["HTTP_X_REAL_IP"];`

Maybe you know where to look for?
Thank you

**Comment by remdex** [comment]
https://doc.livehelperchat.com/docs/blocking/#live-helper-chat-does-not-detect-ip
