### ISSUE TITLE
Additional chat variables in proactive messages

### ISSUE THREAD

**Issue by Sehukso** [LiveHelperChat/livehelperchat#1590]
# Steps to reproduce:
1. Create additional chat variable (let's name it proactive_message)
2. in JS initialization, give it some value:
```javascript
        var LHCChatOptions = {};
        var LHC_API = LHC_API || {};
        if (typeof lhc_var === 'undefined') {
            var lhc_var = {};
        }
        // This is the important line
        lhc_var.proactive_message = "Hello there";

        LHC_API.args = {
            lhc_var: lhc_var,
            mode: 'widget',
            lhc_base_url: '//someurl.sk/',
            proactive: true,
            wheight: 450,
            wwidth: 350,
            pheight: 520,
            pwidth: 500,
            check_messages: true,
            fresh: false,
            lang: department === 'svk/'
        };
        (function () {
            var po = document.createElement('script');
            po.type = 'text/javascript';
            po.setAttribute('crossorigin', 'anonymous');
            po.async = true;
            var date = new Date();
            po.src = '//someurl.sk/design/defaulttheme/js/widgetv2/index.js?' + ("" + date.getFullYear() + date.getMonth() + date.getDate());
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(po, s);
        })();
```

3. use the variable in proactive message. Something like "This is a proactive with {lhc.add.proactive_message} variable"

# expected behavior
There will be proactive message shown with text "This is a proactive with Hello there variable"

# actual behavior
Instead of "Hello there" an empty string is rendered - ""

# conclusion
Actually this worked some time before (not long ago, perhaps a month). But suddently there are no additional variables able to be used in proactive messages.

**Comment by remdex** [comment]
Question, do you see this variable being passed in online visitors list?

**Comment by remdex** [comment]
Sorry, but tested and all works here
![image](https://user-images.githubusercontent.com/1146085/100473950-3a160680-30e8-11eb-8655-e1095cdfa622.png)
![image](https://user-images.githubusercontent.com/1146085/100473961-40a47e00-30e8-11eb-82a9-d9802fbd3381.png)

Please be sure you have not chosen department in additional chat variable. https://doc.livehelperchat.com/docs/custom-fields-and-prefill/#additional-chat-variable-not-visible-by-operator

If you choose department there you have to pass department in your embed code.
