### ISSUE TITLE
JS file not created when any operator is not logged in

### ISSUE THREAD

**Issue by yanlinaung30** [LiveHelperChat/livehelperchat#1603]
I deployed livehelperchat in separate server.
If operator is logged in , it works perfect.

But no operator is logged in, JS file is not found on server.

I have used nginx. What did I miss?

![image](https://user-images.githubusercontent.com/4996766/104162962-f707bc80-5423-11eb-9857-749feacf0fee.png)

**Comment by remdex** [comment]
Try to update from master branch and click clear cache from back office.

**Comment by yanlinaung30** [comment]
@remdex 
Thanks for your prompt response.
It works now!
