### ISSUE TITLE
Jitsi support for Video

### ISSUE THREAD

**Issue by premhunt** [LiveHelperChat/livehelperchat#1614]
Jitsi having better open source license with respect to janus. Is this possible to add Jitsi support https://jitsi.org/ ?

**Comment by remdex** [comment]
With some effort for sure :) but no eta at the moment I'll see which one is better to have :)

**Comment by premhunt** [comment]
Let me know the code place to look on, so that I can raise a PR,if able to finish by myself.

**Comment by remdex** [comment]
Module itself
https://github.com/LiveHelperChat/livehelperchat/tree/master/lhc_web/modules/lhvoicevideo

React APP
https://github.com/LiveHelperChat/livehelperchat/tree/master/lhc_web/design/defaulttheme/widget/voice-call-operator

**Comment by remdex** [comment]
Jitsi integration was done more simpler way
https://doc.livehelperchat.com/docs/integrating/jitsi
