### ISSUE TITLE
notification visitors on apps

### ISSUE THREAD

**Issue by sam-anam1** [LiveHelperChat/livehelperchat#1620]
hello @remdex 
hope you're fine

now days to important that notify me through the app each time a visitor enters website
or any idea how to get notification when visitors get to site on mobile?

**Comment by remdex** [comment]
At the moment this feature does not exists because if you would have hundreds of visitors you would be getting notifcations non stop. So it's like edge case scenario and would be usefull only for a small websites.

**Comment by sam-anam1** [comment]
thank you for your reply 
that's true, but as most I can say all live chat has that and now days I see all live chat that's why felt to ask for it

**Comment by remdex** [comment]
I think you are mixing two things, chat requests which you see now. And general online visitors which is missing in the app :)

**Comment by sam-anam1** [comment]
sorry I just meant online visitors
any plan for notification online visitors on apps please?

**Comment by remdex** [comment]
At the moment not. Unless someone sponsors it 😀
