### ISSUE TITLE
''Send typing'' 

### ISSUE THREAD

**Issue by AchiGR** [LiveHelperChat/livehelperchat#1622]
''Send typing'' function does not work when it is activated and set before the main message of a trigger. For example, when it set in the beggining of the default message. It works only if there is a ''text matching'' advent, where the asked word is detected. Only then ''Send typing'' starts running. 

Please investigate. 

Thank you in advance.

Attached a sample bot where ''Send typing'' is set in the default message. 
[lhc-bot-24.zip](https://github.com/LiveHelperChat/livehelperchat/files/6041080/lhc-bot-24.zip)

**Comment by remdex** [comment]
Here all works.

**Comment by AchiGR** [comment]
Which parameters could blocking this function ?

**Comment by remdex** [comment]
I don't know as all works here.
