### ISSUE TITLE
Quote + file bbcode bug?

### ISSUE THREAD

**Issue by radmirr** [LiveHelperChat/livehelperchat#1624]
Hi!
If you'll try to send picture in quote block you'll get one of two possible results (both looks like bug):

`[quote][file=825_b9a01fa9450c12a51d087861a288df4b_img][/quote]` 
leads to broken bbcode after processing in `erLhcoreClassBBCode::makeSubmessages`, but image remain clickable

![broken-bbcode](https://user-images.githubusercontent.com/60606736/109796054-83bb4380-7c39-11eb-93e6-244b7b670916.png)

`[quote][file=825_b9a01fa9450c12a51d087861a288df4b][/quote]` 
leads to unclickable picture because of missing `msg-body-media` class in message body div element

**Comment by remdex** [comment]
Hmm,
I'll see if I can reproduce.
