### ISSUE TITLE
Ghost Message when sending "0"

### ISSUE THREAD

**Issue by giuliolastra** [LiveHelperChat/livehelperchat#1634]
Hello, 
I'd like to report that when I send a 0 on chat, it doesn't appear, is kinda a ghost message. I've noticed in fact that when I send it, chat doesn't send the message body's div. This happens on either sides. 

Does it depend on me or is an issue?

Thanks!

**Comment by remdex** [comment]
That's a good one :D I'll see in a next few days :)
