### ISSUE TITLE
3.68 hide tooltip on mobile issue on desktop

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1637]
Hi, going in widget themes, need tooltip and select to not show on mobile remove the tooltip also on desktop.
Tested with Firefox 86.01

**Comment by PeopleInside** [comment]
Updated, cleaned cache, tested on incognito and not incognito **still see the issue**.
Did you test the patch? It works?

**Comment by PeopleInside** [comment]
I'm checking to be sure issue is not my side. I'm checking the file has been updated.

**Comment by remdex** [comment]
Yes all works as expected now here

**Comment by PeopleInside** [comment]
I tested in live helper chat demo and works.
On my side did not works.
I checked the file with patch has been replaced, cleared cache but nothing.

Don't know where the issue can be. If I check to not show on mobile also on desktop is not showed.
Thanks anyway remdex.

**Comment by remdex** [comment]
That's the case. Because to check it has to bet tracked as valid IP

**Comment by PeopleInside** [comment]
Yes thanks, all seems work. Thank you!
