### ISSUE TITLE
Status widget on Chrome, bad visual? 3.68

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1639]
Hi, why on Firefox widget is so well showed and in Edge and on Chrome based browser is not so focused?
There is a way to reduce this light on Chromium web browser based?

![SharedScreenshot 1](https://user-images.githubusercontent.com/5006150/111651863-e4847780-8806-11eb-923f-2c06b0fbe268.jpg)
![SharedScreenshot 2](https://user-images.githubusercontent.com/5006150/111651879-e77f6800-8806-11eb-8644-36f252f8eb1c.jpg)

**Comment by remdex** [comment]
It's your PC not LHC as it's same everywhere perhaps again you have some zoom or somehing set.

**Comment by PeopleInside** [comment]
Umh I tested this on my PC and also on Windows Sandbox with Chrome and the result is the same.
Chrome installed from zero.

Can be my PC graphic card?
You see widget same in Firefox and Chrome? No this light effect I see?

**Comment by remdex** [comment]
I ques it's it's just the way different browser renders a little bit different font :)
