### ISSUE TITLE
Display file extension

### ISSUE THREAD

**Issue by viapratica** [LiveHelperChat/livehelperchat#1647]
Helo!

Is there any way, even if editing in the code for the attachment link to be displayed with the extension?

  Example:

Superboy.jpg
or
1efe1df6c2368d21656c1721cd344ed6.jpg

and not:
1efe1df6c2368d21656c1721cd344ed6

Thanks

**Comment by PeopleInside** [comment]
Hi, please don't open multiple discussion about the same issue.
The better place for asking questions is the forum.

You opened a discussion on forum some minute ago: https://forum.livehelperchat.com/viewtopic.php?id=3886

**Comment by remdex** [comment]
You did not explained your workflow. As file extension using regular uploads are shown. If it's paste image is rendered directly.
