### ISSUE TITLE
online_attr_array missing value

### ISSUE THREAD

**Issue by jamgames2** [LiveHelperChat/livehelperchat#1649]
this relate to "https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/modules/lhchat/onlineusers.php"

When "online_attr_system" is not empty then  it make "online_attr_array" to empty value.
because I use to make custom template, so I need this value,

for quick fix just change from
`erLhcoreClassChat::prefillGetAttributes($items,array('online_attr_system_array','notes_intro',`
To
`erLhcoreClassChat::prefillGetAttributes($items,array('online_attr_array','online_attr_system_array','notes_intro',`

**Comment by remdex** [comment]
You in your extension should listen to this event just and modify array in your extension.

https://github.com/LiveHelperChat/livehelperchat/commit/1a340eb9a395c7787168d034430c68c8bf5e0724#diff-1cc955351977f881edc897532ae62cce7b42c58e92d92910dc386cea4acf6fdaR95
