### ISSUE TITLE
[Feature Request] Option to Add Own Status Widget Images For Online and Offline.

### ISSUE THREAD

**Issue by nootkan** [LiveHelperChat/livehelperchat#1650]
Not sure if this is on your list but it would be nice to be able to upload our own images for the online and offline images already in the configuration. 

Currently there is only 3 choices of status widget images and one is a tool tip only. 

It seems that you can only change the image inserted into one of the 3 choices instead of being able to replace the 3 choices themselves.

Hopefully this is possible to do in the future.  Thanks for a great script and your time.

**Comment by remdex** [comment]
Sorry, but I did not understood what exactly you want to change. As online/offline image you can set your own in widget themes. If it's not the one paste a screenshot of what part you are talking about.

![image](https://user-images.githubusercontent.com/1146085/113613115-65da6780-9659-11eb-9cb5-44186e634645.png)

**Comment by nootkan** [comment]
Hi I know about the current options to set your own images in widget themes and I have done so for now.  What I wanted to do is add the images below to replace the current ones used by your script.

![offline193](https://user-images.githubusercontent.com/744769/113627425-5850bd80-9618-11eb-9042-39b2b9b5d489.png)
![online193](https://user-images.githubusercontent.com/744769/113627427-58e95400-9618-11eb-8a40-0f72e4c7ae19.png)

**Comment by remdex** [comment]
These images are genrated on the fly.  So you would need just to override this url. https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/modules/lhrestapi/onlineimage.php

https://doc.livehelperchat.com/docs/development/override-class/
