### ISSUE TITLE
Mobile Android app notification sound issue

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1651]
I'm using theatedt updated LHC 1.5 for Android.
A sound alert me on new chat, the issue is that also if I set no sound for visitor message in the android notification system, every time visitor type and send a new message the sound of the new chat is played. This is very disturbing. Is like LHC Android support just one kind of sound used for new live chat but also for visitor messages without be different settings.

**Comment by PeopleInside** [comment]
This issue happen if chat is opened and operator put the chat in Background for example when you need navigate in the phone.

**Comment by remdex** [comment]
I don't understand what exactly new you want to have?

**Comment by PeopleInside** [comment]
Visitor start a chat than my phone rings.
I accept the chat from LHC Android mobile app.

While chatting I move the app in background and open for example browser or email and visitor still typing and sending messages. All this message play the sound like a new chat is pending the approval.

Looking in the Android settings I choose to play no sound for messages sent from visitor and I set a sound only for new chat.
So the issue is the mobile app is always play sound not only on new pending chat but every time visitor type a message and app is not in the first view on the screen.. also if I disabled sound for new messages.

In the Android notification settings for Live helper chat I see:

New chat and here I set a sound
New messages and here I set no sound

This is not respected as when visitor send message the new chat sound is played for each message.

**Comment by PeopleInside** [comment]
Screenshots:

As you can see New messages sound is set to Nessuna that means no sound but I still get New Chat sound for every message that visitor send. New chat sound should be not played when there is no new chat pending and is just visitor that is sending messages on open chat.

![1](https://user-images.githubusercontent.com/5006150/113721752-15621900-96f0-11eb-9c79-9e75984fa676.jpg)

What is played for each visitor message is the new chat message as set here:

![2](https://user-images.githubusercontent.com/5006150/113721755-15faaf80-96f0-11eb-8b10-5638b3257bbc.jpg)

**Comment by remdex** [comment]
This grouping is done by your phone not by LHC so can't help with that. To be honesti it's mobile app enhancements where you should choose what notifications you want to receive. Your mobile phone and it's settings has nothing to do with that.

**Comment by remdex** [comment]
And why are in general writing this isuse here and not in mobile app.

**Comment by PeopleInside** [comment]
Umh is the app that told to Android about notification supported.
I can see this settings are present but maybe never work correctly and it's not my phone as for other apps all notifications work correctly.

I opened an issue on mobile with some questions.
Thanks
https://github.com/LiveHelperChat/lhc_messenger/issues/30
