### ISSUE TITLE
Adding image for bot is not working

### ISSUE THREAD

**Issue by ninoskuflic** [LiveHelperChat/livehelperchat#1653]
When you edit the bot image, you get the following error:

> We’ll be back soon!
> This service is currently unavailable due to an emergency or scheduled maintenance window. The service will be back online within the next two hours. Sorry for the inconvenience.

> — Online Service Support Team

I don't think this is supposed to be here.

**Comment by remdex** [comment]
See cache/default.log for an error.

https://doc.livehelperchat.com/docs/debug/#during-some-action-app-returns-white-screen-what-to-do

**Comment by ninoskuflic** [comment]
The issue was in SVG - it appears that uploading SVG as an image won't work because of MIME.

**Comment by remdex** [comment]
I think another problem that your server does not support SVG resize as in my hosting i can uplaod SVG and it's resized properly :)
