### ISSUE TITLE
Submitoffline - Request-Type (html) is wrong

### ISSUE THREAD

**Issue by MirkoGrotheVC** [LiveHelperChat/livehelperchat#1659]
The post data are in json format, but no corresponding header is set.
ModSecurity: Access denied with code 400 ... [msg "Failed to parse request body."]

**Comment by remdex** [comment]
I'm not sure what's your problembut this error comes from your server not form LHC.
Content type of send request is
"Content-Type: multipart/form-data;"

But body request varies depending does it have document attatched or not. You are free to create a pull reques if you see where it could be applied

**Comment by PeopleInside** [comment]
As this question has not been updated and seems there is no issue there I'm closing this. 
Fell free to add comments if you still need help.
