### ISSUE TITLE
Dynamic changing of custom chat variables

### ISSUE THREAD

**Issue by MesutErdemir** [LiveHelperChat/livehelperchat#1674]
When I set custom chat variable in console like this;

`lhc_var.email2 = "test@test.com";`

A post request to "https://xxx.com/index.php//chat/updatejsvars/(vid)/xxxxxxx/(hash)/xxxxxxxxxxx" endpoint but request body is empty like this: `data: {}`

So custom chat variable is not changing dynamically but it can be set while starting new chat.

**Comment by remdex** [comment]
It just means your configuration are invalid...
