### ISSUE TITLE
Choosing department not working in canned messages

### ISSUE THREAD

**Issue by muradbayram** [LiveHelperChat/livehelperchat#1679]
Despite I select department, when I try to create a new canned message or edit a canned message and save, it says "Please choose a department!" 
![image](https://user-images.githubusercontent.com/16003435/130494512-c5f5da58-41ec-4053-9599-3be2768c3c31.png)

When I enter some letters (for example just space) in "Fallback message" and "HTML Snippet" fields I can save new canned message but department name doesn't appear in the list.
![image](https://user-images.githubusercontent.com/16003435/130494620-66d16eb2-f177-47be-aa81-a175f3643d8d.png)

**Comment by remdex** [comment]
Here it works.

Please update your versio as might be because of an older version. Try out on demo and here it works.

**Comment by remdex** [comment]
make sure you are assidnec to department also :)

**Comment by muradbayram** [comment]
Thanks for your response :) 
My version is 3.80 and database is updated. I checked demo you are right, there is no problem to create and edit canned messages. I will check my side again.

But I can't see the department name in the canned messages list (may be little thing)

![image](https://user-images.githubusercontent.com/16003435/130508353-d02caafd-425c-4b07-a28b-c1b92b993215.png)
