### ISSUE TITLE
Visitor Flags/Tags

### ISSUE THREAD

**Issue by crowjake** [LiveHelperChat/livehelperchat#1683]
It would be very useful to have a way operators can flag a visitor in ways other than banning... especially using their visitor ID rather than their IP.

Ideally custom flags/tags e.g. 

- suspected troll, 
- high-risk, 
- high-priority
- etc

Then we could automate what happens when a visitor with those flags/tags appears 

- mute
- warn operator before initiating chat
- transfer them to a department

I don't think this is already possible?

**Comment by remdex** [comment]
Now you can have notes in online visitor profile just to put notices about visitor which remains every sessions.
