### ISSUE TITLE
Failed to load resource: the server responded with a status of 503 () https://lhc.domain.com/index.php/widgetrestapi/onlinesettings 

### ISSUE THREAD

**Issue by muhyal** [LiveHelperChat/livehelperchat#1685]
Hi,

We try everything (Re-upload, Upgrade, New install..) but see this error on browser console.
Apache logs show MariaDB version error, but I tried it with a lower version, results same.

PHP: 7.4.3 (FPM)
Webserver: Apache 
MariaDB: 10.3.31
OS: Ubuntu 20.04

We use latest updated Plesk panel.

Failed to load resource: the server responded with a status of 503 () https://lhc.domain.com/index.php/widgetrestapi/onlinesettings 

Apache errors:

AH01071: Got error 'PHP message: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1 in /var/www/vhosts/lhc.domain.com/httpdocs/lib/core/lhchat/lhchat.php:839\nStack trace:\n#0 /var/www/vhosts/lhc.domain.com/httpdocs/lib/core/lhchat/lhchat.php(839): PDOStatement->execute()\n#1 /var/www/vhosts/lhc.domain.com/httpdocs/lib/core/lhchat/lhchat.php(933): erLhcoreClassChat::isOnline(Array, false, Array)\n#2 /var/www/vhosts/lhc.domain.com/httpdocs/cache/compiledtemplates/6e29059c0c87e3b7fbae6853bb5cd219.php(2): erLhcoreClassChat::isOnlyBotOnline(Array)\n#3 /var/www/vhosts/lhc.domain.com/httpdocs/lib/core/lhcore/lhmodule.php(102): include('/var/www/vhosts...')\n#4 /var/www/vhosts/lhc.domain.com/httpdocs/lib/core/lhcore/lhmodule.php(560): erLhcoreClassModule::runModule()\n#5 /var/www/vhosts/lhc.domain.com/ht...', referer: https://lhc.domain.com/

Thanks for your effords.

**Comment by PeopleInside** [comment]
Hi @muhyal, was you able to resolve your issue?
I'm sorry that you get no reply. Usually the error 503 is something that depends on the server, I think.

I hope you have resolved.

**Comment by muhyal** [comment]
Thanks,

I deactivate option in;

System Setting > Departments List > Department > If you want that chat ignored operators online status and went online only by these defined hours can do that here > The online hours of the users are not counted and the active hours of the department are recorded

Now this temporary fix the problem. If we set a work hours, in work hours if this option checked "The online hours of the users are not counted and the active hours of the department are recorded" system gives again 503 error. 

Reproduced on cPanel, Plesk, Apache, Nginx, LAMP & LEMP stack :)

I think this is a bug.

**Comment by PeopleInside** [comment]
What version of PHP and live helper chat are you using to face this issue?
How you installed live helper chat: some control panel or directly by downloading on GitHub and uploading?

Thanks for your reply with details about how you found a workaround.

**Comment by muhyal** [comment]
We try new installs on two different panel (Plesk, cPanel) with clean LHC 3.81 version. 

Tested PHP versions:
7.4.3 (FPM - Apache - Nginx)
7.3.30 (FPM - Apache - Nginx)
8.0.10 (FPM - Apache - Nginx)

**Comment by PeopleInside** [comment]
Can you please write step one by one for reproduce the issue?

Like:
- Go to
- Do this
- Restuls: this

You can re-open this issue if you think is still valid.

Please try also to see if you are able to reproduce the issue in the official demo of live helper chat:
https://livehelperchat.com/demo-12c.html

Thank you very much!

**Comment by remdex** [comment]
I have fixed the issue. Please update from master branch.
