### ISSUE TITLE
Webhook re-executed and ghost messages

### ISSUE THREAD

**Issue by tomaluca95** [LiveHelperChat/livehelperchat#1688]
When I enable webhooks (on the chat.addmsguser event) i see the hook executed multiple time (more than 10 for each message) and on the guest side of the chat i see the message sent multiple time. When I refresh the page all duplicated messages are gone.

I got this error
```json
{"r":"","t":[]}{"error":true,"message":"There was a transaction error caused by unmatched beginTransaction()\/commit() calls: rollback() called without previous beginTransaction()."}
```

in the response of the request `/addmsguser`

With webhooks disabled everything is fine

**Comment by remdex** [comment]
You somewhere made an error, so it terminates transaction in the middle. Plese debug your script as seems there is a fatal error priori to that.

**Comment by remdex** [comment]
Also try this update. So you should see exact error in audit log or response
https://github.com/LiveHelperChat/livehelperchat/commit/6e13fdf42e0521e9990aeee1baae4c74ce47d8dc

**Comment by tomaluca95** [comment]
My script returns 200 OK from the webhook endpoint (I see the remote server access log), the problem is that is called multiple times. I haven't touched the code of the chat.

If i turn off the webhook integration everything is fine but they webhook isn't invoked.

**Comment by remdex** [comment]
Everything is working here, if you want personal help there is commercial support for that. But as i told try to update and see audit log for an error.

**Comment by tomaluca95** [comment]
I applied the last change and i see that the issue is in the file `lib/core/lhgenericbot/lhgenericbotworkflow.php` line 1600

As far as I can understand the code the problem is in the recursion in that function.

I fixed my issue adding the check for `$messageNew['trigger_id'] != $trigger->id` before executing the recursive call.

Thanks for the help.

**Comment by remdex** [comment]
That's the bug in your bot setup. You never should have recursion in your bot workflow.
