### ISSUE TITLE
after update to version - 3.83 and creating a new user.

### ISSUE THREAD

**Issue by khrizo** [LiveHelperChat/livehelperchat#1690]
`Warning: foreach() argument must be of type array|object, null given in /lhc_web/design/defaulttheme/tpl/lhfront/default_new.tpl.php on line 37`

Dashboard source code is incomplete, other parts of the admin works just fine.

**Comment by khrizo** [comment]
I guess something to do with cache, after clearing everything  started working.

**Comment by PeopleInside** [comment]
> after clearing everything started working

@khrizo thank you for write the steps that helped you

I'm happy you have resolved.
Enjoy and have good time!
