### ISSUE TITLE
FEATURE REQUEST - Allow for a chat to automatically open into a full chat that is autoassigne and auto accepted.

### ISSUE THREAD

**Issue by aykaramba** [LiveHelperChat/livehelperchat#1691]
Hi!

My apologies, if I am posting this wrong, please delete and let me know how to submit a feature request properly.

FEATURE REQUEST - Allow for a chat to automatically open into a full chat that is autoassigned and auto accepted.

USECASE:

1) I am using the embedded widget as part of the site design.

2) I have already enabled auto accept and auto assign features, however a visitor still has to post a question for a chat to actually begin, the applet to render into a full chat div and a chat to begin.

3) What I am seeking to accomplish is to have every visitor automatically join a full chat such that I can just start chatting with the visitor right away, start posting comments and so forth.

I am looking to reduce the number of clicks between me and visitors as low as possible.

Live Helper Chat is amazing and the auto assign and auto accept feature already exist so it would be nice to have access to this feature.

QUESTION: Would anyone know what it might take to enable this behaviour?  It seems like this would only need to adjust the function that checks the session state and decides to open up a full chat for users.

Thanks.

**Comment by remdex** [comment]
There is already such feature check start chat form settings and check "Auto start chat if there is no required fields. Usefull in case bot handles chat."
