### ISSUE TITLE
Chat Widget loading issue

### ISSUE THREAD

**Issue by bkskomal** [LiveHelperChat/livehelperchat#1701]
There is an exception coming while loading the chat widget by clicking on widget icon on bottom right. Sometimes the widget icon is not loading as well. The close and minimize button of chat button is also not working.

Exception that I am seeing is attachted in screenshot.

Any help regarding this issue will be very much appreciated.

![Livelhelperchatissue](https://user-images.githubusercontent.com/43546103/136792896-8731f7b2-b0de-400e-9c22-5b9c8f02872b.png)

**Comment by remdex** [comment]
It's a line but not an error. Can you paste real error not the line itself?

**Comment by bkskomal** [comment]
This issue has been resolved. The issue was we were making some changes to document.domain in our project, this was conflicting with the code of live helper chat.
