### ISSUE TITLE
change date in shamsi

### ISSUE THREAD

**Issue by HadiNB** [LiveHelperChat/livehelperchat#1702]
Please indicate a way to convert the date in the script LivechatHelper to solar.

**Comment by remdex** [comment]
And that means? :D

**Comment by HadiNB** [comment]
That is, the calendar and date should be in the format of the Iranian calendar

**Comment by HadiNB** [comment]
thanks for your answer.
I do not mean this. If you check the solar date of Iran, instead of 2021, this year we are 1400 and the days and months are completely different from your date. I mean changing the structure of the default calendar to the history of solar Iran. When the calendar selection list is executed, this calendar should be executed with the structure of the Iranian solar calendar. How can it be changed?
I hope I have been able to provide a complete explanation. To check the type of calendar in Iran, you can refer to the following address: https://www.taghvim.com
