### ISSUE TITLE
Whatsapp autoresponder (open-wa) 

### ISSUE THREAD

**Issue by NSOPORTEDESARROLLO** [LiveHelperChat/livehelperchat#1710]
Hi,

I have a working instance with whatsapp (open-wa), but I can't use autoresponder module, it works fine with web based chat but when I test a new chat by whatsapp it doesn't sent the message, in other hand autoresponder on closed chats work fine with WA.

**Comment by NSOPORTEDESARROLLO** [comment]
Thanks Remdex!

I think using bots I'll find a work around.

**Comment by remdex** [comment]
Recent versions now supports auto responder for third party chats our of the box. 
https://doc.livehelperchat.com/docs/auto-responder
