### ISSUE TITLE
The operator icon on chat window is disappearing in case of new message

### ISSUE THREAD

**Issue by mhdali93** [LiveHelperChat/livehelperchat#1712]
[screen-capture.webm.zip](https://github.com/LiveHelperChat/livehelperchat/files/7404154/screen-capture.webm.zip)

Attached is a video of the error I am facing, also when I put the delay before sending typing in the bot, the operator icon is only visible after the delay time is lapsed.

**Comment by remdex** [comment]
Seems I can't reproduce the issue. Please prepare sample bot without third party dependencies.
