### ISSUE TITLE
Issue with offline text when widget is online

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1719]
I have a custom message for the widget offline, this text has been inserted in

site_admin/abstract/edit/WidgetTheme Widget chat tab

If the visitor see the widget offline than turns online the offline text still be showed until the page is not refreshed.
Can implement that when widget is online the offline text is no more showed and the other way around?

**Actual result:** The chat was offline, without refresh the page the widget is now online but when visitor click on IT will see the Offline message followed by the form to start a chat.

![lhcoffon](https://user-images.githubusercontent.com/5006150/143848749-efc9c1ec-ff04-4ba2-b7c9-052655b2109a.gif)

**Expected result:**

The offline text should be hidden if widget is turned online.

![expected results lhc](https://user-images.githubusercontent.com/5006150/143849199-3251dbb7-e0dd-4c83-9763-6ce33643633c.gif)

**Comment by PeopleInside** [comment]
If the widget turns **from on-line to off-line**, **the online HTML in widget is correctly hidden** and is showed only the off-line HTML content.

If the widget turns from off-line to on-line, the **off-line HTML is not hidden** and is added to the online HTML showed.

I don't know where this should be fixed in the code but need just add the function to hide off-line HTML if the widget turns on-line.

I hope the fix can be done before the end of this year.
Thank you very much!

This looks to be a little bug but is nice to have the right online message when widget turn online from offline mode.
Thank you!

**From ON-to OFF-line - ALL WORKS correctly**

![OFF-LINE correct](https://user-images.githubusercontent.com/5006150/144766604-d987df7b-1f49-4f4b-823c-4e275f514088.jpg)

**From OFF-line to ON-line - WRONG, OFF-line HTML not hidden**

![ON-LINE WRONG](https://user-images.githubusercontent.com/5006150/144766606-2d807ba1-8fbb-4c60-bbe2-29a0a93ccd27.jpg)

Example of what should be:

![ONLINE correct](https://user-images.githubusercontent.com/5006150/144766605-33e6963d-9018-4e82-bea1-661c76f45191.jpg)

**Comment by remdex** [comment]
There is no need to create a duplicate comments as I know what you are trying to do.

**Comment by PeopleInside** [comment]
Hum, you can close this issue because can be resolved by moving from start chat settings HTML to the widget content HTML.
I removed the pre chat HTML and moved to the theme widget content HTML and resolved the issue.

You don't need work on a fix.
I'm closing this as can be resolved without hard work from you.

Thank you <3
