### ISSUE TITLE
PHP 8.0 mobile compatibility issue

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1723]
Requirement: PHP 8.0
LHC 3.9

> From mobile access to http://livechat.domain.ext/site_admin/

Results:

Mobile page won't load correctly.

PHP errors from the server logs:

`AH01071: Got error 'PHP message: TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in [...]/livechat/design/defaulttheme/tpl/lhfront/dashboard/index.tpl.php:13\nStack trace:\n#0 [...]/livechat/design/defaulttheme/tpl/lhfront/default.tpl.php(127): include()\n#1 [...]/livechat/lib/core/lhtpl/tpl.php(568): include('...')\n#2 [...]/livechat/lib/core/lhtpl/tpl.php(541): erLhcoreClassTemplate->fetchExecute()\n#3 [...]/livechat/modules/lhfront/default.php(40): erLhcoreClassTemplate->fetch()\n#4 `

**Comment by remdex** [comment]
I don't think you have the correct files as this is just impossible to have this error. In any case I added chagnes.

**Comment by PeopleInside** [comment]
Fixed, works, thanks!
