### ISSUE TITLE
Blocking affects everyone

### ISSUE THREAD

**Issue by Arnaud0865** [LiveHelperChat/livehelperchat#1730]
Expected behaviour:
Blocking one user prevents them from accessing the chat. Blocking with IP prevents anyone with the same IP to join.

Actual behaviour:
Blocking with IP prevents everyone from joining.

How to reproduce:
- Have a chat
- Block their IP
- Have someone else (with a different IP) try to join

**Comment by remdex** [comment]
From your report it's unclear what exactly is wrong. If you are running lhc under proxy you can activate this option https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/settings/settings.ini.default.php#L18

**Comment by Arnaud0865** [comment]
Can I see this option from the LHC in-app settings? If yes, where?

**Comment by remdex** [comment]
In app no.
