### ISSUE TITLE
connecting tribute or typeahead  with chat widget  for auto completion of questions

### ISSUE THREAD

**Issue by sreenathmurali** [LiveHelperChat/livehelperchat#1731]
@remdex  : Is it possible to integrate  tribute ( https://github.com/zurb/tribute ) or typeahead (https://github.com/twitter/typeahead.js )with  live help widget  for autocomplete queries ??

**Comment by remdex** [comment]
Hi,

Thank yoy for your feedback, but at the moment I don't have plans for that :)

**Comment by sreenathmurali** [comment]
@remdex  : in which script I can try for a customization (auto complete ) ?

**Comment by sreenathmurali** [comment]
@remdex  : Any tweaks can be done to existing widget for autocomplete ( I am not an expert in scripting ) ?
