### ISSUE TITLE
[Feature request] Minified js

### ISSUE THREAD

**Issue by CryptorClub** [LiveHelperChat/livehelperchat#1732]
Hello developers of livehelperchat. You have done a lot of work and chat is really good as Open Source project through time.

The javascript embed code loads pretty fast on external pages/sites, anyway I propose to little bit improve code - to minify js
It should save up to 150ms on page load.

`/help/index.php/chat/getstatus/(position)/api/(ma)/br/(top)/350/(units)/pixels/(leaveamessage)/false/(disable_pro_active)/true?r=&l=url`

Good luck.

**Comment by remdex** [comment]
You are reporting old widget url...

**Comment by CryptorClub** [comment]
> You are reporting old widget url...

With new code has issue with CORS origin. With old one, no such error.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://example.com/help/design/defaulttheme/js/widgetv2/index.js?2022014. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200

https://developer.mozilla.org/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default

**Comment by remdex** [comment]
Old widget will be removed in the next few release.

As for CORS https://doc.livehelperchat.com/docs/integrating/#my-widget-does-not-work-i-have-live-helper-chat-installed-on-one-domain-but-code-is-embeded-on-another-domain
