### ISSUE TITLE
REST API ERROR

### ISSUE THREAD

**Issue by sreenathmurali** [LiveHelperChat/livehelperchat#1735]
Getting following error while connecting to REST API endpoint.

http status code - 100
http error - Operation timed out after 10001 milliseconds with 0 bytes received
content raw -
request parameter- {"headers":[],"url":"http:\/\/localhost:5001\/account"}

I am getting response if I try through postman..

@remdex

**Comment by remdex** [comment]
It just means your php can't connect to that URL. It's your env problems, so nothing I can do :)

**Comment by sreenathmurali** [comment]
http status code - 200
http error -
content raw - [
"Answer-1",
"Answer-2",
"Answer-3"
]

I am getting only answer-1 with Response Location 1 as 0: in REST API output parsing.
How to get all the answers ?
@remdex

**Comment by remdex** [comment]
I'm not sure how exactly you are going to use it but you can use 
https://doc.livehelperchat.com/docs/bot/bot-text/#foreach-cycle

**Comment by remdex** [comment]
Hi,
Usually if you need something more complex you can write your intermedia server and parse deeppavlov response and use response trigger like https://doc.livehelperchat.com/docs/bot/trigger-body
