### ISSUE TITLE
Frontend translation request twice for different languages

### ISSUE THREAD

**Issue by qbadev** [LiveHelperChat/livehelperchat#1737]
When Frontend widget is loading, there are 2 requests for 2 different languages. First is for language I set up in Backend, another one looks like default for english.
`https://chat.domain.com/index.php/lang1/widgetrestapi/lang/translation`
`https://chat.domain.com/index.php/eng/widgetrestapi/lang/translation`
It causes that some texts are defaulted during chat session - these texts should be translated to my main language.
It maybe a bug or misconfiguration.

**Comment by remdex** [comment]
Sorry impossible to understand what you wrote.
Read article about multilanguage and how it works
https://doc.livehelperchat.com/docs/chat/multiple-languages/

**Comment by qbadev** [comment]
Widget is configured to polish language, and it downloads translation for polish, but after this, it downloads also translation for english. I showed to URLs of those requests in my first message. I am not using multilanguage widget, I want only polish frontend.

**Comment by remdex** [comment]
That's normal how it works. English is a fallback language so it has to download it always for Polish you can just pass as argument in embed code
```
lang : 'pol/'
```

**Comment by qbadev** [comment]
I pass mentioned language argument to my embed code. But even if `visitor` word is correctly translated to polish, it is being replaced by english version. I attach an image showing that widget is fully translated to polish except `visitor` word.
![Zrzut ekranu z 2022-02-04 08-57-51](https://user-images.githubusercontent.com/293101/152492991-0aeace79-60dc-4f2a-8cc2-baa621f6876c.png)
It is even possible to see word `gość` (polish translation of visitor) as it is being replaced by `visitor` when widgets shows up.

**Comment by remdex** [comment]
This word is never translated unless you prefill it with correct nick. 
https://doc.livehelperchat.com/docs/custom-fields-and-prefill/#prefilling-and-defining-custom-variables

P.s You can change messages layout so this nick is not shown https://doc.livehelperchat.com/docs/theme/theme/#messages-style

**Comment by qbadev** [comment]
thanks for support. Will try all of these suggestions

**Comment by remdex** [comment]
In any case, I ques I'll add translation support for that particular thing. Just nowadays most of the users just use Themes and change message layout :)
