### ISSUE TITLE
Frontend widget DetectLanguage not working properly

### ISSUE THREAD

**Issue by qbadev** [LiveHelperChat/livehelperchat#1738]
When FE widget language is left default (eng) and `DetectLanguage` checked, FE JS recognizes lang code as two letters (ie. en, fr, es), but LHC works using 3-letter language code. It then downloads wrong (default) translation when initializing.

**Comment by remdex** [comment]
You have to adjust site access settings to use that. https://doc.livehelperchat.com/docs/chat/multiple-languages/#how-to-change-default-language-siteaccess

Better option is just to activate language detection not in embed code but in widget themes.
