### ISSUE TITLE
Can't login using my admin account.

### ISSUE THREAD

**Issue by julemarts29** [LiveHelperChat/livehelperchat#1740]
Hi I installed LiveHelperChat using Softaculous, I can't seem to login using the admin account, tried forgetting password it still doesn't work. I also tried the demo on the website it seems to be working fine. Is this a problem with the database?

**Comment by PeopleInside** [comment]
Hi, before you can receive password you need to be able to login and set correct email SMTP data.
Have you checked if maybe the recovery password email is into the spam folder of your email address?
If I'm not wrong Softaculous let you edit the password, check your installation edit option in Softaculous.

If you still be unable to login you may try to re-install with more attention on save right credentials.

**Comment by julemarts29** [comment]
`https://<domain>/index.php/site_admin/` I used this link to login, also there seems to be no problem with the admin credentials, its just it won't let me login. I doubled checked the credentials and tried re-installing twice.

**Comment by julemarts29** [comment]
![image](https://user-images.githubusercontent.com/28949941/152951959-26a7338b-bedb-4759-8bcb-186904dfb567.png)

I got this error.

this part caused the error
`public function start()
    {
        if ( session_id() === '' && PHP_SAPI !== 'cli' )
        {
            session_set_cookie_params(0); 
            session_start();
        }
    }`

**Comment by PeopleInside** [comment]
Can you try to upgrade your PHP?
If I'm not wrong seems you are using a deprecated PHP 7.3, soon will be end of life also PHP 7.4

Can you try maybe PHP 7.4 or PHP 8.0 or PHP 8.1?

**Comment by remdex** [comment]
@julemarts29 you have incorrectly configured the server as it can't write PHP sessions...

**Comment by julemarts29** [comment]
I haven't been able to change the php version on my cpanel, I tried changing it to 8.0 but when I check server information it still stuck in 7.3. I'll try to contact the customer service of my webhost first if I can change the php version to 8.0.
