### ISSUE TITLE
3.95v Online Visitor show tracking in /site_admin/ ( tracking myself Operator )

### ISSUE THREAD

**Issue by dev-hyperweb** [LiveHelperChat/livehelperchat#1746]
when I logged in to "site_admin/" 
and visit to other page that I active livechat,
and visit back to "site_admin/"
It tracking myself from visiting "site_admin" and show on Online Visitor Section,

Example:
Current page - https://my_domain.com/site_ admin/

so It shouldn't tracking myself,  this bug or working like this ?

**Comment by remdex** [comment]
Most likely your server does not pass some of request URL and is redirected back to home page and in home page we track online visitor. Inspect your google chrome console.

**Comment by dev-hyperweb** [comment]
You right. This cause by sound missing from "design/customtheme/sound/silence.ogg"

but image, I want only to custom one sound, and other sound use from default theme, 
any idea how to settings this for future without copy/move from "defaulttheme/sound" to "customthem/sound" ?

Example, I want to custom only "sound/new_chat"
