### ISSUE TITLE
3.95v "Select Department" not save in "site_admin/"

### ISSUE THREAD

**Issue by dev-hyperweb** [LiveHelperChat/livehelperchat#1747]
Whwn I select some department to show Online Visitor and refreash webpage, department that I select back to "Show All"

This bug ? or not have future yet ?

**Comment by remdex** [comment]
Seems your server missbehaving. Please don't paste things here if you can provide steps to reproduce or can't reproduce in official version.

**Comment by remdex** [comment]
Most likely your server does not pass some of request URL and is redirected back to home page and in home page we track online visitor. Inspect your google chrome console.

**Comment by dev-hyperweb** [comment]
@remdex Could you check my PR that fixed for my issued. This cause by Missing csrf-token headers on http-request
