### ISSUE TITLE
Autoreload static image chat status

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#1756]
When embed code is generated for a static image you can generate a code that will autoreload the image to keep the live chat status updated.

See https://stackoverflow.com/a/70320239

`<img src="test2.jpg" id="reloader" onload="setTimeout( () => { document.getElementById('reloader').src='test2.jpg' + '?' + new Date().getMilliseconds() } ,5000)" />`

Will be nice if LHC can add itself this format.

Currently if the static image is selected for generating the code, LHC will not update the status of the static image.

If 5000 ms is too short time you can set 150000 ms that will be about every 3 minutes

**Comment by remdex** [comment]
Well you can improve documentation with this sample :)
