### ISSUE TITLE
Angular JS Error documentation referenced with non-SSL link

### ISSUE THREAD

**Issue by sirouk** [LiveHelperChat/livehelperchat#1757]
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/design/defaulttheme/js/js_static/53daa665fc5c26fd753c137cf4fa07b7.js

"...http://errors.angularjs.org/1.8.2..."

plus one other non-SSL link

"qr=nn(t.location.href);Wr.href="http://[::1]";"

**Comment by remdex** [comment]
Please clarify why it's an issue for you. If it's security issue fill an issue in https://huntr.dev/
