### ISSUE TITLE
Editing proactive invitations renders a 302 redirection

### ISSUE THREAD

**Issue by markweirath** [LiveHelperChat/livehelperchat#1761]
When I was adding/editing a proactive invitation and restricting the invite to a certain channel or channels it rendered a 302 redirection.
_(Using version 4.03 but also had the issue on earlier version.)_

Checking the databasetable '**lh_abstract_proactive_chat_invitation**' shows that in such a case a '**dep_id**' with value '**-1**' is inserted in the table and this consequently renders the 302 redirection back to the dashboard making it impossible to edit or delete the proactive chat invitation. Changing the value in the database to 0 fixed the redirect so it became editable again... 

I don't know where the problem originates in the code but this is what I could find on my installation of Live Helper Chat.

**Comment by remdex** [comment]
Most likely you don't have permission to edit specific department. It's not assigned to you. If what reproduce on official demo and write steps.
