### ISSUE TITLE
BOT response "Execute Javascript" not working

### ISSUE THREAD

**Issue by andrerinaldi** [LiveHelperChat/livehelperchat#1762]
Hi,

as explained [here](https://doc.livehelperchat.com/docs/bot/execute-js/) we would expect to be able to define a BOT response type that triggers the execution of Javascript code. 

But it's not working: no console.log, no alert.

![image](https://user-images.githubusercontent.com/6502044/169279930-eaa4c2ab-a23e-4ae2-ad33-d406a67809e0.png)

Are we doing something wrong?
We need this to enable an important feature for a customer.

Thank you in advance.

**Comment by remdex** [comment]
You can don't put anything in script identifier and in arguments. To execute in site where widget is embedded use window.parent....
