### ISSUE TITLE
error in upgrade.php with PHP 8.1

### ISSUE THREAD

**Issue by HoffmannTom** [LiveHelperChat/livehelperchat#1769]
Hello,
I tried to upgrade the database to new version.
With PHP 8.1 I get an error:
PHP Fatal error:  __autoload() is no longer supported, use spl_autoload_register() instead in D:\Inetpub\wwwroot\upgrade.php on line 39

The used function is not supported any more with PHP8.x

**Comment by HoffmannTom** [comment]
I think it should be replaced by:

```
spl_autoload_register(function ($class_name) {
    ezcBase::autoload( $class_name );
});
/*
function __autoload( $className )
{
        ezcBase::autoload( $className );
}*/
```

**Comment by remdex** [comment]
Right, just as for update I would suggest to follow https://doc.livehelperchat.com/docs/upgrading/ via git workflow :)

**Comment by HoffmannTom** [comment]
Hello,
I used that website for instructions. Copying the upgrade.php to the root folder and using browser to call this webpage, led to the mentioned error.
