### ISSUE TITLE
Few questions about the chat

### ISSUE THREAD

**Issue by farzadha2** [LiveHelperChat/livehelperchat#1788]
Hi 
I was wondering if someone could shed some light on a few questions i have

1) when click on the chatbox on website goes to another tab and does not show popup i went to system config, then widget code (new)
then i added on the website but it appears like this and when they click on it goes to another page
![image](https://user-images.githubusercontent.com/62571297/191158765-9ccb1fad-c9d5-4336-96a6-bf8afaa36e72.png)

2)  on the client side it seem that they cant attach not sure if i need to enable on the settings on the server couldn't find that option 

3) what is the red dot meaning? on the reports from what understand happens when the client closes chat?
![image](https://user-images.githubusercontent.com/62571297/191158924-e6d760c6-0408-4362-8272-471da483766f.png)

4) i downloaded the app on android then enable the settings on the server and tested with sending a test notification and it works perfectly but when a client starts a chat i get no notification any ideas why?
i tried reading https://doc.livehelperchat.com/docs/mobile/

5) on the cellphone android app i tried looking for the option whisper but couldn't find it

Thank you

**Comment by PeopleInside** [comment]
Is true that the live chat button never usually open a pop up, maybe this can be improved from the developers.
For have a live chat button that open a pop up I need ask on the world wide web for help.

I use the following code:

```
 <script>
         function myPopup(myURL, title, myWidth, myHeight) {
            var left = (screen.width - myWidth) / 2;
            var top = (screen.height - myHeight) / 4;
            var myWindow = window.open(myURL, title, 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width=' + myWidth + ', height=' + myHeight + ', top=' + top + ', left=' + left);
         }
 </script>

  <center>   
           <a onclick=" myPopup ('https://domain.ext/lhc/ita/chat/start/(theme)/xx/(vid)/....50b9fc', 'Live Chat', 500, 715);"><img class="wp-image-1182 aligncenter" alt="live-butt" src="https://domain.ext/lhc/index.php/site_admin/restapi/onlineimage?&online=Live%20chat%20online&offline=Live%20chat%20offline&w=200" id="reloader" onload="setTimeout( () => { document.getElementById('reloader').src='https://domain.ext/lhc/index.php/site_admin/restapi/onlineimage?&online=Live%20chat%20online&offline=Live%20chat%20offline&w=200' + '?' + new Date().getMilliseconds() } ,60000)"></a>
  </center>

  <style>
        .custom-html-widget > center:nth-child(2) > a:nth-child(2) {
	cursor: pointer;
                                                                   }
  </style>
<hr>
```

For other things regarding mobile app you can maybe reply the issue on the mobile app repo; 
https://github.com/LiveHelperChat/lhc_messenger

The green or red icon means the status of the chat when the chat was closed so if the visitor was online or not.

**Comment by farzadha2** [comment]
Hi @PeopleInside thank you so much for the reply, regarding the script would it be similar from the widget like https://livehelperchat.com/ on the bottom right ? 
not sure on your side if the clients can attach pictures? i looked for the option but did not see it

Thank you

**Comment by PeopleInside** [comment]
The script suggested is for open a pop up and once the chat is started, if you has enabled attachments visitor can attach as happen on the widget. The script I found is for open a pop up not a widget in the page. You can see how it works on my website footer https://www.peopleinside.it

**Comment by farzadha2** [comment]
Sorry for the late reply, just saw the messages, i was testing it out and this is what i got 
on the theme footer.php added this part at the bottom
```

 <script>
         function myPopup(myURL, title, myWidth, myHeight) {
            var left = (screen.width - myWidth) / 2;
            var top = (screen.height - myHeight) / 4;
            var myWindow = window.open(myURL, title, 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width=' + myWidth + ', height=' + myHeight + ', top=' + top + ', left=' + left);
         }
 </script>

  <center>   
           <a onclick=" myPopup ('https://chattest.domain.com/lhc/ita/chat/start/(theme)/xx/(vid)/....50b9fc', 'Live Chat', 500, 715);"><img class="wp-image-1182 aligncenter" alt="live-butt" src="https://chattest.domain.com/lhc/index.php/site_admin/restapi/onlineimage?&online=Live%20chat%20online&offline=Live%20chat%20offline&w=200" id="reloader" onload="setTimeout( () => { document.getElementById('reloader').src='https://chattest.domain.com/lhc/index.php/site_admin/restapi/onlineimage?&online=Live%20chat%20online&offline=Live%20chat%20offline&w=200' + '?' + new Date().getMilliseconds() } ,60000)"></a>
  </center>

  <style>
        .custom-html-widget > center:nth-child(2) > a:nth-child(2) {
	cursor: pointer;
                                                                   }
  </style>
<hr>
```
but for some odd reason im getting Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID

thank you

**Comment by PeopleInside** [comment]
Seems you are having issue with your server certificate, you can Google your error to find a solution "net::ERR_CERT_COMMON_NAME_INVALID"

**Comment by farzadha2** [comment]
thanks for the reply, whats odd is that i check the site on other browsers and works fine, ill post back until i find the issue

**Comment by farzadha2** [comment]
Hi @PeopleInside so i was looking into the issue and created a wildcard, what i think might be the issue is something with the script because when i access the website it shows correctly only issue when attached to the wordpress site very odd

![image](https://user-images.githubusercontent.com/62571297/194211488-ad785320-6754-42bf-a787-b2b993ab8602.png)

**Comment by PeopleInside** [comment]
Can we close this thread?
