### ISSUE TITLE
widget cant display

### ISSUE THREAD

**Issue by cbdgftqs** [LiveHelperChat/livehelperchat#1789]
hello, below is the opera console info, and the widget cant display, I am running a local wordpress website ,the script is placed in the theme function.php file

Access to script at 'http://10.0.0.103/design/defaulttheme/js/widgetv2/index.js?2022827' from origin 'http://127.0.0.1' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

how to resolve this ,thx a lot

**Comment by remdex** [comment]
https://doc.livehelperchat.com/docs/install#my-widget-does-not-load
