### ISSUE TITLE
Survey shows error saying "Please re-load window because of an error"

### ISSUE THREAD

**Issue by andrerinaldi** [LiveHelperChat/livehelperchat#1805]
Hi,

we are using LHC version 4.09.

We declared a survey in the back office.
Our operators are redirecting users to this survey explicitly with the dedicated button in chat actions from the panel on the right.

The widget correctly loads the survey, the user fill the info required by the survey and click "Send feedback".
The survey is correctly sent to the backend and registered, but the widget displays an error:
![image](https://user-images.githubusercontent.com/6502044/201657102-a6f0a254-e6cb-42fc-969f-f56f578640df.png)

... with this logs in the browser console:
![image](https://user-images.githubusercontent.com/6502044/201657152-130eaa2e-b12d-4111-aa8d-f9d5dd8e2e8f.png)

We did not change anything in the source code of LHC.

**Comment by remdex** [comment]
Not sufficient data to reproduce.

**Comment by andrerinaldi** [comment]
Sorry, it was a custom javascript that was breaking the frontend. Didn't know that it was added by a colleague.
