### ISSUE TITLE
Access-Control-Allow-Origin issues only in offline/email mode

### ISSUE THREAD

**Issue by Dan-Sun** [LiveHelperChat/livehelperchat#1818]
Hey

I'm currently facing this problem. It worked some versions before, but I can't really tell when it changed. Could also be some other changes to the server and not necessarily due to lhc itself.  

The interesting part here is that we don't have any problems between working hours. So chat function just works. But after working hours, we have enabled the option to send us an email through the widget. 
The problem only occurs when offline mode is enabled resp. after working hours.

So the set up is actually the same like https://doc.livehelperchat.com/docs/nginx-configuration-tips/ and https://doc.livehelperchat.com/docs/install/#my-widget-does-not-load. 

Currently we've just disabled the email option.

Any suggestions? 
Do you need any other info? (There are no other helpful logs, also not in lhc itself.)

Thanks

**Comment by remdex** [comment]
Well error itself shoud tell what's the problem and url. As this error happens due to chat server configuration.

In general to hard to say why it happens as it does not happen here.

**Comment by Dan-Sun** [comment]
Hey @remdex 

Sorry for the late reply. Had no time to get into it.

The problem was on my site. Missed the rights after update for the webuser and some modsec issues.
