### ISSUE TITLE
found translation error in /modules/lhwidgetrestapi/settings.php

### ISSUE THREAD

**Issue by comsyspro** [LiveHelperChat/livehelperchat#1833]
found translation error in /modules/lhwidgetrestapi/settings.php

https://github.com/LiveHelperChat/livehelperchat/blob/470a75e437472ddc7d0299b71f17f0a283fe2d0e/lhc_web/modules/lhwidgetrestapi/settings.php#L409
https://github.com/LiveHelperChat/livehelperchat/blob/470a75e437472ddc7d0299b71f17f0a283fe2d0e/lhc_web/modules/lhwidgetrestapi/settings.php#L420

you need to change 
`'Our staff are ready to help!'`
to
`'Our staff are always ready to help'`
because this will lead to an translation error

**Comment by remdex** [comment]
Why? I prefer to keep `!` at the end. And you can always override translation you don't like.

**Comment by comsyspro** [comment]
for example in all of the translation files it is defined as `Our staff are always ready to help`. when you add the `!` at the end then the translation goes wrong for all other languages instead of english. so either to change this here or in all translation files.
https://github.com/LiveHelperChat/livehelperchat/blob/3e5afbcf80660ca6ff39087fd1bcdc2fcd92905b/lhc_web/translations/ar_EG/translation.ts#L5328

**Comment by remdex** [comment]
It looks more like a bug, with generator who generates default translation file.

**Comment by comsyspro** [comment]
i can only say that without changing this all translations in the "need help widget" only shows the standard english language and the translation won't work. so the source have to be identical so that the translation function is working correectly.

**Comment by remdex** [comment]
Once I push default translations transifex has to pick them up. After that I can update default languages translations only.

**Comment by comsyspro** [comment]
ok then i will update later once again and see.

**Comment by comsyspro** [comment]
i come back to this issue again because this error still exists. and here i have 2 workarounds.
1.)
to work correctly in all language files the line (translation files *.ts) should be changed to `<source>Our staff are always ready to help!</source>` (with an exclamation mark at the end). Whithout this exclamation mark the translation of the need help widget gets false and it always displays only the english translation regardless of the selected language.

2.)
or as described above you can also fix this here by removing the exclamation mark in this settings.php file. with that you can let the translation files *.ts as is.
https://github.com/LiveHelperChat/livehelperchat/blob/470a75e437472ddc7d0299b71f17f0a283fe2d0e/lhc_web/modules/lhwidgetrestapi/settings.php#L409
https://github.com/LiveHelperChat/livehelperchat/blob/470a75e437472ddc7d0299b71f17f0a283fe2d0e/lhc_web/modules/lhwidgetrestapi/settings.php#L420

**Comment by remdex** [comment]
I just updated translations, they should be fine if you put proper translation in translation file.
