### ISSUE TITLE
Hide IP / anonymization for IPv6

### ISSUE THREAD

**Issue by sorrx** [LiveHelperChat/livehelperchat#1834]
Flicking through the server-logfiles I noticed several PHP warnings concerning IP anonymization.
` Undefined array key 1 in [path_to_LHC]/lib/models/lhchat/erlhcoreclassmodelchat.php on line 640`

In this file and a few other places there is a code-block like this
```php
if ($hideIp->value == 1) {
       $parts = explode('.',$instance->ip);
       if (isset($parts[0]) && $parts[1]) {
           $instance->ip = $parts[0] . '.' . $parts[1] . '.xxx.xxx';
       }
}
```
If the instance-ip contains an IPv6 address accessing $parts[1] generates that warning.

Maybe these codeblocks could be outsorced to a new function, that returns something like the following:
```php
return preg_replace(
    [
        '/(\.\d){2}$/',
        '/(:[\da-f]*){2,4}$/'
    ],
    [
        '.XXX.XXX',
        ':XXXX:XXXX:XXXX:XXXX'
    ],
    $ip
);
```
This is slightly edited to replace the last 2 / 4 blocks of an IP - the original code I found here: https://stackoverflow.com/questions/48767382/anonymize-ipv4-and-ipv6-addresses-with-php-preg-replace

**Comment by remdex** [comment]
Thanks. I'll look into that tomorrow 😃

**Comment by remdex** [comment]
Pushed one more time update. I did not wanted to add new function it's just few places where preg match happens and saves one disk call :)
