### ISSUE TITLE
URL Of Page

### ISSUE THREAD

**Issue by evilson** [LiveHelperChat/livehelperchat#1872]
First, I feel kinda dumb having to ask. I've used LHC for a long time on many different domains without a problem, its a great product. I just noticed on this domain that while Away from Chat if a customer uses the form to send a message the, "URL of page from which user has send request: " is empty and so is, "Link to chat if any:" Whats more important is the "URL of page from which user has send request:" This way we can track which products the customers are on. I do not mind paying you for the answers as like I said, this is a great product and credit is due where credit is due.

**Comment by remdex** [comment]
I'm not sure what exactly you are asking here, can give steps by steps to reproduce using [demo we have](https://livehelperchat.com/demo-12c.html)

**Comment by evilson** [comment]
Im sorry but the front end will not report this in Live or Demo mode, its not a front end problem. Where applicable is the email message that is sent to the Admins or Chat Personal assigned to receive offline messages. The email message will look similar to the following:


Hello,

User request data:
Name: Web_User
Email: [email@some_host.com](mailto:email@some_host.com)
Phone: 
Department: Support
Country: 
City: 
IP: xxx.xxx.xxx.xxx

Message:
Testing the email message from a specific product page for URL in message.

Additional data, if any:


URL of page from which user has send request:


Link to chat if any:
-

Sincerely,
Live Support Team


The message above is the default message format from LHC backend. I have not crafted that message or altered it. "URL of page from which user has send request" has to be from some backend switch or variable. Maybe its from the java script itself?

**Comment by remdex** [comment]
Update from master branch and all should be fine now :)
