### ISSUE TITLE
Issue with existing or new start chat setting...

### ISSUE THREAD

**Issue by michael-m0** [LiveHelperChat/livehelperchat#1885]
I did a Live Helper Chat update to 4.16 and a new install and the issue applies to both. On a new install, if I create a new start chat setting and save it, that results in the contents of a chat widget being blank when opened/started.  Inspecting the php log file showed an error "Invalid JSON" in the SQL using JSON_CONTAINS [persistent_session.php:833]. Looking at the database, the dep_ids of lh_chat_start_settings is an empty string causing a problem for JSON_CONTAINS. When I go edit the recently created start chat setting and save it, that fixes the issue and looking at the database dep_ids is now an empty JSON array '[]' and the chat widget works as it should. 

Similarly, doing an update from a previous version, prior to version 4.12, adds the dep_ids field to the existing lh_chat_start_settings and they are all an empty string which results in the same SQL error and breaking the chat widget. I can think of various ways to address this issue, but the easy solution for myself, after updating to 4.16, was to run the SQL 
update `lh_chat_start_settings`
	set dep_ids='[]'
where dep_ids='' 

This won't fix when subsequently creating new start chat settings which will have an empty string for dep_ids, but I could run the SQL again or edit the new start chat settings again to have the system set it properly to [].

Hope this makes some sense, helps others, and the community can address the issue appropriately. 

For reference...
Update_284.sql - ALTER TABLE `lh_chat_start_settings` ADD `dep_ids` text NOT NULL, COMMENT='';

Thank you for your excellent hard work.

**Comment by remdex** [comment]
Can you give a hint what MySQL version you are and info from this command
```sql
SELECT @@GLOBAL.`sql_mode`
```

**Comment by michael-m0** [comment]
SELECT @@GLOBAL.`sql_mode` yields...
'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'

MySQL 5.7.40 fresh install

**Comment by remdex** [comment]
Thank you. I think I reproduced so will publish fix on monday.

**Comment by remdex** [comment]
Decided to fix now, so just update from master branch and all should be fine :)

**Comment by michael-m0** [comment]
Cool. Thanks. Glad I found something.
I saw your fix. 
Another fix I had thought of was a new db update which would run the script I used to fix, replacing any empty strings in dep_ids with [] and then alter the table lh_chat_start_settings such that dep_id default value would be [].

**Comment by remdex** [comment]
It's not necessary anymore, as json_extract would never be executed :) also pushed potential another fix :)
