### ISSUE TITLE
Restrictions for access to the admin panel for trusted networks

### ISSUE THREAD

**Issue by cowanmax** [LiveHelperChat/livehelperchat#1891]
I want to make a restrictions on access to the admin panel for trusted networks.
Usually I add private networks to the nginx config in location section file like:
`
allow 127.0.0.1;
allow 10.22.5.0/24;
deny all;
`
but it doesn't work because config has this rewrite rule:
`
rewrite "^(.*)$" "/index.php?$1" last;
`
I can't comment it because it's necessary for rewriting index.php.
But how in that case to me to restrict access?

**Comment by remdex** [comment]
You can restrict it to site_admin

**Comment by remdex** [comment]
E,g
```
<Location "/site_admin/">
    <RequireAny>
        Require ip 10.22.5.0/24
    </RequireAny>
</Location>
```

**Comment by cowanmax** [comment]
I use nginx.
It doesn't works.

**Comment by cowanmax** [comment]
I have created a new location
`
		location ~ ^/site_admin/	{
   		allow 127.0.0.1;
		allow 10.22.5.0/24;
		deny all;
   }
`
That's right, I'm getting a 403 error.

But inside private network - 404 Error.
