### ISSUE TITLE
How can I send automatic e-mails

### ISSUE THREAD

**Issue by Hibrix-net** [LiveHelperChat/livehelperchat#1895]
Hi,

I'm trying to setup the chat notifications in order to automatically send an email based on the default template called "Chat was closed" found in the "E-mail templates" section.

So I edited the department notifications and checked "Inform then chat is closed by operator, only mail notification is send."
I also filled the field from below with my e-mail, etc. But after closing the chats (clicking the "X Close chat") I don't receive anything.

What I'm doing wrong? Is it necessary to setup the SMTP server for that?
I'm able to send the chat transcript without setting the SMTP server though.

BTW: Is it possible to automatically send chat transcripts to user and/or operator after the end of the chat?

Kind regards,

**Comment by remdex** [comment]
Just reply before closing the issue.

1. There is no e-mail to visitor once chat is closed.
2. If you need SMTP or not depends on your hosting.

E-mail is sent in the following order 1. To e-mail template recipient if filled 2. Department e-mail 3. First system operator
