### ISSUE TITLE
Departamento offline

### ISSUE THREAD

**Issue by OliveiraMannuh** [LiveHelperChat/livehelperchat#1920]
O chat formulário exibe que todos os departamentos estão offline, mesmo com usuários logados nos departamentos. Fizemos a limpeza do cache, mas não localizamos o que pode estar ocorrendo para o chat exibir todos os departamentos offline. 
Alguma sugestão de como resolver esse problema?
![Captura de tela de 2023-03-07 16-41-56](https://user-images.githubusercontent.com/80650085/223535450-7a622650-3e98-48a2-81da-1582dffa0070.png)

**Comment by remdex** [comment]
You even did not bother to write in English so I should bother translate and answer?
