### ISSUE TITLE
Problem using {content_2} on "Set subject"

### ISSUE THREAD

**Issue by igazzaneo** [LiveHelperChat/livehelperchat#1935]
We have encountered an issue regarding the use of the {content_2} variable returned by the REST API.

The "Update chat" -> "Set Subject" command interprets the variable as text instead of a placeholder.

**Comment by remdex** [comment]
Issue was solved with commit https://github.com/LiveHelperChat/livehelperchat/commit/7a6688674da0f76d43b900511dbd7195fd73c3d7
