### ISSUE TITLE
Not Working in Android WebView

### ISSUE THREAD

**Issue by QomariSanjaya** [LiveHelperChat/livehelperchat#1955]
I tried this demo using android WebView, but it just show blank page

https://demo.livehelperchat.com/

**Comment by remdex** [comment]
And how it's related to live helper chat itself? :) it's simething you do not lhc :)

**Comment by QomariSanjaya** [comment]
How it can't be related?
This demo https://propanareloadofficial.id/support/ using livehelperchat and its not working on android webview

**Comment by remdex** [comment]
Browser stack loads. I'm not sure what you are doing but it's not live helper chat problem.
![image](https://github.com/LiveHelperChat/livehelperchat/assets/1146085/b27d2e45-2abf-4e60-a3d1-a30699b2cdcd)

**Comment by QomariSanjaya** [comment]
Thank you for checking on this, You are using mobile web browser of course its work. Try using Android WebView, its only showing blank page

**Comment by remdex** [comment]
So debug it. You are developing something on top of lhc so I have nothing to do with it :)
