### ISSUE TITLE
Trigger keywords translation?

### ISSUE THREAD

**Issue by tangmeng09** [LiveHelperChat/livehelperchat#1959]
Hi there,

Is there a way to setup translations for trigger keywords? 
Of course there is a way to put multiple language keywords all together in the match field. It solves most problem, but no all. Some words have quite different meaning in different language. For example, the word *pays* in English means give money, but in French it means country. We have bot answers for *pays*, *Paie* in English and French. If French user type pays, where it means country, the wrong answer triggered.
Setup the translation group for each keyword might be a solution. Or there is another way?

Thanks in advance!

**Comment by remdex** [comment]
You can have just two departments, one for frech and one for english. Once you have that, then you can setup match condition and enter department id for what department it's available. Or go even futher and have bot by language :)
