### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by rondlite** [LiveHelperChat/livehelperchat#1981]
I want to have the replies from a bot to be converted from the markdown it is sent in to HTML.
Is there already an option to process markdown?
If not, where can I hook it in?

**Comment by remdex** [comment]
Please read docs about bbcode. You can just use h 'html' bbcode...

**Comment by remdex** [comment]
https://doc.livehelperchat.com/docs/chat/bbcode

**Comment by rondlite** [comment]
yes, I read that, that is why I am asking. You are saying I should make the bot send me bbcode instead of markdown.

**Comment by remdex** [comment]
It should be either `[html]your custom html[/html]` content or LHC standard markdown.

**Comment by rondlite** [comment]
yeah but `[text](url)`  is not converted which is default  markdown, that is my reason for asking. I know the LHC, HTML and BBCode ways. Is just that OpenAI has tendency to switch back to markdown when you instruct it to use bbcode since that is what it is trained most for.

**Comment by rondlite** [comment]
I made a bot that handles functions from openai ie self made functions (transfer to human, get pricing, get order status, get current date), that I then handle in LHC and send back the results to my embedding vector database, in this chain the hardest thing turns out to keep OpenAI giving me bbcode instead of markdown.
