### ISSUE TITLE
"Set a subject" modal window doesn't scroll

### ISSUE THREAD

**Issue by tobias-silva** [LiveHelperChat/livehelperchat#1983]
We have too many subjects to categorize the chats and the "Set a subject" modal window can't fit all of them (seems limited to 20 items), and doesn't scroll to show the rest.

Is there anything we can change on the code to make it scrollable? Maybe on the templates?
![Anotação 2023-08-10 100547](https://github.com/LiveHelperChat/livehelperchat/assets/115095153/40594c0f-2d76-4fef-a981-0e49692e7cfd)
![Anotação 2023-08-10 100546](https://github.com/LiveHelperChat/livehelperchat/assets/115095153/d0cedea0-5570-4499-9127-4cb17bc6ae8d)

**Comment by remdex** [comment]
Thats a good point I'll improve ui in next few weeks, as away next one :)

**Comment by remdex** [comment]
Seems cannot reproduce. Seems you updated form older version. Please try resave your subject just and see does it appears in the list.
