### ISSUE TITLE
Composer install not possible

### ISSUE THREAD

**Issue by PlamenVasilev** [LiveHelperChat/livehelperchat#1986]
I'm trying to install the latest version on php 7.4 according to the documentation https://doc.livehelperchat.com/docs/install/
when I run `composer install` I get an error
![image](https://github.com/LiveHelperChat/livehelperchat/assets/4059181/eff4f618-0953-4270-b2f6-f18ee6fc53b8)
In
Inside composer.json the minimum version is 7.3, but composer packages require 8.1

**Comment by PlamenVasilev** [comment]
after removing composer.lock it is working which mans that we have a bug and wrong compose.lock commited

**Comment by remdex** [comment]
Sorry, but here all works... use php 8.x

**Comment by PlamenVasilev** [comment]
I can use any supported version I want. 
7.4 is officially supported, so we have a bug with this version.
