### ISSUE TITLE
Users Experiencing Delay in Typing into Chat Window

### ISSUE THREAD

**Issue by mupiel** [LiveHelperChat/livehelperchat#1987]
Local installation of livehelper chat and users (agents) have started experiencing slow responsiveness when typing into chat windows.  No network congestion or high server load.  Is there something we should look at that may cause this?  It is new and has not been occurring at all over the past year the service has been running.

**Comment by remdex** [comment]
You have to update lhc or use different browser untill chrome fix their own stuff...
https://livehelperchat.com/news-5c.html
