### ISSUE TITLE
Stuck back-office interface on Chrome

### ISSUE THREAD

**Issue by andrerinaldi** [LiveHelperChat/livehelperchat#1991]
Hi,

since yesterday we encountered a really slow back-office interface (sometimes it even stucks) on Chrome, while on other browsers it works fast and smooth.

All our LiveHelper Chat instances have the same problem.

The problem is more evident in the home where there are all the department and chat widgets and the cause seems to be the issues that Chrome detects regarding a lot of form elements without id.

Does anyone experience the same problem?

Thanks in advance.

**Comment by remdex** [comment]
Read official page news about chrome bug and how to fix
