### ISSUE TITLE
Voice message length cannot be changed from 30 seconds

### ISSUE THREAD

**Issue by Chluz** [LiveHelperChat/livehelperchat#1993]
Hi, thank you very much for this great tool, and for making this opensource. 
I'm attempting to use the voice message feature. The feature is working fine, except for the fact that I cannot change the max message length. When navigating to the visitor view, the message send container always indicates 30seconds, and a longer message cannot be left. This is despite changing the max messaged length in site_admin/file/configuration

Any ideas what I might be doing wrong ?
Thanks in advance,

**Comment by remdex** [comment]
Confirmed, will be fixed tomorrow.

**Comment by Chluz** [comment]
Wow, thats fast, thank you @remdex!
