### ISSUE TITLE
Widget HTML Online / Offline BUG

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#2003]
This BUG has been tested on the demo of live helper chat.
I discovered this bug on my website and on my LHC install then tested in the demo and confirmed the issue.

BUG description:
Set an online and and offline HTML text (Online text for the online HTML and OFFLINE text for the Offline) will be bugged if the widget status is offline then the widget is updated in the page without user refresh. When the widget is clicked it will show the online form to start a chat but the offline message instead of the online message.

Screenshot:
![immagine](https://github.com/LiveHelperChat/livehelperchat/assets/5006150/c6fa7b2b-042b-4db1-bff9-906d77aba759)

How to reproduce:
- In the widget themes edit the default theme under the custom content tab find the field for "**Custom html above status/profile body in online mode** " and input a text **ONLINE**
- In the widget themes edit the default theme under the custom content tab find the field for "**Custom html above status/profile body in offline mode**  " and input a text **OFFLINE**

Screenshot:
![immagine](https://github.com/LiveHelperChat/livehelperchat/assets/5006150/73146bb5-42dc-430c-8cb1-b71d05235a7c)

- Save the theme

- Now load the user page with the live chat widget, in the case of live helper chat: https://livehelperchat.com
Chat should be online and you should see correctly ONLINE HTML text. In the live helper chat you need open the pop up then open the widget to see that text because the pro active invitation override the text.

![livescreen](https://github.com/LiveHelperChat/livehelperchat/assets/5006150/6e2bc3c5-6186-44fd-9cb2-005ac46bf6bf)

- Now you need put the department and the operator to be offline and wait the widget is converted to the offline status or you can simply refresh the page.

- Now put again the operator and department to online mode and wait the widget is refreshed without the page refresh.

Expected results:

- The status widget when switch from offline to online, when is clicked should show the start chat with the online HTML on top.

Actual results:

- The status widget when is refreshed without page refresh from offline to online still show the Offline text and never show the ONLINE Text so issues with HTML showed.

![livescreen2](https://github.com/LiveHelperChat/livehelperchat/assets/5006150/cf7165f8-6a08-4bfc-a672-add31b3054db)

Other screen to show better the issue:

![livescreen3](https://github.com/LiveHelperChat/livehelperchat/assets/5006150/05afea0e-8fbc-4f73-9e11-41be94b4708e)

So the widget is not correctly refreshed.

**Comment by PeopleInside** [comment]
Just adding some details.
On my personal LHC install I set some HTML code to be showed before the chat.
**This has been setup in theme widget, Text above start chat form fields.**

![immagine](https://github.com/LiveHelperChat/livehelperchat/assets/5006150/2d7d00ac-cc2d-4acf-b308-fc80922c481c)

The good result when the chat is online is:

![Screenshot 2023-10-19 121056](https://github.com/LiveHelperChat/livehelperchat/assets/5006150/2925d5f4-a869-459c-a035-25dd96187c86)


**The HTML show online time and online status**.

**When the widget switch to offline a offline HTML message is correctly showed.**

![Screenshot 2023-10-19 121354](https://github.com/LiveHelperChat/livehelperchat/assets/5006150/ed3052fe-7108-4e03-b697-b6464b315bfb)

**When the widget switch from offline to online the BUG happen:** the offline HTML is not hidden and is added to the online HTML correctly showed.

![Screenshot 2023-10-19 121731](https://github.com/LiveHelperChat/livehelperchat/assets/5006150/cec9f3cb-e00d-4c2f-90a9-2eccbcc827df)

Note: For the online widget, for add the online chat text I use the field Text above start chat form fields in the theme widget.
I tried to remove the HTML from there and put this on the field online HTML but this is showed above the chat logo I have so its a bad visual. I hope with the fix to see just the offline HTML hidden and the Text above start chat form fields still showed when the widget is online :)

**Comment by PeopleInside** [comment]
I hope next coming version of LHC can fix this issue 🎉

**Comment by PeopleInside** [comment]
I hope this issue can be fixed :)

**Comment by PeopleInside** [comment]
Hi, I updated LHC and cleared cache then I used an incognito mode to test this.
When the widget is switched from offline to online the issue still be present the offline text is still showed.
https://app.screencast.com/1T9R9wCoHAfhy

**Comment by remdex** [comment]
Does not happen here :P

**Comment by PeopleInside** [comment]
Do you checked when widget is turned on from offline without refresh the page?
For me also even updating by master and cleaning cache the issue still be present.

**Comment by remdex** [comment]
Contact via skype and proved that all works :D

**Comment by PeopleInside** [comment]
Thanks, resolved.
The issue was present because the online text was setup in the **Text above start chat form fields** in the main theme widget edit page. Resolved by moving the online text to the custom content tab, online field in the theme edit.
