### ISSUE TITLE
google maps not working anymore

### ISSUE THREAD

**Issue by comsyspro** [LiveHelperChat/livehelperchat#2031]
google maps not working anymore
screenshot
![image](https://github.com/LiveHelperChat/livehelperchat/assets/13809377/33eadc74-dd28-4f4b-a613-f422a5d33cb3)

console output
![image](https://github.com/LiveHelperChat/livehelperchat/assets/13809377/50044e32-6732-42dc-a375-932ab198ac70)

how to bring back the google map view of online visitors?

**Comment by remdex** [comment]
Put correct google map key...
