### ISSUE TITLE
Maintenance Mode in fresh install.

### ISSUE THREAD

**Issue by petraamaral** [LiveHelperChat/livehelperchat#2035]
Hi there,
I am installing LHC in my website for the first time and can't get past the maintenance error. My log is linked here:
[default.log](https://github.com/LiveHelperChat/livehelperchat/files/13919758/default.log)

If I opened this in the wrong space, please let me know so I can close it and do it right

**Comment by remdex** [comment]
I don't know what verrsion you have but I suggest to use atleast 8.x php version.
`Call to undefined function php_strip_whitespace()`
