### ISSUE TITLE
#CSChatMessage.msg-one-line

### ISSUE THREAD

**Issue by mysubcult** [LiveHelperChat/livehelperchat#2040]
![image](https://github.com/LiveHelperChat/livehelperchat/assets/10582537/d8ffefe7-9867-4b2c-b07f-102660874dbb)
1. I wrote a few characters
2.  i add only 1 character and only then a new string and 2 characters added
![image](https://github.com/LiveHelperChat/livehelperchat/assets/10582537/46cd8c0f-71d1-4f66-b067-7b299c9f9869)

**Comment by remdex** [comment]
Impossible to understand...
