### ISSUE TITLE
Making bot navigation using only text messages

### ISSUE THREAD

**Issue by mysubcult** [LiveHelperChat/livehelperchat#2044]
https://doc.livehelperchat.com/docs/bot/text-menu-bot
When you create such a menu, the events do not function as intended. For example, I created a menu with two items labeled as 1 and 2. However, I have other triggers that I intended to activate through events, specifically through custom text matching, but unfortunately, it does not work.
The problem, as I understand it, is that events do not work with the "collect custom data" trigger. Is there a way?

**Comment by remdex** [comment]
reporting issues without explicit details is unpolite and wastes times. Please read some dica how properly report an issues...

**Comment by remdex** [comment]
For others:

One collect atribute workflow is trigered other matching rules is ignored untill this flow is canceled and thats exactly as it should work. Nothing to change there. On failure validation you can choose execute other trigger and cancel previous workflow so other matching rules will work again.
