### ISSUE TITLE
Unable to start a chat from the operator dashboard.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#2051]
I tested this on my website then on the demo side.
The issue seems the same, a maintenance error is showed and / or no chat is really started also if is showed.

How to reproduce:

1. Navigate as visitor from browser 1 at the address of https://livehelperchat.com
2. On the second browser log in into the demo operator side and try to start a chat with the visitor. See the screenshot below

![immagine](https://github.com/LiveHelperChat/livehelperchat/assets/5006150/fe4f8473-8423-46fb-ac7b-007bbe14c276)

![immagine](https://github.com/LiveHelperChat/livehelperchat/assets/5006150/410bf078-02aa-460c-91aa-327b88356487)

Now check on visitor side if the message written by the operator reach the user and will not.
Chat are not started, widget are not opened.

**Comment by remdex** [comment]
Sorry, here all works.

**Comment by remdex** [comment]
Reproduced will publish fix in a hour or so.
