### ISSUE TITLE
Issue in the widget template page

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#2052]
Hi, as in the screenshot a small UI issue is present on Widget theme page.

![immagine](https://github.com/LiveHelperChat/livehelperchat/assets/5006150/7694ad0c-f071-4987-85c4-5fc465acbcd8)

Just go on Widget theme page and you should find the issue.
```

Some changes might take effect after you save a widget theme!

 

<script>
var LHC_API = LHC_API||{};
LHC_API = {
  "args": {
    "mode": "widget",
    "lhc_base_url": "//demo.livehelperchat.com/",
    "wheight": 450,
    "wwidth": 350,
    "pheight": 520,
    "pwidth": 500,
    "department": [],
    "leaveamessage": true,
    "check_messages": false,
    "theme": 2
  }
}
</script>
```

**Comment by remdex** [comment]
And what is the issue?

**Comment by PeopleInside** [comment]
Chat preview is no more showed and an error is replacing the preview

![303872081-7694ad0c-f071-4987-85c4-5fc465acbcd8](https://github.com/LiveHelperChat/livehelperchat/assets/5006150/44940678-d533-4efb-b3ed-e8b396968e28)

**Comment by remdex** [comment]
I see everything...
![image](https://github.com/LiveHelperChat/livehelperchat/assets/1146085/ebb3f37e-aea4-4e06-a18b-79ae46bf38c1)
