### ISSUE TITLE
Rest API - How to filter on a date range

### ISSUE THREAD

**Issue by Julienchilhagopian** [LiveHelperChat/livehelperchat#2074]
Hello,

Here is my GET request on the tchat list **https://[domain_name]/restapi/chats**

I was wondering if it was possible du filter on a date range on the URL during the call ? If so how far in the past chats can we go back using this endpoint ? 

Thanks a lot in advance for your help. 

Julien

**Comment by remdex** [comment]
https://api.livehelperchat.com/#/chat/get_restapi_chats

see filter attributes you can have id filter to fetch incremental or just use time stamp

**Comment by Julienchilhagopian** [comment]
Thanks a lot for the work and the help!

Cheers 
Julien
