### ISSUE TITLE
Problems with iframe screenshots

### ISSUE THREAD

**Issue by tts2** [LiveHelperChat/livehelperchat#2076]
![image](https://github.com/LiveHelperChat/livehelperchat/assets/11350647/7f8f0320-21aa-48fb-ac16-2e9189290a50)
Is it possible to use HTML2canvas to change the iframe tag to img tag before taking a screenshot, and then restore it to the iframe tag after the screenshot is saved?
https://blog.csdn.net/weixin_43831691/article/details/110877024

**Comment by remdex** [comment]
You are free todo those changes as `design/defaulttheme/js/html2canvas.min.js` I'm using same library :) you can just override this file if you want also...

**Comment by tts2** [comment]
I would like to try modifying which files should I modify?
