### ISSUE TITLE
Not accepting chat using "Commands" when in "--silent" mode

### ISSUE THREAD

**Issue by mysubcult** [LiveHelperChat/livehelperchat#2078]
When using commands and the Telegram chat module, the chat will not be assigned to an operator if the —silent function is enabled.

**Comment by remdex** [comment]
To little details what exactly you do.

**Comment by mysubcult** [comment]
> To little details what exactly you do.

![image](https://github.com/LiveHelperChat/livehelperchat/assets/10582537/7c8439c2-bb75-4a9c-b1c6-6f2caf2fb4f8)
When a visitor starts a chat, I respond to their first message with any command I have in LiveHelperChat using the --silent mode, and this chat is not accepted. However, without the --silent mode, the chat is accepted.

**Comment by remdex** [comment]
After review it's intended behaviour and won't be fixed.
