### ISSUE TITLE
Publish 4.36v-with-dependencies.tgz package

### ISSUE THREAD

**Issue by jotamartos** [LiveHelperChat/livehelperchat#2084]
Hi team, 

I'm from Bitnami and just found that there is no "with-dependencies" package for the latest version. Our pipelines uses that package to build, test and release the Bitnami LiveHelperChat solution, could you please make that package available under [the releases](https://github.com/LiveHelperChat/livehelperchat/releases/) section?

**Comment by remdex** [comment]
Sure,

Give a hour or so. You can also just do composer install after cloning official repo.

**Comment by remdex** [comment]
Added

**Comment by jotamartos** [comment]
Thanks for working on this so quickly. I just confirmed that the pipeline downloaded the new version successfully. The Bitnami LiveHelperChat solution will be updated soon.
