### ISSUE TITLE
Bot & Departements working hours not work

### ISSUE THREAD

**Issue by andmattia** [LiveHelperChat/livehelperchat#2085]
I've 2 department
- first work from 8 am -> 1 pm
- second work from 8 am -> 5 pm

I create 2 bot (1 perdepartment) I create a workflow to transfert to operator with a button option but I set to send to "Off line hours" action in case when user ask for operator outside the department window.

In this case if one operator that work for both department are online the messagge "Off line hours" not show and workflow try to send chat to operator. 

Is this configuration unsupported or is it a bug?

**Comment by remdex** [comment]
Just setup so operators online hours are ignored and departments always follow their online hours settings. It should solve your problem :)
![image](https://github.com/LiveHelperChat/livehelperchat/assets/1146085/6bc8426e-e05a-4890-8667-0bc1372c531c)

Aso you can use https://doc.livehelperchat.com/docs/bot/check-conditions

And just check var for strictly department online hours
![image](https://github.com/LiveHelperChat/livehelperchat/assets/1146085/f0ee553e-1a1e-49eb-aad5-17b231043e9b)
