### ISSUE TITLE
iOS App no longer showing in App Store

### ISSUE THREAD

**Issue by mar4096** [LiveHelperChat/livehelperchat#2087]
I only noticed this a week or two ago so it could be the case for a while now, but the LiveHelperChat iOS app is no longer available in the United States App Store. Was this intentionally done or did something expire by mistake maybe?

The error message I am seeing is this:
"App Not Available
This app is currently not available in your country or region."

The mobile app is very useful for receiving new chat notifications. 

Thanks in advance.

**Comment by remdex** [comment]
Hi,
It was intentionally. You can have now just TEelegram integration and have all the same functions and more.

https://github.com/LiveHelperChat/telegram?tab=readme-ov-file#using-telegram-as-a-support-client

**Comment by remdex** [comment]
So decided in any case to extend apple membership. Apps hould be available again in few days...

**Comment by mar4096** [comment]
That is great news! Thank you so much for bringing it back.

I think I may also update to the latest version and try out the Telegram integration as well.

Thanks again.
