### ISSUE TITLE
Bug when responding by whatsapp api

### ISSUE THREAD

**Issue by farzadha2** [LiveHelperChat/livehelperchat#2111]
Hi
Currently when from LHC reponds from the message using the whatsapp api, the users sees this

![image](https://github.com/LiveHelperChat/livehelperchat/assets/62571297/386d6095-cc31-453e-9bc4-031e953515b9)

and when the user responds replying from the message from LHC we dont see it

ex:
 user responds 
![image](https://github.com/LiveHelperChat/livehelperchat/assets/62571297/31f8d6fd-06da-4a8f-ae0f-214e2658bba1)

from LHC
see this

![image](https://github.com/LiveHelperChat/livehelperchat/assets/62571297/b1b6fdd1-6a92-4cd0-9a3a-e21f2ce52a2b)

as from LHC we dont know if he responded from the previous chat 

Thanks

**Comment by remdex** [comment]
I'm not sure what exactly you are reporting here. Is it reply to message? if so, those are not supported at the moment, unless you extend :) or go through paid support to add those

**Comment by farzadha2** [comment]
oh gotcha, i thought it was a bug gotcha thanks
