### ISSUE TITLE
live helper widget disappeared

### ISSUE THREAD

**Issue by comsyspro** [LiveHelperChat/livehelperchat#2119]
Since about 2 days ago the live helper widget disappeared. On the website there is also an image carousel done with swiffy, which uses a runtime.js. When removing this, the live helper widget is shown again. So there is an interference somwhere now. But few days ago there was no problem. Probably something has changed? Or how can you best isolate the live helper widget form other javascript code?

**Comment by remdex** [comment]
Lhc has it's own scope so not possible it wiuld interfere in any way. If you think otherwise you can prepare sample with demo code.

**Comment by remdex** [comment]
Not possible :) unless your library somehow interferes web components :)

**Comment by comsyspro** [comment]
I think it does interfere somehow, so I will replace this swiffy runtime.js image carousel. I also tried different order of javascript code placing it on top and bottom but before 2 days this wasn't needed.

**Comment by remdex** [comment]
If you can't prove it with standalone html and official demo. Your report is just invalid...
