### ISSUE TITLE
Improve widget responsivness

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#2122]
My latop screen is l 35 cm x h 19 cm
resolution is 1920 x 1080 but the live chat is showed cut

Could you improve this to made the chat now showed badly?

![Screenshot 2024-07-16 190402](https://github.com/user-attachments/assets/3090f510-e44c-4ac1-a78e-1af3ee3d4188)
![Screenshot 2024-07-16 190411](https://github.com/user-attachments/assets/a336b0c4-21cf-49f6-adc9-36decf8ad68c)

**Comment by remdex** [comment]
I can't as content does not fit :)

**Comment by PeopleInside** [comment]
Umh why the widget never open in a pop up when there is no enough space?
Why if i resize the browser window to be more smaller the widget fit correctly but on the notebook screen is showed cut?

Browser not in full screen:
![immagine](https://github.com/user-attachments/assets/0cebd062-7dd5-4bf3-bc28-c0697cd29188)

Browser at full screen:
![immagine](https://github.com/user-attachments/assets/25b07dc0-adbb-44e0-99ab-939de37dda0e)

There is no way to resize the widget and avoit the blu bar at the top going out of the screen?

![immagine](https://github.com/user-attachments/assets/2d886f99-da9d-4571-b50f-2f6a2d077656)

**Comment by remdex** [comment]
Does it fits if after open you reaize window?

**Comment by PeopleInside** [comment]
https://app.screencast.com/QMteS7Cir71H1

**Comment by PeopleInside** [comment]
Another useful video with some audio ^_^
https://app.screencast.com/3y1vqdo2lRQs8

**Comment by remdex** [comment]
Update and try

**Comment by PeopleInside** [comment]
Thank you, seems resolved. Later I will try with my latop.
Thanks.
I'm closing the issue for now, thanks remdex :) 🧡🦋🌻
