### ISSUE TITLE
Live Helper Chat for Android 2.0 notifications broken

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#2137]
Hi,
This issue is just to track the issue I reported in the discussions here:
https://github.com/orgs/LiveHelperChat/discussions/2136

I setup Telegram for now and will monitor also this when will get resolved also if maybe not soon.

I discovered that new chat are no more notified on the mobile Android app.
Also seems no notification are sent also if the chat is in progress and a new message is sent from the visitor and the app is opened in background.

Could you confirm the same issue?

Even maybe in the browser.
Is something changed in the mew chat notification and assignment to operators?
Some settings I have to change to revert back how was working in the past where I get notification on the browser and on the app on new chats?

Thanks

I uninstalled the app, reinstalled but still not working.
I expect to get a notification as in the past when a new chat is incoming... while no more notifications are sent from the Android app even if all notification settings are turned on on the Android app device settings.

Currently I'm unable to get notified about new chat on my Android device. Notification are no more working as in the past for me on the Android app., I get no notifications.

I have also disabled auto chat assignment as is no more alerting me about new chats, in the past was working. Now with that disabled on a PC desktop I have no issue to be notified on new chats but on Android mobile device still not get any notifications.

**Comment by remdex** [comment]
You can always configure lhc to send notification for example in slack if you are using it. There is documentation even :)

**Comment by shahmirf** [comment]
Thank you for the update regarding the notification library. While third-party platforms like WhatsApp, Facebook, and Slack are good features to have, they are not a replacement for the official Live Helper Chat mobile app, especially for notifications.

Restoring mobile app notifications is crucial not just for us but for all Live Helper Chat users. Ensuring the app remains fully functional is a priority, and updating the notification library would be the best solution to maintain its usability.

Thanks in advance.

**Comment by remdex** [comment]
I'm working on it. First this or next week will be restored notifications themself. Just correct app window won't open at the moment because of FCM library changes, but notifications you will start to receive once I publish an update.

**Comment by remdex** [comment]
This is fixed in 4.48v. Notifications will be send, just because of internal FCM library changes it won't open correct window, but it's better than nothing :)

**Comment by remdex** [comment]
If you just want to try it out without upgrading you can replace this one file

* https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/lib/core/lhmobile/lhmobile.php

And execute this query

* https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/doc/update_db/update_318.sql

**Comment by stethos** [comment]
Just tried it and it works like a charm. Thank you so much!

**Comment by shahmirf** [comment]
Thanks for updating the notification library. After testing on my end, I've noticed a couple of issues:
1-Android: Notifications don't come through when the screen is off, but they appear immediately when the device screen is turned on.
2-iOS: Notifications are coming through, but there is no sound.
I would appreciate it if you could look into these issues when possible. Thanks for your continued efforts.

**Comment by remdex** [comment]
> Thanks for updating the notification library. After testing on my end, I've noticed a couple of issues:
> 
> 1-Android: Notifications don't come through when the screen is off, but they appear immediately when the device screen is turned on.
> 
> 2-iOS: Notifications are coming through, but there is no sound.
> 
> I would appreciate it if you could look into these issues when possible. Thanks for your continued efforts.

Sorry, but for me all works :)

**Comment by remdex** [comment]
As for reference
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

And place where you can play around with parameters
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/lib/core/lhmobile/lhmobile.php#L468

**Comment by shahmirf** [comment]
> > Thanks for updating the notification library. After testing on my end, I've noticed a couple of issues:
> > 1-Android: Notifications don't come through when the screen is off, but they appear immediately when the device screen is turned on.
> > 2-iOS: Notifications are coming through, but there is no sound.
> > I would appreciate it if you could look into these issues when possible. Thanks for your continued efforts.
> 
> Sorry, but for me all works :)

thanks for response,

**Comment by remdex** [comment]
Next week I'll look to add priority args just.

**Comment by remdex** [comment]
Try to update https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/lib/core/lhmobile/lhmobile.php that file and you should have sound.

**Comment by stethos** [comment]
>>>Android: Notifications don't come through when the screen is off
For me that works well on my Samsug with stock Android 14. Maybe the background battery optimisation was not turned off for LHC?

>>>you should have sound.
Sound works for me with the latest file from today.
