### ISSUE TITLE
Unable to extract data from args.chat.additional_data

### ISSUE THREAD

**Issue by andmattia** [LiveHelperChat/livehelperchat#2147]
Hi try to get data from 

"additional_data": "[{\"key\":\"Vat Number\",\"identifier\":\"vat_id\",\"value\":\"12345678901\"},{\"key\":\"Business Name\",\"identifier\":\"business_name\",\"value\":\"aaaaaa\"}]",

but not work in API Call and in Chat Columns

How can extract data from custom_field

**Comment by remdex** [comment]
I don't understand what exactlou you are calliog...

**Comment by andmattia** [comment]
I try to access to a value {{args.chat.additional_data_array.1.value}}. But API rest still get an errro how can I see wich body is send to my API?

**Comment by remdex** [comment]
In default trigger to execute just use this in trigger  as text message to see what was generated and send.
https://doc.livehelperchat.com/docs/bot/rest-api#output-variables-in-triggers

**Comment by remdex** [comment]
Also you can jsut use

`{{lhc.add.vat_id}}` :)

**Comment by andmattia** [comment]
the problem is 
```json
"title":  "PREFIX"{{args.chat.additional_data_array.1.value}},
    "nick": {{args.chat.nick}},
```

the json value is 
```json
"title":  "PREFIX""aaaaaaa",
    "nick": "aaa"
```

and is not a valid JSON

**Comment by remdex** [comment]
Those values are always json encoded themself if you trust value you can append raw_{{.... and they won't be json encoded themself.
