### ISSUE TITLE
Department stats not update

### ISSUE THREAD

**Issue by andmattia** [LiveHelperChat/livehelperchat#2149]
I see my departments stats in dashboard nevere refresh. 

I've a department with 1 active chats and 2 bot chats but if click no chat or bot exists.

Column "Load Statistics" still have n/a(n/a)
![image](https://github.com/user-attachments/assets/53e39f9c-6590-42f2-b937-06f78b6ba53a)

**Comment by remdex** [comment]
You can click and will see what's there. Those stats shows number if you have some limit set per dep or operator

**Comment by andmattia** [comment]
I see the preference but still remain in state not update until someone work on this department. I not possibile to force refresh all departments?

**Comment by remdex** [comment]
Those stats are updated automatically once some action on lhc trigers. It there is no need manually to do anything...

**Comment by remdex** [comment]
Last thing your operators should be explicitly assigned to departments either directly, or via department groups for those stats to work.

**Comment by andmattia** [comment]
thanks for the clarification. I set all limitis and it work for a department where something happen affter I change it. The other departments still remain freezed so if I correct understend what you say the update happen only when an event trigger the calculation on department

**Comment by remdex** [comment]
Correct, there has to come in new chat or old chat being closed :)

**Comment by andmattia** [comment]
Great! Is it possibile to ingreate documentation about it?
