### ISSUE TITLE
Call RestAPI with response from BOT

### ISSUE THREAD

**Issue by andmattia** [LiveHelperChat/livehelperchat#2150]
I descibe the landscape:
- install ChatGpt extension and configure a Assistants
- create a flow about Q/A from gpt
- create a flow to contact human person

New goal:
- [x] give a message from Assistans that trigger a rest api call 
- [x] call RestAPI to get some data from
- [ ] send a message to user that system start search
- [ ] return date to gpt
- [ ] push back the response to user

is it possibile to do it via normal BOT + RestAPI?

**Comment by remdex** [comment]
Yes. if you saw youtube video you see there is typing indicator once user starts chat and there is no hickups. I use php-resque extension to offload request to background worker. You just have in send message trigger check 'send request in the background'. Using nodejs to extension it would feel even faster :)

**Comment by remdex** [comment]
https://github.com/LiveHelperChat/lhc-php-resque

**Comment by andmattia** [comment]
I see a video about gpt but I see is on "Still working" can you add the link? In the manwhile I can try the resque

**Comment by remdex** [comment]
I don't know what link you want. And it's better to write just in discord :)
