### ISSUE TITLE
Departments unavalability on time perid

### ISSUE THREAD

**Issue by andmattia** [LiveHelperChat/livehelperchat#2151]
I try to cover this case:
- support work from 9 to 18 works fine
- support work from 9 to 12 works fine
- support work from 9 to 12 and 13 to 15 - Not Works

I create to separete departments to achive this but my widget are not able to switch from to different department is it possibile to cover this kind of configuration?

**Comment by remdex** [comment]
What exactly you can't achieve?

**Comment by andmattia** [comment]
I want to disable the chat during the lunch break from 1:00 PM to 2:00 PM.

**Comment by remdex** [comment]
All has to work, if it does not means you misconfigure just.

**Comment by andmattia** [comment]
I'm not sure that I understand your reply.

how can I set a lunch break from 1:00 PM to 2:00 PM.

![image](https://github.com/user-attachments/assets/4f818a67-4ea3-489c-8c4f-7fab6093e478)

The only way is create 2 departments but my chat widget support only one

**Comment by remdex** [comment]
The thing is I don't understand your scenario... If you want that at different work hours different department would be assigned you can just use. 

![image](https://github.com/user-attachments/assets/dc151d1f-f925-4c27-b907-8c5085cf7742)

**Comment by andmattia** [comment]
Great! So you suggest to use one department for 1st time range and add a trasfert to second department with second time range.

I try and it works very well.

Thanks

**Comment by remdex** [comment]
In general I still don't know why you would need different department per different work hours 🤔

**Comment by remdex** [comment]
yes, bot trigger check for conditions can check is there anyone logged. Depending on that you can transfer or not to op. Core issue you have was you can't have multiple work hours on same day.

1. does require small bot change to check is anyone online
2. Multiple work hours require some development.


I would have gone just with first flow and let bot check is anyone online :)

I'll think about adding multiple work hours per day :) or you can sponsor it :D

**Comment by remdex** [comment]
Just pushed updated. You can handle all that with one department now.
![image](https://github.com/user-attachments/assets/aebecbcb-6a3f-4553-bb34-b6ebffc1765f)
