### ISSUE TITLE
Incorrect file format is accepted to upload files using endpoint

### ISSUE THREAD

**Issue by arokiasamy-stack** [LiveHelperChat/livehelperchat#2163]
The file upload displays only jpg and png, but it is accepted when we upload the HTML format even at the endpoint level.
![image](https://github.com/user-attachments/assets/7e4a384a-b074-4f61-8b98-50a6b8c6f276)
![image](https://github.com/user-attachments/assets/91b62622-6502-4cc6-8314-7bfc3fa491d4)

Similarly, the HTML format files are accepted in the below URLs

Incoming webhooks
user import
user account
Theme import 
genericbot/listrestapi

**Comment by remdex** [comment]
You can choose any file. But we process only jpg/png files. I don't see a problem with that. If you want to improve UX you are free to do that :)
