### ISSUE TITLE
PHP error, new installation of LHC

### ISSUE THREAD

**Issue by payfrit** [LiveHelperChat/livehelperchat#2167]
Hi there, i'm attempting to install LHC, getting the following error:

`PHP Fatal error:  Uncaught Error: Failed opening required 'lib/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/lhc.payfrit.com/lhc_web/index.php:30\nStack trace:\n#0 {main}\n  thrown in /var/www/lhc.payfrit.com/lhc_web/index.php on line 30`

what am i doing wrong...?

-John

**Comment by remdex** [comment]
Not following install instructions. Install composer dependencies

**Comment by payfrit** [comment]
I'm using php 8.3.14, installation instructions state "Minimum PHP 8.2. If you will want older php version support you will have to install composer dependencies yourself."

**Comment by payfrit** [comment]
after installing composer and downloading the version that includes all composer dependencies, it is working now.

thank you for the assistance.

**Comment by remdex** [comment]
I just added this section for quick install guide

git cloning is always preferrable way as it includes most recent fixes.

https://github.com/LiveHelperChat/livehelperchat?tab=readme-ov-file#quick-install-guide
