### ISSUE TITLE
Accept Terms and Privacy Checkbox in online/offline form

### ISSUE THREAD

**Issue by salsero72** [LiveHelperChat/livehelperchat#238]
Hi and thanks first of all.

In Italy every online form which requests a user personal data (including email) must have a checkbox that says "I accept your terms & conditions for handling my personal data"  (something like "I state that I accept your privacy policy") And must be compulsory for the user. Form cannot be sent if checkbox is unchecked.

Lacking this checkbox, or letting the user ignore it and send the form withou checking it, the site owner can incurr in 5 zeros fee (up to 120.000 euros).

I'd appreciate if would be implemented. Or at least point me to the right place where to code for it.

The checkbox sould appear and behave as follows:

APPEARENCE:

[   ]  I accept my personal data will be handled according to <a href="domain/privacy_policy_or_whatever.html">our terms and to the Law XYZ</a>

And a part of the text should be linkable to a popup page which explains how his/her data will be handled.

BEHAVIOUR:

If the user does not accept by checking the box, he/she will not be able to send the form (open the chat session)

Thanks.
Nicola.

**Comment by etik61** [comment]
Hi,
I'm really impressed by lhc and it could be a valuable tool for our website.
One minor question regarding GDPR conformity: To make the above mentioned fix really perfect, no cookies should be set and no information related to the visitor be stored or be visible in the dashboard, before checking the box.
As we will be using lhc for commercial purposes, we don't mind to pay for support or to make an adequate donation.
Thanks,
Eckhard

**Comment by remdex** [comment]
> Hi,
> I'm really impressed by lhc and it could be a valuable tool for our website.
> One minor question regarding GDPR conformity: To make the above mentioned fix really perfect, no cookies should be set and no information related to the visitor be stored or be visible in the dashboard, before checking the box.
> As we will be using lhc for commercial purposes, we don't mind to pay for support or to make an adequate donation.
> Thanks,
> Eckhard

For that you will have to write me directly in discord or chat. Nick remdex in skype or just join discord channel https://discord.gg/YsZXQVh
