### ISSUE TITLE
Pass along prefilled attributes for invisible fields in start chat widget

### ISSUE THREAD

**Issue by syastrov** [LiveHelperChat/livehelperchat#274]
When starting the chat widget, I want to prefill some values (the username and email).
I also want to hide them from the start chat form (so the user can't change them).
If I make those fields invisible in the Start Chat settings, the prefill values are not passed along in the form. Right now, the only way to fix this is to set the fields as visible and modify the templates to pass along the value using hidden form fields.

Like this [in design/customtheme/tpl/lhchat/chatwidget.tpl.php]:

```
<input type="hidden" class="inputfield" name="Username" value="<?php echo htmlspecialchars($input_data->username);?>" />
```

I suggest there should be some check if a field is set to invisible and there is some data in the prefilled fields and then pass it along as a hidden field.

```
LHCChatOptions.attr_prefill = new Array();
LHCChatOptions.attr_prefill.push({'name':'username','value':'John Smith'});
LHCChatOptions.attr_prefill.push({'name':'email','value':'john@example.com'});
```

I suggest something like this in design/defaulttheme/tpl/lhchat/chatwidget.tpl.php
(startchat.tpl.php also):

```
    <?php if (isset($start_data_fields['name_visible_in_page_widget']) && $start_data_fields['name_visible_in_page_widget'] == true) : ?>
    <div class="columns small-6 end">
        <label><?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('chat/startchat','Name');?><?php if (isset($start_data_fields['name_require_option']) && $start_data_fields['name_require_option'] == 'required') : $
        <input type="text" class="inputfield" name="Username" value="<?php echo htmlspecialchars($input_data->username);?>" />
    </div>
    <?php elseif (isset($input_data->username)) : ?>
    <input type="hidden" name="Username" value="<?php echo htmlspecialchars($input_data->username);?>" />
    <?php endif; ?>

```

Still, the validation in lib/core/lhchat/lhchatvalidator.php seems to be not accepting the information if those fields are invisible.

Hope you can come up with a solution for this. Otherwise, I will continue to modify the templates (which works fine for me).

Great software and best regards.

**Comment by agencia-feats** [comment]
Alguem conseguiu resolver?
