### ISSUE TITLE
Idea: Live Helper Chat for iOS and Android Platforms!

### ISSUE THREAD

**Issue by jdisho** [LiveHelperChat/livehelperchat#462]
It will be more comfortable for users and operators.

**Comment by alberto234** [comment]
Hello @Joanii,

Are you still a user of LiveHelperChat? If so we have an app (Wurrd) for the operator. You can check out the progress we have made so far by catching up on the forum.
https://forum.livehelperchat.com/viewtopic.php?id=2132
