### ISSUE TITLE
Feature Request: Survey

### ISSUE THREAD

**Issue by parkerj** [LiveHelperChat/livehelperchat#483]
Would it be possible to add option for survey in the future. When you are finished chatting with someone, it would be great if they could fill out a survey afterwards with regards to the help they just received from an online operator.

**Comment by Joeboyc2** [comment]
@remdex I think this should be linked to #545 too

**Comment by remdex** [comment]
https://livehelperchat.com/new-version-2.35v-survey-at-the-end-of-chat-430a.html
