### ISSUE TITLE
Feature request: move position of the user preview text between the two field

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#532]
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/4662205/2666308e-552e-11e4-96ca-315e1a1cca4b.png)

I want ask if in the future version the text operator can see before user tipe enter can be moved between chat field and field where operator write the message.. this because some times user take long time for write a sentence and send and from my operator web console i'm unable to read the last user message because the text who show what user is tiping are over.

Can you move in the blank space between the two field?
Now the text is in the chat field can you move under but always on top of the field where operator write the message?

Sorry for my bad english.
Is not easy to explain but i hope you understand.

![immagine1](https://cloud.githubusercontent.com/assets/5006150/4662326/bb39da48-552f-11e4-878f-8e6f2c61f148.png)

**Comment by PeopleInside** [comment]
Hi Rem, a request.
Can you move the algin of the preview text at the left?

This because if user write a lot operator are not able to resize his message box where write message to the user and some time it's necessary resize and must wait user stop to write.

What do you think, is a problem to move on the left?

**Comment by remdex** [comment]
can you send screenshot how you image it?

**Comment by PeopleInside** [comment]
Sure, thanks for let me know. Here the picture:
![screen](https://cloud.githubusercontent.com/assets/5006150/5695180/fcc48400-9994-11e4-8125-62bf9004c4e9.png)

**Comment by danielc1234** [comment]
Actually, it'd be better if you could move it out of that box completely. Maybe outside the box, below or between. Reason being, when a customer is typing a question, typically I am already starting to type the reply and that text seems to always get in the way.
