### ISSUE TITLE
Feature Request: Operator Status Screen

### ISSUE THREAD

**Issue by Joeboyc2** [LiveHelperChat/livehelperchat#533]
Hi Rem,

Please can we have the onlineoperators tab updated to show operators in groups of Online & Offline.

Currently all operators show in the list if they are logged in to the system, regardless of their Online/Offline state

Can you also add some sort of indication that shows if any of the online operators are currently chatting to customers ie, have chats assigned to them.

thanks

**Comment by remdex** [comment]
Should be satisfied with new dashboard we have now. It should allow to see more clear way of current state of support across different departments etc.

**Comment by PeopleInside** [comment]
@remdex new interface is nice but why there isn't anymore the button for open the chat in the tab and not only in pop up window? I'M using a lot the old chat interface for this reason.. in the new there is no possibility to open the chat in tab not new pop up window :)

**Comment by remdex** [comment]
Just click title and it will be opened in tab :)
