### ISSUE TITLE
Request: Make red field if is wrong or incomplete.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#536]
Hi,
will be great if you can make the thext near the check box red if error message are printed up or color the check box.. make user more clear he have to acept terms and condictions. This is userfull if for example i have the live chat in italian and english person try to start chat so don't understand the error on top.

Can you look if you can color or put a simbol near the terms if they are unchecked?
Thanks.

**Comment by PeopleInside** [comment]
![immagine1](https://cloud.githubusercontent.com/assets/5006150/5788659/702306ca-9e44-11e4-9ea7-32d343a7d523.png)

**Comment by Joeboyc2** [comment]
Hi PeopleInside,

I have created this functionality on my custom version if you would like me to share?

The highlighting only works on the default fields however so if you have any custom fields as detailed here: https://livehelperchat.com/pre-filling-form-fields-and-adding-custom-fields-140a.html
 It may need looking at further.

@remdex would you like to look at my code and include it in the master version? It only a basic bit of code so possibly could be done in a better way but it wirks for me

**Comment by remdex** [comment]
Just try to create a pull requwst and i'll review

On Saturday, July 4, 2015, Joeboyc2 <notifications@github.com> wrote:

> Hi PeopleInside,
>
> I have created this functionality on my custom version if you would like
> me to share?
>
> The highlighting only works on the default fields however so if you have
> any custom fields as detailed here:
> https://livehelperchat.com/pre-filling-form-fields-and-adding-custom-fields-140a.html
> It may need looking at further.
>
> @remdex <https://github.com/remdex> would you like to look at my code and
> include it in the master version? It only a basic bit of code so possibly
> could be done in a better way but it wirks for me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LiveHelperChat/livehelperchat/issues/536#issuecomment-118498679>
> .
>


-- 
Sincerely,
Remigijus Kiminas

**Comment by Joeboyc2** [comment]
Ok cool I'll do that on Monday.

Thank you

**Comment by PeopleInside** [comment]
Thanks @Joeboyc2 and @remdex happy to hear that news.

**Comment by Joeboyc2** [comment]
Hi @remdex & @PeopleInside 

i have now created a pull request for all the files i have amended

Joe

**Comment by Joeboyc2** [comment]
Sorry @peopleinside, @remdex has rejected my pull request so these changes will not be integrated in to the master branch

**Comment by timetrex** [comment]
@Joeboyc2 I hope @remdex reconsiders and offers you some feedback on your push request. This seems like an important improvement that shouldn't be dismissed so hastily.

**Comment by ipso** [comment]
@Joeboyc2 I hope @remdex reconsiders and offers you some feedback on your push request. This seems like an important improvement that shouldn't be dismissed so hastily.

**Comment by PeopleInside** [comment]
Hi,
don't worry the topic is already opened:
https://github.com/LiveHelperChat/livehelperchat/issues/536

work in progress.. as @remdex can improve this will be closed or updated. Maybe @remdex want insert better, safe and more compact code.

The topic is not closed, just the pull request.

**Comment by Joeboyc2** [comment]
HI @PeopleInside, @ipso 

Good News, @remdex has said he will take a look at the code himselfs and add it to the mast branch for an update he'll push out soon :)
