### ISSUE TITLE
New Feature : Pre & Post Customer Survey 

### ISSUE THREAD

**Issue by supportreq** [LiveHelperChat/livehelperchat#545]
The post-chat survey will usually ask about customer satisfaction.

**Comment by remdex** [comment]
Example for future reference during implementation
http://paulabrown.net/rating-stars-5-217.gif

**Comment by PeopleInside** [comment]
Nice :) I Like IT :)

**Comment by thomas1216** [comment]
Looks Pretty Good, A+

**Comment by remdex** [comment]
Implemented and released in new version. https://livehelperchat.com/new-version-2.35v-survey-at-the-end-of-chat-430a.html
