### ISSUE TITLE
Issues on visitor status in operator console (on-line / off-line)

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#584]
If operator edit Information like name or email visitor never go offline when thwy close browser. Issue confirmed by LHC Demo
How to reproduce:

1. Srtart a chat as visitor and acept it form operator side.
2. Edit user Name info and save.
3. Try to change page example settings page on LHC and return after to other page like user online where you can have visitor chat conversation opened.
3. Close visitor side browser.

User still be online.. Caution, maybe not happen the first time, read the message above this one.

Is very strange error.
One time happend and one time no.

If when you close the visitor browser user is offline try to reopen so wait user is again online in the operator console, after close again visitor browser, user still be online.

I'm using Firefox 34.0.5 for client and Chrome for operator console.

I see on my chat some times chat are closed and user still result online in chat list, closed chat. This i can't reproduce in the demo.

I can reproduce some issue for user status. Please try to have a look in what i had says.
Thanks.

Is not an issue from recent update, is still present from different last relases but difficoult to understand and reproduce for record here.

**Comment by PeopleInside** [comment]
Is very strange error.
One time happend and one time no.

If when you close the visitor browser user is offline try to reopen so wait user is again online in the operator console, after close again visitor browser, user still be online.

I'm using Firefox 34.0.5 for client and Chrome for operator console.

I see on my chat some times chat are closed and user still result online in chat list, closed chat. This i can't reproduce in the demo.

I can reproduce some issue for user status. Please try to have a look in what i had says.
Thanks.

**Comment by PeopleInside** [comment]
Also if you put in the chat long link as https://scontent-a-mxp.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/s720x720/1234577_72gg62402624452393_123130941_n.jpg?oh=fd8280f545428a207cf1a9f5600d7f&oe=54FF0160 if user close browser for operator still be online

**Comment by remdex** [comment]
Sorry, but I have nothing do there like all works. Yes perhaps it does not catch all the time status. Because user just closes a browser without enough time for request to send. And you can also check user status in Browsing information tab.
