### ISSUE TITLE
Hidden department are showed when...

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#585]
I have two or more department.

I want generate Embed code for different domain from where the LHC is installed and only for one hidden deparment.

LHC is installed on LHC.ext
I have two deparment

Default (visible)
Otherweb (Hidden)

I want generate Embed code for Otherweb so i select only Otherweb department and i put Otherweb.ext (the different domain) on "For what domain you are generating embed code?"

Now i paste the Embed code in the site Otherweb.ext and i see correctly the widget, correctly i can't select any deparment and i don't see any other department.

Error is when support is offline and user miss to compile mandatory field and press leave message. Errors are printed but with error upstairs to the leave message, now a menu is showed where user can select other depatment and see all departments.

**Comment by PeopleInside** [comment]
Is not the hidden department is showed but other visible department.
http://screencast.com/t/RJ7o3XlFmB6Q

**Comment by remdex** [comment]
Sorry, but cannot reproduce on my local environment, all works here.. You can write me in skype and try to setup testing stuff on my enviroment.

**Comment by PeopleInside** [comment]
Yes, maybe was my LHC whit some problems. Now i have done a clean install on my website. I hope go better. Thanks and sorry remdex. Nice to see your solid chat :-)
Thanks.
