### ISSUE TITLE
Reopen closed chat as new? Otherwise it will be reopened as active.

### ISSUE THREAD

**Issue by shankartechnik** [LiveHelperChat/livehelperchat#589]
Reopen closed chat as new? Otherwise it will be reopened as active. is not shown in my fresh install

**Comment by remdex** [comment]
Good catch, seems it's missing in back office, although in database record exists. Will be fixed in the evening

**Comment by shankartechnik** [comment]
Please leave a word after doing it so i will spend my time in testing

**Comment by shankartechnik** [comment]
also in page mode even if i enable it to 1 in database the reopen don not works considers as new chat

**Comment by shankartechnik** [comment]
any possibility for sending chat id in javascript page embed code for live help

**Comment by remdex** [comment]
Please try now. Even then you changed in database you had to clear a cache :)

**Comment by shankartechnik** [comment]
thanks remdex
