### ISSUE TITLE
any possibility for sending chat id in javascript page embed code for live help

### ISSUE THREAD

**Issue by shankartechnik** [LiveHelperChat/livehelperchat#590]
is there any possibility to send the chat id like operator id in the link to reload the chat

**Comment by remdex** [comment]
No, and won't be because of security.

**Comment by shankartechnik** [comment]
Any idea to make this happen

**Comment by shankartechnik** [comment]
i m working on it

**Comment by remdex** [comment]
Don't forget to share :)

On 13 January 2015 at 13:38, shankartechnik <notifications@github.com>
wrote:

> i m working on it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LiveHelperChat/livehelperchat/issues/590#issuecomment-69732149>
> .
>



-- 
Sincerely,
Remigijus Kiminas
