### ISSUE TITLE
Move the preview text

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#594]
https://github.com/LiveHelperChat/livehelperchat/issues/532
Hi rem,
as for reminder as it talke more time than the prevision and also other user seems to be interested just a reminder to put on entanglement (if you alow) for move the text preview position.
https://github.com/LiveHelperChat/livehelperchat/issues/532
Thanks

**Comment by remdex** [comment]
Yes, thanks fixing co-browsing and IE nonsense at the moment :)

**Comment by PeopleInside** [comment]
Hi rem,
thanks for put this on enhancement. I can understand your message maybe you are refering to other issue not opened and not talked by me :D i think.

This topic is for move the label who show the text tiped in real time by the visitor on the left side or in the middle of the two input box.
Thank you.

**Comment by PeopleInside** [comment]
Hi,
i hope this can be implemented soon.. every time i start a chat with visitor and they write a lot I'm unable to resize my input field where i write my message. I need to resize because some times i write long reply to the visitor so i need to read before send.

The preview text is a very good think but should be moved on the left side or in the center between the two field or in a position without create issue :-)

Actually if user is typing and preview text is active operator are unable to resize his input field.

Thanks

**Comment by PeopleInside** [comment]
How you implemented? How it works now? Thanks

**Comment by remdex** [comment]
Now text is presented between messages and field where to enter a message.

**Comment by PeopleInside** [comment]
Hi rem,
thanks for let me know.. i have tested your demo and i SEE SOME ERRORS.

(tested with Firefox and also with Chrome)

1. seems when operator write the message visitor not see "operator is typing"
2. seems operator are able to see user when change the page (the url are correctly showed in the middle of the box) but operator are not able to see what user write
3. after operator write a message the space between two input field is hidden

Please check.
http://screencast.com/t/6a7x1Ksm

**Comment by remdex** [comment]
Sorry,
But you should have cleared a cache before testing this!!!
On demo all works. So i won't fix anything.

**Comment by PeopleInside** [comment]
You mean of my browser?
I do that test also in anonimose mode but see the same issue.
Well if you say it work i belive in you.

Maybe some days and i can be able to see work also for me :) now in the demo also with a fresh clean browser i see the same issue.. maybe is only I.
Thanks rem.

**Comment by remdex** [comment]
Hi,

I found the issue, it because nodejs extension overrides this part also. I will update Nodejs extension and it should be fixed.

**Comment by PeopleInside** [comment]
Ok thanks rem
1 point for me :-)

**Comment by remdex** [comment]
Yes, this time :)

**Comment by remdex** [comment]
Ok, you can see now if you want, but should be rock solid now :)

**Comment by PeopleInside** [comment]
Oh.. I'M sorry but i think you have to give me another point.

Is better now but well not completly. I found an error.
If the operator write a sentence with the space seems after the space the operator is typing disappear.

You can try to digit this
Hi how are you today?
on operator side and you will be able to see after Hi the "operator is typing" is hide.

OPS is not the space.. maybe if you write also digit some letters and stop to write then you start again "operator is typing" is not well showed.

Tested with Clen browser.

Please confirm the same.

**Comment by remdex** [comment]
Sorry, this time definitely no issue. Operator is typing hides time after some time. There is timeout for that.

**Comment by PeopleInside** [comment]
Understood, is also in my website this issue.

Please what this short demostration of the issue:
http://screencast.com/t/zCySjtNH

As you can see I'm writing a message as operator and user are not well allerted.

**Comment by remdex** [comment]
Sorry I won't change anything at the moment. At the moment there just message could be shown for longer, but it worked all the time like this.

**Comment by PeopleInside** [comment]
Ok maybe "operator is typing" should be showed intermitting if the field are being edited.. when the field not receve input the text can disapear.

As you can see here
http://screencast.com/t/zCySjtNH
after my first message I'M writing a long message to the user until they is not allerted I'm writing.

Maybe this can be implemented in the future. Is userfull because maybe some time write a message to the user require time.. user are not well allerted of operator tying.
I think so, yes.. is not only an issue of this last update was already present.

Thanks
