### ISSUE TITLE
Suggesting enhancemetns for closed chat reports

### ISSUE THREAD

**Issue by praveenvall** [LiveHelperChat/livehelperchat#597]
We have been using chat tool efficiently. However, we have a suggestion to enhance the Reporting feature for closed chats.

It is wonderful if we can enhance the closed chats by adding name,email and subject while closing the chats.
In order to achieve this, we believe we need to be asked to enter these fields manually before closing the chat.
so that it will be easier to have a list of keywords in the subject lines, searching appropriate user history by name and email.

Thank you.

**Comment by remdex** [comment]
Hi,

Well few things.
1. As for forcing to enter e-mail and subject. Won't be done.
2. As for keyword, you an use remarks field.
3. As for extending search options there is already Nick and e-mail or you want something else?

**Comment by praveenvall** [comment]
Does Nick and email search from the chat transcript?
Because if the user is coming on chat without entering any details, how can it be handled?

**Comment by remdex** [comment]
These items can be added by operator

On Friday, January 16, 2015, Praveen <notifications@github.com> wrote:

> Does Nick and email search from the chat transcript?
> Because if the user is coming on chat without entering any details, how
> can it be handled?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LiveHelperChat/livehelperchat/issues/597#issuecomment-70259765>
> .
>


-- 
Sincerely,
Remigijus Kiminas
