### ISSUE TITLE
Request: Please improve the alert to the visitor "operator is typing"

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#601]
Please see with attention this video and look at the issue:
http://screencast.com/t/ZScqkmaMq

More than one time there is issue on alert user operator is typing a message.
I discovered this issue only by testing because you can't see in operator side. Please consider to fix in some way this, "Operator is typing" is very important think who make the chat work well and make visitor wait the message of the operator.

This function are not working well, please look at the video:
http://screencast.com/t/ZScqkmaMq

I hope this can be improved.
https://github.com/LiveHelperChat/livehelperchat/issues/594

**Comment by remdex** [comment]
Sorry, won't be changing anything. I did few changes moments ago, but related to nodejs. Nothing else won't be changed.

**Comment by PeopleInside** [comment]
Hi rem,
i respect you.
Did you see the video and how are working now? This video i have made now.

Why you don't think to fix, implement and make work well this? O.o I don't understand. 
All Live chat who i know has good function who alert the user in real time if operator is typing, are stopped to write and alert also when operator start again to write with the message "operator is typing"..

Had you see the video? What do you think?

Sorry and thanks..
Just understand why this can be fixxed, implemented.

**Comment by remdex** [comment]
Ok, so second point for you today :) fixed in related commit which will appear just in a moment.

**Comment by PeopleInside** [comment]
Yeahhhhhhh I'M very very happy for this. I will check soon. Thanks! Love you ^_^ yeahhh
