### ISSUE TITLE
Invalid captcha code, please enable Javascript!

### ISSUE THREAD

**Issue by In2Deep** [LiveHelperChat/livehelperchat#61]
When using "Ask a question" tab in the FAQ,  I get 

"Invalid captcha code, please enable Javascript!"

Using this page for testing.  3/4 of the way down.  Where it's embedded in the page,  the "Invalid captcha code, please enable Javascript!" is evident when a user asks a question.  

However,  if you use the popout on the left,  it sends fine without the error.

On the production site,  the pop out will not send the message and gives the same error.  There is no captcha visible and since I have the same sort of issue on 2 different servers,  making assumption that it is a bug and not something I have done.  

In common they both have Bootstrap installed.

Thanks!

**Comment by zumbani** [comment]
All you need to do is go to settings in the admin section and click on CLEAN CACHE. Boom
