### ISSUE TITLE
Online User Web Group by IP

### ISSUE THREAD

**Issue by danelsan** [LiveHelperChat/livehelperchat#612]
I see that into table online user can't group by IP.
I see more line with some ip.
Can be group by ip and filter the 
bot firm?

Thanks

**Comment by remdex** [comment]
In what case group by IP would be usefull? Like in most cases all ip are different

**Comment by danelsan** [comment]
In my site more users visit more page and
the rows into user online is more for 1 ip.
For example I visit e page and after go to other page of same site.
The online user register 2 rows with same ip.

If same ip is also same user, but him see 2 pages.

Other example in google analitics is 4 user and into user online are 30 (maybe for bots).

Thanks

**Comment by remdex** [comment]
In that case you are trying to fix here consequences not the reason. The reason you see separate record for each pageview is that you just misconfigured some part of application. You will have to remember what you have changed.

Also while generating embed code make sure that you have entered good domain without http. 

So in any case it's just configuration issue and duplicatte record is just the result of it :)

**Comment by danelsan** [comment]
Thanks for reply. Now I setting the domain into embedeed code.
I'll see if  more page with same ip come again.

**Comment by danelsan** [comment]
Sorry, but IP is duplicated again.

**Comment by remdex** [comment]
Sorry, but without personal look and your site and logins to LHC back office i do not know where is the problem. You will have to figure out yourself where you misconfigured it.

Also this could help you.
https://livehelperchat.com/my-users-looses-chat-session-then-they-navigate-through-the-site-duplicate-online-users-records-377a.html
