### ISSUE TITLE
Delete button operators

### ISSUE THREAD

**Issue by marcelloinfoweb** [LiveHelperChat/livehelperchat#614]
It would be possible to remove the option button to delete the historic chat operators?
This is to keep track case customer claims or maintain a historic full.

**Comment by remdex** [comment]
Could you paste screenshot about what button you are talking?

**Comment by marcelloinfoweb** [comment]
I refer to the image below. It would be better if no operator to see that button, only administrators.

Thanks for the attention

![Delete button operators](http://i62.tinypic.com/2ue4jmg.jpg)

**Comment by remdex** [comment]
In general if you remove from operators role possibility to delete chats this button still will be visible but they will get alert that they cannot delete a chat.

For permission to take effect operators will have to logout and login again.

**Comment by remdex** [comment]
Added permissions to check to interface also. So permissions will represents actual operator permissions.

**Comment by marcelloinfoweb** [comment]
Man, much thanks! :+1:
