### ISSUE TITLE
BUG 2.2 - Now waiting message are showed to the user before the timout time

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#617]
After update the chat i have issue on all chat i receve.
Infact the wait message are sended to the user without respect the time out of 300 i have set up in 

    Home
    System configuration
    Auto responder
    Edit

Please fix it.

HOW to reproduce:

Se in autoreponder a waiting message and set it will be showed after 300 now try to start a chat as visitor and you will see time is no respect, message is showed after some seconds.

**Comment by remdex** [comment]
You did not write what responder does not work is it autoresponder or
proactive auoresponder?

On Thursday, February 5, 2015, PeopleInside <notifications@github.com>
wrote:

> After update the chat i have issue on all chat i receve.
> Infact the wait message are sended to the user without respect the time
> out of 300 i have set up in
>
> Home
> System configuration
> Auto responder
> Edit
>
> Please fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LiveHelperChat/livehelperchat/issues/617>.
>


-- 
Sincerely,
Remigijus Kiminas

**Comment by PeopleInside** [comment]
Sorry,
you have added feature now autoresponder message can repeat.. well but timer not work animore.

User start a chat and after few seconds see the waiting message.. in my case Sorry we are late"

I had write here
Home
System configuration
Auto responder
Edit

Is the autoresponder and i hope proactive works.. be carefull when you add new feautures asked to the user, this may cause BUG in new version :)

**Comment by remdex** [comment]
Fixed, good catch :)

**Comment by PeopleInside** [comment]
Yes, not happy to know new version improvment can cause bug who aren't before.
I see after update my chat the first chat started on my website start to have issue.

Thanks for fixxing.
