### ISSUE TITLE
[SMTP] How to use port 587 and STARTTLS?

### ISSUE THREAD

**Issue by brylie** [LiveHelperChat/livehelperchat#618]
We are trying to configure Mailgun as our SMTP provider, but keep getting the following error:

```
SMTP Error: Could not authenticate.
```

Mailgun recommends using port 587 instead of port 25:
http://blog.mailgun.com/25-465-587-what-port-should-i-use/

How can we configure LiveHelperChat to use STARTTLS and port 587?

**Comment by remdex** [comment]
https://livehelperchat.com/how-to-use-google-smtp-in-live-helper-chat-204a.html
