### ISSUE TITLE
Chattabs dissappear when clicking info button (i)

### ISSUE THREAD

**Issue by brylie** [LiveHelperChat/livehelperchat#619]
When viewing the chat window (/site_admin/chat/chattabs/) and clicking the Information button, a modal dialogue appears. After this dialogue appears, the tabs (Pending Confirm, Active Chats, Unread Messages) are no longer functional.
![chattabs-before](https://cloud.githubusercontent.com/assets/17307/6078595/2d1e6bac-ae03-11e4-9617-44f825f7ee69.jpeg)
![chattabs-after](https://cloud.githubusercontent.com/assets/17307/6078600/32052778-ae03-11e4-8595-690040b79f8a.jpeg)

I am using Firefox 35.0.1 on Ubuntu Linux.

**Comment by remdex** [comment]
Please update to recent version and try then. 
Or just try same thing on demo.livehelperchat.com

**Comment by brylie** [comment]
We are using the hosted service. Our domain name is samposoftware.livehelperchat.com

**Comment by remdex** [comment]
I see, i will be performing updates during the weekend so will see then.

But would be good thing if you could test it on demo.livehelperchat.com first does it still happens there

**Comment by brylie** [comment]
Yes, it happens on the demo site as well. Specifically, the chattabs popup window (/site_admin/chat/chattabs/).

Also on the demo site, the dashboard tabs briefly disappear when clicking on the info icon (person icon), but are rendered again almost immediately.

**Comment by remdex** [comment]
Ok i see, i'll try to investigate.

**Comment by brylie** [comment]
On smaller viewports, where the interface uses collapsible areas instead of tabs, the interface stays in-tact. I.e. all sections remain visible after the modal dialogue appears.

**Comment by sagisman** [comment]
Hello,
i saw same problem but littke different. when open site1 admin panel https://mydomain.com/site1/site_admin/chat/chattabs/ and i have second account by same hosting site2. https://mydomain.com/site2/site_admin/chat/chattabs/ 
if site1 open site2 chatbox adress, site1 can see site2 chatbox information. 
i hope you understand my english sad
So, if i use 1 hosting and have a lot of lhc install adress... they can see each other's pages. Do you have a recommendation for this?
thanks
