### ISSUE TITLE
Feature request: Sequential autoresponder or one more message in autoresponder.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#621]
Hi Rem,
I have this situation on my Live Chat:
- NOW: *
  User start a chat and receve the waiting message from the Autoresponder "Welcome, an operator will be avaiable in 5 minutes please wait..."
  After 300 seconds (5 minutes) is printed to the user the other message 
  who can be repeated: "Sorry we are late keep waiting you will be able to leave message in 5 minutes if no one can reply in live chat"

Good but i want set a repeat message in the middle of this two messages. Example after 100 secons i would like to repeat a message for 5 times "You request is important, please keep waiting we will be avaiable to you soon" because is not correct say after 100 seconds to the user after other 5 minutes can leave a message - is not correct information.

I had tried to add other Autoresponder and set for same department but maybe only one Autoresponder can be assigned to a department.

Will be good have three message and not only two:

The first for the welcome and wait message, the second for keep user waitinf every 100 seconds and after 300 seconds print to the user "Sorry we are late, you will be able to leave a message in 5 minutes"

I want use repeat function for tell to the user to keep waiting every 100 seconds but also i want send a message with "Sorry we are late" after 5 minutes.

Do you understand?
Is good you have implemented repeat function of the second message of the autoresponder, will be also userfull to can have one message more avaiable.

FIRST autoresponder message (immediate) give the welcome to the user and ask to wait

SECOND message (100 seconds for example) ask to the user to keep waiting "Your request is important, please hold on"

the THIRD message after (300 second in my case) says to the user SORRY for the delay and can inform user they will be shorlty able to leave a message if no one reply to the chat

So great user experience. Now is not possibile because only two message are avaiable on the Autoresponder.

I hope you can understand and also think this can be a great good idea as the previous of other user to insert repeat message.
Thanks - Let me know if you have questions.
##

**Comment by remdex** [comment]
Well, as for understanding I understood everything. But as for realisation you will have to wait and I ques very long :)

**Comment by PeopleInside** [comment]
This seems to has been implemented, i am closing it.
