### ISSUE TITLE
Problems with core en_EN language strings

### ISSUE THREAD

**Issue by RCheesley** [LiveHelperChat/livehelperchat#625]
Hello,

As a native English speaker (en_GB) I would like to help improve the quality of the English strings, however I can't seem to find an en_EN translation folder/files.

If you can point me at the correct location I'll submit a PR.

Thanks :)

**Comment by remdex** [comment]
English text, has to be modified in templates themself. I suggest to fork a bootstrap branch at the moment. Like migration almost done.

**Comment by RCheesley** [comment]
Would it not be easier to have a language constant and have en_EN as a language? Just a thought, makes it easier for future updates etc.

**Comment by remdex** [comment]
For me no. Because once templates are changed I have a script which gathers all the translations from application and generates default translation file, and this file is a feed for transifex to automate translations.

**Comment by RCheesley** [comment]
OK could you advise me which files need to be modified and I'll work on it when I can.

**Comment by remdex** [comment]
Basically all templates are there
https://github.com/LiveHelperChat/livehelperchat/tree/master/lhc_web/design/defaulttheme/tpl

Just i suggest, to wait till tomorrow I will publish bootstrap 3 powered back office.

**Comment by remdex** [comment]
Ok, so now it's safe to fork and make translations. Basically the easiest way, just find required text using github search, edit template and create pull request I will take care of everything else.
