### ISSUE TITLE
New Feature : Teams & activate/deactive team

### ISSUE THREAD

**Issue by supportreq** [LiveHelperChat/livehelperchat#626]
Hi,
A new feature can be introduced called as teams, where in each agent along with a department is assigned to a team. 

Teams can be used to define their working hours. Also a manager can make an entire team active or inactive for live chat. Consider a scenario where there are two teams who are available. One team takes phone calls and another responds to online chat. With this the manager can manually allow a specific team to be active or make both team active..

**Comment by remdex** [comment]
In general perhaps, possible but there is a lot of tricky questions, like workflow round robing assigments, online status remakes etc, and i ques without financial support this one definitely won't be done for a very long time.

**Comment by remdex** [comment]
There will be possibility to disable enable groups in new version. But nothing more.
