### ISSUE TITLE
Auto Transfer Chat to another operator in case of no reply after x min

### ISSUE THREAD

**Issue by supportreq** [LiveHelperChat/livehelperchat#628]
Is it possible to auto transfer the chat to another online operator in case there is no reply from the operator currently chatting after x mins?

This feature can be designed per department..

**Comment by remdex** [comment]
DON'T post these questions here. Post them in forum
https://livehelperchat.com/how-to-setup-round-robin-automatic-chats-assignment-workflow-322a.html
