### ISSUE TITLE
Statistics add user wait time

### ISSUE THREAD

**Issue by supportreq** [LiveHelperChat/livehelperchat#629]
In Statistics if we add another parameter, user wait time until an operator accepted the chat?

**Comment by remdex** [comment]
I'm not sure what exactly it should show? what would be coordinates values?
X, Y?

**Comment by supportreq** [comment]
X coordinate -> avg. wait time for chat acceptance
Y coordinate - > user / department / all

duration can be set for a day, month or manually defined..

**Comment by remdex** [comment]
Ok, understood, but you will have to wait. A lot :)
