### ISSUE TITLE
Issue maybe bug with logo when there are multi template.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#630]
My LHC is installed on the domain 1 and use theme 1

I have created a theme 2 and i have put the embed code in other website domain2
Now follow this step and you will se the bug/issue.
Please see this video:
http://screencast.com/t/XAAa0SNc1g
You can see in theme 2 when an error message is printed the logo change with other themplate theme 1.

**Comment by PeopleInside** [comment]
It also happen if you change language of the chat on top right. Theme 2 logo lost and is replaced with logo of Theme 1.

**Comment by remdex** [comment]
Thanks for report, I will look into it
