### ISSUE TITLE
Request: Possibility to resume chat in widget if chat are started from pop up.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#631]
Hi Rem,
in version 2.23 i see if user open widget and from widget open pop up than start a chat and after decide to resume chat in widget this is no possibile.

You can resume chat in widget only if the chat are started from widget.

Can be nice add the possibility to resume the chat in widget in case user has started to chat from the pop up.

**Comment by remdex** [comment]
Implemented.
https://github.com/LiveHelperChat/livehelperchat/commit/97488861b350f52b8c7b79b50c90ebd12c347bda

Just for you for really good bug reports :)

**Comment by PeopleInside** [comment]
Very sweet remdex.
Thank you, you make me happy and make me smile with your kind and funny message. Thanks, life is better in this way.

Thank you!
I'm happy to can improve your fantastic and best live chat :-) also i think is a good implementation this one. Is a small thinks but when user not loose chat and see he can resume chat from pop up to widget can be a great experience. Not all chat works in that way. 

Many thanks!

**Comment by PeopleInside** [comment]
Sorry if i comment again but before update my LHC again i want test this function. I have done now in your demo with clean web browser but i can't see it work.

My step:
1. Click on the live chat widget https://livehelperchat.com/
2. Opened a pop up chat
3. Started chat
4. Until chat are pending for operator i click on the widget for resume chat in widget and no Resume working button are.
5. Also if operator accept the chat in pop up no resume button on the widget.

I'M making something wrong?

**Comment by remdex** [comment]
Resume icon to widget is at the top right corner
![image](https://cloud.githubusercontent.com/assets/1146085/6284213/7b0970b6-b8f6-11e4-9a64-86f367f2206a.png)

**Comment by PeopleInside** [comment]
Oh nice. Thanks.
I was tring opening again widget :) Thanks.
