### ISSUE TITLE
Chrome extension not working anymore

### ISSUE THREAD

**Issue by Ennosuke** [LiveHelperChat/livehelperchat#633]
Since the last updates, sadly I don't know which, the Chrome extension is not working anymore. It just displays a white (blank) page.

**Comment by remdex** [comment]
Sorry, chrome extension has nothing to do with it. Please follow upgrade instructions and if still does not work see https://livehelperchat.com/during-some-action-app-returns-white-screen-what-to-do-215a.html

**Comment by Ennosuke** [comment]
I followed the upgrade instructions and I've done as suggested in the article. You can find the output here: https://paste.ud.de/pcxncits2 As I said it only appears in the chrome extension.

**Comment by remdex** [comment]
Sorry, but I really have no idea, as long chrome extension works with our demo there is nothing to look. for me. Try to clear cache from back office. Just click link Clear cache. If it's still does not work, there is commercial support if needed.

**Comment by remdex** [comment]
I'm not sure is it relevant. But perhaps replacing this file and clearing cache from back office would help. https://github.com/LiveHelperChat/livehelperchat/commit/692b56492082830de1dce657bf8852fc28230998

**Comment by remdex** [comment]
https://github.com/LiveHelperChat/livehelperchat/commit/0521432170d358ef81a158ce4dc2eb5b9908734c
This commit will fix your issue. Finally someone properly reported the issue so it was fixed now.
