### ISSUE TITLE
Position queue

### ISSUE THREAD

**Issue by marcelloinfoweb** [LiveHelperChat/livehelperchat#635]
Is it possible to put on the screen the visitor's position in the queue?
So, lock the text field or even withdrawing and leaving only the numbering of the position.

I believe it is a very important function and essential for a chat.

Even so, his work is amazing and extremely helpful.

**Comment by remdex** [comment]
Here is reason why it won't be fixed. At the moment all lists shows chat request from Newest to oldest. So your operators has to start accepting chats from list bottom and move to the top. At the top is always newest request at the bottom oldest.

**Comment by marcelloinfoweb** [comment]
Maybe I wasn't clear, I'm sorry, I'll try to explain better.

In the customer chat, appear his position.

Screen not attending.


== Portuguese
Acho que não fui claro, me desculpe, vou tentar explicar melhor.

No chat do cliente, aparecer a posição dele.

Não na tela do atendente.

**Comment by remdex** [comment]
Sorry, I still do not get it...

**Comment by marcelloinfoweb** [comment]
Show the client's position in the queue of the chat.

For example: I go on a website and it has the chat link and when I click and fill the data appear the chat screen with my position in relation to all who are asking for help in the same Department.

== Portuguese
mostrar a posição do cliente na fila do chat.

Por exemplo: Eu entro em um site e nele tem o link do chat e quando eu clicar e preencher os dados aparecer a tela do chat com a minha posição em relação a todos que estão pedindo ajuda no esmo departamento.

**Comment by remdex** [comment]
Oh, this one. Now I get it.
Just will have to wait for some time, not sure just for how long :)

**Comment by marcelloinfoweb** [comment]
Very good, thank you!!.

I will follow.

**Comment by PeopleInside** [comment]
Can be an idea to add chat ID number. Like your position is 4 and chat ID 39 :-) so if user want can refer to the chat number in future. Great, just an idea.

**Comment by devoger** [comment]
Yes i vote for this one to...
For instance, each agents can handle only 3 visitors at a time... the queue number is useful.. the user can have an option to wait like "You are 5 visitor waiting on queue." or he can leave a message.
This lessen customer frustrations.

**Comment by marcelloinfoweb** [comment]
Waiting anxious !!! ;)

**Comment by remdex** [comment]
Implemented. Basically text like "You are number 3 in the queue. Please wait..." will be shown if there is more than 1 pending user otherwise old text will be shown.

**Comment by PeopleInside** [comment]
WoW.. Great! Great!
Thanks rem!

**Comment by marcelloinfoweb** [comment]
Very good thank you !!!
Now I will wait for the latest version and update.
Again, thank you ...

**Comment by PeopleInside** [comment]
Now just wait the sentence queue can be available for translation

**Comment by marcelloinfoweb** [comment]
I make available to translate.
