### ISSUE TITLE
MacOS client

### ISSUE THREAD

**Issue by marcelocecin** [LiveHelperChat/livehelperchat#636]
application does not open in OS X 10.10.3

**Comment by remdex** [comment]
As no one is willing to prepare Mac bundle for LHC the only way to get it working is compile bundle yourself. And i do not have a Mac to do that.
https://livehelperchat.com/article/view/67

**Comment by remdex** [comment]
Try this mpw
https://github.com/LiveHelperChat/desktop-compiled/releases/download/1.3/lhc.dmg

**Comment by marcelocecin** [comment]
now it open but occurs an error that not saving the settings
![captura de tela 2015-02-24 as 21 22 53](https://cloud.githubusercontent.com/assets/2955762/6362541/f7a1a66a-bc6c-11e4-9f9d-cecf0b628a9c.png)

**Comment by remdex** [comment]
Can you try in this location just create a file 
settings.xml with content
https://github.com/LiveHelperChat/desktop/blob/master/settings.xml

**Comment by remdex** [comment]
In any case i try to update client that it would create that file by itself.

**Comment by marcelocecin** [comment]
can u explain me how do u compile https://github.com/LiveHelperChat/desktop to OS X ?

**Comment by remdex** [comment]
https://livehelperchat.com/article/view/67

**Comment by marcelocecin** [comment]
i prefer to use http://fluidapp.com/developer/
thank you

**Comment by remdex** [comment]
OK,
You can try this recompiled package now
https://github.com/LiveHelperChat/desktop-compiled/releases/download/1.4/lhc.1.dmg
