### ISSUE TITLE
Permission for Configuring Pro Active Chat

### ISSUE THREAD

**Issue by supportreq** [LiveHelperChat/livehelperchat#637]
Hi,
I am creating a new role with limited access to System Configuration. I am unable to find the policy through using which I can provide limited access to the user for configuring pro active chat configuration..
Please advice..

Thank You

**Comment by remdex** [comment]
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/design/defaulttheme/tpl/lhsystem/configuration.tpl.php#L171
to be able to do that they have also have to have permission to use
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/design/defaulttheme/tpl/lhsystem/configuration.tpl.php#L169

**Comment by supportreq** [comment]
Thanks!
