### ISSUE TITLE
Issue: Is possibile to start a chat from an offline department

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#638]
Hi Rem,
sorry but i find an issue resolved in the past but still present today.
Please see the video at the link above.

User can start a chat from an offline department.

The issue is: Is possibile to start a chat from an offline department using Firefox and closing the offline suggestion not with the cancel button but with the X at the top right.
Please fix it. Thanks.
I have not tested with other browser only Firefox.

Video demostration:

===>>  http://screencast.com/t/y5cNK4QRv

Thanks
I hope this will be definitively resolved. 
**Maybe the X must do the same of the cancel button who works fine**
PS: In Italy in most place the Upload is very poor like 0.50 MB / 1 MB and i take long time to upload a video demostration like this 90 MB but is the best way to show you better :D

**Comment by remdex** [comment]
ok, i will see :)

**Comment by PeopleInside** [comment]
Thanks for fixxing. I will Update in just few moment. Thanks.
