### ISSUE TITLE
Idea/Request: Disable URL or change URL of the logo in pop up from the Widget Theme

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#639]
Suppose i have the live chat installed on mydomain.ext and i want create template and widget for website2.ext

I'm able to set logo for website2.ext but URL in the pop up logo will be of the mydomain.ext
so maybe add the possibility to change that URL in tmplate and maybe choose to not have link in the logo.

So when a template is created or edited should be two options, first for set link of the logo the second for disable logo link (no link) no clicable logo in the pop up.

**Comment by remdex** [comment]
I see understood. Basically option in themes to change logo link and perhaps in future footer ones.

**Comment by remdex** [comment]
Few changes in this commit
1. Widget copyright url will be used also for chat popup
2. Widget theme will be used as company title, so set it proper
3. And some other related stuff.

**Comment by PeopleInside** [comment]
Hi rem,
thanks for that fix.

I really appreciate your fix and work but let me tell you i think is not a good idea make the template name same as footer or maybe you should correct Name field with Name and footer name.

The better way is add other Field with Footer name so user can have template 1 followed by name 2 and etc and this are not visibile to the user.

Is better to can have a name of template not visible to the user because is tecnical name userfull for manage and recognize better the template.

This is only a suggestion, my think and not a request to please fix it. Just a way to say.. maybe is not a good idea remove the hidden template name and make it public.

Finish i wan't disturbe you more.
