### ISSUE TITLE
Idea/Request: move button for better experience

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#640]
Hi,

http://s5.postimg.org/3kgbwachj/image.jpg

if you can move the showed button to the right when an operator close all chat with users 
it will able to return to the main screen 
http://s5.postimg.org/ey2v7hn03/image.png who are now first icon so far from opened chat button so when all chat buttons are closed operator is not redirected to the main icon.

 Othervise i see all time i goes on 
http://s5.postimg.org/3n07j4g4z/image.png
operator list and all time i have manually to go on main icon for see online user.

I mean when i accept chat using
append icon and i don't open a pop up when i close all chat is better goes on online user list (main icon) not the (online operator icon) who is the nearest icon after close all chat.
Do you understand?

Sorry if i posted image link but hithub upload not work for me today, i don't know why.

**Comment by remdex** [comment]
Well it's was implemented some time ago and in configuration you can adjust order of these tabs,, just dig in chat configuration section and you will find the option for that.

**Comment by PeopleInside** [comment]
I'M very sorry. Finded now, sorry. Many function. Thanks.
