### ISSUE TITLE
chrome extension is full white

### ISSUE THREAD

**Issue by centoasa** [LiveHelperChat/livehelperchat#641]
Box on chrome extension is full white, and the parrot have P

**Comment by remdex** [comment]
The only thing i can suggest just read again
https://livehelperchat.com/article/view/63

Most likely you just did not cleared a cache or did not updated database, or just old some plugin i'm not sure from what version you are updating. In general you can try to disable all custom plugins and themes and try clear cache and then to see

**Comment by centoasa** [comment]
LHC full update! cache cleared many times after update
no other extensions abled on my chrome
maybe my chrome is 64bit?

**Comment by remdex** [comment]
No that has nothing to do with it.
https://livehelperchat.com/during-some-action-app-returns-white-screen-what-to-do-215a.html
You will have to follow this article instruction to get an error. Because
No error = no way to help

**Comment by centoasa** [comment]
0: erLhcoreClassDesign::designtpl - lhchat/chattabschrome.tpl.php	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/lhchat/chattabschrome.tpl.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/lhchat/chattabschrome.tpl.php
0: erLhcoreClassDesign::designtpl - lhchat/chattabs.tpl.php	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/lhchat/chattabs.tpl.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/lhchat/chattabs.tpl.php
0: erLhcoreClassDesign::designtpl - lhchat/user_settings.tpl.php	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/lhchat/user_settings.tpl.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/lhchat/user_settings.tpl.php
0: erLhcoreClassDesign::designtpl - lhchat/lists/angular_pending_list.tpl.php	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/lhchat/lists/angular_pending_list.tpl.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/lhchat/lists/angular_pending_list.tpl.php
0: erLhcoreClassDesign::design - images/flags	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/images/flags
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/images/flags
0: erLhcoreClassDesign::designtpl - lhchat/lists/angular_active_list.tpl.php	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/lhchat/lists/angular_active_list.tpl.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/lhchat/lists/angular_active_list.tpl.php
0: erLhcoreClassDesign::design - images/flags	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/images/flags
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/images/flags
0: erLhcoreClassDesign::designtpl - lhchat/lists/angular_unread_list.tpl.php	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/lhchat/lists/angular_unread_list.tpl.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/lhchat/lists/angular_unread_list.tpl.php
0: erLhcoreClassDesign::design - images/flags	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/images/flags
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/images/flags
0: erLhcoreClassDesign::designtpl - lhchat/part/opened_chats_js.tpl.php	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/lhchat/part/opened_chats_js.tpl.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/lhchat/part/opened_chats_js.tpl.php
0: erLhcoreClassDesign::designtpl - pagelayouts/chattabschrome.php	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/pagelayouts/chattabschrome.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/pagelayouts/chattabschrome.php
0: erLhcoreClassDesign::designtpl - pagelayouts/parts/page_head.tpl.php	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/pagelayouts/parts/page_head.tpl.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/pagelayouts/parts/page_head.tpl.php
0: erLhcoreClassDesign::design - images/favicon.ico	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/images/favicon.ico
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/images/favicon.ico
0: erLhcoreClassDesign::design - images/favicon.ico	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/images/favicon.ico
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/images/favicon.ico
0: erLhcoreClassDesign::designtpl - pagelayouts/parts/copyright_meta.tpl.php	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/pagelayouts/parts/copyright_meta.tpl.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/pagelayouts/parts/copyright_meta.tpl.php
0: erLhcoreClassDesign::designtpl - pagelayouts/parts/page_head_css.tpl.php	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/pagelayouts/parts/page_head_css.tpl.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/pagelayouts/parts/page_head_css.tpl.php
0: erLhcoreClassDesign::design - fonts/glyphicons-halflings-regular.eot	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/fonts/glyphicons-halflings-regular.eot
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/fonts/glyphicons-halflings-regular.eot
0: erLhcoreClassDesign::design - fonts/glyphicons-halflings-regular.eot	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/fonts/glyphicons-halflings-regular.eot
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/fonts/glyphicons-halflings-regular.eot
0: erLhcoreClassDesign::design - fonts/glyphicons-halflings-regular.woff2	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/fonts/glyphicons-halflings-regular.woff2
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/fonts/glyphicons-halflings-regular.woff2
0: erLhcoreClassDesign::design - fonts/glyphicons-halflings-regular.woff	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/fonts/glyphicons-halflings-regular.woff
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/fonts/glyphicons-halflings-regular.woff
0: erLhcoreClassDesign::design - fonts/glyphicons-halflings-regular.ttf	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/fonts/glyphicons-halflings-regular.ttf
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/fonts/glyphicons-halflings-regular.ttf
0: shop::default	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
0: erLhcoreClassDesign::design - images/icons/mic.gif	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/images/icons/mic.gif
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/images/icons/mic.gif
0: erLhcoreClassDesign::design - images/general/loading.gif	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/images/general/loading.gif
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/images/general/loading.gif
0: erLhcoreClassDesign::design - images/fonts/fontello.eot	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/images/fonts/fontello.eot
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/images/fonts/fontello.eot
0: erLhcoreClassDesign::design - images/fonts/fontello.eot	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/images/fonts/fontello.eot
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/images/fonts/fontello.eot
0: erLhcoreClassDesign::design - images/fonts/fontello.woff	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/images/fonts/fontello.woff
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/images/fonts/fontello.woff
0: erLhcoreClassDesign::design - images/fonts/fontello.ttf	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/images/fonts/fontello.ttf
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/images/fonts/fontello.ttf
0: erLhcoreClassDesign::design - images/fonts/fontello.svg	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/images/fonts/fontello.svg
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/images/fonts/fontello.svg
0: shop::default	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/vendor/bootstrap/css/bootstrap.min.css
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/vendor/bootstrap/css/bootstrap.min.css
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/vendor/bootstrap/css/bootstrap-theme.min.css
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/vendor/bootstrap/css/bootstrap-theme.min.css
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/css/app.css
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/css/app.css
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/css/override.css
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/css/fontello.css
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/css/fontello.css
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/css/datepicker.css
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/css/datepicker.css
0: shop::default	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/pagelayouts/parts/page_head_css_extension_multiinclude.tpl.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/pagelayouts/parts/page_head_css_extension_multiinclude.tpl.php
0: erLhcoreClassDesign::designtpl - pagelayouts/parts/page_head_js.tpl.php	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/pagelayouts/parts/page_head_js.tpl.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/pagelayouts/parts/page_head_js.tpl.php
0: erLhcoreClassDesign::design - sound	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/sound
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/sound
0: erLhcoreClassDesign::design - js/lh/dist	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/js/lh/dist
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/js/lh/dist
0: erLhcoreClassDesign::design - images/notification	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/images/notification
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/images/notification
0: shop::default	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/vendor/jquery/jquery.min.js
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/vendor/jquery/jquery.min.js
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/vendor/bootstrap/js/bootstrap.min.js
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/vendor/bootstrap/js/bootstrap.min.js
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/js/modernizr.js
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/js/modernizr.js
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/js/lh.min.js
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/js/lh.min.js
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/js/jquery.hotkeys-0.7.9.min.js
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/js/jquery.hotkeys-0.7.9.min.js
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/js/fileupload/jquery.fileupload.min.js
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/js/fileupload/jquery.fileupload.min.js
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/js/jquery.zoom.min.js
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/js/jquery.zoom.min.js
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/js/datepicker.min.js
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/js/datepicker.min.js
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/js/lhc.speak.min.js
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/js/lhc.speak.min.js
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/js/lh/dist/common.js
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/js/lh/dist/common.js
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/js/lh/dist/bundle.js
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/js/lh/dist/bundle.js
0: shop::default	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/tpl/pagelayouts/parts/page_head_js_extension_multiinclude.tpl.php
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/tpl/pagelayouts/parts/page_head_js_extension_multiinclude.tpl.php
0: shop::default	2015-02-27 08:58:07 +0100
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/js/app.js
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/js/app.js
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/js/angular.min.js
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/js/angular.min.js
Not found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/customtheme/js/angular.lhc.js
Found IN - /var/www/vhosts/100asa.it/httpdocs/lhc/design/defaulttheme/js/angular.lhc.js

**Comment by remdex** [comment]
Sorry, it's not an error. It's debug output. Skype me so i could see personally.
