### ISSUE TITLE
when nodejs support is enabled, transferred chats do not appear on "target" operator

### ISSUE THREAD

**Issue by jyrkiput** [LiveHelperChat/livehelperchat#642]
When the nodejs support is used and the chat is transferred, the chat does not appear on the screen of the "target" operator. The chat appears when the page is refreshed. It also seems to appear when the connection to livehelperchat php application gets timed out by web server (in Apache, "Timeout" parameter).

 When nodejs is not running and chat is transferred, it appears in few seconds.

**Comment by remdex** [comment]
For this to work, Redis has to be running as I remember.
Like there is no other way to inform logged operators.

**Comment by jyrkiput** [comment]
Redis is running, forgot to mention that. When I'm monitoring on redis, I'm seeing commands from both of livehelperchat and nodejs, for example following

    1425043436.413708 [0 172.17.0.9:52544] "info"
    1425043436.415202 [0 172.17.0.9:52544] "subscribe" "admin_room_0"
    1425043443.097980 [0 172.17.0.18:39137] "GET" "cachekey_cache_keysite_version"

where .9 is the host where the nodejs is running and .18 is host where livehelperchat is running. Also the web clients seem to be executing connections to nodejs properly, and I can see the "is typing now.." text when operator is typing text.

**Comment by remdex** [comment]
Sorry, then really don't know. Do you have enabled https://github.com/LiveHelperChat/NodeJS-Helper/blob/master/nodejshelper/design/nodejshelpertheme/tpl/pagelayouts/parts/nodejshelper_config.tpl.php#L8 this line to true?
I will try to look myself does it really does not work.

**Comment by remdex** [comment]
Hi found a bug, here is related commit
https://github.com/LiveHelperChat/NodeJS-Helper/commit/7ba7c67c49671946db502c6f9a69fb310b6eed86
