### ISSUE TITLE
Setting chatbox name in embed code

### ISSUE THREAD

**Issue by uteschj** [LiveHelperChat/livehelperchat#643]
Would like to be able to set the chatbox's name when auto creating a chatbox with embed or widget code.

'<b>Thisismynewchatbox</b>' being the new name of the chatbox.

```JS
var LHCChatboxOptions = {hashchatbox:'<?php echo sha1('change_me'.sha1('change_me'.'article_id_1'))?>',identifier:'article_id_1',status_text:'Thisismynewchatbox'};
```

**Comment by remdex** [comment]
https://livehelperchat.com/new-version-2.25v-408a.html
