### ISSUE TITLE
Chrome extension doens't work anymore

### ISSUE THREAD

**Issue by ronschi** [LiveHelperChat/livehelperchat#646]
After upgrading to your bootstrap powered version the chrome extension doesn't work anymore.

http://susepaste.org/16331991

**Comment by remdex** [comment]
https://github.com/LiveHelperChat/livehelperchat/issues/641

**Comment by remdex** [comment]
as for quick fix just find app.js file and delete it and clear cache. In any case it was fixed few days ago.
