### ISSUE TITLE
problem in database connection step!

### ISSUE THREAD

**Issue by aladaghlou** [LiveHelperChat/livehelperchat#647]
I successful runed the Live Helper chat in localhost.
But did not succeed in the online host instaling.
Error in database information step:
Cannot login with provided logins. Returned message: SQLSTATE[28000] [1045] Access denied for user 'xxxxx'@'localhost' (using password: YES)

I am sure the information correctly.
My panel is plesk.

**Comment by remdex** [comment]
Sorry, it's your server issue not LHC closing as invalid.

**Comment by aladaghlou** [comment]
My problem is solved. Thank you
