### ISSUE TITLE
Allow HTML in canned messages

### ISSUE THREAD

**Issue by RCheesley** [LiveHelperChat/livehelperchat#648]
We would like to include HTML in canned messages - for example when asking people to give feedback (we use Hively) we would like to include the feedback snippets.

**Comment by PeopleInside** [comment]
Here must be managed without loose security :-)

**Comment by RCheesley** [comment]
Well of course, you wouldn't necessarily want to allow scripts etc.  Basic HTML - bold, hyperlinks etc should be OK though?  Or have a type of message which is an ending message with a snippet? Or an integration? Just seemed easier to allow HTML in those messages.

**Comment by remdex** [comment]
In canned messages you actually can use bbcode so it should be sufficient, anything else won't be done.

**Comment by remdex** [comment]
As for reference of supported bbcode tags
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/lib/core/lhbbcode/lhbbcode.php

**Comment by RCheesley** [comment]
Could you maybe implement a BBCode editor to make this easier for people
who are not familiar?  Or a link to some guidance? Just a thought, as
there's nothing to indicate that BBCode can be used, as far as I can see.

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 3 March 2015 at 13:13, Remigijus Kiminas <notifications@github.com>
wrote:

> As for reference of supported bbcode tags
>
> https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/lib/core/lhbbcode/lhbbcode.php
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/LiveHelperChat/livehelperchat/issues/648#issuecomment-76942661>
> .
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by remdex** [comment]
Yes just need improve ux

On Tuesday, March 3, 2015, Ruth Cheesley <notifications@github.com> wrote:

> Could you maybe implement a BBCode editor to make this easier for people
> who are not familiar? Or a link to some guidance? Just a thought, as
> there's nothing to indicate that BBCode can be used, as far as I can see.
>
> *Ruth Cheesley*
> *CEO & Co-Founder*
>
> Virya Group Limited
>
> P: +44 (0) 1473 852130
> E: ruth.cheesley@viryagroup.com
> <javascript:_e(%7B%7D,'cvml','ruth.cheesley@viryagroup.com');>
> M: +44 (0) 7920 404314
>
> On 3 March 2015 at 13:13, Remigijus Kiminas <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > As for reference of supported bbcode tags
> >
> >
> https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/lib/core/lhbbcode/lhbbcode.php
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/LiveHelperChat/livehelperchat/issues/648#issuecomment-76942661
> >
> > .
> >
>
> --
> Be like me, be Carbon free - don't print this and save a tree
> IMPORTANT: The contents of this email and any attachments are
> confidential.
> They are intended for the named recipient(s) only. If you have received
> this email by mistake, please notify the sender immediately and do not
> disclose the contents to anyone or make copies thereof.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LiveHelperChat/livehelperchat/issues/648#issuecomment-76976714>
> .
>


-- 
Sincerely,
Remigijus Kiminas

**Comment by remdex** [comment]
And pull request improving UX is always welcome :)
