### ISSUE TITLE
Issue on Restore Password, email is sent with wrong account and not using correct SMTP account.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#650]
Hi rem,
this issue is very dangerous.

Today i had forgotten my password and when i try to recover it i see the confirmation message on the page but on top right error SMTP and no mail was delivered.
http://s5.postimg.org/ma558y75i/Immagine_senza_nome.jpg

After, I had remebered the password and when i was log in i have tested my SMTP settings and work fine, all test passed.

So i tested in your demo and password email was sent correctly but i can see why i have this issue, because password recovery are sended from address apache@domain.com so this is the issue!

My SMTP not accept to send email from myaccount@domain.com to another fake account like apache@mydomain.com.

If i have setup myaccount@domain.com reset password must be sent from myaccount@domain.com or maybe some user like me are not able to receve recovery password.

I hope you can understand and fix.

**Comment by remdex** [comment]
Sorry, there is nothing to fix. Because in code everything is setup properly.

**Comment by remdex** [comment]
See code. You just misconfigured something in your LHC nothing to add.
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/modules/lhuser/forgotpassword.php

**Comment by PeopleInside** [comment]
There is a way to understand why i receve the message SMTP Error: Data not accepted. when i ask to receve reset password?
If i do the mail test and SMTP test i receve correctly the email.

There is a way i can read what happen for understand better?
I don't have edited nothing in LHC

**Comment by remdex** [comment]
Try in setting.ini.php set proper value for this
'site', 'site_admin_email'

**Comment by PeopleInside** [comment]
Seems to be a problem of Relaying.
I'M using TLS on outmail, i use zoho.

Sorry rem but i can't understand well the code, i'm not pretty good in that.
If email are sent from the correct address, maybe i think can be somthing like.. i don't know, are email sended with TLS as i do in the email test under email settings?

I can't explein why I'M able to send email to visitor from LHC, send email from test of email settings and not send reset password email because i see error: **SMTP Error: Data not accepted.**

**Comment by remdex** [comment]
Just in
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/settings/settings.ini.default.php#L8

set same email from which you are sending mails

**Comment by PeopleInside** [comment]
Yes, if i edit the line 8 on the file settings.ini.php in row 8 now works if i set the same email as in the SMTP.

Why i have to mannually put it?
I have missed some settings on LHC or maybe what?

Reset password email should not work as when i send test email who works?
Is normal i have to know to set the same email address editing a file in LHC?

Problem is solved if i put mannualy in that file the same SMTP email address of LHC
Thanks...

**Comment by remdex** [comment]
I have reopened issue. Next version will take care of this situation by itself.
