### ISSUE TITLE
postgresql branch Cobrowsing issue

### ISSUE THREAD

**Issue by xtpclark** [LiveHelperChat/livehelperchat#651]
Hello,

I am currently evaluating using LHC with PostgreSQL 9.3 and NodeJS.  One problem is co-browsing is not working.  How to troubleshoot there is no error. Is because of postgresql branch?  

I have not tried master yet, because postgresql is requirement.  

Any advice would be greatly appreciated.  This is a great program!

Thank you and best regards,

Perry

**Comment by remdex** [comment]
At the moment postgresql branch is a little bit behind master branch. Once I update postgresql branch to the current master branch your issue should be solved. As for timescale between 1-3 upcoming weeks it should be done.

And in general, no error = no help... Just see ajax calls their responses, enable debug out, disable cache etc. How to do all that you can find in documentation.

**Comment by remdex** [comment]
Postgresql branch updated to current version. But i tested what you wrote but here all works. No other options to flag report as works-here and close...

**Comment by xtpclark** [comment]
Thank you - I will test and give better errors in future.
