### ISSUE TITLE
Shift Request notification permission to the top navigation

### ISSUE THREAD

**Issue by supportreq** [LiveHelperChat/livehelperchat#652]
Hi,
Is it possible to shift Request notification permission from Settings -> Chat Configuration to the top menu next to sound icon. As currently only users with specific permission can access the Chat Configuration, while it is important to give this option to the basic user permission also..

Please suggest. Also which poilcy need to be assigned to the role so that user can check this option..

Please help

Thank You

**Comment by remdex** [comment]
Basically just see install default operators role. It does what you want to achieve
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/modules/lhinstall/install.php#L1196

**Comment by supportreq** [comment]
Hi @remdex,

I was able to get the access by providing the system configuration rights to the user. The said rights allows the user to change the system copyrights, online tracking ability, workflows etc which is something which only the admin should have access to.

Notification being the basic part of the system, it should be placed in a separate link or at the top with the sound icons.. Please share your suggestions..

**Comment by remdex** [comment]
See screenshot. It will see just these configuration links, to which they have permission.
![image](https://cloud.githubusercontent.com/assets/1146085/6569900/6ff40a30-c6fa-11e4-8e9e-d535a25c6732.png)

**Comment by supportreq** [comment]
Yes I have given only that access, but it shows all options 
![livechat](https://cloud.githubusercontent.com/assets/4680404/6570114/f3dc6db8-c71a-11e4-9465-04584a5a9acf.jpg)

**Comment by remdex** [comment]
I repeat once again see permissions what has operator role. I won't replay anymore to this ticket, because it's pointless, like you are not reading what i write...
Basically just see install default operators role. It does what you want to achieve
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/modules/lhinstall/install.php#L1196

**Comment by remdex** [comment]
And this is how it looks like after fresh install then operators role are used
![image](https://cloud.githubusercontent.com/assets/1146085/6570275/4bdd7ffe-c700-11e4-84f4-88c090cd0c95.png)

**Comment by remdex** [comment]
Your operators has also has to logout and login to see new permissions.

**Comment by supportreq** [comment]
I added this code : <input type="button" class="btn btn-primary btn-lg" value="<?php echo erTranslationClassLhTranslation::getInstance()->getTranslation('system/configuration','Request notification permission')?>" onclick="lhinst.requestNotificationPermission()" />

in top menu and it worked!!
