### ISSUE TITLE
invisible embed option causes js error on chat close

### ISSUE THREAD

**Issue by joelstransky** [LiveHelperChat/livehelperchat#659]
When you choose "Invisible, only JS API will be included" as the Position in the embed configuration, clicking the close X in a chat window will cause a js error.

Clicking the close calls `toggleStatusWidget()` in getstatus.tpl.php which does not handle the case where `document.getElementById('lhc_status_container')` might return `null`. 

Suggested fix:
>toggleStatusWidget : function(hide){
    	**if(document.getElementById('lhc_status_container') == null) return;**
    	if (hide == true){    		
    		this.addClass(document.getElementById('lhc_status_container'),'hide-status');
    	} else {
    		this.removeClass(document.getElementById('lhc_status_container'),'hide-status');    		
    	}
    },

**Comment by remdex** [comment]
If you open 
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/design/defaulttheme/tpl/lhchat/getstatus.tpl.php#L467

You would see that there is already such check. Perhaps you are running old version...

**Comment by joelstransky** [comment]
Yes, still running 2.18. thanks
