### ISSUE TITLE
New Report Issue LHC 2.28v : Wrong pop up size out of the user screen on FIREFOX

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#661]
Hi rem,
after the last update now, with the new LHC version 2.28 
pop up window go out of the user screen for user with FIREFOX.

LHC 2.28 new feature seems to work well with Chrome, Internet Explorer 11, BUT not with Firefox, pop up window go out of the user screen for user with Firefox.
Video demostration:
http://screencast.com/t/uQdwB6H9QE

How can fix? Is very bad to see!

**Comment by remdex** [comment]
Well you have really big form :)

**Comment by PeopleInside** [comment]
Yes i know ehehehe but should work as before :P ahahah i hope. Thanks.

**Comment by remdex** [comment]
Sorry, but it won't work as before. This one I can promise. It's your form madness not LHC problem in general. But we need some logic or some max height for resize not sure.

**Comment by remdex** [comment]
In any case you can override this template. It does this magic :)
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/design/defaulttheme/tpl/pagelayouts/parts/dynamic_height.tpl.php

**Comment by PeopleInside** [comment]
If not work just before are not very well :) because yes will be confortable for user who have small form with few options, not work if user have different option so set max pop up size not work animore.. so i can't decide the rigth size for the pop up window. I don't like much this new idea if they can't be fixxed but okay maybe is my problem because form are not little. For me is LHC issue :) >.< before i was able to set the right pop up size, now no more and pop up goes out of the screen ^_^

I don't know what edit for override template.. and i think is not a good idea put an update who cause issue where before all worked fine and well :) user has to set the right size :) or maybe automatic is good, if works :)

**Comment by remdex** [comment]
You can try to update this single file from github. Basically it should not resize popup if it's content is bigger then user screen available height. So in your case it should keep height you have provided.

**Comment by PeopleInside** [comment]
Well, works very well :D thanks. Now is better. ^_^ you had make LHC more intelligent ahaha :) Thanks rem.
