### ISSUE TITLE
Improvements: Statistics Improvements

### ISSUE THREAD

**Issue by devoger** [LiveHelperChat/livehelperchat#666]
1. It would be helpful if we can set a define date of statistics "general tab" not the graph. At the moment it shows base on 24h time not all time or base on my specified time.
See image:
![stats3](https://cloud.githubusercontent.com/assets/8411294/7013688/de3fb92e-dc91-11e4-9035-2a2b63a32cb2.png)

2. It would be a nice idea to be able to export statistics via CSV file format for safe keeping.

**Comment by remdex** [comment]
All this is already implemented I think.
