### ISSUE TITLE
on startchatformsettings let the check box for acept terms be checked by default

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#667]
Hi,
can you add an option to choose to auto checked by default the accept terms box on startchatformsettings page?

This will made more easy to start a chat for the user. User are informed if they start a chat agree the terms.

**Comment by PeopleInside** [comment]
Thanks for implementing this. This will available from next version or can be already available? Where admin can set the check box checked by default?

Thanks again, great.

**Comment by remdex** [comment]
yes, or you can just replace files and you will get it by now

**Comment by PeopleInside** [comment]
Thanks but Where admin can set the check box checked by default? on start chat settings or in Misc? Thanks again!

**Comment by remdex** [comment]
Start chat form settings
