### ISSUE TITLE
Choose name\email with facebook\google intergrations

### ISSUE THREAD

**Issue by Ireheart** [LiveHelperChat/livehelperchat#668]
Many live chats are now putting social media login integrations in, zopim as shown in the example do this and it's very successful. I would like to propose something similar.

![screenshot 2015-04-11 00 50 11](https://cloud.githubusercontent.com/assets/7198208/7099138/bb0392f4-dfe4-11e4-9c06-bd4ffc31e092.png)

**Comment by remdex** [comment]
Of
https://github.com/LiveHelperChat/livehelperchat/issues/495
