### ISSUE TITLE
New chat request - inputs not aligned

### ISSUE THREAD

**Issue by skiner68** [LiveHelperChat/livehelperchat#670]
Hello, 
I 've noticed a little design problem in new chat request. In case email is required and language select is displayed, inputs (name & email) are not aligned correctly:

Screen from FF:
![chat](https://cloud.githubusercontent.com/assets/11733592/7133387/39932cb4-e293-11e4-93d4-253557696f18.png)

Tested on WIN 8 in Chrome 41.0.2272.118 m, FF 37.0.1, IE 11. We are using LHchat 2.28

**Comment by PeopleInside** [comment]
Can't reproduce in my VPS LHC installation.

I have insert email mandatory and tried to select different language but always widget and email field is align correctly with Firefox ESR

**Comment by remdex** [comment]
But I managed to reproduce :) it's a bug. Just a lot of cases with this language selector :)

**Comment by PeopleInside** [comment]
Maybe space on top fix the problem. I had activated Operator intro text and with this i can't see the issue so maybe is a space problem :) without Operator intro text there is this issue :D

**Comment by skiner68** [comment]
Thanks for your replies and help! In case 'Text above start chat form fields' is active, inputs are aligned correctly. I have just inserted '.' into 'Text above...' and that will help us for a while.... better one stupid dot than broken design :-)
Another little problem is that 'Text above...' is not localized (we use one template for more language variations of our site(s)) . Yes, I know I could simply copy the template, save it as new one and insert the string translated, but this way is not ideal.

**Comment by skiner68** [comment]
Thank you very much for your time spend on this. I have just made an update and found another situation - please see the picture. This is a new chat form when no operator is online.

![chat](https://cloud.githubusercontent.com/assets/11733592/7604480/aeb932ec-f943-11e4-91f7-701fbd7b8d53.png)

**Comment by remdex** [comment]
This one won't be changed.

On 13 May 2015 at 08:45, skiner68 <notifications@github.com> wrote:

> Thank you very much for your time spend on this. I have just made an
> update and found another situation - please see the picture. This is a new
> chat form when no operator is online.
>
> [image: chat]
> <https://cloud.githubusercontent.com/assets/11733592/7604480/aeb932ec-f943-11e4-91f7-701fbd7b8d53.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LiveHelperChat/livehelperchat/issues/670#issuecomment-101520122>
> .
>



-- 
Sincerely,
Remigijus Kiminas
