### ISSUE TITLE
Tooltip should be hidden only if "x" button is pressed.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#671]
What happen now:

1. visitor open the website with the live chat status bar on-line and with the tooltip visibie.
2. visitor click on the status bar for start a chat so see the widget
3. user decide to not start a chat and close widget or start a chat and ends the chat
RESULT: tooltip is no more visible.

What should be:
Same above of the point 1, 2, 3 but as RESULT the tooltip is showed to the visitor again.
Only if the visitor click on "x" for close it tooltip will be hidden for the time inserted in the settings.

**Comment by remdex** [comment]
Won't be changed. Why iterate user...
