### ISSUE TITLE
From forum: Alow user to open pop up of closed chat or disable pop up button when chat is ended by the operator.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#672]
As from the forum:
https://forum.livehelperchat.com/viewtopic.php?id=1151
Is for reminder and not loose the idea to improve :D

A solution who look at the security is:

- **keep the message "chat was closed" in the pop up and disable the pop up button in widget only when the operator ends the chat with the visitor so this stop normal user to can press pop up button and loose conversation.** Are not a security risk because if the pop up is opened is printed the message "chat was clos*ed" and no access to the closed chat. Disable the pop up button is for prevent the error from the user to press that and loose the chat.

- **Also if user try to switch from pop up to widget when the chat has ended by the operator the button for switch to widget should not work so not close the pop up and not pass to widget.**

**Comment by PeopleInside** [comment]
Tested in demo but I'M unable to reproduce it works.
What I made wrong?

1 Started visitor chat
2. Accepted by operator and closed by operator
3. From client side i press in the widget the pop up button and widget is closed, pop up opened with the message "chat closed" and no text of the chat closed.

The closed chat is lost, user can't see any more.

**Comment by remdex** [comment]
If i mark as fixed, does not mean that I update demo each time. Only now update demo

**Comment by PeopleInside** [comment]
OPS. Sorry :D
