### ISSUE TITLE
Blank window on Windows 8

### ISSUE THREAD

**Issue by jesobreira** [LiveHelperChat/livehelperchat#674]
Hi!

I'm running LHC Windows client in two machines at my company. One of them is Windows 8 64 bits, other is Windows 7 32 bits. I could install on the webserver, put on website etc. Everything works fine on the Win7 machine. But when I open it on the Win8 machine, I see the login screen. It starts becoming blank as I go passing the mouse over the items. After the login, all I can see is a blank (white) window. So: http://postimg.org/image/6ftf35ggv/
I tried both Qt4 and Qt5, tried changing the folder to some folder that does not need UAC... but nothing helped.

Is that just with me?

**Comment by remdex** [comment]
Is that just with me? - YES

**Comment by jesobreira** [comment]
Perhaps it's not something with Qt on Windows?
https://www.google.com/search?q=qt+blank+window many guys (developers) having the same issue.
I'm considering the fact that, after posting this issue, I've tested in two (very) different computers (both with Windows 8 - one of them came with Win8 installed by default), and in both I'm having the same problem...
