### ISSUE TITLE
widget dropdown to choose department

### ISSUE THREAD

**Issue by centoasa** [LiveHelperChat/livehelperchat#676]
Sorry, but is there a way to setup widget to permit guest to choose department?

**Comment by remdex** [comment]
Yes, if you enter more than 1 department in back office it will appear automatically.

**Comment by centoasa** [comment]
unfortunately it is not so. Try on www.100asa.it

**Comment by centoasa** [comment]
Sorry, found it (I've had cecked invisible)
Thank you
