### ISSUE TITLE
403 Access denied

### ISSUE THREAD

**Issue by unicaus** [LiveHelperChat/livehelperchat#682]
403 Access denied, user can not access the app

**Comment by remdex** [comment]
Your issue does not make any sense at all. One more nonsense post and you will get a ban. At-least put some efforr to describe your problem...

**Comment by unicaus** [comment]
installed via softaculous. admin panel is accessible. but the user interface shows 403 Access Denied.

**Comment by unicaus** [comment]
And remdex, thought it would be enough to understand the issue for the developers.

**Comment by remdex** [comment]
Write to softaculous not me. LHC has nothing to do with it.

**Comment by unicaus** [comment]
softaculous installed your software, they have nothing to do with it, if it does not work. Isn't it your responsibility to fix errors?

**Comment by remdex** [comment]
No. Your server's - your problems.

**Comment by unicaus** [comment]
tried on three different servers. same issue. thanks by the way, I can see you won't help.
