### ISSUE TITLE
there is a d letter near chat time. Is normal? What is?

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#685]
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/7869421/e6ce3ae2-0582-11e5-9e32-d95cb630705c.png)

I see this also in the demo.
Is not very nice.

This **seems to be only in admin/operator side**, NOT in customer side.

This is visible on open chat from operator side.
How to reproduce:

Open a chat in operator side and you will see the letter d near the message time.

**Comment by remdex** [comment]
Let's pretende you never saw this :D

**Comment by PeopleInside** [comment]
^_^
mmmmmm.. you make difficult to me find little issue ahaha

Is always more difficult and more hidden in some place you never imagine ^_^
Thanks Rem.
Have a great week!
Thanks for the Fix
**FIXXED**
