### ISSUE TITLE
auto transfer chat when previous operator internet drops

### ISSUE THREAD

**Issue by myselfgaurav** [LiveHelperChat/livehelperchat#687]
how can chat be auto auto transferred  when previous operator internet drops suddenly.

how can we do it >

**Comment by remdex** [comment]
What technical conditions should be met under your "previous operator internet drops suddenly." sentence?

**Comment by myselfgaurav** [comment]
like operator internet closes suddenly or power off

**Comment by remdex** [comment]
Sorry, but I have no other choice just close this issue as invalid. It's impossible in web application detect these things.

**Comment by myselfgaurav** [comment]
i think we can do it , by checking if operator becomes online for few mintues in middle of chat

**Comment by remdex** [comment]
Sorry, but i won't waste resource on such things in LHC :) you can always try to do that yourself :)
