### ISSUE TITLE
Screen Sharing is not working.

### ISSUE THREAD

**Issue by thomas1216** [LiveHelperChat/livehelperchat#691]
Hello

i clicked at the Screen Sharing icon and them at the blue eye butoom at the top, but i dont see the User Screen, 

the only thing which appear at the user screen right top side is the following message

![image](https://cloud.githubusercontent.com/assets/11229573/8009876/ab6401f6-0b79-11e5-80d9-2c5142511248.png)

Thanks for the Help.

**Comment by remdex** [comment]
No error = no fix
