### ISSUE TITLE
Operators must have only his/her department in dropdown list. 

### ISSUE THREAD

**Issue by surendrakumar1992** [LiveHelperChat/livehelperchat#692]
When i login as operator i see my department(as admin assign me) as well as All department option so operator can see total no of chat. which is wrong. How we can hide 'All Department' option from operators.

**Comment by remdex** [comment]
Edit operators role and remove permission "Allow user to edit his responsible departaments" and this option from user account should be gone.

**Comment by surendrakumar1992** [comment]
![image](https://cloud.githubusercontent.com/assets/12594740/8018625/a546f196-0c43-11e5-9032-7079352979f6.png)

This screen share with you.  Allow user to edit his responsible departaments --> Select No with i still see 'All Department ' on operator dasbooard.

**Comment by remdex** [comment]
I think this permission is not used anymore. The one i talked about is assigned in users module.

**Comment by surendrakumar1992** [comment]
Hey thanks for fast response..
Man can you help me step by step, Please
And one more thing. If operator click on -->> 'Chat List' --> Under 'Choose what type of list you want to see' If operator select Active Chat then he redirect to Active Chat page. On that page he can also browse by Name and department. How i can handle this also

**Comment by remdex** [comment]
1. For step by step there is commercial support. 
2. This one did not understood what you want there..

**Comment by surendrakumar1992** [comment]
Okay thanks.
There is a option for reset default setting after some change.
