### ISSUE TITLE
Getting No Access error while accessing XML/desktop API.

### ISSUE THREAD

**Issue by surendrakumar1992** [LiveHelperChat/livehelperchat#693]
Hello friends.
I am getting 
XMLHttpRequest cannot load http://localhost/livechat/lhc_web/index.php/xml/checklogin. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access.
while accessing XML/desktop api. Please help
I try to add 
header('Access-Control-Allow-Origin: *');
        header("Access-Control-Allow-Credentials: true");
        header('Access-Control-Allow-Headers: Content-Type');
        header('Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE, PUT');
but still getting same issue.
Thanks in advance.

**Comment by remdex** [comment]
This api is not intendet for JS usage but for desktop client. These headers won't be added. 
Also you shoul dhave just overrided file in extension and cleared cache. How to write extension just see demo extensions.

**Comment by surendrakumar1992** [comment]
Thanks @remdex  for fast response.
Please where is demo extension ?

**Comment by remdex** [comment]
https://github.com/LiveHelperChat/livehelperchat-extensions

**Comment by surendrakumar1992** [comment]
Hey @remdex  thanks for fast response. I used 
https://github.com/LiveHelperChat/sugarcrm 
as reference. What code goes into bootstrap.php? I override modules with web xml files. now i am confused that what code goes in bootstrap.php
Thanks Man

**Comment by surendrakumar1992** [comment]
Thanks..
One more query
Where from you display date and time of chat.
![udddntitled](https://cloud.githubusercontent.com/assets/12594740/8079732/40b95194-0f84-11e5-83bc-ba583ca25834.png)
