### ISSUE TITLE
Error filling up Error.log file

### ISSUE THREAD

**Issue by danielc1234** [LiveHelperChat/livehelperchat#696]
Hi, although the LHC is still working, we are getting thousands and thousands of these error messages in our error.log file.

2015/06/13 16:03:44 [error] 23369#0: *40961 connect() failed (111: Connection refused) while connecting to upstream, client: 75.129.168.200, server: node.oursite.net, request: "GET /socket.io/?EIO=3&transport=polling&t=1434225766090-207 HTTP/1.1", upstream: "http://127.0.0.1:3000/socket.io/?EIO=3&transport=polling&t=1434225766090-207", host: "node.oursite.net", referrer: "http://www.oursite.net/index.php/site_admin/"

We tried to increase the sockets as advised here.. http://glynnbird.tumblr.com/post/53280292271/node-js-increasing-the-size-of-the-socket-pool

in the file located here. /www/oursite.net/extension/cobrowsing/server.js and another node.js file but did not fix.

Would like to try and figure out why this is happening.....   :)

**Comment by remdex** [comment]
LHC has nothing to do with your enviroment.

**Comment by danielc1234** [comment]
Agreed, but LHC on our system is using node.js, which is an extension of LHC. And settings for node.js are found within LHC.

I was just hoping you may have some general ideas on how to troubleshoot this error.

**Comment by joaoei** [comment]
Did you troubleshoot this error? I'm having the same problem.
