### ISSUE TITLE
Request: See what the user have searched for reach the website on google or other search websites

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#703]
Hi,
this i don't know if you want implement in the future and i think will be possibile to do.

Different times i see some visitors surfing my websites.. i see they come from google where find me but i can't understand what they have looked for for find my website.

So will be great know what they search like in a statistics so you are able to know what the visitor are looking for.

Will be this a privacy issue for the user? Maybe not.. is bad if i know someone looked for psicology or help and finded my website? This can help me to help better the visitor.

What do you think?
Like when you see a visitor come from google yuo can also have a field where when is possibile you can know what this user searched for reach you.

Like word searched: ... hiuse, help, ecc

**Comment by remdex** [comment]
Technically google has changed how it refers users and just hides search phrase so I just do not have power to know what user was looking for. So i'm afraid i have just to close it :)
