### ISSUE TITLE
Waiting for operator text doesn't match in Popup window

### ISSUE THREAD

**Issue by Joeboyc2** [LiveHelperChat/livehelperchat#704]
Hi Rem,

I'm running the latest build and have noticed an issue.

If you use the widget themer to change the text displayed when a user is waiting for an operator this is not replicated when the widgets is changed to a popup window, when going back to the widget the text changes back to that what has been supplied in the widget theme.

Here are some screen shots, is this correct, if so please can you let me know when file i can amend to match the text so it reads the same as the widget.

Text matched what i have typed in the themer
![image](https://cloud.githubusercontent.com/assets/8202030/8481830/733f9cda-20dd-11e5-92a2-40a6ed4b34ec.png)

Text has changed back to default - Popup
![image](https://cloud.githubusercontent.com/assets/8202030/8481856/9aa26e60-20dd-11e5-9dc1-7163846e3c2f.png)

Thank you for all you great work so far

Joe

**Comment by remdex** [comment]
I see, seems widget theme text is lost. Will take a look in a few days.

**Comment by PeopleInside** [comment]
Tried to reproduce in LHC demo but i can't reproduce. 
In the demo seems to be work.

remdex are you able to see the issue in the LHC Demo? Maybe is me who can't reproduce in demo.. :)

**Comment by remdex** [comment]
Have not tried, but i'll check. Thanks for trying to reproduce, perhaps he's using old template or what :)

**Comment by remdex** [comment]
Few days appeared to be few hours :)

**Comment by PeopleInside** [comment]
Thank you @Joeboyc2 for report this. Thank you @remdex for fix :)

**Comment by Joeboyc2** [comment]
Thank you Rem.

i really appreciate you looking in to this some promptly.

i have manually added you changes to my local file and it working just fine.

thank you again

Joe
