### ISSUE TITLE
Standard language codes for widget

### ISSUE THREAD

**Issue by ZeiP** [LiveHelperChat/livehelperchat#706]
Hi,

I made a Drupal module for the software: https://drupal.org/project/livehelperchat . The language codes used in the widget URLs don't seem to be conforming to any standard, so I had to hard-code a mapping from Drupal's default two-character language codes to the LHC language codes. 

Would it be possible to start using the standard two-character language codes for LHC, although maintaining some kind of mapping for the old codes not to break the old widgets?

**Comment by remdex** [comment]
Sorry, but start using 2 letters code is not possible just and would break a lot of existing installs.

As I remember current language codes are based on 3 letters country codes. http://www.w3.org/WAI/ER/IG/ert/iso639.htm perhaps this.
http://www.loc.gov/standards/iso639-2/php/code_list.php

Really don't remember on which one it was based initially. Perhaps in the future it will change, but not soon :)

**Comment by ZeiP** [comment]
Oh well, it already works for us with the mapping :)

The language codes were mostly conforming to 639-2, but there were some that I couldn't find at least from the Wikipedia list. They're marked with a question mark in the module code: http://cgit.drupalcode.org/livehelperchat/tree/livehelperchat.module#n60  I was able to guess some of them, but some are currently missing.

**Comment by remdex** [comment]
Workflow to know correct two letters code let say
http://cgit.drupalcode.org/livehelperchat/tree/livehelperchat.module#n76 CSE
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/settings/settings.ini.default.php#L383 there you see it's https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/settings/settings.ini.default.php#L385 cs

Which is downloaded from transifex. So it's Chech langauge i think :)
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/doc/shell/update_translations.sh#L44

https://www.transifex.com/projects/p/live-helper-chat/language/cs/

Just simple example which can help you out :)

**Comment by ZeiP** [comment]
Ah, there they are. I can fix the mapping on the module based on this. Thanks for the lightning-quick replies! :)

**Comment by remdex** [comment]
Closing, like i ques nothing will be done more on this issue.
