### ISSUE TITLE
often time on site is always 0

### ISSUE THREAD

**Issue by centoasa** [LiveHelperChat/livehelperchat#709]
Very often on live chat list I've:
10 m. fa
00:00:00

Why is 00:00:00 while customer move into the site?

**Comment by remdex** [comment]
Hi,

Time on site is increased once user does at-least one pageview being on your site, like time is calculated last page view time - first pageview time = time on site. 

If user does not do second page view there is no time on site.

**Comment by centoasa** [comment]
Also nove through the website time on site is always 0

Inviato da TypeMail



Il giorno 15 lug 2015 18:59, alle ore 18:59, Remigijus Kiminas <notifications@github.com> ha scritto:

**Comment by centoasa** [comment]
I've seen also that every page user visit, I've new row on admin

**Comment by remdex** [comment]
https://livehelperchat.com/my-users-looses-chat-session-then-they-navigate-through-the-site-duplicate-online-users-records-377a.html

**Comment by centoasa** [comment]
I've just install a fresh latest release, but issue still remain. No edit/modify to stock installation.

**Comment by remdex** [comment]
Sorry, but I don't be-leave you.... There is commercial support. Just contact by skype...

**Comment by centoasa** [comment]
you want to check? I can give you the access credentials to the site so check out for yourself what I'm saying and then you will be able to disprove

**Comment by remdex** [comment]
Just skype me with details...

On 16 July 2015 at 11:17, Remigio <notifications@github.com> wrote:

> you want to check? I can give you the access credentials to the site so
> check out for yourself what I'm saying and then you will be able to disprove
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LiveHelperChat/livehelperchat/issues/709#issuecomment-121873960>
> .
>



-- 
Sincerely,
Remigijus Kiminas
