### ISSUE TITLE
Operator is typing is not hide some times if chat is closed

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#710]
Hi rem,
as some one has alerted some times ago, also in the last LHC version if operator write something and than close the chat the type sentence continue to stay in user interface.

I suggest to add a command when close chat is pressed to hide this sentence so when chat is closed this sentence operator is typing is hidden.
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/8698403/300a4cc8-2afe-11e5-8df0-6a2a401494b8.png)

**Comment by remdex** [comment]
Can you reproduce it on demo.livehelperchat.com?

**Comment by PeopleInside** [comment]
Sure,
you just have to type something and close chat after that without wait, in visitor side the sentence continue to stay as in the screen shot upstairs.

**Comment by PeopleInside** [comment]
Thanks as soon the new close button will be in translation i will update :) Thanks for the fix
