### ISSUE TITLE
Improvement: Check if visitor browser language is between widget or pop up language and swith

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#711]
In my LHC I use Italian and English language who user can select for translate chat interface.
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/8709785/59928b22-2b45-11e5-8eca-0558587d20f0.png)
This should keep as is.

Improvement will add a function who LHC detect visitor browser language and swith automatically the interface between the active languages.. in my case Italian or English.

Actually if a English visitor visit my website and not know the LHC see the chat in Italian as is default language. Will be good if LHC can detect user language between my active Languages in the screen shot and activate for the user the right Language and let always the user change manually with the language button on top.

**Comment by remdex** [comment]
Sorry, but this one won't be fixed unless someone will implement it... Just to complex and little advantage and it's more easier just adjust generated embed code with CMS itself. Like google etc always provide link to user language.
