### ISSUE TITLE
Suggestion: Replace "Close and Start a new one" with "Close for start new chat"

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#712]
Hi,
i suggest to replace the new button text "Close and Start a new one" with "Close for start a new chat" because is more correct than Close and.. if you press the button you don't start new one chat and maybe visitor not need to start new chat so "Close for start a new chat" is more correct.

Or just only Close.
Also for Italian translation is more correct.

It's a suggestion.
:-)

**Comment by Joeboyc2** [comment]
Sorry, I don't quite understand this. Both translations in to English sound wrong, can you show a screenshot of the button or give some context as to when this shows?

**Comment by PeopleInside** [comment]
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/8761122/6ad98776-2d40-11e5-9f2c-22b5f8a97f05.png)
This is what visitor see on closed chat.
Button with "Close and start new one" but i think will be more correct only "Close" or "Close for start a new chat" but maybe visitor has just finished the chat and not need or not want to start new one.

The button "Close and start a new one" Seems if you press you close and start a new chat. It's a good idea the button but maybe just "Close".
The button do this: close the chat window, maybe the words can be changed with better one.

I hope is more clear now.

**Comment by Joeboyc2** [comment]
ah i see, thank you for getting back to me.

Yeh i agree, it should not say "Close and Start a new one" and probably should just say "Close".

but i guess the functionality behind that button means that it closes the window and then automatically starts a new chat, saving the customer time.

but feel it probably should be split in to 2 buttons or the text should just be "Start a new Chat"

i think that would be the best idea

@remdex @PeopleInside what do you think?

**Comment by PeopleInside** [comment]
I think usually a closed chat not need to be reopen so just "Close" or "Close for start new chat" is okand will made less work to Rem because no code changed needed just only correct the sentence (the text) in the button and will be great. If visitor want start new chat just click again in the widget status but this means operator has closed the chat too early as customer have other questions.

So i think just only correct the text in the button.
