### ISSUE TITLE
Feature request: make some department visible only if is online

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#715]
In the Department (edit department) should be added an check box for make a department visible only if is online.

Why this?
Because some department should not receve offline message and should not be visible if is offline.
Maybe is also userfull for Busy department or away department who activated for me personal autoreply message.

If this two department can be set to be visible only if is online will be great. This can help my case but can be also userfull for other think to have a deparment active and visible only if dep is online.

Will be great add this check box funztion in edit department. (Visible only if online)

**Comment by PeopleInside** [comment]
For let more clear this i have a screenshot
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/8825138/0290c9dc-307d-11e5-995f-2128693533bc.png)

So will be good for me hide the red offline department but let them visible if they are online. So will be great go on department settings and check an option called "show only if is online" :-) So user will see only Italian and English department and if the busy or away or special operator connect the department will be visible to the user as it goes online.

**Comment by remdex** [comment]
Implemented here
https://livehelperchat.com/new-version-2.39v-bubbles-chat-and-some-more-changes-434a.html
