### ISSUE TITLE
Automated Hosting - Can i limit the numbers of operators per instance?

### ISSUE THREAD

**Issue by thomas1216** [LiveHelperChat/livehelperchat#716]
Hello

Automated Hosting - Can i limit the numbers of operators per instance?

**Comment by remdex** [comment]
yes

**Comment by thomas1216** [comment]
Can you told me. how to do it? if is possible, Many thanks

**Comment by remdex** [comment]
Your question does not make any sense to me, because in manager panel you can set how many operators instance can have. "Users" tab
