### ISSUE TITLE
Automated installation script

### ISSUE THREAD

**Issue by download13** [LiveHelperChat/livehelperchat#717]
I was wondering if there's a possibility of adding an automated installation script so we could specify all the variables asked for during installation (mysql username/password/etc) in a config file of some kind.

Then, as long as all the requirements are met the installation script can just run automatically and perform the setup the first time you go to the login page.

I already tried specifying all the database information in the `settings.ini.php` file before installation, but it still asks for username/pass/etc when I go to install it.

**Comment by remdex** [comment]
Really don't think so it's easy achievable. But well, if you create pull request i could try to review it :)

**Comment by remdex** [comment]
Merged pull request
