### ISSUE TITLE
Feature Request - Have a feedback after operator closed the chat - see picture

### ISSUE THREAD

**Issue by thomas1216** [LiveHelperChat/livehelperchat#729]
Hello 

Will be Nice if customers can left a feedback on every Chat, we'll know if we're making customers happier, instantly. Then track results over time with, detailed reports.

![image](https://cloud.githubusercontent.com/assets/11229573/8904504/e255c334-342d-11e5-8134-4aac4140be48.png)

**Comment by remdex** [comment]
Any wish to sponsor that? 
P.s it's duplicate basically of #483

**Comment by thomas1216** [comment]
how the Sponsor works?

**Comment by remdex** [comment]
I'm not sure are you the same user but basically. Similar thread here.
https://forum.livehelperchat.com/viewtopic.php?id=1347

So if you both sponsor this it would be half price pasted here. Of course if it's not the same user.

**Comment by remdex** [comment]
P.s this feature is funded now and will be implemented in the next few weeks.

**Comment by remdex** [comment]
https://livehelperchat.com/new-version-2.35v-survey-at-the-end-of-chat-430a.html implemented and released. Over time this feature will be improved with more options i ques :)
