### ISSUE TITLE
Stored Cross Site Scripting Identified

### ISSUE THREAD

**Issue by indraveni** [LiveHelperChat/livehelperchat#731]
The chat box of this application is reading every user input data. And thus, its also accepting the javascript submitted by the users.This message with javascript is logged at the server and is visible through the admin panel. 

In the Admin Panel, the javascript is executed, which is opening up a security problem of stored cross site scripting.
![livehelperchat_stored_xss](https://cloud.githubusercontent.com/assets/8177068/8924846/99828fc8-351f-11e5-8d89-528cf6f22f47.PNG)

**Comment by remdex** [comment]
Can i get exact steps to reproduce?

**Comment by remdex** [comment]
And can you reproduce it on
https://demo.livehelperchat.com ?

**Comment by indraveni** [comment]
Yes,

(1) Access the URL: http://localhost/livehelperchat/lhc_web/ and fill the
input fields as following
Name: <script>alert(1);</script>
Your Message:  <script>alert(1);</script>

The above submitted the values at the client interface normally and is
giving message that operator will be available shortly.

(2) Logged in as admin and accessed,
http://localhost/livehelperchat/lhc_web/index.php/site_admin/#/dashboard
and no moving the mouse over the above recently inserted message, the alert
is popped up.

Hope this helps.

Please let me know if you want any screenshots.

-------------------
Regards
Indraveni

**Comment by indraveni** [comment]
You may try logging in as admin in the above given demo website, and see if
there is an entry in the dashboard with javascript alert(1). If so, please
move your mouse over it and check if it gets executed.

Please let me know if that worked out.

Regards
Indraveni

**Comment by remdex** [comment]
Hi,
No it does not worked.
![image](https://cloud.githubusercontent.com/assets/1146085/8925114/d55ceab4-350d-11e5-8f67-e205cbde3723.png)

I ques you are running older version. This security issue was fixed some time ago. So i ques you are testing on older version.

**Comment by remdex** [comment]
Just try to reproduce on http://demo.livehelperchat.com

**Comment by remdex** [comment]
Ok, closing issue because seems that you were testing older version of LHC. If I'm wrong I'll reopen. Thanks for effort in any case :)

**Comment by indraveni** [comment]
Yes, it's slight older version. Just tried on latest and seems its fixed.

Good and Thanks

Indraveni
