### ISSUE TITLE
Operator Logout option

### ISSUE THREAD

**Issue by praveenvall** [LiveHelperChat/livehelperchat#732]
Issue: An operator can login using the same ID from different machines without logging out.

This login should have some limitations where the administrator should give special permissions to the operators to login from a different computer when the first computer abruptly goes down.

Results: When multiple users login with the same ID will cause the operator privacy with the client.
The messages will be driven by different operators assuming the other operator didn't respond.

Either you can group such open operators to a Trainee group where the Administrators can help them as and when required with the same name.

But a full featured operator should be able to login only from one IP address and will need to allow by administrator to use other computers.
It is also better to record the sessions of the operators using the IP address.

**Comment by remdex** [comment]
Set to true this:
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/settings/settings.ini.default.php#L18

**Comment by praveenvall** [comment]
This statement has been marked as true and tested 
'one_login_per_account' => true,

Actually  in the new release, this statement was not available, so I have copied and pasted into the settings.ini.default.php manually into the given array.

But still different users can login with the same name.
