### ISSUE TITLE
Copyright icon on widget URL is not working properly.

### ISSUE THREAD

**Issue by thomas1216** [LiveHelperChat/livehelperchat#737]
Hello when someone clicked in the copyright icon in the widget  point to the address

Example

When you clicked in the copyright icon should go to:  http://www.example.com  and not to http://www.example.com/www.example.com

**Comment by PeopleInside** [comment]
It seems is your issue and not LHC Issue.
Have you put the link with http:// or https:// before?
Are you able to reproduce in the demo of LHC and please provide step to reproduce but maybe you have put the link in wrong way, check better.

Thanks.

**Comment by thomas1216** [comment]
Thanks, I found the Problem.
