### ISSUE TITLE
More Than One Department

### ISSUE THREAD

**Issue by parkerj** [LiveHelperChat/livehelperchat#739]
When generating widget code to use more than one department, the chat does not show up. Below is an example of the code which is generated when selecting more than one department.

```
<script type="text/javascript">
var LHCChatOptions = {};
LHCChatOptions.opt = {widget_height:340,widget_width:300,popup_height:520,popup_width:500,domain:'example2.org'};
(function() {
var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
var referrer = (document.referrer) ? encodeURIComponent(document.referrer.substr(document.referrer.indexOf('://')+1)) : '';
var location  = (document.location) ? encodeURIComponent(window.location.href.substring(window.location.protocol.length)) : '';
po.src = '//example.com/lhc/index.php/chat/getstatus/(click)/internal/(position)/bottom_right/(ma)/br/(check_operator_messages)/true/(top)/350/(units)/pixels/(leaveamessage)/true/(department)/1/2?r='+referrer+'&l='+location;
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
})();
</script>
```

**Comment by PeopleInside** [comment]
Hi **parkerj**,
sorry but at my first look you report is not valid.
Have you tested on demo.livehelperchat.com?

I think is your issue not Live Helper Chat issue.
Also the code you pasted here is edited by you and is not original generated code.

All works for me and also test in the demo didn't show any issue.
Please provide step to reproduce.
1.
2.
3.
4, 
etc.

Please if you solve this close the topic.

**Comment by parkerj** [comment]
The problem is at the end of po.src = '....(leaveamessage)/true/(department)/1/2?r='+referrer+'&l='+location;' As you can see there are two departments (1 & 2). This is generated when I choose the departments I want when generating the widget embed code. If I remove '/2' from the list, the chat works and shows up, but when there are more than one departments like what I am showing above, chat does not show up on the site.

**Comment by PeopleInside** [comment]
Please try to reproduce in demo.livehelperchat.com then provide the steps for reproduce.
I have generated two department in the demo and i have copied the embed widget code in a rela time html editor online and the chat is showed correctly so your explain not helps me to reproduce the issue as i AM able to generate embed code for two department and all works fine.

**Comment by PeopleInside** [comment]
Have you resolved?
