### ISSUE TITLE
NoScript for Firefox consider LHC chat call as XSS attack and chat stop working on browsers with NoScript plugin

### ISSUE THREAD

**Issue by zaidchauhan** [LiveHelperChat/livehelperchat#744]
Hello, 

It is related to Issue - https://github.com/LiveHelperChat/livehelperchat/issues/206

Below is the output logged in console by plugin. Due to this affected users considering our application as vulnerable. Any help will be apprciated.

[NoScript InjectionChecker] JavaScript Injection in ///lhc_web/index.php/chat/chatwidget/(leaveamessage)/true/(theme)/1/(vid)/7g60b6038fyykbpo14?URLReferer=%2F%2Fapp.mytaxprepoffice.com%2F%23%2Fhome&prefill[username]=Milan%20Saraiya%20(016720143420178)&prefill[email]=milan.saraiya%40i-link.co.in&prefill[phone]=(456)789-4566&dt=MyTaxPrepOffice%20Ã¢??%20Tax%20Software%20for%20your%20Tax%20Office
(function anonymous() {
lhc_web/index.php/chat/chatwidget/(leaveamessage)/true/(theme) / COMMENT_TERMINATOR /
DUMMY_EXPR
})
[NoScript XSS] Sanitized suspicious request. Original URL [https://chat.mytaxprepoffice.com/lhc_web/index.php/chat/chatwidget/(leaveamessage)/true/(theme)/1/(vid)/7g60b6038fyykbpo14?URLReferer=%2F%2Fapp.mytaxprepoffice.com%2F%23%2Fhome&prefill[username]=Milan%20Saraiya%20(016720143420178)&prefill[email]=milan.saraiya%40i-link.co.in&prefill[phone]=(456)789-4566&dt=MyTaxPrepOffice%20%E2%80%93%20Tax%20Software%20for%20your%20Tax%20Office] requested from [https://app.mytaxprepoffice.com/]. Sanitized URL: [https://chat.mytaxprepoffice.com/#6250017314905367851].

**Comment by remdex** [comment]
Sorry, but no idea what to change...

**Comment by zaidchauhan** [comment]
Will you please guide me where I should look for this ?
