### ISSUE TITLE
Browse offers embed code

### ISSUE THREAD

**Issue by centoasa** [LiveHelperChat/livehelperchat#746]
"Browse offers embed code" show layer only when operator is connected? For me work so; I think it's better work for all time the flag active is on.

**Comment by PeopleInside** [comment]
Hi centoasa,
do you means the job title "personal assistant" present in the live demo?

The job title editable under the operator profile?

**Comment by PeopleInside** [comment]
If you mean to have proactive invitation also if the live chat is offline I think is already supported and this can be setup in the settings.

**Comment by centoasa** [comment]
No, I mean browse offer module.

**Comment by remdex** [comment]
Sorry @centosa but browse offers does not have anything related to operator status. So really not sure how can i help you :)

**Comment by centoasa** [comment]
Thanks Remigijus. But I very don't understand why  from some times ago browse offer no longer appear. Same position in tpl_footer, same website, bur none,  nothing appear.
