### ISSUE TITLE
Issue on info label

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#758]
On On-Line visitor there is an issue,
I hope the screen above can help you to understand and fix.

As you can see the last visitor .. have the issue is not possible to see the IP because the label are not in the foreground.

![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/9860009/cd4851e6-5b29-11e5-9a0a-2d4671038af0.png)

![immagine](https://cloud.githubusercontent.com/assets/5006150/9860022/dc6e0f1c-5b29-11e5-88c2-b2448ea615d5.png)

**Comment by remdex** [comment]
Yes, kinda understood
