### ISSUE TITLE
Missing titles on widget

### ISSUE THREAD

**Issue by tomwys** [LiveHelperChat/livehelperchat#763]
![selection_235](https://cloud.githubusercontent.com/assets/255939/10105963/393e28cc-63b2-11e5-9aa4-4e549e1d8e20.png)

**Comment by remdex** [comment]
In short - there was never intention to have titles there :)

**Comment by tomwys** [comment]
But why so many of blank space then?

**Comment by remdex** [comment]
Perhaps just font issue. Can't remember how it looked in old version with old font awesome font. Will need to check :)

**Comment by Kern3l** [comment]
It has min-width: 160px.

**Comment by remdex** [comment]
It's fixed now in one of to-days commits :)
P.s demo is not updated yet :)
