### ISSUE TITLE
Can't configure amazon ses.

### ISSUE THREAD

**Issue by kramarz** [LiveHelperChat/livehelperchat#764]
In amazon ses when using smtp username is not sufficient to place in "from" field of email. It results with data not accepted error.
In my opinion you should not overwrite "from" with smtp username by default.
https://github.com/LiveHelperChat/livehelperchat/blob/86c9bbc58af3a46a2d631394f14b9110394624ab/lhc_web/lib/core/lhchat/lhchatmail.php#L41

**Comment by remdex** [comment]
What should be in that case from address?

**Comment by kramarz** [comment]
well, if it is already set in line 25 You should not set it to another value. Otherwise there is no point in asking for two different values: From and Username

**Comment by remdex** [comment]
Ok, makes sense i'll change after few hours

**Comment by remdex** [comment]
Changed to 
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/lib/core/lhchat/lhchatmail.php#L41

**Comment by kramarz** [comment]
Thanks, It will work for us.

PS.
I'm not sure why you are still overriding it in line 43 but i'm not sure why there is conditional expression checking if username/password are empty in first place.
