### ISSUE TITLE
exception 'ezcPersistentQueryException' with message 'A query failed internally in Persistent Object: SQLSTATE[22001]

### ISSUE THREAD

**Issue by serathius** [LiveHelperChat/livehelperchat#766]
String data, right truncated: 1406 Data too long for column 'user_typing_txt'

culprit: https://github.com/LiveHelperChat/livehelperchat/blob/a16a071ff418011d3471b65c41a011ddc2141dd9/lhc_web/modules/lhchat/chatwidgetchat.php#L60

if referer string length is over 50 then message "Chat was deleted" appears.

**Comment by remdex** [comment]
This happens only in postgresql version and has been fixed few weeks ago. As a solution just make this field bigger.

**Comment by serathius** [comment]
I will provide additional information:
> Livehelperchat version - 2.36
> Database Mysql: mode STRICT_TRANS_TABLES
Insert/update value bigger than in field, can result in database rejecting changes.
Result depends on Mysql mode. 
Application should not depend on starting database configuration. 
If it do so it should:
* change configuration
* inform user during installation

I don't know any php, but normally HTTP_REFERER http header is standard url addres.
http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

So I don't understand your logic, if I pointed to exact line that copies that header to field.

**Comment by remdex** [comment]
I see now. In that case your comment makes sense. Just never encountered this issue with Mysql. Will need to fix.

**Comment by serathius** [comment]
ye, It's fault of Mysql, default mode allows Updates/Inserts that truncate data. I really recommend switching to strict mode, If you don't want to encounter strange bugs. Like
data migration that sets lowers max size of fields, just cuts out additional bytes, without any information, and can lead to data corruption.
