### ISSUE TITLE
default_site_access in Embedded code url

### ISSUE THREAD

**Issue by serathius** [LiveHelperChat/livehelperchat#768]
If I understand correctly, If language is not provided in embedded code url default_site_access will be selected. 
That rule is also used when generating code to be embedded, when selected language is same as default_site_access.

Problem appears when you put use language same as default_site_access in url. This results in redirection. 

This is problem when writing code that decides what language to use. 
That code needs to know which default_site_access is selected and skip inserting language code to url. 
I think passing default_site_access should be allowed.

**Comment by remdex** [comment]
For that reason in automated hosting I just have fake default site access :)
https://github.com/LiveHelperChat/automated-hosting/blob/master/instance/doc/doc.txt#L113
16 - 17 item.

In general in default version nothing will be changed. But in your case you can follow these two items :)

**Comment by serathius** [comment]
Pls don't promote bad programming habits.

**Comment by remdex** [comment]
It's not habit it's just the way it works. Default site access should never be embeded in URL. In default version you never can generate embed code with eng siteccess if what. So i'm not sure what you mean there....

**Comment by serathius** [comment]
So what you do on your automated hosting when pull request with new language was merged?

**Comment by remdex** [comment]
I just update settings that's all.

**Comment by serathius** [comment]
Ok, I would not call this automatic. I have done what you proposed, it works for now.
