### ISSUE TITLE
site_access meaning

### ISSUE THREAD

**Issue by serathius** [LiveHelperChat/livehelperchat#769]
I'm working on integrating livehelperchat in client panel (django). 
My client panel uses LANGUAGE_CODE header to determine which language should be used to render templates.
LANGUAGE_CODE uses ISO 639-1, so I find myself in need to translate ISO 639-1 to site_access.
Easiest way is to use ready library.
But, after looking in https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes I found that it doesn't match.

Example
- site_access: esp
- language: es
- locale: es_MX (Mexican?)

Standard:
- ISO 639-1: es
- ISO 639-2/T, ISO 639-2/B,  ISO 639-3: spa
- locale: es_ES

Language fallback mechanism would be nice addition. 
##

**Comment by remdex** [comment]
See this plugin for language code matching
https://www.drupal.org/project/livehelperchat

**Comment by serathius** [comment]
Comment from plugin
>  // There definitely should be a better way... Hope LHC ultimately turns to real lang codes

**Comment by remdex** [comment]
I know :) pull request are always welcome, but no one bothers :)
