### ISSUE TITLE
Failed to Decode Downloaded Font 

### ISSUE THREAD

**Issue by danielc1234** [LiveHelperChat/livehelperchat#771]
This is probably not a big deal, but I am seeing some errors in my Chrome console. I have attached a screen shot of what I am seeing. Also, my pencil button for responses seems to have incorrect padding parameters. 

Thanks

![2015-10-06_0844_001](https://cloud.githubusercontent.com/assets/1151357/10308893/0d854d8e-6c07-11e5-9a9b-efe907ff6ab9.png)

![2015-10-06_0844](https://cloud.githubusercontent.com/assets/1151357/10308897/193b4b92-6c07-11e5-8a5f-dd4579cab582.png)

**Comment by remdex** [comment]
1. For download font - make sure your server passes woff2 files
2. Yes it's known bug which I keep forgetting to fix :)
