### ISSUE TITLE
Message custom when offline

### ISSUE THREAD

**Issue by marcelloinfoweb** [LiveHelperChat/livehelperchat#773]
How is it possible to put a message when you do not have attendant online? I would like to put a mansagem custom when any department is offline and does not display any field in the widget or in the incorporation of the page. If you are not able to put this field by the administrator, how do I put in the source code with some condition? Which file do I change?

**Comment by PeopleInside** [comment]
https://github.com/LiveHelperChat/livehelperchat/issues/444

**Comment by marcelloinfoweb** [comment]
Exactly this, thanks for the reply. The redirection does not work in the current version. In which file can I edit this screen.

**Comment by PeopleInside** [comment]
If you are running an old version you should update. Keep in a webserver old version is a security risk as new version fix problems and bugs.

So if you have an old version maybe you should not post here any help request i think... as many issue or function are added and resolved in the last edition.

However this function has not yet implemented. I AM happy to see other people like this idea as me. For the question about LHC help there is a forum at https://forum.livehelperchat.com

Sorry I can't help with that, only Rem can.
Maybe Rem will reply to you soon.

Good Luck.

**Comment by marcelloinfoweb** [comment]
I'm using the latest version. Where is the file where I can edit?

**Comment by PeopleInside** [comment]
I have done in theme edit CSS the last CSS field with this code

#form-start-chat  
{
	visibility: hidden;
               }
