### ISSUE TITLE
Stuck on Comparing current database structure, please wait...

### ISSUE THREAD

**Issue by genachka** [LiveHelperChat/livehelperchat#777]
On 2.3.6, when I go to System Configuration > Update information it shows that 2.3.7 is the new version but it is stuck on showing *Comparing current database structure, please wait...* (I've let it stay there for hours)

I'll manually do the update, but would be good to know why this is happening and fix it?

**Comment by remdex** [comment]
Just use this https://livehelperchat.com/during-some-action-app-returns-white-screen-what-to-do-215a.html and see chrome debug console. And yes you can update manually if you wish. Perhaps some PHP library missing etc.. No idea but all works here.

**Comment by genachka** [comment]
Should have looked at debug console. Sure enough: /index.php/site_admin/system/update/(action)/statusdb

The console was showing a 403 on above POST attempt and tracked it down to the Nginx rule.
