### ISSUE TITLE
BUG: chat transcript not work if survey are active after the chat.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#780]
How to reproduce:
1 create survey
2. create embed live chat code with survey
3. start a chat and chat say Hi as operator
4. say Hi as visitor
5. send a predefied message (canned message)
6. close the chat from operator side (end)
7. vote the chat
8. ask for chat transcript

results: not work - you can put your email but when press send the pop up not close and no email are sent

Tested also in the demo.

**Comment by PeopleInside** [comment]
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/10869302/7a1fa88c-80ab-11e5-9f75-b7a09acaa074.png)

![immagine senza nome1](https://cloud.githubusercontent.com/assets/5006150/10869303/7f4475fe-80ab-11e5-8abb-e953ca15ab1a.png)

Ok as you can see chat is ended and there are surveys on the background. I can put my email for receive the transcript chat but when I press send nothing happen and no mail are sent. The email window continue to be and are not hidden, the email is not sent

**Comment by PeopleInside** [comment]
Hi Rem,
tested with the new update on my server and also in your demo the results is:

NOT YET SOLVED - NOT YET FIXED

How to reproduce:
1. create a surveys
2. generate embed code with survey selected
3. start a chat from visitor side and accept it in visitor side
4. now close the chat from operator side
5. the user will see the survey, try to ask chat transcript this will be the results:

![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/11017446/5c29a438-859f-11e5-8bb1-83d7b8614704.png)

the input box for the mail is not visible

**Comment by remdex** [comment]
now fixed

**Comment by PeopleInside** [comment]
Thanks. Fixed ^_^
