### ISSUE TITLE
BUG: If message is no required for start a chat the name Live Support is not printed

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#781]
If you set Name (required) and message optional in the widget start chat settings, when you start a chat with only your name 

and the chat have to print a standard message the message 

this are printed without the name on top Live Support:

**WRONG because missed the title Live Support (Supporto Live) before the message.**
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/10866157/94734186-8023-11e5-8d9f-8b40798d1179.png)

CORRECT
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/10866161/be70bb80-8023-11e5-8249-fe3d4ca445ff.png)

**Comment by remdex** [comment]
Visitor title won't be shown if it does not have a body. Other issue with invisible operator title was fixed.
