### ISSUE TITLE
Online Visitors Problem

### ISSUE THREAD

**Issue by ysnps** [LiveHelperChat/livehelperchat#784]
Hi,
First, thanks for this script. This is excellent. But i need your help.
İ've installed just today. In this morning, everything was working without any problem but now i can not see how many online visitor right now. Google analytics says 13 ( realtime ) but i can not see any of them. I've cleaned cache, tried with different browsers but it still.

Normally, i have 80+ realtime visitor in the nights.

Is there any idea?
![3](https://cloud.githubusercontent.com/assets/7982671/10908218/e17a258c-8238-11e5-91b2-ab2a28c7bce1.jpg)
![4](https://cloud.githubusercontent.com/assets/7982671/10908219/e1818a2a-8238-11e5-8706-8f9cd04061a4.jpg)

**Comment by remdex** [comment]
By default LHC does not track online visitors while none of operators are logged. You can enable online visitors tracking while none of operators are logged in chat configuration.
