### ISSUE TITLE
Issue Toltip is not showed anymore (after closed) after 1 hours

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#785]
Need help tooltip timeout, after how many hours show again tooltip?
I have set 1 hours but seems the tooltip are not showed also after 1 hours.

And maybe I want set 30 minutes or 10 minutes this is not possible at the moment?
As I can see the toltip is not showed anymore after the 1 hours setup by me in the settings.

For test i will need set inferior time but not supported seems, at the moment. I think here can be a new issue.

Is working as day maybe not hours because after one hours I can't see anymore the the tooltip or there are something are not working well

**Comment by remdex** [comment]
In new version theme overrides tooltip settings. So set 1 hour in theme

On Wednesday, 4 November 2015, PeopleInside <notifications@github.com>
wrote:

> Need help tooltip timeout, after how many hours show again tooltip?
> I have set 1 hours but seems the tooltip are not showed also after 1 hours.
>
> And maybe I want set 30 minutes or 10 minutes this is not possible at the
> moment?
> As I can see the toltip is not showed anymore after the 1 hours setup by
> me in the settings.
>
> For test i will need set inferior time but not supported seems, at the
> moment. I think here can be a new issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LiveHelperChat/livehelperchat/issues/785>.
>


-- 
Sincerely,
Remigijus Kiminas

**Comment by PeopleInside** [comment]
Thanks, finded the new options in theme.
