### ISSUE TITLE
unable to send message to online user

### ISSUE THREAD

**Issue by rdsisystem** [LiveHelperChat/livehelperchat#786]
Hi 
We are unable to send the message to online user when the chat widget is open on the website. since we want to send msg, that online user which will come on our website. its sending the one time msg, when chat widget is closed. 
Please help!
Thanks in Advance

**Comment by PeopleInside** [comment]
Hi **rdsisystem**,
good point. Actually seems LHC (Live Helper Chat) can send only one message to the visitor when the chat widget is closed.

Will be a great function allow to send more than one message to the user... maybe if the operator send a second message this should be appended after the first.

This maybe is to set In Entanglement and maybe you should wait for this if will be approved.
 If you are using LHC for work you can consider to give an offer and ask this can be developed before.

Great point :+1:

**Comment by rdsisystem** [comment]
I just want, operator can send one message when  the chat widget is open, nothing more. can you please tell where is that check.
thanks

**Comment by rdsisystem** [comment]
any help please !

Thanks

**Comment by remdex** [comment]
Well, I ques you are misunderstanding something. Widget in user has to be closed for proactive invitation message to be seen by visitor.

**Comment by rdsisystem** [comment]
Thanks for the reply, sir, But i opened the widget through code first time on the site, after that its not showing message from operator from the online member section

thanks

**Comment by PeopleInside** [comment]
Hi **rdsisystem**, 
**remdex** has wrote: 

 > Widget in user has to be closed for proactive invitation message to be seen by visitor

so it's normal if the user widget is opened you was not able to send a message to the user.
Maybe you can ask here to implement message can be also sent to the user if the widget chat is already opened.

Also the function for send more than one message.
