### ISSUE TITLE
Nginx: Is this normal?

### ISSUE THREAD

**Issue by Rhyswilliamsza** [LiveHelperChat/livehelperchat#787]
Hi There,

Whilst running Live Helper Chat on my nginx installation, I've noticed that the URL defaults to /index.php/?args, as opposed to just /?args. This creates an issue within settings when trying to open things (as they all open in /index/etc instead of /etc, and therefore do not work (giving a server error)). I am also unable to start a live chat at all, however online users works fine.

Thanks,
Rhys

**Comment by remdex** [comment]
Hi,

Just read how to remove index.php from URL
https://livehelperchat.com/how-to-remove-index.php-from-url-229a.html

Also you can use let say standard symphony or laravel nginx rules. They will work also nicely with lhc
