### ISSUE TITLE
chatbox messages overlapping

### ISSUE THREAD

**Issue by uteschj** [LiveHelperChat/livehelperchat#789]
It seems that messages in the chatbox are overlapping.

OS: w7 64
Browser: Chrome Version 46.0.2490.86 m

This screen shot is directly from the livehelperchat.com site demo.

![image](https://cloud.githubusercontent.com/assets/7292075/11196794/b78a53d2-8c7e-11e5-9a53-40e879329a28.png)

**Comment by PeopleInside** [comment]
Yes also from Mobile Firefox.

Confirmed I can see the issue on the liveheperchat.com. chat box as your
screen.

Thanks for reporting

Inviato da dispositivo mobile. | Sended  by mobile device
Il 16/Nov/2015 23:31, "uteschj" <notifications@github.com> ha scritto:

**Comment by remdex** [comment]
Hmm, seems i forgot chatbox module after messages restyle.

On Tuesday, 17 November 2015, PeopleInside <notifications@github.com> wrote:

> Yes also from Mobile Firefox.
>
> Confirmed I can see the issue on the liveheperchat.com. chat box as your
> screen.
>
> Thanks for reporting
>
> Inviato da dispositivo mobile. | Sended by mobile device
> Il 16/Nov/2015 23:31, "uteschj" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> ha scritto:
>
> > It seems that messages in the chatbox are overlapping.
> >
> > OS: w7 64
> > Browser: Chrome Version 46.0.2490.86 m
> >
> > This screen shot is directly from the livehelperchat.com site demo.
> >
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/7292075/11196794/b78a53d2-8c7e-11e5-9a53-40e879329a28.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/LiveHelperChat/livehelperchat/issues/789>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LiveHelperChat/livehelperchat/issues/789#issuecomment-157193607>
> .
>


-- 
Sincerely,
Remigijus Kiminas

**Comment by uteschj** [comment]
bump
