### ISSUE TITLE
Allow custom Button

### ISSUE THREAD

**Issue by breaker84** [LiveHelperChat/livehelperchat#791]
Allow custom button that can show Online and Offline image. Sort of:
online.png and offline.png.

**Comment by PeopleInside** [comment]
+ 1
This will be nice!
Il 20/Nov/2015 00:46, "breaker84" <notifications@github.com> ha scritto:

**Comment by PeopleInside** [comment]
From the Forum https://forum.livehelperchat.com/viewtopic.php?pid=6332#p6332

**Comment by PeopleInside** [comment]
This settings for button image should be added here https://demo.livehelperchat.com/site_admin/system/embedcode#/design

**Comment by remdex** [comment]
this one does not require any development you can use chat api and implement status showing by yourself using. 
https://livehelperchat.com/how-to-use-chat-api-module-206a.html

Also you can use native status code placement and just use CSS on site to style the link.

**Comment by PeopleInside** [comment]
From the Forum another user are requesting this https://forum.livehelperchat.com/viewtopic.php?id=1777 also me think will be userfull
