### ISSUE TITLE
Live Helper chat is not working on https website

### ISSUE THREAD

**Issue by rdsisystem** [LiveHelperChat/livehelperchat#793]
Hello,

Live helper chat is not working on my https website "https://hostpinger.com/". I have implemented live helper chat on other website, its working fine but its not working on this site.

Can you please help me

Thanks

**Comment by PeopleInside** [comment]
Hi,
help topic should maybe not posted here but for there there is a forum at https://forum.livehelperchat.com

Also thanks for posting your website link BUT you don't says what error you see or what is wrong. Please for support open a topic in the Forum.
This is not the right place, here only bug or feature request.

Be more specific in the description of the issue when you will post in the forum and remember to check well your server error log file. If you continue to have issue try a fresh new install. The Live Helper Chat works fine under https.

Thank you!

**Comment by PeopleInside** [comment]
Hi,
your issue seems to be a not valid SSL certificate.

Hope you will fix this soon.
Please close this once your issue is resolved.
Thanks.

**Comment by rdsisystem** [comment]
thanks for the support. and in future will post in forum.

**Comment by PeopleInside** [comment]
This topic is to flag as invalid.

The issue was a customer issue and has now been solved by using a valid SSk for chat.
This issue can be closed as invalid.

Please close it,
thank you!

Issue resolved by customer.

**Comment by PeopleInside** [comment]
** This topic here in GitHub can be closed **
