### ISSUE TITLE
Prefill custom fields doesn't offer hidden: true/false option.

### ISSUE THREAD

**Issue by ipso** [LiveHelperChat/livehelperchat#797]
Prefill for non-custom fields has the hidden:true/false option to show/hide it, however for custom fields this option doesn't seem to be used, so even if the field is prefilled it can't be hidden from the user like the other fields.

**Comment by PeopleInside** [comment]
Thanks for posting, now wait a reply from remdex, the owner. :) I can't help you with that :)

**Comment by remdex** [comment]
Hmm,
Can you paste how your embed code looks like? you can remove domain.

**Comment by ipso** [comment]
Below is the JS code we are using. We are also trying to find a way to prevent visitors using this code from tracking/appearing on the Online Visitors page (we do want other visitors to appear though), but haven't found the documentation to do that, is there a way?

```
var LHCChatOptions = {};
LHCChatOptions.attr_prefill = new Array(); //Chat Form info.
LHCChatOptions.attr_prefill.push({'name':'username','value': current_user.first_name + ' ' + current_user.last_name,'hidden':true});
LHCChatOptions.attr_prefill.push({'name':'email','value': ( current_user.work_email != '' ? current_user.work_email : current_user.home_email),'hidden':true });
LHCChatOptions.attr_prefill.push({'name':'phone','value': ( current_user.work_phone != '' ? current_user.work_phone : current_user.home_phone),'hidden':true });
LHCChatOptions.attr_prefill.push({'name':'registration_key','value': LocalCacheData.getLoginData().registration_key,'hidden':true});
LHCChatOptions.attr_prefill.push({'name':'company','value': current_company.name,'hidden':true});

LHCChatOptions.attr_prefill_admin = new Array();
LHCChatOptions.attr_prefill_admin.push({'index':'0', 'value': current_company.name, 'hidden':true});

LHCChatOptions.opt = {
	widget_height: 340,
	widget_width: 300,
	popup_height: 520,
	popup_width: 500,
	domain: 'mydomain.com'
};

(function() {
	var po = document.createElement( 'script' );
	po.type = 'text/javascript';
	po.async = true;
	var refferer = (document.referrer) ? encodeURIComponent( document.referrer.substr( document.referrer.indexOf( '://' ) + 1 ) ) : '';
	var location = (document.location) ? encodeURIComponent( window.location.href.substring( window.location.protocol.length ) ) : '';
	po.src = 'https://chat.mydomain.com/index.php/chat/getstatus/(click)/internal/(position)/api/(ma)/br/(top)/350/(units)/pixels/(leaveamessage)/true/(department)/2/(disable_pro_active)/true?r=' + refferer + '&l=' + location;
	var s = document.getElementsByTagName( 'script' )[0];
	s.parentNode.insertBefore( po, s );
})();
```

**Comment by remdex** [comment]
Ok, this one needs more clarification. About what exact field you are talking here
1. Custom field which was generated from back office? Because if so - you can choose hidden type here
2. For JS custom field there is option hidden
3. For standard fields there is also option hidden

So I'm not sure about what part you are talking here hmm

**Comment by ipso** [comment]
In this case its the "Company" custom field, the default chat form displays that field to the user, but in some cases where the user is already logged in and we know the company name we want to prefill it and hide it so the user never sees it.

**Comment by ipso** [comment]
I applied this commit, but given the above example, the chat widget still asks the user to fill out the "Company" field. It is pre-filled with the value it should be already, but its still visible to the user where it should be hidden.

Am I missing something perhaps?
