### ISSUE TITLE
Errors in Log File.

### ISSUE THREAD

**Issue by danielc1234** [LiveHelperChat/livehelperchat#799]
Getting thousands of these errors in my log files. 

2015/09/29 08:23:14 [error] 8175#8175: *2053565 FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): Cannot start session with empty session ID in /home/www/mysite.net/ezcomponents/Authentication/src/session/authentication_session.php on line 205" while reading response header from upstream, client: 75.234.243.234, server: mysite.net, request: "GET /index.php/site_admin/chat/syncadmininterface HTTP/1.1", upstream: "fastcgi://unix:/tmp/php5-fpm.sock:", host: "www.mysite.net", referrer: "http://www.mysite.net/index.php/site_admin/"

Is there a way to fix the code in this file? ezcomponents/Authentication/src/session/authentication_session.php

Thanks
Daniel

**Comment by PeopleInside** [comment]
Maybe this should be posted in the forum, not here.
https://forum.livehelperchat.com/

**Comment by remdex** [comment]
This is not LHC related issue.
