### ISSUE TITLE
Feature Request: JS widget code to prevent online visitor tracking.

### ISSUE THREAD

**Issue by ipso** [LiveHelperChat/livehelperchat#800]
We have a special domain that gets a ton of traffic, we would like to offer chat to these visitors, but we don't want to bother tracking them or cluttering up the Online Visitors list. So it would be nice to have a JS flag in the widget options that would disable online tracking for certain visitors while still having it enabled for others.

**Comment by PeopleInside** [comment]
tracking for certain visitors?
witch one?

How can LHC know difference between visitors?
Maybe is logic to deactivate tracking for a widget but all tracking i think is too hard do different... some visitor yes and some other no.

**Comment by ipso** [comment]
Yeah, just a JS flag that disables tracking for visitors whenever that is set, seems like it should be fairly straight forward.

**Comment by PeopleInside** [comment]
Are you able to do?
Maybe you can merge the code for to be approved here on github.

I am not a programmer so maybe it's me who are not able to understand well what you want do. Implemented a script who flag alone? by yourself or are you to flag? flag on what event? What be on for flag a visitor and other no? 

Maybe it's me.. you have to just wait a reply from the chat owner.
God luck. :-)

**Comment by remdex** [comment]
This one is implemented. See embed code generation window.

**Comment by ipso** [comment]
```
po.src = 'https://chat.domain.com/index.php/chat/getstatus/(click)/internal/(position)/api/(ma)/br/(dot)/true/(top)/350/(units)/pixels/(leaveamessage)/true/(department)/2/(disable_pro_active)/true?r=' + refferer + '&l=' + location;
```

Using the above po.src, it seems to be still be tracking, as the visitors appear in the online users list along with the pages they are visiting...

Am I missing something perhaps?

**Comment by remdex** [comment]
No it's all good and working here. Record itself is not deleted once it was tracked. But new pageviews are not logged and pageview request is not logged.

**Comment by ipso** [comment]
I deleted the online user record, then refreshed the page with the above po.src, and it immediately added it back to the online user list.

**Comment by remdex** [comment]
Sorry, but here all works... Install fresh version and see yourself...

**Comment by remdex** [comment]
Added more required changes. Thanks for report :)

**Comment by ipso** [comment]
That appears to have fixed the issue. Thanks!
