### ISSUE TITLE
Possibile bug: pro active chat not work if a specific department is selected.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#804]
Hi,
from the discussion of the forum
https://forum.livehelperchat.com/viewtopic.php?pid=6492#p6492

I found a possible issues.

If in Live Helper Chat there are more than one department and user want a pro active only in a specific department, when you select a specific department in pro active page from the drop down and save, the pro active will not work.
Works only if no department are selected.

**How to reproduce**

**First Step.**
In the demo of Live Helper Chat i created a department B.
So Department are two now, Default and B.

**Second Step.**
In the pro active configuration page 
https://demo.livehelperchat.com/site_admin/abstract/list/ProactiveChatInvitation
I have edited the two working pro active by editing only from Department Choose option to department B and tested to change 5 times page on LHC on private browsing.

Results: The pro active not work. 
If I select Choose option works.

This seems to be a bug.

**Comment by remdex** [comment]
The thing is if you choose department in proactive invitation. In embed code you have to choose this department also for proactive invitation to work.

**Comment by PeopleInside** [comment]
Oh thanks!
I will report to the user, thank you!

**Comment by PeopleInside** [comment]
Yes but it should work also if in Embed code is selected all or more department ... it should work... and not works, works only in a widget with have only that department... but maybe I can have Support and Commercial widget and I want send pro active from Commercial. That is not working because for working i must have only commercial in the widget.

This is not good.
