### ISSUE TITLE
Uncaught Security Error in Chromium

### ISSUE THREAD

**Issue by Rogier076** [LiveHelperChat/livehelperchat#805]
Hi,

I'm having a problem in Chromium. I did a clean install of Debian Jessie, and then installed a screen recorder (vokoscreen) and Chromium, since I wanted to record a clean video of navigating my site and using the live helper chat. 

When clicking the live helper chat and filling in name and message, all is good. Message is sent and no problems. But then no more messages can be sent. Instead the (browser) console is full of errors:
```javascript
Uncaught SecurityError: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
(anonymous function) @ a611846ffdc63fcb6c9317608e9d038a.js:11
n.event.dispatch @ a611846ffdc63fcb6c9317608e9d038a.js:3
r.handle @ a611846ffdc63fcb6c9317608e9d038a.js:3
```
This file is in `cache/compiledtemplates` , although I disabled cache when upgrading to the latest version (no result, I was 2 versions behind). 

When I click the `open in a new window` button in the chat, and then type a message there, everything works fine.

I Googled the error and it seems a Chrome thing, although I have no problems on my windows desktop with chrome. Changing Chromium security settings should fix the problem.  Is this something in my (livehelperchat) settings or is it a bug? One can hardly ask its visitors to change their browsers security settings if they can't inform about the errors in the first place.

**Comment by remdex** [comment]
It's not a bug in LHC. Just in LHC settings you can choose where to save chat settings either in session storage or cookies. So in 
Chat configuration -> Misc -> Disable HMTL5 storage, check it if your site is switching between http and https
