### ISSUE TITLE
Chat Widget Syncing Issue

### ISSUE THREAD

**Issue by bkrajendra** [LiveHelperChat/livehelperchat#808]
I've Just installed latest LHC master branch on my server. Everything looks ok, no script error in console. Chat from Admin console to Frontend Chat widget goes perfectly. But If visitor types anything its not displayed in admin chat box. 

Also notification is shown by browser for each msg coming from chat widget, but it is not updated in admin chat panel.

To see the chat by user, I have to refresh the my admin chat box every time.
Please help me to resolve this issue.

Ive installed this on subdomain with following .htaccess file content in directory.

```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```

Let me know if I'm missing something.

**Comment by PeopleInside** [comment]
Hi, 
this place is for report BUG or requests. Is not for support.
Why you don't use the forum?
https://forum.livehelperchat.com/

Good luck.

**Comment by bkrajendra** [comment]
Hey @PeopleInside 
Thanks. I'll remember this next time and post at forum.
Find this Link to forum post for answer to your question and more details..
https://forum.livehelperchat.com/viewtopic.php?pid=6536#p6536

**Comment by PeopleInside** [comment]
Thank you, I see your post and will reply just in some minutes.
Thanks also for close here and for the detailed post. 
:-)
Great job!
