### ISSUE TITLE
Issue/Bug: LHC Version 2.41 Visitor Activity Interval between chat status checks in seconds NOT WORK

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#812]
Hi,
after the last update of Live Helper Chat 2.41 now the widget are no more updated so if the chat goes offline the widget is not refreshed.

I have tested and after the last update seems this BUG is added.
Please be careful when update the live chat :)

I AM testing right now and this function no work anymore on my chat.
Same on the demo.

**Comment by remdex** [comment]
I do not understand what means widget is not refreshed?

**Comment by PeopleInside** [comment]
Oh sorry,
I mean status wiget where you see support are online.

Function to update when visitor is still on the page and live support go
online or offline... you have to change the page for see updated status
online or offline.

The automatic check you suggest to put on 290 seconds not work anymore so
status widget chat "support online" are no more updated.

How to reproduce:

(I will write here in just some minutes)
Il 29/Dic/2015 14:07, "Remigijus Kiminas" <notifications@github.com> ha
scritto:

**Comment by PeopleInside** [comment]
I was thinking here the request was clear but is better explain fully.
After update to 2.41 now IF visitor in on the page and status widget show support are offline, if support go online the widget is not more updated to online also if I have set the check time in the Visitor Activity Interval between chat status checks in seconds and I have checked in the Embed code Automatically check for messages from the operator/invitation messages ?

How to reproduce:

1. set a time in seconds on settings, livehelp configuration, chat configuration, visitor activity, Interval between chat status checks in seconds, 0 disabled. in the demo is set as 120
2. Generated page embed code and check the option Automatically check for messages from the operator/invitation messages ?
3. use that code in the visitor page so if now you see "support offline" from visitor side and from operator side you go online with the live chat the widget in the visitor side is not updated on online

**Comment by remdex** [comment]
Sorry, but I cannot reproduce.

**Comment by PeopleInside** [comment]
Yes,
are you able to see the status widget switch from online to offline without refresh the page @remdex ?

I mean not the opened widget, when widget is minimized and Support are online and widget show to the user support are online, if you put offline from operator side the live chat and user not change the page the widget continue to show support online.

I tested more than one time on the demo and on my website and I found this new bug after update to 2.41

**Comment by remdex** [comment]
Sorry but as it old cannot reproduce on my dev enviroment. I switch to offine widget becomes offline, i switch to offline, widget becomes green again.

**Comment by PeopleInside** [comment]
Ok, now in the demo seems to work.
Maybe this new commit has solved the issue?
https://github.com/LiveHelperChat/livehelperchat/commit/f7a0dbbdc769ab60ba3fd0d38641211eeb4e3f27

Thank you anyway.
