### ISSUE TITLE
How to change #lhc_status_container css style

### ISSUE THREAD

**Issue by pvd276** [LiveHelperChat/livehelperchat#817]
widget chat status #lhc_status_container 
allway under all content in my website, and can't see it
i change z-index: 99999 in file
lhc_web/design/defaulttheme/tpl/lhabstract/custom/widget_theme.tpl.php
but it not change. maybe it in cache ?
how to clear cache and fix it
##

**Comment by PeopleInside** [comment]
Hi,
sorry for support use the Live Helper CHat Forum.
https://forum.livehelperchat.com/viewforum.php?id=1

Thank you.

**Comment by remdex** [comment]
You can override it using CSS hierarchy or just using themes..
