### ISSUE TITLE
Chrome tab lhc admin panel ajax does not update unless tab is in focus

### ISSUE THREAD

**Issue by fatrolls** [LiveHelperChat/livehelperchat#818]
Chrome tab lhc admin panel ajax does not update unless tab is in focus, pretty much if I'm watching a video or even have chrome minimized and possibly even maximized but not actively focused on (not sure about the last one).. as soon as I focus on it, I get a massive sound blast that scares the shit out of me and all my possible clients have already left
##

**Comment by PeopleInside** [comment]
This sound similar to this https://github.com/LiveHelperChat/livehelperchat/issues/811

**Comment by fcordeiro** [comment]
Try to access chrome://flags/#automatic-tab-discarding and change tab discarding from "standard" to "disabled".

**Comment by remdex** [comment]
#811 Yes these two issues are related. I'm not sure is there any workaround for these issues although...
