### ISSUE TITLE
Nodejs helper causes delays

### ISSUE THREAD

**Issue by akrus** [LiveHelperChat/livehelperchat#824]
Hi,

I've just found strange issue. We have nodejs helper running with settings.use_publish_notifications=true. When I open the customer form and type any message, it takes ~10 seconds to appear in the list of active chats in admin interface. Without nodejs I suppose it's based on settings and takes 2-3 seconds, but it's polling it all the time.
Sometimes it doesn't even appear within 10 seconds and can take minutes instead.

Is it expected behavior or something is wrong with it?

**Comment by bodomic** [comment]
Thanks for reporting this, we're having the same issue and haven't found any clue yet.
We use 2.4.2, if it helps.

**Comment by PeopleInside** [comment]
What browser are you using?

**Comment by akrus** [comment]
Chrome and Firefox

**Comment by PeopleInside** [comment]
@akrus you expect the same problem with Firefox also?

**Comment by akrus** [comment]
Yes :-/

**Comment by remdex** [comment]
I ques something wrong with your NodeJS installation

**Comment by akrus** [comment]
What could be wrong with it?
