### ISSUE TITLE
Unable to install live chat helper in osticket

### ISSUE THREAD

**Issue by Sabyainnovative** [LiveHelperChat/livehelperchat#831]
I have tried the process as shown in installation txt file, but still live chat is not working in my domain.
Please help me 
Thank you
##

**Comment by PeopleInside** [comment]
Hi,
this is place for bug report or feature request. For support please open a topic in the forum https://forum.livehelperchat.com/viewforum.php?id=1 and please close this topic on GitHub as is not a bug or feature request. Thank you.
