### ISSUE TITLE
BUG: Redirect user to contact form create a wrong widget offline page.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#836]
If you have pending chat and press from operator side the button to redirect user to the contact form. the user will be redirected but in the widget will showed a **wrong page who cannot be used for send message as is truncated**!.

Also this is pop up template showed in the widget. Is wrong!

See the screen above:
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/13120277/61c191e0-d5ad-11e5-9a7e-c30d5cad33fc.png)

**Comment by PeopleInside** [comment]
The wrong offline message page is showed also if no operator reply to the chat and user is redirected to the offline form.

Please fix asap ... when is possibile. Thanks.

**Comment by PeopleInside** [comment]
Version affected by this BUG:

    2.41
    2.42
    2.43
    2.44

Version 2.40 IS NOT AFFECTED. I will resume this version until this issue has not been resolved.

**Comment by PeopleInside** [comment]
From the Forum other user start to have the same issue https://forum.livehelperchat.com/viewtopic.php?pid=7092

**Comment by githubertus** [comment]
Yep,
and sorry for the duplicate posting. Next time I'll take a look HERE, first.

**Comment by PeopleInside** [comment]
Hi,
no problem @githubertus it's a pleasure can help you.
Have a great week end and week :)

**Comment by PeopleInside** [comment]
This has not been resolved and new version 2.45 was released but by be affecting this BUG visitor are unable to leave offline message. The only way at the moment is continue to use the last version not affected the old 2.40 until this issue will be not fixed. 

Is bad also for user who test the demo and see this BUG when no operator answers and visitor are redirected to a wrong offline page in the widget.

**Comment by PeopleInside** [comment]
Version 2.46 Affected

**Comment by PeopleInside** [comment]
This is a very important BUG, I WILL be unable to update LHC from version 2.40 until this is not fixed. Now version 2.40 have issue with Google Maps but I can't update to new version until the BUG of offline form will be not fixed.

**Comment by PeopleInside** [comment]
I want FIX this issue but I really no idea where put the hands and FIX than try to merge here. Sorry, hope this issue can be resolved soon.

**Comment by doncaz** [comment]
https://github.com/LiveHelperChat/livehelperchat/commit/7312d186de94dfd6b368f7552faf7cf3d5530c6d
