### ISSUE TITLE
ProActive Chats doesn't pop up

### ISSUE THREAD

**Issue by praveenvall** [LiveHelperChat/livehelperchat#839]
I have LHC V 2.44 with Assigned Department and Proactive chat template.

And then I have the following code in respect of my website for LHChat.

Masked my domain names for security reasons and the concern is that the chat invitation will not popup automatically even if I set  `<script type="text/javascript">
var LHCChatOptions = {};
LHCChatOptions.opt = {widget_height:460,widget_width:400,popup_height:520,popup_width:500,domain:'www.domain.com'};
(function() {
var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
var referrer = (document.referrer) ? encodeURIComponent(document.referrer.substr(document.referrer.indexOf('://')+1)) : '';
var location  = (document.location) ? encodeURIComponent(window.location.href.substring(window.location.protocol.length)) : '';
po.src = '//<domainname>/index.php/chat/getstatus/(click)/internal/(position)/bottom_right/(ma)/br/(top)/350/(units)/pixels/(leaveamessage)/true/(department)/1/(operator)/1/(theme)/1?r='+referrer+'&l='+location;
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
})();
</script>
You may view the settings for proactive chat in the following link 
`[https://drive.google.com/file/d/0B2MHIbx4_PBpRHNlN19USmVuVDA/view?usp=sharing](url)

And please advise what is going wrong.

**Comment by praveenvall** [comment]
(check_operator_messages) condition resolved the issue 

many thanks Marco

**Comment by PeopleInside** [comment]
Hi @praveenvall ,
thank you for close this issue, is not a BUG and the forum is here for help you.
Thanks for close this issue and for your positive feedback.
This is your topic with the solution:
https://forum.livehelperchat.com/viewtopic.php?id=1734

Have a great day!
