### ISSUE TITLE
HTML link for live chat in emails

### ISSUE THREAD

**Issue by Topspot** [LiveHelperChat/livehelperchat#840]
HTML link for live chat in emails, for example: when we send email we want HTML link because java script doesn't work out there.
I am using it in newsletters

Here is an article:

https://www.livechatinc.com/blog/invite … rom-email/
##

**Comment by PeopleInside** [comment]
Thank you for posting this here.
From the forum:
https://forum.livehelperchat.com/viewtopic.php?id=1740

**Comment by simsketch** [comment]
This can easily be done by adding the js function to an HTML page in `<body onload="liveChatFunction()">`

**Comment by remdex** [comment]
Exactly, you can trigger start chat by calling on your page something like
lh_inst.lh_openchatWindow()

**Comment by PeopleInside** [comment]
Hi, this issue seems to be a replied question, i will close this issue for now. If there are some reason why this should stay open let us know.
