### ISSUE TITLE
Chat Log of All user are seen

### ISSUE THREAD

**Issue by ajithfort** [LiveHelperChat/livehelperchat#842]
Hi,
 i installed the livehelperchat. Then went to General->ChatboxList->new and then added Chatbox name:
Name of manager: Identifier : and clicked save button. Now the widget appears in front end and i can type messages there. when another visitor to my site opens the chat he can see previous chat, which is not what i want. I want a user to see his chat only how can i do it?

**Comment by ajithfort** [comment]
hi again. i resolved it i saw the same issue here in the forum [link](https://forum.livehelperchat.com/viewtopic.php?id=1717) It helped to solved it.

**Comment by PeopleInside** [comment]
Thank you for close this and point the right link to a solution :-)
