### ISSUE TITLE
BUG: Pro active chat issue

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#843]
Pro active chat not works 
if 
in the pro active
is selected a Department.

Works only if as Department you have selected Choose option.

Also if the operator profile have not assigned to all department will be unable to set Choose option so make pro active works.

Pro active should works fine also with specific department or you should remove department option in the pro active and test if all works fine.

From my test and user experience, pro active will works only if Choose option is selected in the pro active Department drop down.

I have solved issue in this topic https://forum.livehelperchat.com/viewtopic.php?pid=7055#p7055 and not only this. Helped people to make pro active works. Not easy.

This has been tested on the demo also.

**Comment by remdex** [comment]
If in proactive chat you select department you have to select department also in embed code.
