### ISSUE TITLE
repo got disabled by saying it has sensitive information

### ISSUE THREAD

**Issue by motobhakta** [LiveHelperChat/livehelperchat#845]
Hello GitHub Team,

What is the step to re-enable the repo which got disabled by github staff by saying security data may have in repo.

Kindly help us to re-enable back.

Thanks

**Comment by PeopleInside** [comment]
Hi @motobhakta,
I AM unable to understand your request.

This is livehelperchat project, you will not find here GitHub staff but maybe livehelperchat Staff.

As from what I know there are no repo removed for security data.

Your request seems to be invalid on in the wrong place or I cannot understand you. Sorry.

**Comment by remdex** [comment]
It's invalid issue. Let's close it :)
