### ISSUE TITLE
Feature request (userfull): Chat offline, widget open when chat was online: redirect user to contact form whe press start chat and foward the content in the field in the offline form.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#846]
Hi,
some times my livechat is online, visitor comes to my website and open chat widget.
Here visitor start to put name, email and chat questions, in the meantime my livechat goes offline.

Actually user when press start chat in this situation are able to start a chat and see the pending autoresponder I have.

On the top widget a sentence alert the user there are no operator available but under is printed my auto responder who invite the user to wait.

Will be good (I think) change this process with:
when user press start a chat and chat is already offline, all field showed in the widget can pass his content in the field of the offline message so user are not redirected to start chat template but to offline form will all field already compiled.

Where before user had wrote the question, this text is now in the message field and will be sent as offline message when user press send offline message.

Is not good user can start a chat also if there are no more operator available.

**Comment by PeopleInside** [comment]
Ok here is some screen shot:
![1](https://cloud.githubusercontent.com/assets/5006150/13670472/7ce959fc-e6ca-11e5-9007-41b23e59b444.png)

Visitor arrive in the website. Chat is online.
Visitor start to compile field and chat goes offline.

After all is compiled user press start chat but chat is offline.
This is what happen:

![2](https://cloud.githubusercontent.com/assets/5006150/13670501/a71bb8d2-e6ca-11e5-8e4a-ccdb2a71f654.png)

Visitor can start a chat and see pending autoresponder (please wait) only on top there are a sentence (who can be also ignored by the user because maybe read only the green autoresponder) ... and chat is now pending.

This should work different. User when press Start Chat and chat is offline should be redirected to offline message with all field compiled in the start chat compiled in the offline message so can see there are no operator and if want can press send message with the initial chat request. So soon an operator will reply by email.

Is not good users can start a chat also if chat is offline and they have already chat widget opened.

**Comment by remdex** [comment]
Sorry, but this one won't be changed. It's possible to have automatic redirect to contact form if chat is not accepted for some time.

**Comment by PeopleInside** [comment]
Hi @remdex I think you don't understand the issue. Sometimes happen a visitor open a chat widget when a chat was online without start chat, than chat go offline and visitor write name and other data in widget and start a chat. The visitor are able to start a chat also if the live chat are offline so request are... when visitor press start chat can you add a check... if the chat is currently offline user will be redirected to the contact form and message are transferred in message offline field so user has to press leave message.

The issue is... when i put the chat offline I continue to receive chat from people who has already opened the widget without compiling it.

Thank you.
