### ISSUE TITLE
[ISSUE] Password reset: issue if there are many operator with the same e-mail

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#851]
Password reset must work in different way.

For solve this can be user full deny operator with the same mail but this will be a limitation.

I suggest to ask email and username of the account to reset and add a function who can send an email with all operator username registered...

So click on reset password and the page ask username and email and under there are a link username lost? If user click just insert email for receive a list of all username registered.

So user can read it, find the username and do the password reset process with username and email and the password will be reset to only the user inserted not all profile.

Actually if you have multiple operator with different email is a problem to reset password.
##

**Comment by remdex** [comment]
Well it's company responsibility to ensure that e-mails are unique. Perhaps in the future it will be changed at the moment it will remain as is.

**Comment by PeopleInside** [comment]
I don't want have unique emails. I need some operators have the same.
