### ISSUE TITLE
socket.io location incorrectly set if LHC is installed in a subdirectory

### ISSUE THREAD

**Issue by FathomsDown** [LiveHelperChat/livehelperchat#853]
In the System configuration -> Chat configuration -> Screen Sharing menu, the "socket.io path, optional" incorrectly sets the socket.io path if LHC is installed in a subdirectory. Could the path setting be changed to detect of LHC is installed in a subdirectory or, if it has to be set, remove the "optional" label from the option?

**Comment by remdex** [comment]
You can set any path you man in socket.io configuration window.
