### ISSUE TITLE
[ Widget Chrome/Edge BUG Issue ] If a website is opened and chat started than minimized and the page on the site is changed chat widget will stop to work

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#854]
Hi,
this BUG are affecting all Chrome user.

1. open livehelperchat.com with Chrome
2. Start a chat
3. Minimize the chat widget
4. Change the page

The chat widget will be stop to work.
Video demostration: http://screencast.com/t/5CCHfhY1fMg
Discussion on the forum: https://forum.livehelperchat.com/viewtopic.php?id=1796

**Comment by PeopleInside** [comment]
Also I see there are no settings in MISC or Theme for disable the minimized button on the widget. A settings maybe should be present where you can disable close button or pop button in the theme but no option to disable minimize button.

Hope this bug of minimization wrong wiew on Chrome can be fixed soon because made user loose chat.

**Comment by PeopleInside** [comment]
Temporary fix for this issue can be disable the minimize button with the CSS code:

You can "fix" for now this issue by removing the minimize button.
For do that you need enter into widget theme and in CSS first field put that CSS code:

#lhc_min  {
visibility: hidden;
}

Than save and test. The minimize button will be no more visible so user will not have this issue.

**Comment by PeopleInside** [comment]
The BUG is affecting also Edge Browser.

**Comment by huudepzai** [comment]
I've been tried. But i want button minisize because chatbox is big!

**Comment by PeopleInside** [comment]
I know so you have to keep the BUG for now.
There are no ETA for the fix actually. I AM sorry to cannot help you more. 
BUG has been open here and affect also Edge browser.

In my install I have disabled that button for now after your reporting.

**Comment by huudepzai** [comment]
i add css 
.lhc-min #lhc_iframe_container{
height:0px !important;
}
and it 's ok

**Comment by PeopleInside** [comment]
Yes you are right, this is the solution.
Thank you, I will replace my code with that who solve the issue!

Great! ^_^
