### ISSUE TITLE
Proactive invitation issue

### ISSUE THREAD

**Issue by onlyindia** [LiveHelperChat/livehelperchat#855]
Proactive invitation not working on smart phones. Same issue found in your demo version.

**Comment by PeopleInside** [comment]
Hi,
thank you for the report but this is not a good report so consider if no more detail will be added can be closed.

When you create report please try to put as more details possibile.
Thanks!

**Comment by sajawalsz** [comment]
Yes the bug came to me aswell. Chat is not opening proactively on mobile. Please help.

**Comment by remdex** [comment]
No steps to reproduce, so issue is closed as invalid.
