### ISSUE TITLE
live helper chat-  ssl certificate problem

### ISSUE THREAD

**Issue by eminzeybek** [LiveHelperChat/livehelperchat#859]
Hi, we have used "live helper chat" for a long time. we purchased ssl certificate for get paid with credit card, But chrome browser give a warning ("ERR_INSECURE_RESPONSE") because of live helper chat. So our website is appeared insecure. 

We tried all of them: 
In chat configuration enter "Chat configuration" => "Misc" in field "Please enter explicit http mode. Either http: or https:, do not forget : at the end." enter https:
Uncheck if checked - "Use secure cookie, check this if you want to force SSL all the time
But there is nothing. İt didn't work. Can you help us? Thank you. Best regards.

**Comment by PeopleInside** [comment]
Hi, sorry here only BUG report and this is not valid BUG report as seems you have issue with configuration on your own server or LHC about SSL.

For support close this topic and use the Forum next time. Also your report are not useful, please provide more info like a URL where you have issue.

If you want use the live chat on SSL website you have also to force SSL in the chat. This is your server side configuration not LHC. If you don't want force SSL for your chat you can have issue but you can also set https as protocol in LHC and when generate Embed code choose https.

If your live chat allow to load as insecure content is normal your SSL website are not fully safe and with the padlock.

**Comment by PeopleInside** [comment]
**This is just a reminder to close this topic. There are no issues with SSL and Live Helper Chat.**
Hope you have solved your issue.

Thank you!
