### ISSUE TITLE
IE 11 Chat Spam Bug

### ISSUE THREAD

**Issue by tcables** [LiveHelperChat/livehelperchat#861]
Hello,
I just set up a new instance of v2.43 and when a user sends a chat request from the web client (index.php) he is spammed continuosuly by any reply from a tech support agent or admin. 

Example:

> User: Hi, your product is not working.
> Admin/Tech; I'm sorry let me help you.
> Admin/Tech; What seems to be the issue?
> Admin/Tech; I'm sorry let me help you.
> Admin/Tech; What seems to be the issue?
> Admin/Tech; I'm sorry let me help you.
> Admin/Tech; What seems to be the issue?

This will happen every 2-3 seconds, indefinitely, and include all messages that a tech/admin sends the client.

If you setup a brand new database and instance of Live Helper Chat (all versions, including 2.43) you can easily reproduce this using Internet Explorer 11. i have not tested this in IE 10, 9, or 8.

 It works just fine though with **no issues in FireFox.**

**Comment by tcables** [comment]
Actually this one is my bad, it occurs when running the website on localhost only - which is not a real use case.

**Comment by PeopleInside** [comment]
Hi @tcables thank you for opening and closing this topic as been resolved.
Have a great day ^_^ and time!
