### ISSUE TITLE
Firefox crashes when attempting to begin chat.

### ISSUE THREAD

**Issue by simsketch** [LiveHelperChat/livehelperchat#863]
Exhibiting really weird behavior. Black screen for 20 seconds or more. Then browser crashes or sometimes right away. Was able to replicate on several machines.

**Comment by simsketch** [comment]
looks like it eats up all available memory until the browser crashes.

**Comment by simsketch** [comment]
Needed to change configuration to be explicitly https.

**Comment by simsketch** [comment]
one possible cause:

The connection to wss://wsah.livehelperchat.com/socket.io/?EIO=3&transport=websocket&sid=xAyDUZte_Nj3kKySA3-C was interrupted while the page was loading.

The connection to wss://wsah.livehelperchat.com/socket.io/?EIO=3&transport=websocket&sid=5K1iVc29f2tiKooxA3-B was interrupted while the page was loading.

**Comment by PeopleInside** [comment]
I use Firefox and never seen Firefox crash for Live Helper Chat.
** Seems an invalid topic for me **

**Comment by simsketch** [comment]
Thanks for your comment! You are correct...the issues was completely unrelated to Live Helper Chat.

**Comment by PeopleInside** [comment]
Thank you @simsketch for your positive feedback and also for closing this.
