### ISSUE TITLE
SensorNotRequired	Warning on the visitor tracking/Google maps page

### ISSUE THREAD

**Issue by simsketch** [LiveHelperChat/livehelperchat#865]
SensorNotRequired	Warning	
The sensor parameter is no longer required for the Google Maps JavaScript API. It won't prevent the Google Maps JavaScript API from working correctly, but we recommend that you remove the sensor parameter from the script element.

https://developers.google.com/maps/documentation/javascript/error-messages#deverrorcodes

**Comment by PeopleInside** [comment]
Hi,
thank you, this is just a warning.

A more serious issue seems to be with Google Maps API required.
https://github.com/LiveHelperChat/livehelperchat/issues/890
