### ISSUE TITLE
[ From the Forum: Feature request ] : Add header message on new message in the chat header widget if the widget is minimized.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#867]
Hi,
user Munib from the Live Heper Chat Forum (Topic [at this address](https://forum.livehelperchat.com/viewtopic.php?pid=7577#p7577))

has given a great idea!

> I want to show notification when message received at user side like (You have new message). How can I achieve this? Definitely sound is play when message received but I want to give a new feature to user when new message received and chat box is minimized. Can i add style to header of chat box to show user you have new message? How can i do this?

I have tested on the demo of Live Helper Chat and if I start a chat from visitor side than put the widget minimized and operator write to the user a new message... only the sound are played.
As you told should be in the header something to let the user know the sound is from the chat... like a title with "New message" ... is a good idea.
##

**Comment by remdex** [comment]
It's tricky to implement so will stay as enhancements.
