### ISSUE TITLE
[Feature request] Hide widget status but allow active chat to be showed on certain subsites

### ISSUE THREAD

**Issue by biro11** [LiveHelperChat/livehelperchat#875]
Hi everyone,

it would be great, if LiveHelperChat know to hide widget status, but allow active chat to be showed for certain subsites on domain. I create topic on forum for this. So this feature is more described here - https://forum.livehelperchat.com/viewtopic.php?id=1881

Thanks

**Comment by PeopleInside** [comment]
Hi **@biro11**  ,
thank you! :-) for your suggestion. Good Title and topic description.

**Comment by PeopleInside** [comment]
Maybe this has been solved here: https://forum.livehelperchat.com/viewtopic.php?id=1888 if not please let me know and I will reopen IT.

**Comment by PeopleInside** [comment]
Thank you for closed this :) as is resolved. Have a nice time!
