### ISSUE TITLE
smtp do not work  self-signed certificate use php 7 

### ISSUE THREAD

**Issue by keramist** [LiveHelperChat/livehelperchat#879]
tls 587  (starttls donot wok)
ssl 465

error shows    can not connect to mail host
but it works for php 5.5
please resolve it
thanks

**Comment by PeopleInside** [comment]
Hi,
this is not an issue with Live Helper Chat but is a change in the PHP from the version 5.6 you need to setup PHP for support your SSL connection.

This is PHP configuration Issue on your server not Live Helper Chat SMTP Issue.
Please see: 

- http://php.net/manual/en/migration56.openssl.php
- http://php.net/manual/en/migration70.php

**This topic is invalid, please close it.** Thanks
