### ISSUE TITLE
Subdomain $_SESSION closing after refresh

### ISSUE THREAD

**Issue by comboreaper** [LiveHelperChat/livehelperchat#880]
Hello there,
I using your LiveHelperChat on my website. Everything is working fine except my subdomain. On subdomain if you refresh page or if you go to some link on the subdomain, chat will be closed. I'll be grateful for any advice or help. Thank you!

**Comment by PeopleInside** [comment]
Thank you for closing this https://forum.livehelperchat.com/viewtopic.php?pid=7838#p7838
