### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by danielc1234** [LiveHelperChat/livehelperchat#885]
Hi,

Noticed in my browser console that we are getting errors. I have pasted the image here.

Failed to decode downloaded font: http://www.oursite.com/design/defaulttheme/fonts/MaterialIcons-Regular.woff2
/index.php/site_admin/#/pendingchats:1 OTS parsing error: invalid version tag

Any ideas?

![2016-07-01_1008](https://cloud.githubusercontent.com/assets/1151357/16524812/a4b1191a-3f77-11e6-8c63-93d26dd9fba2.png)

**Comment by PeopleInside** [comment]
Sorry I cannot give support here.

**Comment by danielc1234** [comment]
Invalid topic? Can you please explain a little more in detail exactly what you mean?
These errors are showing up as a result of something going on in the LHC, so I thought it would be a legitimate question.

Thanks

**Comment by PeopleInside** [comment]
**First** of all, why you are requesting support here in GitHub where is flagged Future request or Bug Issue?

For discuss about issue there are the Offical Forum https://forum.livehelperchat.com/viewforum.php?id=1

**Second**

The link you provide are not pointing to live helper chat installation, also the screen you posted... I think you have not understood how to install LHC. You cannot have LHC inside your website folder design!

**Comment by danielc1234** [comment]
First - This could very well be a bug, hence why posting here.

Second - This is the administration view of the LHC software. It looks like LHC is trying to load fonts, etc, but having issues. I could be wrong, but trying to get some insight. LHC is installed and working fine, just bringing this to the attention of the developers. Maybe something that would cause issues, not sure.

**Comment by PeopleInside** [comment]
Are you able to reproduce the issue on the demo?
https://livehelperchat.com/how-to-report-a-bug-properly-310a.html

**Comment by PeopleInside** [comment]
And now you opened a topic on the Forum https://forum.livehelperchat.com/viewtopic.php?id=1952

**Comment by danielc1234** [comment]
Because you told me to! WTH bro. I'll try to figure it out myself. This was a waste of time.

**Comment by PeopleInside** [comment]
You have posted incomplete post without details. I think this is not god way to as support about people who give his time for free :) but maybe I AM wrong and I AM not understanding you, sorry.

**Comment by remdex** [comment]
There is nothing to debug, because url to font is invalid by itself. Issue is closed.
