### ISSUE TITLE
Latest update 2.46 Cannot login livehelperchat HTTP ERROR 500

### ISSUE THREAD

**Issue by fatrolls** [LiveHelperChat/livehelperchat#886]
I get HTTP ERROR 500 when I try to login with the correct password, if I put in wrong password I get to the correct page with red box "Incorrect username or password".

I'll try restarting the httpd service maybe it will help

since http 500 is a internal error must be the http server

my error_log has this information

[Sun Jul 03 10:14:00 2016] [notice] caught SIGTERM, shutting down
[Sun Jul 03 10:14:00 2016] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Sun Jul 03 10:14:01 2016] [warn] Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Sun Jul 03 10:14:01 2016] [notice] Digest: generating secret for digest authentication ...
[Sun Jul 03 10:14:01 2016] [notice] Digest: done
[Sun Jul 03 10:14:01 2016] [warn] Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Sun Jul 03 10:14:01 2016] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips configured -- resuming normal operations

**FIXED IT**

Turns out after 2.41 last version I had you need to copy over a few more newer files in the root directory such as `bower.json` , `package.json` `gulpfile.js` `webpack.config.js` and `index.php`

**Comment by PeopleInside** [comment]
Hi,
Please use the Live Helper Chat Forum ( https://forum.livehelperchat.com/viewforum.php?id=1 ) when you have issue not GitHub.

Happy to read you have solved your Issue,
**please close this topic with the close button on the bottom. Thanks**

**Comment by PeopleInside** [comment]
Thank you :-) :+1:
