### ISSUE TITLE
Several bugs in the code

### ISSUE THREAD

**Issue by AppChecker** [LiveHelperChat/livehelperchat#893]
Hi, we checked your project by [AppChecker ](https://cnpo.ru/en/solutions/appchecker.php)and it found several defects:
1) [lhc_web/ezcomponents/ImageConversion/src/interfaces/handler.php line 123](https://github.com/LiveHelperChat/livehelperchat/blob/67d799d0977fddfc45d2b9dbb57ba84d29261a5e/lhc_web/ezcomponents/ImageConversion/src/interfaces/handler.php#L123)
`if ( strpos( $file, "'" ) !== false || strpos( $file, "'" ) !== false || strpos( $file, '$' ) !== false ) `
single quote is sought twice, may be it should be:
`if ( strpos( $file, '"' ) !== false || strpos( $file, "'" ) !== false || strpos( $file, '$' ) !== false ) `

2) [lhc_web/lib/models/lhuser/erlhcoreclassmodeluser.php line 340](https://github.com/LiveHelperChat/livehelperchat/blob/67d799d0977fddfc45d2b9dbb57ba84d29261a5e/lhc_web/lib/models/lhuser/erlhcoreclassmodeluser.php#L340)
`if ($this->filename != '' || $this->filename != '') {`
$this->filename is checked twice

3) [lhc_web/design/defaulttheme/tpl/lhchat/part/above_text_area_user.tpl.php line11](https://github.com/LiveHelperChat/livehelperchat/blob/67d799d0977fddfc45d2b9dbb57ba84d29261a5e/lhc_web/design/defaulttheme/tpl/lhchat/part/above_text_area_user.tpl.php#L11)

`<?php if ( (isset($chat_embed_mode) && $chat_embed_mode == true) || (isset($chat_embed_mode) && $chat_embed_mode == true)) : ?>
`

isset($chat_embed_mode) && $chat_embed_mode == true)  is duplicated

We hope it will be useful

**Comment by remdex** [comment]
Thanks!
