### ISSUE TITLE
Fix PHP Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP

### ISSUE THREAD

**Issue by edgardmessias** [LiveHelperChat/livehelperchat#895]
Examples:
```
erLhcoreClassTemplate has a deprecated constructor
lhPaginator has a deprecated constructor
```

**Comment by edgardmessias** [comment]
@remdex , these files have deprecated constructor:
* lhc_web/lib/core/lhform/PHPExcel/Shared/PCLZip/pclzip.lib.php - Line:215
* lhc_web/lib/core/lhtpl/tpl.php - Line: 88

**Comment by remdex** [comment]
Thanks, I'll fix these today also with few other changes also

**Comment by remdex** [comment]
Fixed also

**Comment by edgardmessias** [comment]
Thanks.
