### ISSUE TITLE
Users stuck in old active chats which have been closed by the operator continue chatting but no notification 

### ISSUE THREAD

**Issue by fatrolls** [LiveHelperChat/livehelperchat#896]
Users stuck in old active chats which have been closed by the operator continue chatting but no notification.

Those users are not in the last 10 chats so you cannot see them on there but users rejoin in old chats and I cannot see them talking they don't light up in unread messages or pending chat

only refreshing the website puts it in the unread messages.

I don't know i tested it out again it works properly but there was 1 guy very old guy who rejoined the chat started chat 2 weeks ago and rejoined and I didn't even know he was chatting.

**Comment by remdex** [comment]
Sorry, but it's definitely to little info to try to reproduce something and try to fix. I'll have to close the issue just.
