### ISSUE TITLE
LiveChatHelp reported as Malware!

### ISSUE THREAD

**Issue by rtwmerchants** [LiveHelperChat/livehelperchat#897]
Here is my message from hosting company.
This is shown when accessing the admin page:
The web service to this account has been limited temporarily!
Please find more information on the reason why service was limited and what actions to take to restore it in your User area.
Get Limit Removed

This is the message in the hosting user admin area:
The reports below show the results from the latest security scan we have performed on your account. We list all domains infected with malicious code with information on the exact location of the malware and the date that code was detected.

Malware infected URLs per domain rrchat.revolution-restoration.com Scan date: 2016-08-11 11:03:16.817632125 -0500
URL	
http://rrchat.revolution-restoration.com	Hide infection
HEX|eval_base64_obf_mailer|82c1fa3a175969ffb817688a6b1fbab6|02/06/16|/home/rtwmerch/public_html/RRChat/doc/node_servers/cobrowsing/menu85.php

Here is email just sent saying it's malware:
We would like to notify you that a malicious code was detected on your rrchat.revolution-restoration.com website and and a huge number of email spam messages originating from it. In order to prevent further malicious activity from your account we have limited access to it, because malware is a threat not only to the health of your own website but also to the other accounts hosted on the same server.
For your convenience we have opened a usage report regarding that case in your Customer Area.From there you can see a full security report with the exact location of the malware and if needed, order malware cleanup services via our website security partner Sucuri. 
https://ua.siteground.com/usagereports.htm
Best regards,
The SiteGround Team

What can be done? I have Live Helper Chat on other site but they are not affected yet. Can anyone help? Thanks!

**Comment by remdex** [comment]
It sounds more like your server was hacked not LHC itself :)
