### ISSUE TITLE
closed_chat missing

### ISSUE THREAD

**Issue by kentraub** [LiveHelperChat/livehelperchat#898]
According to Home page dashboard widgets order under chat configuration->Misc.  closed_chat is a widget that should be on the dashboard and it is not.  Supported: online_operators, departments_stats, online_visitors, pending_chats, unread_chats, transfered_chats, active_chats, closed_chats.  Is this a bug?

**Comment by remdex** [comment]
No,
In account settings you have to enable Closed chats tab. Account => Visible lists and check closed chats tab :)
