### ISSUE TITLE
live chat not workin

### ISSUE THREAD

**Issue by ghulanfareed** [LiveHelperChat/livehelperchat#900]
when i get widget embed code and place in my file then chat icon live help online show but when i click on it and does not load, and loading give only loading. please help me what is the issue.

**Comment by PeopleInside** [comment]
Hi,
As I told in the forum the issue is your localhost install. No support for local host install also here is not the right place for asking support.
Thank you

**Comment by doncaz** [comment]
https://github.com/LiveHelperChat/livehelperchat/commit/0fcb4a9378adeb6ea1b056c13ba8eb3ad191c190

**Comment by ghulanfareed** [comment]
Dear i am working on live server, and place chat code in sub folder and test that encoded code in other live file. any how thanks for response.

**Comment by doncaz** [comment]
pull newest version

**Comment by PeopleInside** [comment]
Seems a patch has been released for this issue. Lucky :)
