### ISSUE TITLE
500 Errors

### ISSUE THREAD

**Issue by Flash100** [LiveHelperChat/livehelperchat#902]
Remdex fixed an issue for me today.  2.4.6 syntax error #901  (which was also a 500 error issue)  and seems similar to live chat not workin #900

I still cannot launch a chat on the visitors end

www.pianowizardacademy.com

It just spins, and if I expand the widget I can see a 500 error in Chrome and the full link would look like

http://conductor.allegrorainbow.com/livehelp/index.php/chat/startchat/(leaveamessage)/true/(theme)/1/(vid)/0er35xpypf8ifqugv75o/(er)/1?URLReferer=%2F%2Fwww.pianowizardacademy.com%2F

and that returns: 

"conductor.allegrorainbow.com is currently unable to handle this request.  HTTP ERROR 500"

Also, where livehelperchat is installed,

https://conductor.allegrorainbow.com/livehelp/index.php/site_admin/theme/adminthemes

is also producing a 500 error.

This wasn't an upgrade, I just uploaded the latest github version and overwrote...all was working fine prior so doing that so that was poor judgement on my part.   I still ran the upgrade script and cleared cache.

**Comment by doncaz** [comment]
https://github.com/LiveHelperChat/livehelperchat/commit/8a0d15d90d7465d4002b0cb12a740220aca0f668 try to download newest version now, I downgrade all code, and remove all array shorteners

**Comment by Flash100** [comment]
Thank you. but it is HALF resolved.

www.pianowizardacademy.com

The widget SPINS and doesn't go nowhere.  The only difference is now when you expand the window it WORKS.   So only in the lower right hand widget is where it is still not working.

And

https://conductor.allegrorainbow.com/livehelp/index.php/site_admin/theme/adminthemes

still doesn't work.
