### ISSUE TITLE
500 Errors #902 

### ISSUE THREAD

**Issue by Flash100** [LiveHelperChat/livehelperchat#903]
500 Errors #902 ticket was closed.

Thank you. but it is HALF resolved.

www.pianowizardacademy.com

The widget SPINS and doesn't go nowhere. The only difference is now when you expand the window it WORKS. So only in the lower right hand widget is where it is still not working.

And

https://conductor.allegrorainbow.com/livehelp/index.php/site_admin/theme/adminthemes

still doesn't work. I cleaned cache.

**Comment by doncaz** [comment]
it should work, try to find in logs what the errors, but I recommend you to upgrade PHP version up to 5.4+

**Comment by Flash100** [comment]
This is in the error log, though it doesn't say what the error is, at least I don't think it does

24.168.64.30 - - [23/Aug/2016:17:25:21 +0000] "GET /livehelp/index.php/chat/getstatus/(click)/internal/(position)/bottom_right/(ma)/br/(check_operator_messages)/true/(top)/350/(units)/pixels/(leaveamessage)/true/(identifier)/PWA/(theme)/1?r=&l=%2F%2Fwww.pianowizardacademy.com%2Fbuy-piano-wizard-academy HTTP/1.1" 200 44939 "http://www.pianowizardacademy.com/buy-piano-wizard-academy" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"

**Comment by Joeboyc2** [comment]
Hi Flash,

Looks like your widget is trying to display the content on your local site rather the  on the remote site where the live chat is being hosted

If you look at the like know in the error,  nowhere does it say: https://conductor.allegrorainbow.com/livehelp

**Comment by Joeboyc2** [comment]
I think you should be able to manually amend the embed link like this: https://conductor.allegrorainbow.com/livehelp/livehelp/index.php/chat/getstatus/(click)/internal/(position)/bottom_right/(ma)/br/(check_operator_messages)/true/(top)/350/(units)/pixels/(leaveamessage)/true/(identifier)/PWA/(theme)/1

**Comment by Flash100** [comment]
Tried that same thing.   Widget spins, clicking on the expand button and the chat form shows.

**Comment by Joeboyc2** [comment]
Oh... did you update the embedded code? Rather then just doing it on the fly in the browser

I'm sure manually adding the domain to the list should work.

On a side note, I'm not actually able to see the livechat widget on the site is it live?

If you not able to pass this you can always disable the widget and have the click launch the windows chat screen.

I have had to do this in the past as our install is on and intranet where the company was still using ie8

**Comment by Flash100** [comment]
Joe
www.pianowizardacademy.com  is where the widget is.  Lower right side.   Remember, livehelp is installed on the allegrorainbow domain.

**Comment by Joeboyc2** [comment]
https://conductor.allegrorainbow.com/livehelp/index.php/chat/chatwidget/(leaveamessage)/true/(fullheight)/false/(theme)/1/(survey)/1/(vid)/hswm0xkhn6nd9lf5h99p?URLReferer=%2F%2Fwww.pianowizardacademy.com%2Fpiano-wizard-desktop-wallpapers%2F&r=%2F%2Fwww.pianowizardacademy.com%2F&dt=Piano%20Wizard%20Desktop%20Wallpapers%20»%20Piano%20Wizard%20Academy

**Comment by Flash100** [comment]
The embed code should be fine, since you are able to click the expand button in the widget and see the chat form.

**Comment by Joeboyc2** [comment]
This is the link I get when clicking the widget:

https://conductor.allegrorainbow.com/livehelp/index.php/chat/chatwidget/(leaveamessage)/true/(fullheight)/false/(theme)/1/(survey)/1/(vid)/hswm0xkhn6n****_https://conductor.allegrorainbow.com/livehelp_**d9lf5h99p?URLReferer=%2F%2Fwww.pianowizardacademy.com%2Fpiano-wizard-desktop-wallpapers%2F&r=%2F%2Fwww.pianowizardacademy.com%2F&dt=Piano%20Wizard%20Desktop%20Wallpapers%20»%20Piano%20Wizard%20Academy

Some how you have the Web address listed aging in the middle of the link

**Comment by Joeboyc2** [comment]
Remove the *'s and join it all together and that what I get

**Comment by Joeboyc2** [comment]
Is there any chance you can send me over your file that contains the embed code so I can look at it?

**Comment by Flash100** [comment]
You can try it from here too :  www.cybermidi.com

Here is the code from there:

<script type="text/javascript">
var LHCChatOptions = {};
LHCChatOptions.opt = {widget_height:340,widget_width:300,popup_height:520,popup_width:500,domain:'cybermidi.com'};
(function() {
var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
var referrer = (document.referrer) ? encodeURIComponent(document.referrer.substr(document.referrer.indexOf('://')+1)) : '';
var location  = (document.location) ? encodeURIComponent(window.location.href.substring(window.location.protocol.length)) : '';
po.src = '//conductor.allegrorainbow.com/livehelp/index.php/chat/getstatus/(click)/internal/(position)/bottom_right/(ma)/br/(check_operator_messages)/true/(top)/350/(units)/pixels/(leaveamessage)/true/(theme)/1/(survey)/1?r='+referrer+'&l='+location;
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
})();
</script>

**Comment by Joeboyc2** [comment]
This is the link I get from the other site:

http://conductor.allegrorainbow.com/livehelp/index.php/chat/chatwidget/(leaveamessage)/true/(fullheight)/false/(theme)/1/(survey)/1/(vid)/n06h9ksrm24bqxr0861?URLReferer=%2F%2Fwww.cybermidi.com%2F&dt=CYBERMIDI%20Pro%20MIDI%20Files%2C%20backing%20tracks%20for%20performers%2C%20custom%20MIDI%20production%2C%20sheet%20music.

It's missing the https://

Most likely because it is missing from you embed code:

po.src = '//conductor.allegrorainbow.com/livehelp/index.php/

**Comment by Flash100** [comment]
It doesn't work either way.  Used to work both ways.  The point is it works fine when you EXPAND the box, but not when you click on the widget.

**Comment by Joeboyc2** [comment]
Yeh that's because they run from 2 different links and the way they run is different, it's not obvious from looking buy when you look at the code they use different templates and different routes

I'll take a look when I'm at work tomorrow, but in the mean time I would suggest turning on the debug output so you can see what us failing

**Comment by Flash100** [comment]
OK, debug might have provided some clues. 

For the widget:

Parse error: syntax error, unexpected '[' in /var/www/html/allegrorainbow.conductor/public_html/livehelp/cache/compiledtemplates/57352fbb5b24eb72e4b0ce64be721e73.php on line 2

For https://conductor.allegrorainbow.com/livehelp/index.php/site_admin/theme/adminthemes

Parse error: syntax error, unexpected T_USE, expecting T_FUNCTION in /var/www/html/allegrorainbow.conductor/public_html/livehelp/lib/models/lhabstract/erlhabstractmodeladmintheme.php on line 5

**Comment by remdex** [comment]
You have to update php version to atleast 5.4
