### ISSUE TITLE
Department

### ISSUE THREAD

**Issue by kentraub** [LiveHelperChat/livehelperchat#904]
Currently Department is shown on emails when someone fills out the offline form.  Can {Department} also be added to allowed Variables for XMPP.  With this, when you use the chat bot you can get New chat request [{chat_id}] from [{department}]
{messages}
Click to accept a chat
{url_accept}

And know what Department the chat is in, especially if you are a member of several departments.
##

**Comment by Joeboyc2** [comment]
Sounds like a great suggestion and hopefully easy to implement.....

**Comment by falsefifth** [comment]
yes, jabber texting!
