### ISSUE TITLE
CSS Styling disappeared when I embedded the chat button in html

### ISSUE THREAD

**Issue by maureenv** [LiveHelperChat/livehelperchat#905]
Hi everyone,

I've created custom CSS styling for my button in Edit - Widget Themes. If I embed the code using "Position: Bottom Right Corner of the screen" my button looks good as you can see in the image below (the green button):

![stylingnotgone](https://cloud.githubusercontent.com/assets/16403532/17933395/effcec0c-69e1-11e6-9dc1-402dced3ce19.png)

However, I want my button to go in the sidebar so I tried embedding the code using "Position: Native Placement - It will be shown where the HTML is embedded". Now my button is in the correct place but all of the styling is gone (see image below). I've also tried moving the location of the `<div id='lhc_status_container'></div>` tag throughout my site but the styling is still missing. 

![stylinggone](https://cloud.githubusercontent.com/assets/16403532/17933375/d8f998c0-69e1-11e6-8a3e-8b79ff0aceaa.png)

I've also made a post in the forum about this here: https://forum.livehelperchat.com/viewtopic.php?id=2048 

Do you know what might be causing this issue? Any help would be greatly appreciated.

Thank you,

Maureen

**Comment by Joeboyc2** [comment]
Hi Maureen,

Are you intending for he popup widget to still function while it is in the bar on the left of the screen, or have you disabled this and having the chat be displayed in a popup window?

**Comment by PeopleInside** [comment]
Joeboyc2 i think the post of Maureenv us clear and is not relates to pop up.

**Comment by Joeboyc2** [comment]
A better option for you to have the button where ever you like is to set the link to a subpage on your site and then use the page embed code on the subpage to display the chat interface

I have done this myself in the past and it worked fine, you do however love the ability to show the online and offline status, but this can be achieved in other ways

**Comment by Joeboyc2** [comment]
Hi PeopleInside,

Im aware of the question, im just trying to understand how Maureen is intending for the chat's to be handed.

As far as i am aware the widget interface can't be manually located, other than the options available in the embed widget config page

**Comment by maureenv** [comment]
Hi Joeboyc2, 

Thank you for your response to my question. To be honest, I liked where the button was located on the bottom right hand corner but I was told by my team to move it into the sidebar. Then the pop up chat will appear on the bottom right hand corner when the user clicks on the button. The issue I've come across is that for some reason my CSS styling disappears when I try to include my pop up button in a custom location instead of the bottom right corner. It appears that if I create a style sheet for the button and style the #lhc_status_container ID I can resolve the issue. I just don't know why the styling that I applied in the Edit - Widget Themes disappears if I don't leave the button on the bottom-right hand corner of the page.

Thank you

**Comment by remdex** [comment]
If you choose native position you have to style it directly in your site CSS. It's just the way it works :)
