### ISSUE TITLE
[From the forum] User are unable to start a chat

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#906]
Hi,
in the forum seems two different topic and user has been made in the next hours.

Problem seems to be the same, when visitor try to start a chat is printed the error "Your request was not processed as expected - but don't worry it was not your fault. Please re-submit your request. If you experience the same issue you will need to contact us via other means."

I have read user has also tried to disable captcha but this not solve the issue.

Topic are located here:

1. https://forum.livehelperchat.com/viewtopic.php?id=2051
2. https://forum.livehelperchat.com/viewtopic.php?id=2055

I tried to start a chat for see if was a Browser issue but I can confirm the users issue. Don't know how to help this users.

**Comment by anbadmin** [comment]
Any help would be greatly appreciated.. Thanks..

**Comment by nilsinhopessim** [comment]
Obrigado, o link para teste está em: 
http://chat.chuteiraautotrato.com.br/

**Comment by PeopleInside** [comment]
Other user has this issue: https://forum.livehelperchat.com/viewtopic.php?pid=8433

**Comment by remdex** [comment]
It's just ajax captcha is expired, user has to resubmit form.

**Comment by PiperMp3** [comment]
Not true, resubmitting or not, the issue is still there.
Clearing all cache from any browser, clean cache from LHC, now throwing Gateway 504 error if Session Captcha is disabled.

All worked 100% last night, issue been there since. If online - Everything works, but its very slow now.
When offline. If Session Captcha enabled - Your request was not processed as expected
If Captcha disabled - 504 Bad Gateway.

Please reopen issue

**Comment by slarrauri** [comment]
Same problem here, in my case was the http:// if i use https:// works fine. so i redirect the trafic to https://

**Comment by greench** [comment]
If you run multiple instance of live helper chat, please all of them have same `secret_hash` value in their `settings/settings.ini.php` file.

**Comment by praveenvall** [comment]
[https://ibb.co/k0mphVW](url)
The error appeared as everyone said. As per my experience, we have noticed this error is happening on EDGE Browsers for version 3.62 and above. I have never faced any issues well before. 
I think the developer should focus on somoething. I have done a new installation

**Comment by remdex** [comment]
@praveenvall Make sure you have not checked session cookie.
![image](https://user-images.githubusercontent.com/1146085/112858822-ebd73b00-90ba-11eb-8483-d0ba949d29a1.png)

@greench by itself it's not a problem as only you can access it :)
