### ISSUE TITLE
Hide custom chat button styling while offline

### ISSUE THREAD

**Issue by maureenv** [LiveHelperChat/livehelperchat#908]
Hello, I've added my button in a custom location using 
`<div id="lhc_status_container" ></div>
`
but when I do this all of my custom CSS applied in the Live Helper Chat site isn't applied. I decided to create my own stylesheet for the button which solved this problem. However, now when all users are offline the styling applied to lhc_status_container still shows. 

When users are online:
![online](https://cloud.githubusercontent.com/assets/16403532/18318977/cfa03714-74f1-11e6-80a4-e77e4b7cdd83.png)

When users are offline:
![offline](https://cloud.githubusercontent.com/assets/16403532/18318983/d6321228-74f1-11e6-9689-a09c22ee2ea4.png)

I want the green rectangle to go away when no users are online. 

Is there anyway I can use Javascript to do something like:

`if (all users are offline){
    document.getElementById("lhc_status_container").style.display = "none";
}`

Thank you
##

**Comment by remdex** [comment]
Hi,
This fix allows you to make it something like
#lhc_status_container .lhc-status-native-offline{
display:none;
}

// Also possible
#lhc_status_container .lhc-status-native-online{
display:none;
}
