### ISSUE TITLE
Error 503 in loadinitialdata

### ISSUE THREAD

**Issue by patrakov** [LiveHelperChat/livehelperchat#910]
Hi.

I have upgraded LHC to version 2.46v (before, it was some random git snapshot far in the past). After that, a problem appeared: some operators would not see the typical content of the dashboard. I.e. no department stats, no active chats, no pending chats. The bug has been traced to a 503 error in /index.php/site_admin/chat/loadinitialdata.

This error appears because of a bad SQL query. Namely, in erLhcoreClassChat::getLoggedDepartmentsIds(), for some reason (maybe because these users are intentionally not assigned to any department), the $departmentsIds parameter is an empty array. Thus, the resulting SQL query contains the invalid "IN ()" construction.

Also I found a similar potential issue in erLhcoreClassChat::isOnline().

Other places of the code clearly have protection against the empty list of departments, so how about applying the patch below or something similar?

``` diff
diff --git a/lhc_web/lib/core/lhchat/lhchat.php b/lhc_web/lib/core/lhchat/lhchat.php
index dc8cb81..b031f3f 100644
--- a/lhc_web/lib/core/lhchat/lhchat.php
+++ b/lhc_web/lib/core/lhchat/lhchat.php
@@ -648,6 +648,9 @@ class erLhcoreClassChat {
       $rowsNumber = 0;

        if ($dep_id !== false) {
+       if (is_array($dep_id) && count($dep_id) == 0) {
+           $dep_id = -1;
+       }
                $exclipicFilter = ($exclipic == false) ? ' OR dep_id = 0' : '';

                if ($ignoreUserStatus === false) {              
@@ -711,6 +714,9 @@ class erLhcoreClassChat {
         $isOnlineUser = (int)erLhcoreClassModelChatConfig::fetch('sync_sound_settings')->data['online_timeout'];

         $db = ezcDbInstance::get();
+        if (empty($departmentsIds)) {
+            $departmentsIds = array(-1);
+        }

         if ($exclipic == true)
         {
```
##

**Comment by remdex** [comment]
Other part of this issue was fixed there. https://github.com/LiveHelperChat/livehelperchat/commit/5a0659dee108c333de688d13b8acb2d6b9ff32c9
As for isOnline it's not needed there.
