### ISSUE TITLE
Vagrant fast test

### ISSUE THREAD

**Issue by Loksly** [LiveHelperChat/livehelperchat#911]
I've written my own Vagrantfile to test your app.
I want to share it so someone can find it useful.

Just remove the extension of the file (remove .txt). And run at command line:

``` bash
vagrant up
```

Once the deployment is completed you may access it through:
http://localhost:9000/ 

You need a mysql server with an empty database, you may use something like this:

```
create database lhc;
GRANT ALL PRIVILEGES ON lhc.* TO 'myuser'@'%' identified by 'mypasswd';
flush privileges;
```

Note this is not the best way to deploy a production system but a developing one.

[Vagrantfile.txt](https://github.com/LiveHelperChat/livehelperchat/files/476855/Vagrantfile.txt)
##

**Comment by remdex** [comment]
I have written article there
https://livehelperchat.com/fast-test-live-helper-chat-with-vagrant-450a.html

Thanks for contribution :)
