### ISSUE TITLE
Blank page when trying to send test message in XMPP settings

### ISSUE THREAD

**Issue by daschenbrener** [LiveHelperChat/livehelperchat#913]
Running php 7
Mariadb 10
Apache 2.4.6
livehelperchat 2.4.7

I am trying to setup XMPP settings and when i go through your info 

https://livehelperchat.com/openfire-pidgin-and-live-helper-chat-configuration-tutorial-363a.html

and when I go to test message, i get a blank screen, and when I go to my logs, i get 

> [Mon Sep 19 15:29:02.152683 2016] [cgi:error] [pid 20873] [client 1.1.1.1:50034] AH01215: PHP Fatal error:  Uncaught Error: Function name must be a string in /home/mydomain.com/domains/mydomain.com/public_html/lib/core/lhxmp/XMPPHP/XMLStream.php:571, referer: http://mydomain.com/index.php/site_admin/xmp/configuration
[Mon Sep 19 15:29:02.152716 2016] [cgi:error] [pid 20873] [client 1.1.1.1:50034] AH01215: Stack trace:, referer: http://mydomain.com/index.php/site_admin/xmp/configuration
[Mon Sep 19 15:29:02.152737 2016] [cgi:error] [pid 20873] [client 1.1.1.1:50034] AH01215: #0 [internal function]: XMPPHP_XMLStream->endXML(Resource id #81, 'STREAM:FEATURES'), referer: http://mydomain.com/index.php/site_admin/xmp/configuration
[Mon Sep 19 15:29:02.152782 2016] [cgi:error] [pid 20873] [client 1.1.1.1:50034] AH01215: #1 /home/mydomain.com/domains/mydomain.com/public_html/lib/core/lhxmp/XMPPHP/XMLStream.php(424): xml_parse(Resource id #81, '<stream:feature...', false), referer: http://mydomain.com/index.php/site_admin/xmp/configuration
[Mon Sep 19 15:29:02.152813 2016] [cgi:error] [pid 20873] [client 1.1.1.1:50034] AH01215: #2 /home/mydomain.com/domains/mydomain.com/public_html/lib/core/lhxmp/XMPPHP/XMLStream.php(475): XMPPHP_XMLStream->__process(), referer: http://mydomain.com/index.php/site_admin/xmp/configuration
[Mon Sep 19 15:29:02.152843 2016] [cgi:error] [pid 20873] [client 1.1.1.1:50034] AH01215: #3 /home/mydomain.com/domains/mydomain.com/public_html/lib/core/lhxmp/lhxmp.php(13): XMPPHP_XMLStream->processUntil(Array), referer: http://mydomain.com/index.php/site_admin/xmp/configuration
[Mon Sep 19 15:29:02.152885 2016] [cgi:error] [pid 20873] [client 1.1.1.1:50034] AH01215: #4 /home/mydomain.com/domains/mydomain.com/public_html/cache/compiledtemplates/0cb88c4ac01337b785132406833a11dc.php(2): erLhcoreClassXMP::sendTestXMP(Object(erLhcoreClassModelUser)), referer: http://mydomain.com/index.php/site_admin/xmp/configuration
[Mon Sep 19 15:29:02.152914 2016] [cgi:error] [pid 20873] [client 1.1.1.1:50034] AH01215: #5 /home/mydomain.com/domains/mydomain.com/public_html/lib/core/lhcore/lhmodule.php(94): include('/home/mydomain.com...'), referer: http://mydomain.com/index.php/site_admin/xmp/configuration
[Mon Sep 19 15:29:02.152949 2016] [cgi:error] [pid 20873] [client 1.1.1.1:50034] AH01215: #6 /home/mydomain.com/domains/livechat.ri in /home/mydomain.com/domains/mydomain.com/public_html/lib/core/lhxmp/XMPPHP/XMLStream.php on line 571, referer: http://mydomain.com/index.php/site_admin/xmp/configuration

Thanks

David

**Comment by Joeboyc2** [comment]
Hi @daschenbrener

I think your PHP version is too high, try running an older 5. Version

**Comment by remdex** [comment]
This error has been fixed in one of my clients version. Just need to track back somehow what has he changed :)

**Comment by daschenbrener** [comment]
@Joeboyc2 T hanks but not really possible to run 5 anymore.
@remdex thank you for the replay as well and i look forward to your findings. And thank you very much for your work on this, i will make my way over to the donation area shortly

**Comment by daschenbrener** [comment]
Here is what I did to fix this error in the XMLStream.php file
line 571 
$handler[2]->$handler[1]($this->xmlobj[2]);
to this
$handler[2]->{$handler[1]}($this->xmlobj[2]);

and line 591
from
$handler[1]->$handler[0]($this->xmlobj[2]);

to this

$handler[1]->{$handler[0]}($this->xmlobj[2]);

and that seemed to fix it.

hope this help

**Comment by doncaz** [comment]
https://github.com/LiveHelperChat/livehelperchat/commit/534636dbf16768ce79fca4961b957fa3ba03ff4b
