### ISSUE TITLE
Issue [Database] after updgrading from 2.48 to 2.49

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#919]
![lhc issue 249](https://cloud.githubusercontent.com/assets/5006150/19120756/3f06ac80-8b24-11e6-9d2d-9ed0a35035b1.png)

I press the update button but this message continue to be.
What I should do to fix and see everithing update?
Thanks.

**Comment by PeopleInside** [comment]
If I try to do manually the first I see error:
Query SQL:
ALTER TABLE `lh_abstract_survey` CHANGE `max_stars` `max_stars_1` int(11) NOT NULL

 Messaggio di MySQL: Documentazione
#1060 - Duplicate column name 'max_stars_1'

**Comment by PeopleInside** [comment]
Second give this error:

Query SQL:

ALTER TABLE `lh_abstract_survey_item` CHANGE `stars` `max_stars_1` int(11) NOT NULL

Messaggio di MySQL: Documentazione
#1060 - Duplicate column name 'max_stars_1'

**Comment by remdex** [comment]
Sorry, but personally I could not reproduce it just. In any case update https://github.com/LiveHelperChat/livehelperchat/commit/f4c031b8381c4a1df903edbacb447166028414e1 fetch these changes and it will fix itself.

**Comment by PeopleInside** [comment]
Thanks, works
