### ISSUE TITLE
if the url too long,there are width display problem

### ISSUE THREAD

**Issue by iTiaNex** [LiveHelperChat/livehelperchat#923]
in the app.css
add something like this to control the width of a tag
```
    .abbr-list a{
    position: absolute;
    display: inline-block;
    max-width: 100%;
   overflow: hidden;
}
```

**Comment by PeopleInside** [comment]
This issue is present also on the operator panel where you see onlineusers. When the referral is a long link go out of the window.

**Comment by PeopleInside** [comment]
Works great, thank you @iTiaNex and remdex

**Comment by iTiaNex** [comment]
@PeopleInside  @remdex 
sorry,it should be 

`.abbr-list a.ng-binding{
    position: absolute;
    display: inline-block;
    max-width: 100%;
   overflow: hidden;
}`
