### ISSUE TITLE
[Issue from the Forum] in the maps visitor are showed more than time selected in the dropdown

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#924]
From the forum https://forum.livehelperchat.com/viewtopic.php?pid=8671
If I go on the maps and I see dropdown should show visitor from the last 30 seconds I can see in the maps are not showed only visitor in 30 seconds but more 12 minutes, 24 etc.

There are an issue here?
##

**Comment by remdex** [comment]
It was not a bug. I always showed last 50 visitors. Does not matter on their visit time. Now i'll pay attention to their last visit time. It will use same time as online visitors. Combobox with time you see in online map is used just to determine after how long visitors marker should be hidden.
