### ISSUE TITLE
Request: Create a page in the documentation who explain to the user what step follow in case of migration from one folder to another or different domain.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#927]
Hi @remdex,
sometimes I hear people asking how setup LHC after change the folder name or change the domain.
I know for Wordpress you can find some tutorial online. Can you consider to do a small guide and add it to the Documentation?

So I will post the link to the Documentation in request like this one:
https://forum.livehelperchat.com/viewtopic.php?pid=8787

Forum Topic.
Thank you.

The user has to change the Database?
Steps to do... this will be useful 
##

**Comment by PeopleInside** [comment]
Update: User also often try to move from localhost to web hosting. This will cause to they always issues. Is maybe because there are no expert and have "the bad" idea of install before in local host and after in web or maybe also ... will be userful add in this tutorial also steps from local host to web?

Usually I not give any help to users that change folder name, domain or want move from local host to web. Maybe in the future with a guide I can support this kind of user or maybe just the first one who are changing domain and / or folder name.

**Comment by PeopleInside** [comment]
Rem I created a post on Announcements on the Forum https://forum.livehelperchat.com/viewtopic.php?id=2160 as this is not the first time some user need help for moving from localhost to webhosting or need help on moving LHC on different domain or different folder name.

I think so user can find information easily.

**Comment by remdex** [comment]
https://livehelperchat.com/how-to-move-chat-from-one-location-to-another-125a.html

**Comment by PeopleInside** [comment]
Thanks @remdex I was unable to find it. I will add in the Forum FAQ section so I will able to help more users.
