### ISSUE TITLE
Issue: If I create a embed code for a widget with more than one department operator assigned to just one department of those are unable to see visitors

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#935]
**AS YOU CAN SEE OPERATOR A is unable to see online visitors and Admin cannot exclude visitor list of website 4**

**Issue is not in the operator B case where all work well.
Issue is on Admin who cannot exclude website 4 from show online visitors issue 934 and Operator A unable to see online visitor issue 935**

So seems Website 4 need a new LHC install separated (Two different LHC setup)
or a different chat service until issue 934 and 935 will be fixed.

![immagine1](https://cloud.githubusercontent.com/assets/5006150/20032707/ba60d7a0-a390-11e6-81ca-3c4da0ad3ff2.jpg)

**Administrator account can always see all visitors** and here is missed the function to be able to filter online visitor based on department https://github.com/LiveHelperChat/livehelperchat/issues/934 

BUT

**operator will be unable to see visitor on the site** (if they not start a chat) **if the embed code of the widget have more than one department.**

STEP TO REPRODUCE:
website A has 4 department ( 1,2.3,4) so embed code widget is created with this 4 department and put on website A
website B has 1 department (5) so embed code widget is created with just this department (5) and put on website B

Administrator can see online visitor of website A and B and cannot decide to see only website A visitor https://github.com/LiveHelperChat/livehelperchat/issues/934 

**Operator B of website B assigned to only department 5 can see online visitor where the embed code has only department 5 and not more than that.**

Operator A assigned to the department 1,2,3,4 cannot see online visitor because the widget has 4 department. If I create a embed code where widget have only department 1 Operator A can see online visitors but if there are more than one department and you don't allow the operator to manage and be online for all department operator can't see online visitors.

I cannot understand why if there are also department 2,3,4 selected in the Embed widget operator A cannot see online visitor. Can see a visitor only when it start a chat.

In your documentation page about "[My operators can not see online visitors, what I'm missing?](https://livehelperchat.com/my-operators-can-not-see-online-visitors-what-i-m-missing-343a.html)"
you say:

> By default if user does not have assigned "All departments" in user departments assignment management window he won't see anything.

I think this is not a good things. Also if the operator has assigned only department 1 and nor 2,3,4 they should see online visitor where the widget include just or also department 1.

I need operator is assigned to only one department not 4 department and operator should see all online visitor where that department with name (4) are available.

**Comment by PeopleInside** [comment]
PICTURE:
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/20032376/23802ca2-a389-11e6-8d8e-37d360a301fe.png)

So if i paste this Embed code in a website with only few department selected and log in with operator profile B who can see only visitor from his department Italiano and English operator will no see any online visitor because there are some others departments not assigned to operator B.

For see online visitor you have to generate an Embed code with only Italiano and English department but I need also other department for other operators so, when other operators are online different department are showed online. I cannot assign all department to the operator A

**Comment by PeopleInside** [comment]
I think this issue can be resolved by fixing the issue https://github.com/LiveHelperChat/livehelperchat/issues/934 because once this is fixed you can select All department as mentioned here https://livehelperchat.com/my-operators-can-not-see-online-visitors-what-i-m-missing-343a.html and filter visitor so close for now. Waiting a fix on #934 934

**Comment by PeopleInside** [comment]
Issue cannot be solved only by the mentioned issue because if you select all department all department will be online when operator goes online and operator should not be assigned to all department so issue persist. If the operator is assigned at 2 department of 4 should see online visitor where widget have his department.

**Comment by remdex** [comment]
Your explain is way to complex...
