### ISSUE TITLE
Unauthenticated SMTP Test doesn't send e-mails but doesn't give any errors.

### ISSUE THREAD

**Issue by diogovk** [LiveHelperChat/livehelperchat#937]
I'm using a VM downloaded from livehelperchat's website.
I'm trying to configure our server to send e-mails, so I access "Email configuration" in the control panel.
I set our internal SMTP server and port and click test.
It gives me "Configuration updated", but no e-mail is sent.

I installed sendmail in the chat server, and if I type:

> env -i /usr/sbin/sendmail -t -i << END
> To: diogo.v@malwee.com.br
> Subject: Hi
> Message
> Hi hello
> END

The e-mail is sent correctly.
I tried checking logs for errors but I couldn't find anything.

I was expecting that either I had some sort of error in the logs or in the administration page, or a successful mail being sent.
I tried the documentation for help in this matter, but I couldn't find anything.

Am I missing something? Should I enable debug?

**Comment by PeopleInside** [comment]
Hi,
why you don't use the Forum for questions? :)

Please see this documentation link:
https://livehelperchat.com/how-to-use-google-smtp-in-live-helper-chat-204a.html

Have you used ssl:// or tls:// before the host address?
Have you checked your SPAM folder?

**Comment by PeopleInside** [comment]
YES this seems to be a bug. Same for me, test are not working anymore.
Thanks for the report!

**Comment by diogovk** [comment]
>Have you used ssl:// or tls:// before the host address?
I'm using plain smtp in the port 25.

>Have you checked your SPAM folder?
Yes, I did.

Thank you for confirming the bug. Please let me know if there's anything I can do to help.

**Comment by PeopleInside** [comment]
Sorry I was reading your request as support request and is a valid report bug.
I tested in two different LHC installations with the right email settings and the test seems not working anymore.

At the moment you cannot do anything just wait. **Thank you for your report!** @diogovk

**Comment by remdex** [comment]
Hi,

Well in general mail just have to work. Because internally i cannot reproduce. Try do not use SMTP at all and just use sendmail function. Without setting SMTP at all. Also try do not set any "Sender address" and "Default from e-mail address"
Just I cannot fix what i cannot reproduce.
