### ISSUE TITLE
[Feature request] Reactive "Pro active chat invitations".

### ISSUE THREAD

**Issue by khaclam** [LiveHelperChat/livehelperchat#946]
How do I reactive "Pro active chat invitations" after user closed it?

Now, when access to my website, the "Pro active chat invitations" will be displayed. 
If user click to close button, it will be closed and doesn't display again when user reload or go to next page.
So, I want to display it again, even if the user closes it before?

Thanks.

**Comment by PeopleInside** [comment]
This is the user forum post https://forum.livehelperchat.com/viewtopic.php?id=2243
Please include URL to a forum discussion next time. Thank you!

**Comment by remdex** [comment]
You can have configured proactive invitation timeout.
There is in chat configuration setting called "Proactive message timeout in hours. After how many hours proactive chat message should be shown again." you can decrease it to 1 hour. So after 1 hour it will reopen.
