### ISSUE TITLE
Update PhpMailer (& composer proposition)

### ISSUE THREAD

**Issue by PingusPepan** [LiveHelperChat/livehelperchat#951]
Hello,
I was having problems with old PhpMailer version and I edited autoloading to disable included PhpMailer, added composer autoload and requierd PhpMailer from composer. Everything seems to works just fine without editing anything in LHC itself (except the autoloader stuff). The bug is gone because it was only in the old PhpMailer version.

Is there a possibility to change PhpMailer to be loaded via composer? It would need to be somehow included in default download to make sure users with no access to composer can still run LHC just as before. It would make my life much easier.

Thanks

**Comment by Coralsolutions** [comment]
I'll try to update phpMailer

**Comment by remdex** [comment]
I'll try to update PHPMailer ASAP

**Comment by PingusPepan** [comment]
@remdex No need to hurry because of me, I have already sorted my problem out by using composer. I guess updating PhpMailer would reduce bugs for other users like me. And the composer idea was to make it easier to update PhpMailer in the future. But if it is the only dependency, then it may be a bit unnecessary.

Thanks that you care!

**Comment by s3zwirni** [comment]
Hurry needed because of actual bug:
http://www.openwall.com/lists/oss-security/2016/12/26/1
Would be great to get an update for this.

**Comment by remdex** [comment]
Fixed in these two commits
https://github.com/LiveHelperChat/livehelperchat/commit/d434d832b03aef633069c3379f34c56af4f4200e
https://github.com/LiveHelperChat/livehelperchat/commit/e603f5acf213c1591c35f9c626dbd64a50b023c5

**Comment by PeopleInside** [comment]
Version of PHP MAILER 19 is also affected. Need to upgrade to the last version 21

**Comment by remdex** [comment]
It was done yesterday ;)

**Comment by remdex** [comment]
Please - before posting review commits. it's 5.2.21
https://github.com/LiveHelperChat/livehelperchat/commit/357882333dd540d4a2ae6e7adc25472dc2d64732

**Comment by PeopleInside** [comment]
OK right sorry now I see.

**Comment by Arjoni** [comment]
Will the update be posted on the website? How do we get the latest version?

**Comment by s3zwirni** [comment]
Go to https://github.com/LiveHelperChat/livehelperchat and click on "clone or download" and you will get the actual git-sources.

**Comment by Arjoni** [comment]
Isn't this the dev version?

**Comment by macbroadcast** [comment]
No its allways the master, if you want the dev version you need to select another branch on the left dropdown menu.

**Comment by ipso** [comment]
The vulnerability goes much deeper than phpmailer,  and even PHP itself. The problem is actually with executing commands through a shell, which PHPs built-in mail() function does.

Instead,  do yourself a favor and switch to using SMTP for sending all mail and you will be much safer/secure, even without any of these updates. That's your best bet for a production system without having to update LHC/phpmailer at all.

On most Linux distributions you can just point the LHC email settings to:

Host: localhost
Port: 25
