### ISSUE TITLE
Catch Cross-window messaging errors

### ISSUE THREAD

**Issue by julianuphoff** [LiveHelperChat/livehelperchat#956]
The statement `var action = e.data.split(':')[0];` throws an error if another iframe uses Cross-window messaging.

```
Uncaught TypeError: e.data.split is not a function
    at handleMessage:889
```

**Comment by grshop** [comment]
if there is another e.data in our case it was an object from another javascript then it could not split it. 

we added if (typeof e.data === 'string') { I am sure there is probably a more elegant way as well looking for if the string contains a colon.
