### ISSUE TITLE
Issue with Proactive chat messages when multiple users login

### ISSUE THREAD

**Issue by praveenvall** [LiveHelperChat/livehelperchat#968]
I am using LiveHelperchat for almost 2 years but today I faced a strange issue after I have upgraded my version.

I am using the latest version of LHC. When multiple users login to the chat tool, there comes a blank window on a proactive message and it appears like below for the visitors

<img src="http://i68.tinypic.com/2cojtkj.jpg" alt="2cojtkj.jpg">

**Comment by remdex** [comment]
Well, that's really to little steps to reproduce or tell anything more. Just try to update to recent version.
