### ISSUE TITLE
Canned message delay is not working

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#969]
1. settings >> live help configuration (tab) >> canned message >> edit message > 
2. check Automatically send 
3. Delay in second 30
4. Save

5. start a chat in visitor side
6. accept from operator

canned message are immediately sent

**Comment by remdex** [comment]
You are mixing two features. Auto send does not pay attention to delay. Delay are used only if manually is selected canned message and Send delayed canned message is clicked.
