### ISSUE TITLE
Close button doesn't work on mobile

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#971]
Hi,
the chat dropdown close button is not working on mobile.
Tested also in the demo.

This is a BUG report from the forum; discussion [here](https://forum.livehelperchat.com/viewtopic.php?pid=9547)

**Comment by ncaeiro** [comment]
update: happens both via mobile and desktop/laptop, not only on mobile! if visitor is using IE 11 chat close button works well, problem occurs only with Chrome (Version 55.0.2883.87 m) and Firefox (50.1.0). Chat window screenshot here: http://www.nunocaeiro.com/img/lhcchat.png
