### ISSUE TITLE
Add in the operator profile a settings for not receive chat notification if the operator is set to offline

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#972]
From the [forum topic](https://forum.livehelperchat.com/viewtopic.php?id=2343) a user is reporting that if 3 operators are online and one of them are offline - the offline operator continue to be informed about incoming chats on his department. This is disturbing,

**I think should be added an option in a single operator profile where single operator can decide to do not receive notification if his status is set to offline. If is not possible I suggest to leave as is now.**

_The bold text because if you fix in different way the risk is to create a new issue as I explain here:_
By fixing the offline issue reported to the user for all operator will be created a new issue for operators that receive chat in automated works hours so I suggest to add an option in the profile for let a single operator to be not notified about chat when the statues is set to offline.

I AM using automated hours and my operator profile are offline but I need receive chats because I need also that statues of operators are not ignored so I can put live chat online also out of the automated hours, if is necessary.

I think if the issue reported by the user should be fixed should be fixed in the single operator profile so the single operator profile can decide to not get notified on new chat if himself is offline.

**Comment by PeopleInside** [comment]
Hi, seems you introduced the support of this on 2.54 but you add as default for all so now I AM missing chat because if I AM not manually online I miss chat as there are no more sound notification for offline operator. As you not added this as option now I cannot correct this and version 2.54 is problematic for me.

**Comment by remdex** [comment]
This one fixed with todays one of the commits.
