### ISSUE TITLE
Update available?

### ISSUE THREAD

**Issue by jozephbrasil** [LiveHelperChat/livehelperchat#975]
I am getting this:

Your version - 2.51
Current version - 2.53

But on git the latest version is 2.52. Something is wrong...

**Comment by PeopleInside** [comment]
Your version seems to be 2.51
the last available Live helper chat version is 2.53 as you can see here:
https://livehelperchat.com/news-5c.html

Please press close bottom as this topic is invalid.
Thank you!

**Comment by uok** [comment]
Your version - 2.53
Current version - 2.54

as of today only **2.53** is available for download in [releases ](https://github.com/LiveHelperChat/livehelperchat/releases) and to get **2.54** you need to download current master (which is a little confusing and not best practice)

**Comment by PeopleInside** [comment]
I understand you @uok . You said that in [releases](https://github.com/LiveHelperChat/livehelperchat/releases) you expect to see version 2.54 but it's not.

Usually @remdex put the current version in releases only when a new version (2.55) is available but logic let think that 2.54 should be present in GitHub right now and than when 2.55 is released will be added in that page. I do not know why now is working in this way but maybe remdex has motivation for this.

**Comment by remdex** [comment]
It's now always matches.
