### ISSUE TITLE
Autoresponder text issue

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#976]
Hi @remdex ,
thanks for have fixing the issue https://github.com/LiveHelperChat/livehelperchat/issues/945 but I will report still be a bug now.

In the auto responder page the **wait message** and the **Show visitor this message when wait timeout passes** are showed fully so I can write a long sentence and I can save, close the page and come back again and my text still be present at full

BUT

in visitor side I see my **Show visitor this message when wait timeout passes** is truncated.

Admin side all is OK:
![lhc ok - admin side](https://cloud.githubusercontent.com/assets/5006150/22555237/54896afa-e963-11e6-885f-77770891f0fd.png)

Visitor side and chat operator side NOT OK:
 
![non ok visitor side](https://cloud.githubusercontent.com/assets/5006150/22555517/3f94cef4-e964-11e6-91d3-38f1cbd8b489.png)

Could you please fix this last things?
Thanks.

**Comment by PeopleInside** [comment]
This is my waiting message:

`[b]LiveChat 9-23 [/b][url=https://www.peopleinside.it/liveticket/kb/faq.php?id=11][Info][/url]: La ricerca di un operatore è iniziata, l'attesa massima è di 15 minuti, ti preghiamo di avere pazienza... potrebbe volerci un po' di tempo. | [b]LiveChat 9-23 [/b][url=https://www.peopleinside.it/liveticket/kb/faq.php?id=11][Info][/url]: System are looking for an avaiable operator, hold on please. The max waiting time is 15 minutes. Please be patient, this process can take some time.`

This is my visitor message after the waiting time:

`Sei importante per noi. La tua richiesta è in corso. L'attesa massima totale è di 15 minuti prima di poter lasciare un messaggio. Ti preghiamo di attendere... | You are important to us. Please hold on, your request still be in progress. The max total waiting time is 15 minutes before you can leave a message. Please stay on hold...`

**Comment by remdex** [comment]
I think it's fixed in some of previous commits.
