### ISSUE TITLE
AJAX page navigation not working properly! HTML5 History API

### ISSUE THREAD

**Issue by UralZima** [LiveHelperChat/livehelperchat#981]
Hi. My site use AJAX page navigation, using HTML5's history API. So page is never reloaded, and LHC also. LHC print wrong info about footprint, showing one page. Also, when user navigates to another page, LHC don't detect it. The URL location bar changes when user navigates to another page. Another tracking features working wrong I guess.
Now many sites use this navigation, especially on big CMSes, where drop-in plugins available.
How to fix it? I can call some LHC's javascript function on page change, if it will help somehow.

Please help.
Thanks for awesome work

**Comment by remdex** [comment]
On page change you can call just.
It should do the job :)
lh_inst.startNewMessageCheckSingle();
There is also another method called - lh_inst.logPageView();

First one also triggers proactive invitation if there is any. Second only log's the page :)
