### ISSUE TITLE
BUG from the Forum: time message issue on operator side (missed)

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#983]
Hi,
from the [forum discussion](https://forum.livehelperchat.com/viewtopic.php?pid=9668) user nuno-m-caeiro is reporting the issue tested and confirmed by me.

Timestamp is showed correctly in visitor side but is not on the operator side.
How to reproduce:

1. Start a chat from visitor and accept chat from operator side
2. Send a message as visitor. If the current time is 11.00 AM wait for the 11:01 or 11:02 than send a new message from visitor side

Results: On the visitor side you can see first message was sent at 11:00 and second at 11:01 or 11:02 but at operator side you will see only the first time 11:00 and not next time.

Chat timestamp ok for Operator:
http://nunocaeiro.com/img/chat_timestamp_operator_ok.jpg

Chat timestamp not ok for Visitor:
http://nunocaeiro.com/img/chat_timestamp_visitor_not_ok.jpg

**Comment by ncaeiro** [comment]
Can someone provide me any update about this? Seems like was somehow forgotten. Thanks!

**Comment by PeopleInside** [comment]
For fast fix there are commercial support. This will be not fixed soon.

**Comment by ncaeiro** [comment]
:/

**Comment by PeopleInside** [comment]
You have to consider that Live helper chat is an Open Source this mean you can download and use for free. This also means that people who are working on this is using his free time after work to fix issue. This is not always easy and possible.

This is also why as user I AM try to provide limited free support based on my knowledge because I believe in Open Source.

Unfortunately as from what I know there are only one chat owner back to programming Live helper chat so you have to wait if you want see your report fixed for free.

I want not to be bad, I AM only trying to let you know how is working.
Hope this explain is helping you to do your evaluation.
