### ISSUE TITLE
In version 2.54 if you have set automated hours and operator are offline all chat notification and sound are missed to that operator in the automated online time

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#987]
Hi,
I went just inform that I tried two times to upgrade to version 2.54 but when I do incoming chat is no more alerting me with sound.

IF I resume 2.53 all work fine.

**Comment by PeopleInside** [comment]
If I update only the database no problem.
Seems if I upload the file of 2.54 the problem start to be.

Also if I told to Softaculous script installer to update my LHC the problem start to be.

All new chat are not more alerted to me with sound and with notification.
I cannot upgrade to 2.54 need wait a fix

**Comment by remdex** [comment]
You are using automatic chat assignment to user?

**Comment by PeopleInside** [comment]
No I AM not.

**Comment by PeopleInside** [comment]
I AM using this on Apache:

```
Header always edit Set-Cookie "(?i)^((?:(?!;\s?HttpOnly).)+)$" "$1; HttpOnly"
Header always edit Set-Cookie "(?i)^((?:(?!;\s?secure).)+)$" "$1; secure"
```

do not know if the issue with the new version can be related to that.

**Comment by PeopleInside** [comment]
I @remdex ,
I have two different LHC installations and all is giving issue 
if there are version 2.54

Seems the issue can be related the edits made maybe in departments, I do not know but I AM not using automatic chat assignment. In the demo I AM unable to reproduce the issue but maybe because is a new installation. The issue seems present if you upgrade the live helper chat.

This topic report is important because all work fine with 2.53 and is not with 2.54 by upgrading it. I will try also to work on this day for try to understand but I AM not a programmer and do not know what change from 2.53 to 2.54 who can cause that issue.

**Comment by PeopleInside** [comment]
Issue finded. Issue is not present if the operator of the department are online.

The issue is present if I have automated chat time on and me as operator are offline. So I do not receve no more chat notification. How I can fix this?

Have you made change about [this topic](https://github.com/LiveHelperChat/livehelperchat/issues/972)?
Maye if yes you have not followed my suggestion to add the non notification as checkbox in the operator profile and by made this as default create issue to me because live helper chat is no more working for me on version 2.54

How to reproduce:
1 put operator offline in the demo. Chat will be online for visitor because there are automated chat but if there are incoming chat no sound so I missed a lot of chats on my websites for this change.

**Comment by PeopleInside** [comment]
I AM using Live helper chat 2.53 last commit [7f03f46 PHP7 Compatibility Fixes](https://github.com/LiveHelperChat/livehelperchat/commit/7f03f465955e6fe564e1163000003f29c41b3c2f) who works well and are not affected from notification issue.

The issue seems to be coming after that and may be depend on [Redo notification](https://github.com/LiveHelperChat/livehelperchat/commit/ab8a5b69618b3c7bf0831af1cdd306096481d417) commit or somewhere else after. I don't know how to fix this issue as I do not understand the code.

The issue is very important for me because on 2017 I start to use automated work hours and no more operator status so... with the last change I AM miss all chat because I AM not notified with browser notification and sound about new chat.

**Comment by PeopleInside** [comment]
OK I replaced the 8 changed files in the [Redo notification](https://github.com/LiveHelperChat/livehelperchat/commit/ab8a5b69618b3c7bf0831af1cdd306096481d417) with previous files of version 2.53 before this commit and this solve the notification issue.

Seems your commit create issues on departments with work hours active and operator status. If the operator is offline and departments is online than chat is not notified.

You can try easily on the demo.
Log in and put you offline than start a chat on visitor side where the chat is online.
The pending chat is not be notified: no sound and no browser alert if you have set in the settings.

This should be absolutely fixed.
Thank you. End of my investigation now just wait a fix.

Issue found.

**Comment by remdex** [comment]
1. Yes, if operator is marked as offline notifications are not send to him. It was intentional decision
2. As for general logic i'm rewriting notification login to simplify it. So perhaps i'll include option to receive notifications even if operator are offline.

**Comment by PeopleInside** [comment]
Thanks for the point 2 because if is active work hours has no sense that I need to put myself online than offline manually because no chats are received.

Now I have replaced all notification editing in my version 2.54 so I can use the new version but without this edit made recently who cause chat loss.

I will be grate if once the feature 2 will be introduced an update can ben sent here and maybe so this topic can be closed.
Thanks remdex.

**Comment by PeopleInside** [comment]
Hi @remdex , I do not agree with the new change forced to all user as this made automated work hours not working well as before.

If there will be other updates and the point 2 will be not fixed soon I have to replace all files 8 files and JS again for have the chat work.
Hope the option to have chat notification active can be implemented on the next released. For now I patched (in bad way maybe because I AM not a programmer) the version 2.54
Thanks.
