### ISSUE TITLE
Disable chats list

### ISSUE THREAD

**Issue by Arjoni** [LiveHelperChat/livehelperchat#990]
Hi,
I want to disable chats list menu for operators. The exact link of the menu is /site_admin/chat/list. I have tried every permission but it's still there.
What permission is linked to this? How can I disable it? I have removed configuration menu from the dashboard but operator can still access the option when going to dashboard - chats list. The problem is that the operator can see all departments and users when searching for chats.
Any suggestions?
Thanks

**Comment by remdex** [comment]
This cannot be disabled without disabling all chat functionality completely.

**Comment by Arjoni** [comment]
Maybe add it as a permission? Can it be disabled with CSS or something like this?
