### ISSUE TITLE
Not Translate

### ISSUE THREAD

**Issue by gustotc** [LiveHelperChat/livehelperchat#991]
I downloaded the latest version and installed it in linux mint, but when I select another language other than English it does not show anything else. Everything goes blank.

Is there any dependency on linux to perform the translation?

**Comment by gustotc** [comment]
![selecao_076](https://cloud.githubusercontent.com/assets/7175315/23508815/21e725e4-ff32-11e6-9fde-b187b1c64693.png)
![selecao_075](https://cloud.githubusercontent.com/assets/7175315/23508820/263c4d86-ff32-11e6-84ac-360e204ed9d7.png)

**Comment by PeopleInside** [comment]
I suggest to you to check your server error log.
Try also to change language in the demo for see if this can be a reproducible bug:
https://livehelperchat.com/demo-12c.html

GitHub usually is used to report bug or ask question when I cannot give support on the forum... I do not have received any topic who is talking about the issue reported by you.

Please consider this is a free open source project who is done in free time after work. As you can understand is not possible assist all users with server issues. Maybe some configuration of your server can have conflict so you see a blank page.

I suggest to you to check your error log.
Thank you and good luck.

In the official live helper chat website you can also find info about commercial support.

**Comment by gustotc** [comment]
I understand. Thanks for the feedback.
