### ISSUE TITLE
CoBrowser not work in misc HTTP/HTTPS

### ISSUE THREAD

**Issue by andmattia** [LiveHelperChat/livehelperchat#996]
I found an issue when you have chat system on HTTPS and chat widget installed on site not HTTPS only HTTP.

In this case when open a chat works fine and you are able to ask user to co browsing, user can accept the co browser but on chat you nevere receive the scree cast.

Version is 2.54

**Comment by remdex** [comment]
I can't do nothing about that. Protocols must match just in that case.
