### ISSUE TITLE
Option to close chat when the browser is closed is missed.

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#998]
Hi,
today an user has reported that also if all options in Misc is set to disallow chat reopen, if the browser window of the visitor is closed with an opened chat, chat will be reopened once the user come back to website.

I had tested this in the demo;
In Misc I disabled:
- Reopen chat functionality enabled, 0 - No, 1 - Yes
- Automatically reopen chat on widget open
- Allow user to reopen closed chats?

For me is good that if the user close the browser for error are able to take the chat again but someone is asking how they can customize this and close chat if the browser is closed. I tried all settings but seems there are no way to close the chat if the browser is closed.

Can you check @remdex and add an option to let the user decide if want the chat closed also if the browser is closed or have the chat still be opened?

Thank you.

**Comment by remdex** [comment]
Sorry, but I can't detect is it browser closed or just window reloaded. So this is not possible just...

**Comment by PeopleInside** [comment]
Thank you.
